### ISSUE TITLE
Demo app needs to be updated

### ISSUE THREAD

**Issue by jayrave** [mikepenz/Android-Iconics#100]
I started integrating Iconics into my application and was using the [demo application](https://play.google.com/store/apps/details?id=com.mikepenz.iconics.sample) to look up icons' name. Some icons that I could find in the demo app were missing from the library and the reason turned out to be #99. It would be great if the demo application can be updated to reflect it

**Comment by mikepenz** [comment]
ah ok. sorry you are right. uploaded the new version. thanks.

**Comment by jayrave** [comment]
Great!! Thanks for an awesome library

**Comment by mikepenz** [comment]
thanks
