### ISSUE TITLE
Using both this library and Calligraphy with base context

### ISSUE THREAD

**Issue by jd-alexander** [mikepenz/Android-Iconics#101]
How do I go about wrapping the base context so calligraphy and this library can be used together. Wanted to use icons in normal textviews and buttons.

**Comment by mikepenz** [comment]
@jd-alexander you can use this library also without wrapping the base context. You will then have to use the custom views.

**Comment by jd-alexander** [comment]
Ok :+1:

**Comment by mikepenz** [comment]
v2.5.0 is now compatible with calligraphy. see the upgrade notes ;)

**Comment by jd-alexander** [comment]
Awesome! Thanks Mike.
