### ISSUE TITLE
set Iconics as ImageResource?

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/Android-Iconics#102]
is it possible to set Iconics as a ImageResource? like this:
imageView.setImageResource(FontAwesome.Icon.faw_info_circle);
its not working for me! can I cast it?

**Comment by mikepenz** [comment]
@TheLoyalCruel the icons are no ressources. The drawables are generated via an icon font.
So you have to go via the `IconicsDrawable` and set the icon as `drawable`
