### ISSUE TITLE
Using the custom IconicsImageView in a list

### ISSUE THREAD

**Issue by Orbyt** [mikepenz/Android-Iconics#103]
So when using these icons as an ImageView, it says theres 2 options, either inject the context and use a regular ImageView and add the icon in the properties, or use the custom IconicsImageView. Would there be any performance problems using a couple of the custom IconicsImageView on cards in a list/recyclerview? Would it for any reason be slower than using a regular ImageView and injecting the context to add the icon?

**Comment by mikepenz** [comment]
@Orbyt both do the same so there is no difference in performance. The lib will create drawables from the icon font addon and those are drawn if shown. 

There is a third possibility that you set the `drawable` inside your adapter programatically. 
Really depends what you need.

**Comment by Orbyt** [comment]
Thanks.

**Comment by mikepenz** [comment]
@Orbyt if you have any troubles let me know ;). But the new context inject method is really cool :D

**Comment by Orbyt** [comment]
@mikepenz Do you know of any use cases where using the inject method instead of the custom imageview would be an advantage?

**Comment by mikepenz** [comment]
@Orbyt in general i would suggest to use the inject method as it is really transparent and you can continue using the normal `ImageView`s (and the fact that they are probably replaced with updated `ImageView`s from the support libs, not sure if this already happens but it is done for `ImageButton`s)
So no change of you code to the `IconicsImageView`. Nor any other things. Just add the attributes. 
Another real advantage is, as soon as you inject the context, it is also possible to use the Iconics on all views which extend `ImageView` (the icon via the attributes) or `TextView` (within the text) so no changes within your code either. 

There is one advantage of using the `IconicsImageView` when you set the `IconicsDrawable` via xml and want to modify the color at a later point. The `IconicsImageView` comes with methods to do this. On an `ImageView` you would have to create a new `IconicsDrawable` which is not slower or anything, just the fact that you have to know which icon to create :D

**Comment by Orbyt** [comment]
@mikepenz Awesome, will keep that in mind. Thanks!
