### ISSUE TITLE
conflict with Calligraphy

### ISSUE THREAD

**Issue by DJafari** [mikepenz/Android-Iconics#104]
i want use `Android-Iconics` and `Calligraphy` toggether, how can do it ?

https://github.com/chrisjenx/Calligraphy

**Comment by mikepenz** [comment]
@DJafari if you can't use the context thing you will either have to use one of the provided custom views `IconicsImageView`, ... or set the icons programtically via the `IconicsDrawable`

**Comment by mikepenz** [comment]
v2.5.0 is now compatible with calligraphy. see the upgrade notes ;)

**Comment by DJafari** [comment]
thanks you a lot man
