### ISSUE TITLE
Failed to resolve Google Original icons lib

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/Android-Iconics#105]
Gradle build failed to resolve:
compile 'com.mikepenz:google-material-typeface:2.2.0.1.original@aar'

**Comment by mikepenz** [comment]
@androideveloper wrong version:
http://mvnrepository.com/artifact/com.mikepenz/google-material-typeface

It is: `2.1.0.1.original`

**Comment by androideveloper** [comment]
Ok, i will try. Read.me file contains the wrong version, please fix.
