### ISSUE TITLE
Update community-material-typeface-library

### ISSUE THREAD

**Issue by echthard** [mikepenz/Android-Iconics#106]
How often do the icon libraries get updated? I can see the community-material-typeface-library is at v1.3.41 on the website. I would like to use some new icons that are not yet in Android-Iconics.

**Comment by mikepenz** [comment]
@echthard icons are updated as soon as i see that there is a new version. Will update to the new version later today

**Comment by echthard** [comment]
First: thank you for everything you share!

Second: I see you have updated the cmd library, but how come barcode-scan from https://materialdesignicons.com/ isn't available?

**Comment by mikepenz** [comment]
@echthard thanks.

not sure. it is not included in their release. perhaps in a future release?
