### ISSUE TITLE
Have issues with setImageDrawable but not with setBackground

### ISSUE THREAD

**Issue by thekalinga** [mikepenz/Android-Iconics#108]
When I try setImageDrawable on an image within a container, I get an empty container (by container I mean the layout that the image is contained in)

```java
ImageDrawable drawableLeft = findViewById(...);
drawableLeft.setImageDrawable(new IconicsDrawable(context, drawableLeftIconName)
                        .colorRes(R.color.button_default)
                        .sizeDp(drawableLeftIconNameSize == 0 ? R.dimen.font_icon_medium_size : drawableLeftIconNameSize));
```

If I try set an image from resource, I dont have any issue issue.

```java
drawableLeft.setImageDrawable(a.getDrawable(R.styleable.CustomButton_drawableLeft));
```

In order to see whether the issue is just setImageDrawable, I tried setting the background on a button & it works fine.

```java
keyBoardSwitcher.setBackground(new IconicsDrawable(context)
                    .icon(GoogleMaterial.Icon.gmd_keyboard)
                    .colorRes(R.color.button_default)
                    .sizeDp(R.dimen.default_icon_size));
```

I am facing this issue even with Support Action Bar home indicator

```java
IconicsDrawable menuIcon = new IconicsDrawable(getContext())
                .icon(GoogleMaterial.Icon.gmd_menu)
                .colorRes(R.color.search_bar_text_color)
                .sizeDp(R.dimen.default_icon_size);
        getSupportActionBar().setHomeAsUpIndicator(menuIcon);
```

If I place the above code, my complete action bar is becoming invisible. If I replace the same with regular image resource, I dont see any issue

```java
getSupportActionBar().setHomeAsUpIndicator(R.drawable.hamburger);
```

Is there something I'm missing w.r.t setting ImageDrawable?

Any help is appreciated.

**Comment by mikepenz** [comment]
@thekalinga the first thing i see is that you try to set the image size with this method `sizeDp` but you provide a ressource id instead you should use this method `sizeRes`

**Comment by thekalinga** [comment]
Thank you.. That solved the issue
