### ISSUE TITLE
Does not work with the Preview mode in Android Studio layout editor

### ISSUE THREAD

**Issue by somghosh** [mikepenz/Android-Iconics#11]
Is there a way to fix it?
 My code looks like below - if I remove the IconicsTextView it renders properly, but not with it

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:layout_marginLeft="@dimen/card_gap"
        android:layout_marginRight="@dimen/card_gap"
        android:gravity="center_vertical">

        
        <TextView
            android:id="@+id/like_count_tv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:text="47 likes"
            android:textColor="@color/gray7"
            android:textSize="14sp"
            android:textStyle="bold" />

        <IconicsTextView
            android:id="@+id/like_icon_tv"
            android:text="{faw-heart-o}"
            android:textColor="@color/em_green_base"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toRightOf="@id/like_count_tv"
            android:layout_alignTop="@id/like_count_tv"
            android:gravity="center"
            
            android:paddingLeft="30dp"
            android:paddingRight="30dp"
            android:textSize="14sp"/>

    </RelativeLayout>

**Comment by mikepenz** [comment]
@somghosh as far as i know the editor can only show static data. So let's say it would be possible to set a preview text. The icons are generated during runtime so there is nothing to show. 

I can't try it right now, but if you mean that the editor can't show the layout at whole or displays an exception it is possible to fix, have to check.

**Comment by somghosh** [comment]
Thanks @mikepenz - I mean that the editor can't show layout as a whole. I am fine with visualizing the fonts (created at runtime), but I would like to see the rest of the layout - and as of now I can only do so by changing IconicsTextView to Textview manually each time, and then changing it back again to run

**Comment by mikepenz** [comment]
@somghosh fixed in v0.7.1

**Comment by somghosh** [comment]
Thanks @mikepenz . Would you be pushing it to the maven repo anytime soon - since I use most libraries that way
        //for Iconics library 
    compile 'com.mikepenz.iconics:library:0.7.0@aar'

This and the ActionItemBadge are the best two time-savers I've come across recently :)

**Comment by mikepenz** [comment]
@somghosh v0.7.1 is already on maven central. Just change it to this:

```javascript
    compile 'com.mikepenz.iconics:library:0.7.0@aar'
```

Thank you so much. I try my best to help others :). 

If you create an application, and need an about this app section + proper credits (an open source section in your app to show which libs you use and which licenses they have) you probably will like this:
https://github.com/mikepenz/AboutLibraries

**Comment by somghosh** [comment]
Thanks Mike. I am using the following, but still the preview seems not to work upon using the latest release in my build.gradle

            <IconicsButton
                android:id="@+id/helpticket_from_tracking_app_btn"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"

                android:layout_marginLeft="10dp"

                android:background="@drawable/button_w_rounded_corner_standout"
                android:text="{gmd-message}"
                android:textColor="@color/white"
                tools:text="X" />

**Comment by mikepenz** [comment]
@somghosh thanks for the info.

**Comment by thomasdsouza** [comment]
Thank you for yourawesome work. 
IconicsTextView also causes preview to go blank. Using 0.9.1 in Android Studio 1.2.1.1 on Windows 8.1

**Comment by sherpya** [comment]
try with 1.0.0 with changed widget namespace, looks like android studio gets tripped if the widget has android.view namespace, I think this bug can be closed

**Comment by thomasdsouza** [comment]
Thank you very much @sherpya. I tried and confirm that it works!. This saves me a lot of time. Thanks again guys.

**Comment by somghosh** [comment]
Thanks @thomasdsouza @sherpya  - did you mean 1) try with android studio 1.0.0? and 2) i didnt understand how you can chang the widget namespace - can you detail a bit please. Thanks

**Comment by mikepenz** [comment]
@somghosh no version 1.0.0 of this library. the second part is nothing for you to do. just make sure you read the upgrade notes...

**Comment by mikepenz** [comment]
@sherpya thanks
@thomasdsouza thanks
