### ISSUE TITLE
cmd_image missing from CommunityMaterial font

### ISSUE THREAD

**Issue by xsorifc28** [mikepenz/Android-Iconics#111]
I believe [cmd_image](https://materialdesignicons.com/icon/image)  isn't mapped to a character, I am not able to find [cmd_image](https://materialdesignicons.com/icon/image) in CommunityMaterial.Icon

**Comment by mikepenz** [comment]
@xsorifc28 it seems the export of their icons does not include all icons. i can't do anything about that. there was already a second icon which was missing. i checked in their download and it was also missing there. the addon includes all icons which were inside their official font download + css mapping with the current version a week ago

**Comment by xsorifc28** [comment]
Thank you for looking into this. I will file an issue with their repo.

**Comment by mikepenz** [comment]
i can check again if you want. as written it was a different icon the last time

**Comment by xsorifc28** [comment]
According to [this](https://github.com/Templarian/MaterialDesign/issues/856), it was called file_image_box. I've opened an issue to request and rename the font character for consistency.

**Comment by mikepenz** [comment]
@xsorifc28 ok thanks
