### ISSUE TITLE
IconicsDrawable do not render for Fragment menu items

### ISSUE THREAD

**Issue by Plastix** [mikepenz/Android-Iconics#112]
I have an AppCompatActivity with a menu that contains a single support Fragment. The fragment contains its own menu items as well. 

In my fragment I am doing the following:
```java
 @Override
    public void onCreate(Bundle savedInstanceState) {
       ...
        // Tell the activity we have menu items to contribute to the toolbar
        setHasOptionsMenu(true);
       ...
}

 @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        // Inflate the menu items from the Fragment's menu
        inflater.inflate(R.menu.menufragment menu);

        menu.findItem(R.id.filter).setIcon(
                new IconicsDrawable(getContext(), CommunityMaterial.Icon.cmd_filter_variant)
                        .actionBar().color(Color.WHITE)
        );

        super.onCreateOptionsMenu(menu, inflater);

    }
```
The menu XML for the fragment looks like this:
```XML
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".MainActivity">

    <item
        android:id="@+id/filter"
        android:orderInCategory="10"
        android:showAsAction="ifRoom"
        android:title="@string/menu.filter" />

   ...
</menu>
```
The items show up in the overflow menu but they don't show up with icon drawables. What am I doing wrong? I tired the same code in the activity's menu and it works. Go figure.

**Comment by mikepenz** [comment]
@Plastix  can you please provide a screenshot. 
But if i understand you correctly you expect the icon to show up in the small dialog when you click on the overflow button. But those items do not have the icon. If your element is shown in the toolbar itself (not in the overflow) it will show the icon.

**Comment by Plastix** [comment]
The issue is that it isn't showing up on the toolbar with an icon. Switching my XML to `android:showAsAction="always"` doesn't fix it either.

**Comment by mikepenz** [comment]
@Plastix i have an idea what could cause the issue, but it is not Android-Iconics related. I am sure that a normal icon (from resources) won't change your behavior. 

If i'm right your issue is that you have to replace `android:showAsAction="always"` with `app:showAsAction`

**Comment by Plastix** [comment]
Wow I completely overlooked that! Thanks for the help.

**Comment by mikepenz** [comment]
No problem. Great that it works now ;)
