### ISSUE TITLE
Getting a wrong Icon

### ISSUE THREAD

**Issue by anupsarode** [mikepenz/Android-Iconics#113]
Hello,

First of all, thanks for making this library. It helps me a lot.

I'm trying to get the wallet icon from Community Material set. But I'm getting the Google wallet icon.

```
Drawable icon = new IconicsDrawable(this, CommunityMaterial.Icon.cmd_wallet);
```

Attached is the screenshot. I need to fetch the second icon, but I get the first icon. I'm pretty sure I'm using the correct name 'cmd_wallet'.

Can you please guide me how I can use that wallet Icon?

My gradle file imports

```
compile 'com.mikepenz:iconics-core:2.5.0@aar'
compile 'com.mikepenz:community-material-typeface:1.3.41.1@aar'
```

![screen shot 2015-12-07 at 10 15 23 pm](https://cloud.githubusercontent.com/assets/2538927/11633346/c46853d4-9d30-11e5-959d-097ae7c8f34c.png)

Best,
Anup Sarode

**Comment by mikepenz** [comment]
@anupsarode their official icon pack (if i download the whole icons) does not include the `wallet` icon. just the `google-wallet` one.

The official google material icons include the icon you search for: https://www.google.com/design/icons/#ic_account_balance_wallet

Best,
Mike
