### ISSUE TITLE
IconicsImageView and stateful colors

### ISSUE THREAD

**Issue by stuckless** [mikepenz/Android-Iconics#114]
I tried setting the iiv_color property to a stateful color (ie, drawable resource with selectors that set the color for normal, focused, selected, and unselected).  The Icon renders with the default color, but, it doesn't appear to change color when the other states are applied.  I've set, focusable=true, focusintouchmode=true, and clickable=true, so I can see the icon reacting to the focus states (ie background changes, etc, but the color never changes).

I'm just wondering if having stateful colors for the icons is possible or out of scope.

I can provide more details if needed.

Great work on this project.

**Comment by mikepenz** [comment]
@stuckless could you please provide some sample code you tried?

**Comment by stuckless** [comment]
So, in res/drawable, I have, iconbutton_textcolor.xml
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_focused="true" android:state_pressed="false" android:color="#ff0000" />
    <item android:state_focused="true" android:state_pressed="true" android:color="#000000" />
    <item android:state_focused="false" android:state_pressed="true" android:color="#000000" />
    <item android:color="#ff0000" />
</selector>
```

In my button style (styles.xml), apply the color
```
    <style name="NavIconButton">
        <item name="android:layout_width">34dp</item>
        <item name="android:layout_height">34dp</item>
        <item name="iiv_color">@drawable/iconbutton_textcolor</item>
        <item name="android:padding">5dp</item>
        <item name="android:background">?android:attr/selectableItemBackground</item>
        <item name="android:clickable">true</item>
        <item name="android:focusable">true</item>
        <item name="android:focusableInTouchMode">true</item>
    </style>
```

And then in my layout xml, I use the IconicsImageView with google material icon, and I set the button style, which sets the color selector.
```
            <com.mikepenz.iconics.view.IconicsImageView
                android:id="@+id/nav_media_play"
                style="@style/NavIconButton"
                app:iiv_icon="gmd-play-circle"
                android:tag="play" />
```

When my button renders, it renders as RED, but never changes to BLACK when the view is focussed or clicked.

Is this enough?  Or do you need more?

**Comment by mikepenz** [comment]
@stuckless thanks for the code. i never tried something like this. i expect this to not work with the `IconicsLayoutInflater` but i may be wrong. Will check if such a behavior is possible.

**Comment by mikepenz** [comment]
Ok after some debugging. At the moment i do not allow `ColorStateList`s. But would be a great advantage ;). Will keep it on the list for things to ad

**Comment by stuckless** [comment]
Thanks for looking.  Awesome project.  it's not a critical feature, but, would be useful.  Configuring state are a bit of PITA... might be nice if IconsImageView just had attributes for focusColor, pressedColor, and normal color :)

**Comment by alorma** [comment]
I achieved so mething like this using:

```
public class MultipleStateIconicsImageHolder extends ImageHolder {
  private IIcon icon;
  private IIcon pressedIcon;
  private int pressedColor;

  public MultipleStateIconicsImageHolder(IIcon icon, int colorDefault, IIcon pressedIcon,
      int pressedColor) {
    this.icon = icon;
    setColor(colorDefault);
    this.pressedIcon = pressedIcon;
    this.pressedColor = pressedColor;
  }

  @Override
  protected void apply(ImageView imageView, int colorDefault) {
    IconicsDrawable drawableDefault = getIconicsDrawable(imageView, colorDefault, icon);

    IconicsDrawable drawablePressed = getIconicsDrawable(imageView, pressedColor, pressedIcon);

    StateListDrawable drawable = new StateListDrawable();

    int[][] states = new int[][] {
        new int[] { android.R.attr.state_activated },
        new int[] { android.R.attr.state_checked },
        new int[] { android.R.attr.state_pressed }
    };

    for (int[] state : states) {
      drawable.addState(state, drawablePressed);
    }

    drawable.addState(new int[]{}, drawableDefault);

    imageView.setImageDrawable(drawable);
  }

  @NonNull
  private IconicsDrawable getIconicsDrawable(ImageView imageView, int color, IIcon icon) {
    IconicsDrawable drawableDefault = new IconicsDrawable(imageView.getContext());
    drawableDefault.icon(icon);
    drawableDefault.color(color);
    drawableDefault.sizeDp(24);
    drawableDefault.paddingDp(2);
    return drawableDefault;
  }

  @Override
  public boolean isValid() {
    return icon != null;
  }
}

```

**Comment by mikepenz** [comment]
I think the solution of @alorma is really great. 
I will keep in mind to probably add `ColorStateList` support in the future
