### ISSUE TITLE
IconicsTextView get ligature

### ISSUE THREAD

**Issue by kumold** [mikepenz/Android-Iconics#115]
is there will be a method to get a ligature?
For example, when called on IconicsTextView with icon "{faw-adjust}", it returns string "{faw-adjust}".

**Comment by mikepenz** [comment]
@kumold can you please be a bit more specific?

**Comment by mikepenz** [comment]
@kumold i will close this until all the required information is added. thanks.

**Comment by kumold** [comment]
One example is text comparison like iconicTextView.getText().equals("{faw-adjust}")

**Comment by mikepenz** [comment]
the thing is that the text will be replaced with the unicode character mapped by the specific font. So there will be no more `{faw-adjust}` inside the text. You may be able to check if the text equals the unicode value defined per icon:
https://github.com/mikepenz/Android-Iconics/blob/develop/fontawesome-typeface-library/src/main/java/com/mikepenz/fontawesome_typeface_library/FontAwesome.java#L192
