### ISSUE TITLE
Search in the whole Iconic sets

### ISSUE THREAD

**Issue by 7ShaYaN7** [mikepenz/Android-Iconics#116]
I think this is a good idea to have possibility of search through all font sets, to get the right icon for specific needs.

**Comment by mikepenz** [comment]
@7ShaYaN7 good idea. you can also do a pull request if you want to ;)

**Comment by 7ShaYaN7** [comment]
appreciate that!

**Comment by mikepenz** [comment]
@7ShaYaN7 it's already in now :)

**Comment by 7ShaYaN7** [comment]
That's sufficient for now! But if you present the query results in one place, definitely you provide a nice time saving solution.

Thumbs up for keep coding on and make it up! ;)

**Comment by mikepenz** [comment]
thanks

**Comment by NathanC** [comment]
@mikepenz Sorry to resurrect a 7 year old issue, but can you clarify what you meany by your comment above? What `Drawer`, what `badges`? It sounds like this is something in Android studio? I'm using the compose library if that gives any needed context.

(I'm rewriting my React Native app as a Native jetpack compose project, and was missing @expo/vector-icons which provides a [web search](https://icons.expo.fyi/). I'm really happy I stumbled across this library, but it would be great to have some way of searching for icons by name from all the sets :)

**Comment by mikepenz** [comment]
@NathanC the sample app hosted as part of the iconics project has the menu on the left side. if you open this menu you will see all icon sets there. when you filter the menu (the drawer will show the count of icons per icon set) 

This only refers to the sample app which is only meant to showcase the different icons and the usage of the drawable. 

For a full compose app you may also just use `VectorDrawable`'s directly (depending on how many icons you need) 

- https://developer.android.com/jetpack/compose/graphics/images/material


The community material icons set has a huge set of icons which all can be retrieved as vector drawable: https://materialdesignicons.com/

**Comment by NathanC** [comment]
@mikepenz  Ah okay, so there's no way to search through all the packs at once? I may just limit myself to material community packs for now, in that case.

What is the right way to extract a `VectorDrawable` for an icon from the `ComunityMaterial` object? The `Icon` composable takes a `ImageVector`, what is the distinction between a `VectorDrawable` and an `ImageVector`, and how can I convert it? There's [this answer](https://stackoverflow.com/a/71187184/954986), but I'm quite new to android/compose so I don't quite get how they relate.

It also looks like there's a library specifically for [compose icons](https://github.com/DevSrSouza/compose-icons), so I may use that, though it looks like it doesn't have as much variety as your library :)

**Comment by mikepenz** [comment]
You can filter through all, and the sidebar will show if any particular pack had matches. But there is no view to see all mixed

`VectorDrawable` would not need the `Android-Iconics` library at all. you would get it from the project on the website and then just use directly. 

Best follow the respective documentation on google for these.
