### ISSUE TITLE
No applicable method to...?

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/Android-Iconics#118]
I'm trying to use an Iconics icon with MaterialDrawer, with this code:

```java
PrimaryDrawerItem timerSection = new PrimaryDrawerItem().withName("Timer").withIdentifier(TIMER_SECTION).withIcon(CommunityMaterial.Icon.cmd_timer).withTintSelectedIcon(true).withSelectedIconColorRes(R.color.colorOrange).withSelectedTextColorRes(R.color.colorOrange);
```

But I'm getting the error:

```
No applicable method to '(com.mikepenz.community_material_typeface_library.Community.Icon)'
```

I'm importing the correct classes, and I've included Iconics and the Community Material libraries in my build.gradle. What am I missing? :(

**Comment by mikepenz** [comment]
@drinfernoo which versions are you using?

The exception is really strange as there is no `Community.Icon` just a `CommunityMaterial.Icon`

**Comment by drinfernoo** [comment]
```
compile 'com.mikepenz:iconics-core:2.5.1'
compile 'com.mikepenz:community-material-typeface:1.3.41.1'
```

And I do believe the error says CommunityMaterial.Icon, my mistake.

**Comment by mikepenz** [comment]
@drinfernoo when you clean build the project? 
where does the error occur?

**Comment by drinfernoo** [comment]
It's a compile-time error, so I'm unable to do a full build.

**Comment by mikepenz** [comment]
@drinfernoo oh. i assume you updated from a previous version?

Check your imports i think you may still have the old import in your file

**Comment by drinfernoo** [comment]
I am also using MaterialDrawer, if that matters?

I'm using:

```
compile 'com.mikepenz:materialdrawer:4.6.1'
	compile 'com.mikepenz:iconics-core:2.5.2'
	compile 'com.mikepenz:community-material-typeface:1.3.41.1'
	```

**Comment by mikepenz** [comment]
as already stated do you have wrong imports in your java file?

**Comment by drinfernoo** [comment]
```
import com.mikepenz.community_material_typeface_library.CommunityMaterial.Icon;
import com.mikepenz.iconics.*;
```

I think so? Whatever was added by my IDE ;)

**Comment by mikepenz** [comment]
remove those imports and import them new

**Comment by drinfernoo** [comment]
I already have :(

**Comment by mikepenz** [comment]
i do not understand why it tries to import `CommunityMaterial.Icon` it should only
```
import com.mikepenz.community_material_typeface_library.CommunityMaterial
```

**Comment by drinfernoo** [comment]
I still get the same error after changing it. I also took out the

    import com.mikepenz.Iconics.*;
Since I'm not directly using anything from there.

**Comment by mikepenz** [comment]
@drinfernoo can you provide a sample app showcasing this. i really do not have any more ideas why this happens for you :/. does it also happen with other icon fonts available for the `Android-Iconics`?

**Comment by drinfernoo** [comment]
I'm unable to use it at all. I've also tried with FontAwesome and Meteocons :( I could put up a gist of a class with the code, but I can't see how any of the other stuff is relevant. If I'm including it in my build.gradle, and importing it in my class, what else can go wrong?

I don't really understand the error, since I'm not calling a method anyway, but rather a constant, right?

**Comment by mikepenz** [comment]
@drinfernoo i really don't understand why you have this issue. If you have your project on GIT or any other SCV, i could take a look and try to reproduce your issue. Just give me temporary access, and i will try it. 

I am sure there must be some strange configuration issue. 

And yes the `Icon` is an `enum` so no method.

**Comment by drinfernoo** [comment]
https://github.com/drinfernoo/Cuber/blob/master/app/src/main/java/com/blango/cuber/BaseActivity.java, line 83 ;)

**Comment by mikepenz** [comment]
@drinfernoo just provide to compile your project with AndroidStudio but i can't get it to run. a lot's of issues. 

one thing which i saw is that the `MaterialDrawer` import should look like:
```gradle
compile('com.mikepenz:materialdrawer:4.6.1@aar') {
   transitive = true
}
```

**Comment by mikepenz** [comment]
Why have you discommented the iconics library? https://github.com/drinfernoo/Cuber/blob/master/app/build.gradle#L49 without this one it won't have the core

**Comment by drinfernoo** [comment]
I commented it out with the hope that it was actually having a conflict and that that would fix it, but even with it being included, I can't make the library work. I've given up :)

**Comment by mikepenz** [comment]
@drinfernoo which development environment are you using? With Android Studio i was not able to get it running.

**Comment by drinfernoo** [comment]
AIDE, which I know isn't strictly (or leniently) supported, but it does support enums, gradle builds, Maven, etc... I've been able to get every other library to work but this one :/

**Comment by mikepenz** [comment]
@drinfernoo ok this may describes why i can't compile and run the project. I have the bad feeling that AIDE may causes some strange problems. I had no other reports like this, but as it is not the official development environment it's a bit hard to support. 

You can't use Android Studio?
