### ISSUE TITLE
How can i use this Icons in NavigationView

### ISSUE THREAD

**Issue by AruLNadhaN** [mikepenz/Android-Iconics#119]
Thanks for the great library. I need to use these Icons in my Drawer (NavigationView). So I tried to implement like the below method. But it is not working ?

```xml
        <item
            android:id="@+id/nav_home"
            android:icon="@drawable/avatar_denholm"
            app:ico_icon="gmd-plus-circle"
            android:title="Home"/>
```

**Comment by mikepenz** [comment]
@AruLNadhaN you can't define an `Android-Iconics` icon via xml on the `NavigationView` as this one is a menu and does not extend from `TextView` or `ImageView`. You can only set the icon programmatically
