### ISSUE TITLE
IconicsDrawable size() not working?

### ISSUE THREAD

**Issue by Orbyt** [mikepenz/Android-Iconics#120]
Im using an IconicsDrawable to add a plus icon to a FloatingActionButton.

Code:
```
mFab.setImageDrawable(new IconicsDrawable(this)
.icon(CommunityMaterial.Icon.cmd_plus)
.sizeDp(8)
.color(ContextCompat.getColor(this, R.color.accent)));
```

This doesnt seem to size the icon correctly. I did notice however, that if I set the size to something like `.sizePx(8)`, the icon will be fuzzy, but setting it to `.sizePx(80)` causes the icon to become clear again, suggesting that it is in fact trying to size the icon, but something else if forcing its dimensions to stay the same. What could be causing this?

**Comment by mikepenz** [comment]
@Orbyt if you try to create an icon with the size of 8px it will be really tiny, and the `FloatingActionButton` will probably scale it up the the required size again. You should set the size of the icon to the size the icon will be displayed. 

There is also no difference in any methods like `sizePx`, or `sizeDp` as they all call the same methods:
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L412

**Comment by Orbyt** [comment]
@mikepenz 

`You should set the size of the icon to the size the icon will be displayed.`

Well thats my question, it doesnt resize the icon properly, no matter what value I use. 8px and 80px both have the same physically looking size, the 8px is obviously blurry though as its being forced to scale.

**Comment by mikepenz** [comment]
@Orbyt that's the behavior a `ImageView` works. Make sure your `ImageView` and the `FloatingActionButton` extends the `ImageView` displays the icon the correct size. So you create the `IconicsDrawable` let's say with 24dp, and you make the size of the `ImageView` also 24dp. So it will look best. 

I can't (and it would not make much sense) modify the default behavior of `Drawable`s and `ImageView`s

**Comment by Orbyt** [comment]
@mikepenz Yea im using the default FloatingActionButton implementation, but was using `wrap_content` for the width/height, perhaps thats the issue. Ill mess around with it later. Thanks!
