### ISSUE TITLE
Choose your desired fonts  this is right 

### ISSUE THREAD

**Issue by vipheyue** [mikepenz/Android-Iconics#122]
`compile 'com.mikepenz:foundation-icons-typeface:3.0.0.1@aar'`  !!!!  you write compile `'com.mikepenz:foundation-icons-typeface-typeface:3.0.0.1@aar'`

  this you lost   .--->   `compile 'com.mikepenz:materialize:0.5.1@aar'`

```gradle
    compile 'com.mikepenz:iconics-core:2.5.2@aar'
    compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar'
    compile 'com.mikepenz:material-design-iconic-typeface:2.2.0.1@aar'
    compile 'com.mikepenz:materialize:0.5.1@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.5.0.1@aar'
    compile 'com.mikepenz:octicons-typeface:3.2.0.1@aar'
    compile 'com.mikepenz:meteocons-typeface:1.1.0.1@aar'
    compile 'com.mikepenz:community-material-typeface:1.3.41.1@aar'
    compile 'com.mikepenz:weather-icons-typeface:2.0.10.1@aar'
    compile 'com.mikepenz:typeicons-typeface:2.0.7.1@aar'
    compile 'com.mikepenz:entypo-typeface:1.0.0.1@aar'
    compile 'com.mikepenz:devicon-typeface:2.0.0.1@aar'
    compile 'com.mikepenz:foundation-icons-typeface:3.0.0.1@aar'
    compile 'com.mikepenz:ionicons-typeface:2.0.1.1@aar'
```

**Comment by mikepenz** [comment]
@vipheyue what do you mean?

**Comment by mikepenz** [comment]
I will close this one until enough information was provided

**Comment by vipheyue** [comment]
typeface:3.0.0.1@aar not  -typeface-typeface:3.0.0.1@aar'  in use guide 
and  use guide lost a provided  compile 'com.mikepenz:materialize:0.5.1@aar'  .this may make user produce problem

**Comment by mikepenz** [comment]
@vipheyue ok thanks i modified that one. 

Regarding the `compile 'com.mikepenz:materialize:0.5.1@aar'` dependency. This one is no dependency of the **Android-Iconics** library. 
The **Materialize** library is the dependency of the `MaterialDrawer` and is automatically added via the `transitive = true`

```gradle
compile('com.mikepenz:materialdrawer:4.5.9@aar') {
    transitive = true
    exclude module: "iconics-core"
}
```
