### ISSUE TITLE
Wrong icon name

### ISSUE THREAD

**Issue by gzlock** [mikepenz/Android-Iconics#123]
>com.nrop19 E/Iconics: Wrong icon name: gmd_remove_red_eye
>com.nrop19 E/Iconics: Wrong icon name: gmd_thumbs_up_down

https://design.google.com/icons/#ic_remove_red_eye
https://design.google.com/icons/#ic_thumbs_up_down

>https://github.com/mikepenz/Android-Iconics/blob/develop/google-material-typeface-library/src/main/java/com/mikepenz/google_material_typeface_library/GoogleMaterial.java
>gmd_remove_red_eye('\ue417')
>gmd_thumbs_up_down('\ue8dd')

How to find the icon name?

**Comment by mikepenz** [comment]
@gzlock you include this dependency: 
```gradle
compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar' 
```
?

**Comment by gzlock** [comment]
@mikepenz 
Sorry, forgot post this information.
I used Android Studio included
```
compile 'com.mikepenz:iconics-core:2.5.3@aar'
compile 'com.mikepenz:google-material-typeface:2.2.0.1@aar'
```
![image](https://cloud.githubusercontent.com/assets/2311740/12079466/226f5cee-b275-11e5-9aff-c1739e50b048.png)

But the target version is not the 2.1.0.1.original@aar

**Comment by gzlock** [comment]
The above picture is wrong,I selected this one
![image](https://cloud.githubusercontent.com/assets/2311740/12079477/6db77916-b275-11e5-9c0c-2267e2a38c53.png)

**Comment by mikepenz** [comment]
@gzlock you include the wrong font. 

The material design iconic is this one: http://zavoloklom.github.io/material-design-iconic-font/

You have to use this one:
```gradle
compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar' 
```
The **original** is important. 
Don't be confused about the 2.1.x instead of 2.2.x as this comes from a migration i have done. (i used the material iconic as default google material typeface for a few weeks)

https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md#font-addons

**Comment by gzlock** [comment]
@mikepenz Yep,that's a font version problem.

I have a new question: How to align text vertically center?
Not just the button view, the text view is like this
android:gravity and android:textAlignment have no effect
![image](https://cloud.githubusercontent.com/assets/2311740/12080004/bd3edf9e-b287-11e5-948f-ef32f8e8f18b.png)

Layout
```
<Button
android:id="@+id/video_thumb_up"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:text="@string/thumb_up"
android:gravity="center"
android:textAlignment="center" />

<Button
android:id="@+id/video_thumb_down"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:text="@string/thumb_down"
android:gravity="center"
android:textAlignment="center" />
```
String
```
<string name="thumb_up" translatable="false">{gmd_thumb_up} +1</string>
<string name="thumb_down" translatable="false">{gmd_thumb_down} -1</string>
```

**Comment by mikepenz** [comment]
@gzlock read this please: https://github.com/mikepenz/Android-Iconics/issues/121
