### ISSUE TITLE
Provided default fonts are not recognized

### ISSUE THREAD

**Issue by localh0rzd** [mikepenz/Android-Iconics#124]
Hi,

I am trying to add the library to a new project, but am failing at getting it to work inside an AppCompatActivity.

I configured the project accordingly to the README and added all provided fonts to my build.gradle, but nonetheless it does not work for some reason.

Both ```TextView``` and ```IconicsTextView``` print the string as is. The string ```abc{hif-test}defgh{faw-adjust}ijk{fon-test1}lmnopqrstuv{fon-test2}wxyz``` generates the following logcat lines:

```
E/Iconics: Wrong fontId: hif_test
E/Iconics: Wrong fontId: faw_adjust
E/Iconics: Wrong fontId: fon_test1
E/Iconics: Wrong fontId: fon_test2
```

I'm able to build and run the demo app, so the build system is probably not at fault.

Snippet of Acitivity in question defining the Layout Inflater:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    LayoutInflaterCompat.setFactory(getLayoutInflater(), new  IconicsLayoutInflater(getDelegate()));
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_login);
/* ... */ }
```
View used for testing:

```
<TextView
    android:text="abc{hif-test}defgh{faw-adjust}ijk{fon-test1}lmnopqrstuv{fon-test2}wxyz"
    android:textColor="@android:color/black"
    android:layout_width="wrap_content"
    android:layout_height="56dp"
    android:textSize="16sp"/>
```

**Comment by mikepenz** [comment]
@localh0rzd `hif`, and `fon` are just samples from the demo, those are not contained inside the provided font addons. 

A list of all font addons can be found here:
https://github.com/mikepenz/Android-Iconics#available-fonts

`faw-adjust` should be found. This is inside the following font addon
```gradle
compile 'com.mikepenz:fontawesome-typeface:4.5.0.1@aar'
```

If it does not recognice the font, can you please try to register the font via:
```java
Iconics.registerFont(new FontAwesome());
```
Shown in the sample here: https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17

Have you enabled proguard for your application? Normally it should autodetect the font

**Comment by localh0rzd** [comment]
First off, thank you for your lightning fast answer.

After adding the registerFont() call inside the onCreate() of my Application class, it works. I didn't expect that I have to register the fonts if I use a custom Application class.

>Have you enabled proguard for your application? Normally it should autodetect the font

Not using ProGuard.

**Comment by mikepenz** [comment]
@localh0rzd in general it should automatically detect the fonts, but it seems in some cases it can't. 
The problem is the `iconics-core` doesn't know about the addons. I would try to detect them via a string ressource which defines the class of the font addon. if this is found i try to init the class. 

I will check it again if i can find what's wrong. 

If the fonts are used via code this does not happen, just via xml. 

Thanks.

**Comment by mikepenz** [comment]
@localh0rzd ok just tried it in the sample. the detection algorithm detects the fonts correctly. Not sure why it may file in your case. 

If you could debug into the `Iconics.init(ctx)` (Line 52) method it would be great. Which FONTS does it detect?

**Comment by localh0rzd** [comment]
@mikepenz The resulting fonts-array in line 54 is empty.

**Comment by mikepenz** [comment]
@localh0rzd thanks. 

Could you also please try what is returned if you call the `getFields(Context ctx)` method on the `GenericsUtil`
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/utils/GenericsUtil.java#L20

Like:
```java
GenericsUtil.getFields(this)
```

**Comment by localh0rzd** [comment]
Oh, shame on me. I somehow managed to have an applicationId inside my build.gradle, which does not correspond with the package name of the application. Because of this, the generated packages are not found by ```return Class.forName(packageName + ".R$string");```, as the packageName seems to be derived from the gradle file.

I'm sorry for wasting your time. :D

**Comment by mikepenz** [comment]
@localh0rzd no you don't wasted my time :D. Now i know why in some rare cases people still have to register the font addons :D. 

Thank you so much for your time, and for debugging and for finding this case where the `R`-Detection fails. 

Thanks
