### ISSUE TITLE
Not showing on overflow menu

### ISSUE THREAD

**Issue by ayublin** [mikepenz/Android-Iconics#125]
Is it possible to use the icon on overflow menu item? Here is my menu item:

```xml
<item
    android:id="@+id/action_settings"
    android:orderInCategory="100"
    android:title="@string/action_settings"
    app:showAsAction="never" />
```

Then here is how I assign the icon:

```java
menu.findItem(R.id.action_settings).setIcon(
    new IconicsDrawable(MainActivity.this, GoogleMaterial.Icon.gmd_settings)
            .actionBar().color(Color.WHITE)
);
```

But the icon won't appear, it works for action bar item though.

Thanks!

**Comment by mikepenz** [comment]
@ayublin no Android doesn't allow you this. There are some "hacks" which might allow you to show an icon there, but this is not **Android-Iconics** specific

http://stackoverflow.com/questions/18374183/how-to-show-icons-in-overflow-menu-in-actionbar

**Comment by ayublin** [comment]
Ah, sorry, I didn't aware of this, I just checked and indeed, the project that I saw having icons inside overflow menu has the "hacks" you referenced. Thank you for the blazing quick response!
