### ISSUE TITLE
Use inside default navigation drawer

### ISSUE THREAD

**Issue by jeetdholakia** [mikepenz/Android-Iconics#126]
I'm using this library inside the default navigation drawer but there seems no provision to use it as android:icon attribute. How do I use it?

I'm aware you have a material navigation drawer library,but I'd be happy to use this with default nav drawer...

**Comment by mikepenz** [comment]
@jeetdholakia you can't use them via `xml`. But you can set them programmatically as `Drawable` 
https://github.com/mikepenz/Android-Iconics#use-as-drawable
