### ISSUE TITLE
Problem with ForegroundColorSpan etc

### ISSUE THREAD

**Issue by jonathan-caryl** [mikepenz/Android-Iconics#127]
If I use `ForegroundColorSpan` or `TextAppearanceSpan` to style some text, then when I use 

    LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));

I find my styled text becomes unstyled text. I've written a very simple [test app](https://github.com/jonathan-caryl/IconicsTest) that shows the issue.

The problem seems to be down in `IconicsUtils` `findIconsFromEditable` where it's getting `StyleSpan`s from the `Editable` which doesn't cover `ForegroundColorSpan` or `TextAppearanceSpan`. Perhaps the base `MetricAffectingSpan` should be used there instead?

**Comment by mikepenz** [comment]
@jonathan-caryl i even found that i can use the `ParcelableSpan` which is used by the other spans too. Tested it right now, and seems to work. 

Thank you so much for the sample app and the detailed report. A new version will be out soon ;)

**Comment by jonathan-caryl** [comment]
Thanks for the quick response!
