### ISSUE TITLE
Is it possible to use this with official Android support FloatingActionButton?

### ISSUE THREAD

**Issue by tachang** [mikepenz/Android-Iconics#128]
http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html

This is the xml you generally use. Do I put something in android:src ?
I tried android:src="{faw-check}" and a few others but not sure.

```
    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="16dp"
        android:clickable="true"
        android:src="@drawable/ic_done"
        app:layout_anchor="@id/viewA"
        app:layout_anchorGravity="bottom|right|end"/>
```

**Comment by tachang** [comment]
Just adding to this:

**Comment by tachang** [comment]
If there is an easy way to do this in xml I'd love to know but I did this in code:

```

        FloatingActionButton floatingActionButton = (FloatingActionButton) convertView.findViewById(R.id.my_button);

        IconicsDrawable icon = new IconicsDrawable(convertView.getContext())
                .icon(FontAwesome.Icon.faw_android)
                .color(Color.RED)
                .sizeDp(24);
        floatingActionButton.setImageDrawable(icon);
```

**Comment by mikepenz** [comment]
@tachang as the `FloatingActionButton` extends from `ImageView` you can set the drawable via xml if you use the `IconicsLayoutInflater` https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional

Then you can do this:
https://github.com/mikepenz/Android-Iconics#as-imageview-only-available-if-you-follow-step-3-or-inject-the-context

**Comment by ayublin** [comment]
I have followed the instruction and able to show an Icon in the form of `ImageView`, but somehow I can't get it to work on FAB:

    <android.support.design.widget.FloatingActionButton
    	android:id="@+id/fab"
    	android:layout_width="wrap_content"
    	android:layout_height="wrap_content"
    	android:layout_gravity="bottom|end"
    	android:layout_margin="@dimen/fab_margin"
    	app:ico_color="#ffffff"
    	app:ico_icon="gmd-list-filter"
    	app:ico_size="48dp"
    	/>

I am not sure if this is related, but I am getting this message on logcat:

    I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

It will disappear if I remove the `IconicsLayoutInflater`.

Anyone has got the chance to test if the Icon can work with FAB?

Thanks!

**Comment by mikepenz** [comment]
@ayublin i already used it with the official FAB as it extends from `ImageView`. So i can confirm it is compatible.

I never saw the message you get in the log. Interesting :O
