### ISSUE TITLE
problem using an icon in an activity or xml file

### ISSUE THREAD

**Issue by mikekaraa** [mikepenz/Android-Iconics#129]
Hi please provide straight forward code for using an icon in an activity or xml file?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional
https://github.com/mikepenz/Android-Iconics#as-imageview-only-available-if-you-follow-step-3-or-inject-the-context
