### ISSUE TITLE
Always getting X instead of an icon

### ISSUE THREAD

**Issue by blipinsk** [mikepenz/Android-Iconics#130]
Hi! I've got an issue with the library... 
No matter how I use it (either with `IconicsImageView` or with `IconicsDrawable` with a regular `ImageView`), no matter which icon I wanna display (from which set) I always get an image of an X within a rectangle. 

This particular example was achieved with:

    <com.mikepenz.iconics.view.IconicsImageView
        android:layout_width="72dp"
        android:layout_height="72dp"
        app:iiv_color="@android:color/holo_red_dark"
        app:iiv_icon="gmd-favorite"/>

![](https://cloud.githubusercontent.com/assets/6371716/12577980/53ca6bf2-c41e-11e5-952f-503d4675841e.png)

My dependencies include:

    compile 'com.mikepenz:iconics-core:2.5.5@aar'
    compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar'

It's a Nexus 5 with Android 6.0.1

Any idea what might be the issue?

**Comment by mikepenz** [comment]
@blipinsk does this also happen with the sample app?

**Comment by blipinsk** [comment]
@mikepenz surprisingly, no.

**Comment by mikepenz** [comment]
@blipinsk any custom font set for the whole application which may overwrite the icon font? Proguard? Any log outputs which could state that it can't find the font?

**Comment by blipinsk** [comment]
@mikepenz 

 1. No custom font set for the whole application.
 2. Proguard disabled
 3. Nothing in logs...

thats so weird.

**Comment by blipinsk** [comment]
Might compiling for Java 1.8 be the issue?

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by mikepenz** [comment]
@blipinsk weird enough. i can test with java 1.8 if it changes something

**Comment by blipinsk** [comment]
GoogleMaterial.java:108 throws an exception: `java.lang.RuntimeException: Font asset not found fonts/google-material-font-v2.1.0.1.ttf"

**Comment by mikepenz** [comment]
You use Android Studio with default build?

**Comment by blipinsk** [comment]
@mikepenz Ok, I found the issue. I am using some fonts in my app. They are stored in `assets/Fonts` (with a capital `F`). As I found out looking through the `/build`, the `google-material-font-v2.1.0.1.ttf` has been put inside my `Fonts` directory instead of `fonts` directory. And your library is expecting the font to be in `fonts/google-material-font-v2.1.0.1.ttf` and not in `Fonts/google-material-font-v2.1.0.1.ttf".

**Comment by mikepenz** [comment]
@blipinsk ok to be honest i would have never guessed somthing like that. 
Interesting enough that the build does not fail or notify about conflicting folders. Upper/Lower-case things are always bad. :/

Thanks for the detailed info. I hope it helps others in the future.

**Comment by blipinsk** [comment]
Thanks for help anyways!

**Comment by sytolk** [comment]
The same problem https://github.com/mikepenz/Android-Iconics/issues/133 but I don`t have assets/fonts :)

**Comment by 7ShaYaN7** [comment]
#927 as well.
