### ISSUE TITLE
for Maven users wrong dependency

### ISSUE THREAD

**Issue by sytolk** [mikepenz/Android-Iconics#131]
I have maven project (instead of gradle) but google-material-typeface package its have wrong dependency to Group:Android-Iconics and artifact:library-core you can check here in Compile Dependencies:
http://mvnrepository.com/artifact/com.mikepenz/google-material-typeface/2.2.0.1
Maybe its obsolete I have include the new one Group:com.mikepenz artifact: iconics-core
 Its need to exclude it in my pom.xml to compile the project

```xml
<dependency>
            <groupId>com.mikepenz</groupId>
            <artifactId>iconics-core</artifactId>
            <version>2.5.5</version>
            <type>aar</type>
        </dependency>

        <dependency>
            <groupId>com.mikepenz</groupId>
            <artifactId>google-material-typeface</artifactId>
            <version>2.2.0.1</version>
            <type>aar</type>
            <exclusions>
                <exclusion>
                    <groupId>Android-Iconics</groupId>
                    <artifactId>library-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by mikepenz** [comment]
@sytolk sorry i can't support anything else than the default build tools and setup from Android. The `pom.xml` you linked above is automatically generated by the gradle build and not managed on my side.

If you have s olution how this can be changed let me know.

Sorry for this.

**Comment by sytolk** [comment]
Maybe its have some wrong in gradle-mvn-push.gradle this:
```
pom.groupId = GROUP 
pom.artifactId = POM_ARTIFACT_ID
```
for the dependency this parameters is wrong replaced for the GROUP with Project name `Android-Iconics` instead of defined in gradle.properties `GROUP=com.mikepenz` and POM_ARTIFACT_ID with module name `library-core` instead of `POM_ARTIFACT_ID=iconics-core`

I dont know what is wrong with gradle build but only solution that I have is to exclude wrong dependency name for the core library in google-material-typeface and include the right one manually in my pom.xml

**Comment by sytolk** [comment]
the same thing for `material-design-iconic-typeface` all libraries
```
compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar' 
compile 'com.mikepenz:material-design-iconic-typeface:2.2.0.1@aar'
compile 'com.mikepenz:fontawesome-typeface:4.5.0.1@aar'
compile 'com.mikepenz:octicons-typeface:3.2.0.1@aar'
compile 'com.mikepenz:meteocons-typeface:1.1.0.1@aar'
compile 'com.mikepenz:community-material-typeface:1.3.41.1@aar'
compile 'com.mikepenz:weather-icons-typeface:2.0.10.1@aar'
compile 'com.mikepenz:typeicons-typeface:2.0.7.1@aar'
compile 'com.mikepenz:entypo-typeface:1.0.0.1@aar'
compile 'com.mikepenz:devicon-typeface:2.0.0.1@aar'
compile 'com.mikepenz:foundation-icons-typeface:3.0.0.1@aar'
compile 'com.mikepenz:ionicons-typeface:2.0.1.1@aar'
```
have wrong dependency to groupId = Project Name artifactId=module name
```xml
<groupId>Android-Iconics</groupId>
<artifactId>library-core</artifactId>
```

**Comment by mikepenz** [comment]
@sytolk i just double checked again. the `gradle-mvn-push.gradle` uses the original `maven` plugin from gradle. and the pom's are auto generated. seems there may be some problems with the maven plugin. 

perhaps jcenter will have different poms. have to try it
