### ISSUE TITLE
mising icon 

### ISSUE THREAD

**Issue by sytolk** [mikepenz/Android-Iconics#134]
I have in sample app gmd_bug_report icon but its missing in code
google-material-typeface v. 2.2.0.1
```java
GoogleMaterial.Icon.gmd_bug_report //this static enum not exist
```
gmd_exit_to_app is missing too

**Comment by mikepenz** [comment]
@sytolk as written in the other thread you mix up two font addons. 

You want to use the following: 
`compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar'`
