### ISSUE TITLE
Wrong fontId when switching flavours

### ISSUE THREAD

**Issue by carstenbaumhoegger** [mikepenz/Android-Iconics#136]
Hi Mike!
I'm using your lib in an App that has various flavours with different applicationIds.
I implemented the lib and everything worked fine. But when I switch the flavour, no icon get's shown and I get "Wrong fontId" for every icon in the log.
When I switch back to the first flavour everything works fine again.
I did clean builds to make sure this isn't the problem but that has no effect.

Do you know what could cause this problem?
Thanks in advance!
Carsten

**Comment by mikepenz** [comment]
@carstenbaumhoegger 

Seems like the auto addon resolver can't find the `R` class when you switch your applicationIds, The easiest solution is that you just `register` your font's programmatically. So the `Iconics` class can resolve the font. 

https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17

for `GoogleMaterial` this would look like:

```java
Iconics.registerFont(new GoogleMaterial());
```

**Comment by carstenbaumhoegger** [comment]
thanks for this super fast response, solved it!

**Comment by mikepenz** [comment]
Great ;)
