### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by theblitz** [mikepenz/Android-Iconics#137]
It seems that some of the icons that appear here no longer appear in the newest version of Google Material Icons - 'com.mikepenz:google-material-typeface:2.2.0.1@aar'
They do exist in the older version.

For example, the "person" icons.

**Comment by mikepenz** [comment]
@theblitz you do not use the `GoogleMaterial` font but the `Material Design Iconic` font. I had to rename those because of confusion. So the original `GoogleMaterial` is the following:

```gradle
compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar'
```

**Comment by Rainer-Lang** [comment]
@theblitz I like to use the community icons. There are many (maybe all) of the original Google icons included.

**Comment by theblitz** [comment]
Is there any reason not to include more than one of the icon libraries? Will it make the app a lot bigger?
None of them seem to have all the icons I want.

**Comment by mikepenz** [comment]
@theblitz the size depends on the font. the icon font with the most icons is the `community material design icons` with 188kb 
https://github.com/mikepenz/Android-Iconics/blob/develop/community-material-typeface-library/src/main/assets/fonts/materialdesignicons-v1.3.41.ttf

So it depends

**Comment by Rainer-Lang** [comment]
@theblitz You can create your own font with only icons inside which you really use. Mike has a link in the readme about this.

**Comment by Templarian** [comment]
Just because I see traffic coming from this GitHub issue I want to point out that starting from v1.5.54 all the optimized SVG's can be downloaded at the page below. This should make the process of creating subsets easier ([icomoon](https://icomoon.io/) / [grunt-webfont](https://github.com/sapegin/grunt-webfont)), until this feature is offered on the site.

https://materialdesignicons.com/design

**Comment by AAverin** [comment]
@mikepenz regarding to what @Templarian mentioned, looks like some of the icons present on Community Material Icons page are missing from the font that is provided by the library.
How often is font updated and would it be possible to make sure it stays up to date?
