### ISSUE TITLE
Support spin?

### ISSUE THREAD

**Issue by dongseok0** [mikepenz/Android-Iconics#138]
Hi, 

Is it supporting spin?
( https://github.com/JoanZapata/android-iconify#icon-options )

**Comment by mikepenz** [comment]
@dongseok0  I understand that you may have seen this in a similar library. But I do not want to copy the other libs featue, even if it would be useful in some cases.

Sorry for this. I hope you understand it.

**Comment by Rainer-Lang** [comment]
@mikepenz Maybe as a feature for a future release? What would be also useful, if there would be some animations.... :)

**Comment by dongseok0** [comment]
Yeah, I think it's not copying other libs feature. It's feature of FontAwesome. 
Anyways, thanks!
