### ISSUE TITLE
XML + Menus

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#141]
How to use it with menus defined in xml? I want to replace a `android:icon="..."` menu tag with one that uses your library...

Is it only possible to set menu icons manually in code?

**Comment by josmanperez** [comment]
@MFlisar  this can't be done. Menu does not extend from `TextView `or `ImageView`. See this for reference:
[https://github.com/mikepenz/Android-Iconics/issues/119](url)

**Comment by MFlisar** [comment]
Thanks. Wouldn't it be possible to make a custom `MenuInflater` for that?

**Comment by josmanperez** [comment]
@MFlisar yes, but you have to do it programmatically. What you have to do is, in the activity or fragment retrieve the navigation View that you are implementing and then get the menu and then the menuItem and finally you can set up your icon as a `drawable ` [https://github.com/mikepenz/Android-Iconics#use-as-drawable](url)

Something like this:

`Menu menuNav = navigationView.getMenu();
MenuItem menuItem = menuNav.findItem(R.id.your_nav_icon);
menuItem.setIcon(new IconicsDrawable(this).icon(Ionicons.the_icon_you_want));`

Hope it helps.

**Comment by MFlisar** [comment]
Thanks, that's no problem, it's just a thing you have to do when converting your project... What I'm currently doing though...

**Comment by josmanperez** [comment]
Glad it helps :)

**Comment by mikepenz** [comment]
@MFlisar theoretically it would be possible to have a custom `ManuInflater` allwing this. The problem is that the `MenuInflater` is not as extensible as the `SupportLayoutInflater` is. That means I would have to copy and paste all classes from the android source code, which has a few bad side effects. If Google updates something we will miss this. I tried it once to `extend` the `MenuInflater` but I can't hook into the correct methods...

If someone has ideas, I am always happy about pull requests ;)

**Comment by mikepenz** [comment]
@josmanperez thanks for answering

**Comment by MFlisar** [comment]
I want to follow up on this. What would you think of a custom wrapper, that inflates the menu with the provided menu inflator and than just reparses the xml file, checks for iconics tags and than updates the icons in the menu with the corresponding settings?

Speed is not that good (xml is parsed 2 times) but it's compatible with any android version and it's independent from any `MenuInflator` implementation...

I would need a function where I pass in a list of xml attributes with their values and get in return an IconicsDrawable, is that already existing somewhere?

**Comment by ssuukk** [comment]
Wouldn't Android Studio still complain with "Error:(5, 23) String types not allowed (at 'icon' with value '{gmd_accessibility}')."?

I was very happy I found this project until I realised all my app icons appear in either preferences or ActionBars :D

**Comment by MFlisar** [comment]
I'm not sure. Never saw an error just a warning if you use strings directly in xml.

Btw, some if the iconic libraries have defined the strings and you can use them like following:

    icon="@string/gmd_accessibility"
