### ISSUE TITLE
Wrong position - how to correctly replace default google icons

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#142]
I tried to replace the original `gmd_play_arrow` icon with the one from this library... Setting the original icon was working perfectly (it's centered), using this library I have to manually adjust the position...

I use the play button in two places, once in a custom view and once in a floating action button:

**Custom View**

    Drawable d = ContextCompat.getDrawable(getContext(), R.drawable.ic_play_arrow_white_48dp);

Replaced with:

    Drawable d = new IconicsDrawable(context, GoogleMaterial.Icon.gmd_play_arrow).sizeDp(48).paddingDp(2).color(Color.WHITE);

**FAB**

     fabPlay.setImageResource(R.drawable.ic_play_arrow_white_24dp);

Replaced with:

     fabPlay.setImageDrawable(new IconicsDrawable(fab.getContext()).icon(GoogleMaterial.Icon.gmd_play_arrow).color(Color.WHITE).sizeDp(24).paddingDp(1));

**Result**

On the left you see what it looks like before using iconics, on the right how it looks like afterwards.
The first row shows the custom view, the second row shows a FAB...
As you can see, the size is not the same + the positioning is not correct as well, the icon is off to the left when using iconics

![icons](https://cloud.githubusercontent.com/assets/2437726/13014125/9c4b9666-d1b2-11e5-9edd-cab378ae9240.png)

**Comment by mikepenz** [comment]
@MFlisar the icons use the positioning defined in the font. If this is wrong in the font provided by Google it will also be the same inside the app.

Hmmmm ok i just messured the distanced from the arrow on the right, and it is exactly in the center. The simbol is just bigger so it seems it is off the center but that coms automatically because this is a triangle xD The only thing you have to do is provide the correct image scaling and define the `IconicsDrawable` with the correct size + padding

**Comment by MFlisar** [comment]
**Size**

I have no tool to measure at home, but calculating with the pixels shown in my drawing program I see following relations (vertical center of arrow):

Left:
* Space left of arrow in circle: 67px
* arrow width: 60px
* space right of arrow in cirle: 49px

Right:
* Space left of arrow in circle: 100px
* arrow width: 97px
* space right of arrow in cirle: 40px

So the ratio of left : width : right is not anywhere near the same... It's appearently of to the left...

But that seems to be caused by the font... As you said...

**Size**

So it's not possible to create a drawable of a special size the way I tried it? I have to include the padding in the drawable as it will always stretch to the full size otherwise?

**Comment by mikepenz** [comment]
@MFlisar that can't be true. I can say by eye that on the right the space from the arrow to the end of the dark circle is not twice as much on the right. (the red rectangles are both the same width)
![9c4b9666-d1b2-11e5-9edd-cab378ae9240](https://cloud.githubusercontent.com/assets/1476232/13015449/633240b2-d1b9-11e5-8c58-7e212157a238.jpg)

First you should change the `ScaleType` of that FAB to not scale the image. If it does not scale it will work automatically without you defining the padding.

**Comment by MFlisar** [comment]
You missunderstood... You have to compare left with right... The right side is your library and there the triangle is centered (from a object point of view)...

**Comment by mikepenz** [comment]
@MFlisar hmmm ok then I don't understand the issue. As shown in my image the triangle is centered exactly. It only has a different size than on the right. And the size can be changed by defining the correct size and changing the `ScaleType` to one which does not scale up the image

**Comment by MFlisar** [comment]
The problem is that the original icon is NOT centered exactly... But as you said, that's probably because it's wrong in the font (compared to the original icon)

The tipp with the `ScaleType` worked...

**Comment by mikepenz** [comment]
@MFlisar ok now we come closer. The font is correct then. The font has all icons perfectly centered. It does not contain the different paddings the **png**'s from Google contain. You can adjust the `IconicsDrawable` to get it pixel perfect too, but this can't be done on the library side. There is no rule how Google positioned the drawables. Sorry that it took me so long to see the issue.


ok great ;)

**Comment by MFlisar** [comment]
Ok thanks, good to know that the font does center all icons and google does have variable positions...

**Comment by mikepenz** [comment]
@MFlisar yeah it is really hard. But in most cases i still prefer the centered once. You can still adjust the positioning pixelperfect via the `IconicsDrawable` without loosing the always scaling properties ;)

**Comment by TheAndroidMaster** [comment]
@MFlisar a way to solve this would be to use the following settings on the icon:
sizeDp - 56
paddingDp - 8
iconOffsetXDp - 4

The problem with the icon is that it's centered by the sides of the icon and doesn't take into account the actual proportions. Since more of the icon is to the left of it's actual center, it makes it look like the center is slightly to the left of where it really is. The offset of 4 dp fixes that problem, but an option for the library to measure the size of the icon and change the offset accordingly would be nice.

**Comment by mikepenz** [comment]
@TheAndroidMaster could you please add some images to show the acutal issue?

**Comment by TheAndroidMaster** [comment]
@mikepenz take a look at [this](https://medium.com/@erqiudao/the-play-button-is-not-optical-alignment-4cea11bda175#.70spgjyeg), it might help ;)

**Comment by mikepenz** [comment]
@TheAndroidMaster yeah this would be awesome, but I am afraid this is not possible. I do not know of a solution (and I did not find one) how to calculate the arc center point of a path i paint on a canvas. 

If you or someone else knows how to do it. Please open a pull request ;)
