### ISSUE TITLE
FloatingActionButton icon size too small

### ISSUE THREAD

**Issue by AngleV** [mikepenz/Android-Iconics#143]
Hi mike

I m using your lib to place an icon on a FloatingActionButton like this 
```java
fab.setImageDrawable(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_share)
.color(Color.WHITE).sizeDp(16));
```
but the icon is too small.. even when i increase the sizeDp value.

the xml of fab has layout width and height set to 30dp.

**Comment by mikepenz** [comment]
@AngleV do you have the correct `scaleType` for your FAB? Do you have defined any padding? If you define the size of the `IconicsDrawable` to **16dp** the drawable itself will be that size. But that must not mean that the `ImageView` will display it exactly like this if you have defined a `scaleType` or if there is any padding on that view

**Comment by AngleV** [comment]
@mikepenz 

this is my fab's layout

```
           <android.support.design.widget.FloatingActionButton
                android:id="@+id/fab_share"
                android:layout_marginTop="@dimen/fab_small_margin_top"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:layout_below="@id/detail_image"
                android:layout_alignParentRight="false"
                android:layout_marginLeft="20dp" />
```

**Comment by mikepenz** [comment]
@AngleV could you please also add a screenshot. seems fine. should exactly display as **16dp** then.

**Comment by AngleV** [comment]
set it to SizeDp(32) and i get this 

![screenshot_2016-02-13-21-41-21-1](https://cloud.githubusercontent.com/assets/7430985/13029652/c6fb6344-d29a-11e5-94e5-51e8e2e1c5ef.png)

**Comment by Rainer-Lang** [comment]
I'm not sure, but from reading the docu http://developer.android.com/intl/es/reference/android/support/design/widget/FloatingActionButton.html
```Floating action buttons come in two sizes: the default and the mini. The size can be controlled with the fabSize attribute.```
There are "only" 2 sizes possible.

And for my understanding the original fab has always a padding. Maybe this could be your "problem" here...

**Comment by AngleV** [comment]
@Rainer-Lang 

i tried to padding="0dp"

didn't work :(

**Comment by mikepenz** [comment]
@AngleV great ;). 

@Rainer-Lang thanks for helping ;)

**Comment by Rainer-Lang** [comment]
@AngleV Could you try one of the "normal" sizes?

**Comment by AngleV** [comment]
well
it does not work as it should be after all.

even at mini or normal size the size of icon is fixed and not take account the sizedp value

**Comment by Rainer-Lang** [comment]
Did you also try something like ```app:ico_padding="4dp"```?

**Comment by mikepenz** [comment]
@AngleV as mentioned above. That's the behavior of the FAB (of the ImageView) and the `Drawable` can't do anything against this.

**Comment by Rainer-Lang** [comment]
@AngleV "Bigger" was for me a problem, but I wanted the icon inside the fab smaller - and this helped me.

**Comment by AngleV** [comment]
@Rainer-Lang 
right now i got the same problem..The icon inside fab is huge. i set app:ico_padding="4dp" as you mentioned but no luck

**Comment by Rainer-Lang** [comment]
@AngleV This is my fab - and it has a small "+"-icon:
```
<android.support.design.widget.FloatingActionButton
	android:id="@+id/fab"
	android:clickable="true"
	android:layout_width="wrap_content"
	android:layout_height="wrap_content"
	app:elevation="6dp"
	app:borderWidth="0dp"
	app:pressedTranslationZ="12dp"
	android:layout_gravity="bottom|end"
	app:ico_size="24dp"
	app:ico_padding="4dp"
	app:ico_icon="cmd_plus"
	app:ico_color="@android:color/white"
	app:fab_colorPressed="@color/accent_pressed"
	app:rippleColor="@color/ripple"
	app:layout_anchorGravity="bottom|right|end"
	tools:src="@drawable/fab_add">
</android.support.design.widget.FloatingActionButton>
```

**Comment by juanlabrador** [comment]
Please, try with android:scaleType="center"

**Comment by roslamir** [comment]
It works. Using android:scaleType="center" enlarges the ImageView inside the FAB.

**Comment by RupeshYadav** [comment]
Make this entry in dimens


<dimen name="design_fab_image_size" tools:override="true">36dp</dimen>

Like_
<resources xmlns:tools="http://schemas.android.com/tools">
    <dimen name="fab_margin">16dp</dimen>
      
    <dimen name="design_fab_image_size" tools:override="true">59dp</dimen>
</resources>

You can adjust its size according to your need e.g., 36/42/54 dp

**Comment by RupeshYadav** [comment]
Make this entry in dimens
 
`<dimen name="design_fab_image_size" tools:override="true">36dp</dimen>`

Ex
`<resources xmlns:tools="http://schemas.android.com/tools">
    <dimen name="fab_margin">16dp</dimen>
    
    <dimen name="design_fab_image_size" tools:override="true">42dp</dimen>

</resources>`

You can adjust its size according to your need.

**Comment by casaurabhkhatri** [comment]
The simple solution is :

For decreasing:
            android:scaleX=".8"
            android:scaleY=".8"

For Increasing:
            android:scaleX="1.2"
            android:scaleY="1.2"

You can easily edit it. :+1:

**Comment by AhmadullahSaikat** [comment]
Please use `android:scaleType="center"` for your issue.

For custom size:
```
        app:fabCustomSize="40dp"
        app:fabSize="auto"

```

For maximum ImageSize: `app:maxImageSize="20dp"`

**Comment by AndroidDeveloperLB** [comment]
Suppose I want a FAB that has an icon, and I want to have padding around the icon and have the FAB of a custom size, why this doesn't work for me:

```
            <com.google.android.material.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" android:padding="8dp" android:scaleType="center"
                app:backgroundTint="#ffc02e" app:fabCustomSize="30dp" app:fabSize="auto"
                app:srcCompat="@drawable/..."/>
```
?

**Comment by JunYou-Park** [comment]
change
`app:maxImageSize="45dp"`
