### ISSUE TITLE
Iconic Image view set setColorRes()

### ISSUE THREAD

**Issue by yaserseyedi** [mikepenz/Android-Iconics#144]
When I set ColorRes for `IconicsImageView` the color does not apply
```java
private IconicsImageView messageIcon;
IconicsImageView messageIcon = (IconicsImageView) parent.findViewById(R.id.message_icon);
messageIcon.setColorRes(R.color.gray);
```

Even if I set iiv_color on the xml or not

**Comment by mikepenz** [comment]
@yaserseyedi your `IconicsImageView` has an `IconicsDrawable` set?
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/view/IconicsImageView.java#L165

**Comment by yaserseyedi** [comment]
yes it is

**Comment by mikepenz** [comment]
@yaserseyedi  can you please try it again with v2.5.7? Sorry for the late answer. I was pretty busy the last few days
