### ISSUE TITLE
Iconics with android SpannableString

### ISSUE THREAD

**Issue by kuno** [mikepenz/Android-Iconics#145]
hi

Dose any one know it is possible to use Iconics with Android [SpannableString](http://developer.android.com/reference/android/text/SpannableString.html)  directly ?

It seems once I enabled Iconics in an activity, then `SpannableString` dose not work any more ...

**Comment by mikepenz** [comment]
@kuno you can directly use the API if you want:

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L139

Can you be a bit more specific why `SpannableString` does not work?

**Comment by kuno** [comment]
@mikepenz 

Thanks for you reply.

So you seems suggestion, if I have a `SpannableString` in an activity, then I can not enable `Iconics` in the level of whole activity, like [readme](https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional) said.

The only way to do it is to render text specifically by directly Using the api.

Am I understanding correctly  ?

**Comment by kuno** [comment]
The problem in my case was once I enable `Iconics` in an activity by doing [this](https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional) in `onCreate` method.

Then the normal `ClickableSpan` dose not work anymore. It do not render text correctly, and nor response to user clicking.

**Comment by mikepenz** [comment]
@kuno with the current version I remember all `ParcableSpan`s and reapply them afterwards. May I can change it to `CharacterStyle` as the `ClickableSpan` directly extends the `CharacterStyle` interface

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/utils/IconicsUtils.java#L37

**Comment by kuno** [comment]
@mikepenz 

So you plan to fix this in future release ?

Another off-topic question: how to use `Iconics` in an adapter ?

**Comment by mikepenz** [comment]
@kuno can you please try it again with v2.5.7?

**Comment by kuno** [comment]
@mikepenz 

Thanks, the `v2.5.8` release did solve  my problems.

**Comment by mikepenz** [comment]
great :)
