### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by pperliti** [mikepenz/Android-Iconics#149]
Hi,
my app has a single activity and many fragments. I use MaterialDrawer and Android-Iconics.
My /res/values/strings.xml contains many {faw-...} strings:

```xml
<string name="label_generic_list_item_location">{faw-hospital-o} %s</string>
<string name="label_generic_list_item_healthservice">{faw-stethoscope} %s</string>
<string name="label_generic_list_item_practitioner">{faw-user-md} %s</string>
```
I use these strings within an Adapter's view inside a RecyclerView:

```java
@Override
public void onBindViewHolder(AvailabilityViewHolder holder, int position) {
   //...
   /* Bind contents */
   String appointmentLocation = "...";
holder.subTextView.setText(recyclerView.getContext().getString(R.string.label_generic_list_item_location, appointmentLocation));            
   //...
}
```

At the very beginning of the main Activity I do:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
    //...
    super.onCreate(savedInstanceState);
    //...
}
```

On my Android 4.1/4.4 I'm experiencing frequent app crashes that suddenly disappear when I comment/remove the line 

`LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));`

App crashes sometimes during view rendering, other times while scrolling the recycler view.
I also tried your alternative (injecting context) but nothing changed.

Do you have any idea why it's happening? 

Here are somesome logs attached.
[crash-1.txt](https://github.com/mikepenz/Android-Iconics/files/147972/crash-1.txt)
[crash-2.txt](https://github.com/mikepenz/Android-Iconics/files/147973/crash-2.txt)
[crash-3.txt](https://github.com/mikepenz/Android-Iconics/files/147975/crash-3.txt)
[crash-4.txt](https://github.com/mikepenz/Android-Iconics/files/147982/crash-4.txt)

Thank you in advance.
Paul

**Comment by mikepenz** [comment]
@pperliti just checked the error logs. They are really weird. They show no reference to the `Android-Iconics` library.

Do you have any special `Spannable`s set on your text, or anything else? I never experienced such issues before, and I also use the `Iconics` a lot

**Comment by mikepenz** [comment]
@pperliti I know it may not already be the solution, but what if you would have the icon as a separate `IconicsImageView` prior to the `TextView`? Would give you more flexibility and you would not have to use the `IconicsLayoutInflater`

**Comment by pperliti** [comment]
Hi Mike, 
I don't have any `Spannable` in my code. Instead I have simple `TextView`s (in my fragments): I'm just setting their text value with `getString(R.string.label_generic_list_item_location, parameter)` where `R.string.label_generic_list_item_location, parameter` refers to `<string name="label_generic_list_item_location">{faw-hospital-o} %s</string>` in my `strings.xml` and `parameter` it's a simple string. `{faw-hospital-o}` refers to a FontAwesome icon.
Unfortunately I cannot provide any test-case, since my app it's still in an early stage and depends on a remote server REST calls.

**Comment by mikepenz** [comment]
@pperliti ok just debugged it via the sample. The issue is that if you use the automatic detecing of fonts within a `RecyclerView` that it reuses the fields and this causes an inconsistent state as it switches out everything very fast. 
To be able to automatically also replace the placeholders with an icon if you set the text, the `IconicsFactory` registers an `addTextChangedListener` which will fire if the text is changes. This is to takes a short time, also the modification of the string and replacing with the icon. Which can cause your described exception.

You can easily fix this if you directly set the icon within the adapter with the following code:

```java
view.setText(Iconics.style(ctx, new SpannableString("{faw-hospital-o}")));
```

**Comment by pperliti** [comment]
Thank you
