### ISSUE TITLE
Can you support TextView drawableLeft drawableRight ... attributes?

### ISSUE THREAD

**Issue by jiqimaogou** [mikepenz/Android-Iconics#150]

**Comment by mikepenz** [comment]
@jiqimaogou you can do this programmatically and just set the drawable
http://stackoverflow.com/a/4502650/325479

**Comment by jiqimaogou** [comment]
hard code in View is ugly, I wish to set it in the layout.xml.

**Comment by mikepenz** [comment]
@jiqimaogou just checked again. Doesn't really make sense to add so much overhead into the library for this rare case. I really recommend that you simply set it via code.
