### ISSUE TITLE
RoundedCorner color

### ISSUE THREAD

**Issue by emojahedi** [mikepenz/Android-Iconics#151]
Hi,
How roundedCorner color can be changed. by default it is black.
Thanks

**Comment by mikepenz** [comment]
@emojahedi could you please add a screenshot? In general the rounded corners are transparent. Are you sure your views background is transparent too?

**Comment by mikepenz** [comment]
Please report back. 

I will close this until additional information was provided. Thanks.

**Comment by emojahedi** [comment]
Hi,
Please excume me, I got really busy and totally forgot this.
This is the screent shot
![screenshot_2016-03-08-20-11-30](https://cloud.githubusercontent.com/assets/6801549/13608816/a422ca4a-e56b-11e5-897a-d4eb94dea07d.png)

The code I used to produce this black round corner is:
 ` new IconicsDrawable(mContext)
                        .icon(GoogleMaterial.Icon.gmd_toc)
                        .roundedCornersDp(50)
                        .sizeDp(20), R.string.items)`
I also noticed that increasing roundedCorner size has no effect on it.
Thank a lot

**Comment by mikepenz** [comment]
@emojahedi you define a your rounded corner as 50dp whereas your icon only has an size of 20dp. That won't work. 
The max corner radius which would change something would be 10dp (size / 2) 
What's your desired result?

**Comment by emojahedi** [comment]
Oops, I totally got the point wrong, I thought it is something like a circle which surrounds the main icon.

**Comment by mikepenz** [comment]
@emojahedi oh ok. There is no function included to draw a circle around your icon. sorry
