### ISSUE TITLE
Is it possible to surround an icon with a circle?

### ISSUE THREAD

**Issue by theblitz** [mikepenz/Android-Iconics#153]
Is it possible to surround an icon with a circle without having to use a background drawable?

**Comment by mikepenz** [comment]
@theblitz you can define a background and it's color and then you can define the radius of the corners. If you take width of the drawable / 2 it will be a circle

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L645

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L543

**Comment by theblitz** [comment]
Won't that give me a solid background rather than a circle around it?

**Comment by mikepenz** [comment]
@theblitz oh well. Seems i misunderstood your initial question. 
I'm afraid just a circle is not possible. You can either add a border to the icon itself, have a solid background. change the corner radius of the background, but not border for the background. 

sorry. 

for this you will need a background drawable or whatever is fine for you

**Comment by theblitz** [comment]
NP.
I think I'll just go for the background drawable.

Many thanks.

**Comment by mikepenz** [comment]
Thanks ;)
