### ISSUE TITLE
set Drawable Top Left

### ISSUE THREAD

**Issue by AngleV** [mikepenz/Android-Iconics#157]
Hi @mikepenz 

I got an IconicDrawable and i placed inside a multiline TextView

```
      IconicsDrawable mydr = new IconicsDrawable(mContext)
                .icon(GoogleMaterial.Icon.gmd_thumb_up)
                .color(mContext.getResources().getColor(R.color.colorPrimary))
                .sizeDp(9);

        mydr.setBounds(0, 0, mydr.getIntrinsicWidth(), mydr.getIntrinsicHeight());
        holder.myview.setCompoundDrawablePadding(10);
        holder.myview.setCompoundDrawables(mydr, null, null, null);
```
The problem is that the drawable is center vertically and i can't figure out how to position it at top left corner of textview.

got any idea ?

**Comment by AngleV** [comment]
it seems that iconOffsetYDp does the job !!!!

**Comment by mikepenz** [comment]
@AngleV the `IconicsDrawable` reacts as a normal `Drawable` would. I assume in this case it's easier to have an `ImageView` on the left of the `TextView`

**Comment by AngleV** [comment]
@mikepenz 

Yes the solution you propose is an idea that would work. But i want to avoid extra nested linearlayouts inside my whole layout.

However an extra method to redirect the draw like below would be perfect.
Take a look


```
 @Override
    public void draw(Canvas canvas) {
        int halfCanvas= canvas.getHeight() / 2;
        int halfDrawable = mDrawable.getIntrinsicHeight() / 2;

        // align to top
        canvas.save();
        canvas.translate(0, -halfCanvas + halfDrawable);
        mDrawable.draw(canvas);
        canvas.restore();
    }
```

**Comment by mikepenz** [comment]
You could extend the `IconicsDrawable` and overwrite the `draw` method for your case

**Comment by AngleV** [comment]
This is what im doing right now :)

Thanks Mike

**Comment by mikepenz** [comment]
@AngleV thanks for adding your solution to the issue so someone else can reuse it if he gets the same issue

**Comment by AngleV** [comment]
no prob mate !!!  :+1:
