### ISSUE TITLE
Using icons in TextInputLayout

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/Android-Iconics#159]
Hi,
Firstly, thanks a lot for creating this wonderful package. I am trying to add an icon with TextInputLayout. in the onCreate method i have initialised as per step 3 of readme

LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
then in my XML I use

```
<android.support.design.widget.TextInputLayout
        android:id="@+id/input_layout_password"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <EditText
            android:id="@+id/input_password"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="{faw-camera-retro} email"/>

    </android.support.design.widget.TextInputLayout>
```

Can you please let me know what I am missing.

Cheers!!!

**Comment by mikepenz** [comment]
@rakesh1988 it can't automatically replace an icon in a hint. This is only possible for text. You might have to manually set the `Spanable` you can generate via the `Iconics` class

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L139
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L177

**Comment by rakesh1988** [comment]
Thanks or the input.
