### ISSUE TITLE
Pushing latest update to maven central

### ISSUE THREAD

**Issue by paolomcgrath** [mikepenz/Android-Iconics#16]
Any chance you could push the latest build to maven central? The placeholder icon in the library is overriding our default app icon with iconics 0.7.6, so i'm guessing there hasn't been a more recent push.

Thanks!

**Comment by mikepenz** [comment]
@paolomcgrath oh sorry. yeah will publish it later today.

**Comment by paolomcgrath** [comment]
Great, thank you :)
