### ISSUE TITLE
No icon appearing on FloatingActionButton

### ISSUE THREAD

**Issue by LaurentTreguier** [mikepenz/Android-Iconics#161]
Hello, I am currently trying to use Android-Iconics to add icons to, among other things, a `FloatingActionButton` from the official Google design support library. However (as the title suggests) I can't seem to get anything appear on the button. It works flawlessly on an ImageButton or an ImageView, but nothing shows for the `FloatingActionButton`... I am using the design library version 23.3.0, Android-Iconics version 2.5.11, and tried using Google Material Design Icons as well as the Material Design Iconic Font, but nothing seems to work. I am testing on Android 4.4.2.
It looks like the problem lies within the `VisibilityAwareImageButton` class, since it doesn't work with it either, but everything works fine with the `ImageButton` class, from which `VisibilityAwareImageButton` inherits... Or does the problem lie somewhere else ? I've only just started writing my application, so there is really nothing too complex or strange in it that might do something nasty, and this puzzles me...

```xml
<ImageButton
        android:layout_width="48dp"
        android:layout_height="48dp"
        app:ico_color="@android:color/darker_gray"
        app:ico_icon="gmi-account-add"
        app:ico_size="24dp" /> <!-- This works perfectly -->

<android.support.design.widget.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_marginBottom="@dimen/activity_vertical_margin"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginRight="@dimen/activity_horizontal_margin"
        android:clickable="true"
        app:fabSize="normal"
        app:ico_color="@android:color/darker_gray"
        app:ico_icon="gmi-account-add"
        app:ico_size="24dp" /> <!-- This doesn't -->
```

**Comment by mikepenz** [comment]
@LaurentTreguier please try out the suggestions mentioned here: 
https://github.com/mikepenz/Android-Iconics/issues/160

(you might want to start with the last comment: https://github.com/mikepenz/Android-Iconics/issues/160#issuecomment-208435767)

**Comment by mikepenz** [comment]
EDIT: just saw that the same works on the `imageButton` above.

**Comment by LaurentTreguier** [comment]
I just tried and yes, it works well when done programmatically.

**Comment by mikepenz** [comment]
hmmm defining a `width` and `height` for the fab doesn't change anything? trying out different scale types?

**Comment by LaurentTreguier** [comment]
Nothing... I've changed the `width` and `height`, tried out just about every `scaleType`, and nothing changes. What's intriguing is how small the `VisibilityAwareImageButton` class is... It inherits from `ImageButton`, for which everything is fine, but for `VisibilityAwareImageButton` it doesn't.

```java
class VisibilityAwareImageButton extends ImageButton {

    private int mUserSetVisibility;

    public VisibilityAwareImageButton(Context context) {
        this(context, null);
    }

    public VisibilityAwareImageButton(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public VisibilityAwareImageButton(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        mUserSetVisibility = getVisibility();
    }

    @Override
    public void setVisibility(int visibility) {
        internalSetVisibility(visibility, true);
    }

    final void internalSetVisibility(int visibility, boolean fromUser) {
        super.setVisibility(visibility);
        if (fromUser) {
            mUserSetVisibility = visibility;
        }
    }

    final int getUserSetVisibility() {
        return mUserSetVisibility;
    }
}
```

This is the entirety of `VisibilityAwareImageButton`...

**Comment by mikepenz** [comment]
@LaurentTreguier I really do not know why the `VisibilityAwareImageButton` should be an issue when using via xml. :/ You might need to define the visibility in the xml? (just a thought)

**Comment by LaurentTreguier** [comment]
Do you mean `android:visibility="visible"` ? It still doesn't change anything... Which version of Android have you tried on ?

**Comment by mikepenz** [comment]
It was on Android 6.0.1 but with an older version of the support libs

**Comment by mikepenz** [comment]
@LaurentTreguier after some more debugging I have no idea why it is not working. 
The only weird thing I see that it will never enter the `IconicsLayoutInflater` with the `FloatingActionButton` so it is also not able to set the icon

**Comment by LaurentTreguier** [comment]
@mikepenz By the way you are saying this, it sounds like you are able to reproduce it ?

**Comment by mikepenz** [comment]
With the latest support libraries yes. But I have no solution for it. The only idea I have right now is to set the icon programatically

**Comment by Rainer-Lang** [comment]
@LaurentTreguier Instead of ```app:ico_icon="gmi-account-add"``` try this: ```app:ico_icon="gmi_account_add"```

**Comment by LaurentTreguier** [comment]
@Rainer-Lang still no luck

**Comment by Rainer-Lang** [comment]
Sorry. I had a version in the past where this was a problem....

**Comment by mikepenz** [comment]
I am out of ideas. @Rainer-Lang has the same setup as with which I tried it now.
android gradle tools 2.0.0 (he uses 2.1.0-alpha5)
buildTools 23.0.3
support libraries 23.3.0
AppCompatActivity as base activity
latest version of the iconics
...

**Comment by mikepenz** [comment]
@LaurentTreguier oh the only difference is that he uses the alternative `ContextWrapper`

https://github.com/mikepenz/Android-Iconics#3-alternative-inject-into-context-optional

**Comment by LaurentTreguier** [comment]
...and it finally works ! Thanks for pointing at this, I should have tried it out.

**Comment by mikepenz** [comment]
@LaurentTreguier to be honest I didn't know that the `FloatingActionButton` does not go through the `IconicsLayoutInflater` and I am really sorry for the trouble. :/. 

I will have to do another debugging session and try to find out what the system does behind my `IconicsInflater`. 

Thanks for your time and support.

Thanks @Rainer-Lang for finding the final solution ;)

**Comment by AAverin** [comment]
Confirming, icon on FAB only works with Context wrapper
