### ISSUE TITLE
Is correct this usage of IconicsButton ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/Android-Iconics#162]
Hi mike, for a long time i use the IconicsButton like this:

```
                <com.mikepenz.iconics.view.IconicsButton
                    android:id="@+id/btnTest"
                    android:layout_width="48dp"
                    android:layout_height="48dp"
                    android:text="{gmi-plus-circle}"
                    android:textColor="@android:color/white"
                    android:textSize="24dip" />
```

with the text size in "dip" is correct ? or i should use "sp" now ?

**Comment by mikepenz** [comment]
@seba123neo yes it is fine: https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/res/layout/activity_playground.xml#L194

You have to remember the `IconicsButton` will set the icon via the text, so the textsize in dip might not be the same as if you use an `ImageButton` and set the icon as image with 24dp

**Comment by seba123neo** [comment]
ok, thanks mike.
