### ISSUE TITLE
Icon lookup problem when font name's size is >3

### ISSUE THREAD

**Issue by papylhomme** [mikepenz/Android-Iconics#163]
Hello,

I tried to use a custom font and ran into a small problem: Using the generation tool, I entered a long name for my font (habitat), everything went fine, including icon usage in code, but when trying to resolve the icon by name it failed. A few Ctrl+Click later and I found the culprit in ```IconicsDrawable```:

```java
    public IconicsDrawable(Context context, String icon) {
        mContext = context.getApplicationContext();
        prepare();

        try {
            ITypeface font = Iconics.findFont(context, icon.substring(0, 3));
            icon = icon.replace("-", "_");
            icon(font.getIcon(icon));
        } catch (Exception ex) {
            Log.e(Iconics.TAG, "Wrong icon name: " + icon);
        }
    }
```

Is there any reason to limit the name of the font to 3 character ? It seems to work fine with a longer one, and it can be easily solved using an indexOf.

P.S: Aside from that, great work with this library, really easy to use, including the generation tool. It's a huge benefit for my app !

**Comment by mikepenz** [comment]
@papylhomme hi. Yes this is intended. The font shortcut should be always 3 characters long, as defined in the interface for the `ITypeface`
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/typeface/ITypeface.java#L38

The reason why i limited it to 3 characters is that the icons can be used via xml too and in other locations too. When I resolve it there I will always check if a id is 3 characters long, if it's longer or shorter I will ignore it and go on. It is done like this for performance, and other optimizations. 

Just use a 3 character ID ;). There are enough possible combinations still available with 3 characters ;) 

Thank you so much
