### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by irsalshabirin** [mikepenz/Android-Iconics#169]
I've got this error when I set the `Activity` with this code : 
```
LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
super.onCreate(savedInstanceState);
```

When I load data from database MySql to set a TextView with this syntax :
`textView.setText(String.format("{faw-clock-o}  %s", t.updatedAt));`

this my `Log Cat` :

> java.lang.IndexOutOfBoundsException
>                                                                    at android.view.GLES20Canvas.drawTextRun(GLES20Canvas.java:969)
>                                                                    at android.text.TextLine.drawTextRun(TextLine.java:989)
>                                                                    at android.text.TextLine.handleText(TextLine.java:791)
>                                                                    at android.text.TextLine.handleRun(TextLine.java:958)
>                                                                    at android.text.TextLine.drawRun(TextLine.java:398)
>                                                                    at android.text.TextLine.draw(TextLine.java:196)
>                                                                    at android.text.Layout.drawText(Layout.java:355)
>                                                                    at android.widget.Editor.drawHardwareAccelerated(Editor.java:1425)
>                                                                    at android.widget.Editor.onDraw(Editor.java:1350)
>                                                                    at android.widget.TextView.onDraw(TextView.java:5446)
>                                                                    at android.view.View.draw(View.java:15278)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14214)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.draw(View.java:15281)
>                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:598)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14214)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.draw(View.java:15281)
>                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:598)
>                                                                    at android.widget.ScrollView.draw(ScrollView.java:1689)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14214)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14209)
>                                                                    at android.view.View.getDisplayList(View.java:14236)
>                                                                    at android.view.View.draw(View.java:15006)
>                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
>                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
>                                                                    at android.view.View.draw(View.java:15281)
>                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:598)
>                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2653)
>                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14214)
>                                                                	at android.view.View.getDisplayList(V

**Comment by mikepenz** [comment]
@irsalshabirin the `StackTrace` has no reference to the Iconics. Can you reproduce this every single time?

**Comment by irsalshabirin** [comment]
there are no errors that indicate about iconics. But when I comment this line:
`textView.setText(String.format("{faw-clock-o} %s", t.updatedAt));`
applications run smoothly.

I just find an error in logcat like the above.
My device is Xiaomi mi4c using MIUI 7,

however, I found a solution by replacing the `TextView` be `IconicsTextView` and the issue is finished. Thank you very much. This library is very cool 👍  💯

**Comment by trungie** [comment]
I've experienced this as well. I set am using `LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));` as well.

@mikepenz you are right, there is no iconics code, however when i comment out the code with the iconics `{faw-...` it works.

**Comment by trungie** [comment]
I can confirm that changing from `TextView` and using the `LayoutInflatorCompat.setFactory` to using `com.mikepenz.iconics.view.IconicsTextView` works!

**Comment by mikepenz** [comment]
@trungie it's really weird. because the two use exact the same code. It just seems that the system does something really weird when using a `TextView` strange thing is that this only happens if you use `String.format` as far as I've seen, because setting a normal "String" does not result in any issues

**Comment by trungie** [comment]
@mikepenz for some reason now that i use `IconicsTextView`, I can't use `textView.setText(Html.fromHtml(htmlString))` anymore. Is this a bug? The text just comes up plain.

**Comment by mikepenz** [comment]
@trungie "plain" in terms of the html is not applied, or the icon is not replaced?

**Comment by trungie** [comment]
@mikepenz html styles not applied. I'm using `<font color="... ` Icon appears.

**Comment by mikepenz** [comment]
Hmmm most styles should persist from the HTML markup, as I try to keep those spannables when applying the icons. Is "bold" or "italic" working?

**Comment by trungie** [comment]
@mikepenz No `<strong>` doesn't work!

**Comment by mikepenz** [comment]
`<b>`?

**Comment by alvinpb** [comment]
Can confirm @trungie issue. <b> doesn't work either.

**Comment by mikepenz** [comment]
@alvinpb seems like the `Html.fromHtml` styles text a bit different than the normal spannables, because those should be kept via `Android-Iconics` 

In general I always suggest to use the `Android-Iconics` in `ImageView`s because it gives you much more control about how it is displayed than within the text

**Comment by alvinpb** [comment]
Yep understand. Maybe my use-case isn't really supported. I have an IconicsTextView - am trying to mix in the following way - HTML + ICON + HTML

**Comment by mikepenz** [comment]
@alvinpb can you please retest this with the lastest version
