### ISSUE TITLE
Google Materials icons not working on IconicsTextView

### ISSUE THREAD

**Issue by gpulido** [mikepenz/Android-Iconics#17]
I have registered on a customApplication the google material icons:
```Java
Iconics.registerFont(new GoogleMaterial());
```
And try to use it on a textview:

```xml
<android.view.IconicsTextView
                        android:id="@+id/next"
                        android:layout_width="48dp"
                        android:layout_height="wrap_content"
                        android:text="{gmd_android}"
                        android:textColor="@android:color/white"
                        android:textSize="16sp"
                        android:contentDescription="Next"/>
```

But the inflater tries to create it throws a null exception.
I have tried with a fontawesome icon and it works (even without it registered on the application)

If I try to use the GoogleMaterial icons through
```Java
new IconicsDrawable(getActivity(), GoogleMaterial.Icon.gmd_android)
```
it does work.

I don't know what is happening here:

(Using 0.7.9)

**Comment by mikepenz** [comment]
@gpulido with the newest version you don't have to register the GoogleMaterial font anymore because it is included as default. See the README ;)

And why it won't show the icon :D you have to write `{gmd-android}`

**Comment by gpulido** [comment]
@mikepenz Sorry if this is very dumb. I've been able to use the gmd-android or the gmd-edit icon. (thank for pointing me the error). But I'm trying to use the gmd-skip-next, and it is not working. I'm able to use it programatically through "gmd_skip_next" but not on the Iconicstextview.

**Comment by mikepenz** [comment]
@gpulido just tried this within an textview with the newest version. i can use {gmd-skip-next} within a textview without problems
