### ISSUE TITLE
Not able to use it as a Textview in adapters but Imageview is working fine in adapters?

### ISSUE THREAD

**Issue by iampawan** [mikepenz/Android-Iconics#172]

**Comment by mikepenz** [comment]
@iampawan please provide details

**Comment by iampawan** [comment]
i Have initialised in activity Oncreate :  LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));

But when i cant use it  eg {faw-music} in textView in an adapter class which i am using for listview, 
It works fine for Imageview but textView not working

**Comment by mikepenz** [comment]
@iampawan yeah but how do you set it for the `ImageView`? How will you define it for the `TextView`?

**Comment by iampawan** [comment]
This one is working : 
{
<com.mikepenz.iconics.view.IconicsImageView
    android:layout_width="72dp"
    android:layout_height="72dp"
    app:iiv_color="@android:color/holo_red_dark"
    app:iiv_icon="gmd-favorite" />
}

These are not working: {
<com.mikepenz.iconics.view.IconicsTextView
        android:text="abc{hif-test}defgh{faw-adjust}ijk{fon-test1}lmnopqrstuv{fon-test2}wxyz"
        android:textColor="@android:color/black"
        android:layout_width="wrap_content"
        android:layout_height="56dp"
        android:textSize="16sp"/>


&

<TextView
    android:text="{gmd-chart} Chart"
    android:textColor="@android:color/black"
    android:layout_width="wrap_content"
    android:layout_height="56dp"
    android:textSize="16sp"/>
}

**Comment by mikepenz** [comment]
@iampawan any log output you see?

**Comment by iampawan** [comment]
ok i will send you the log after sometime.. thanks

**Comment by mikepenz** [comment]
Any new feedback? Will close for now
