### ISSUE TITLE
Is there any way to thin the icon borders?

### ISSUE THREAD

**Issue by iampawan** [mikepenz/Android-Iconics#173]

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L669

**Comment by iampawan** [comment]
Can you provide a sample if u can @mikepenz .

Thanks a lot

**Comment by mikepenz** [comment]
I am not sure why calling a method requires a sample :O 

This will change the thikness of the border around the icon itself.

**Comment by iampawan** [comment]
i am asking for sample because doing this is not making it thin... but makes it think .. i mean i dont know how much width i need to provide

**Comment by mikepenz** [comment]
that's something I can't tell you :D you can provide it also as `px` or `dp` but that's something on your side. nothing which needs to be done in a sample.

**Comment by iampawan** [comment]
Yeah thats right i gave it a shot but it was giving me unexpected results .
 Anyway thanks for this awesome library @mikepenz
