### ISSUE TITLE
Image view (XML) doesn't work, cannot set icon via app:ico_icon 

### ISSUE THREAD

**Issue by edesdan** [mikepenz/Android-Iconics#174]
Hi,
I have just started to use the library in my project. I have followed all the steps described in the README section to include the google material icons and use them as icons sources for ImageView. Anyway it seems that it doesn't work at all. Here my code:

```java
 <ImageView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="48dp"
        android:layout_height="48dp"
        app:ico_icon="gmd-location-on"
        app:ico_color="@android:color/black"
        app:ico_size="48dp"/>
```

In my activity:
```java
    /**
     * Define IconicsLayoutInflater to enable automatic xml icons detection
     * @param newBase
     */
    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
```

My gradle:

```
    compile 'com.mikepenz:iconics-core:2.5.11@aar'
    //Icons
    // Google Material Icons
    compile 'com.mikepenz:google-material-typeface:2.2.0.1@aar'
    //Font awesome
    compile 'com.mikepenz:fontawesome-typeface:4.6.0.1@aar'
    //Material icons
    compile 'com.mikepenz:material-design-iconic-typeface:2.2.0.1@aar'
```

Do I miss something?

**Comment by mikepenz** [comment]
@edesdan any special logoutput you get?

**Comment by edesdan** [comment]
Hi, thanks for the suggestions but still same issue. Looking at the logs I can only find: 

```
05-16 22:10:52.378	indian.fig.whatsaround	19083	-	E	Iconics 	 Wrong icon name: gmd_location_on 

```
Whats wrong with that? I think the name is correct.

**Comment by edesdan** [comment]
ok I found a similar issue here: https://github.com/mikepenz/Android-Iconics/issues/67. Following the suggestion:

```
Iconics.init(getApplicationContext());
Iconics.registerFont(new GoogleMaterial());

```

the icon is finally displayed.

What I should do? Is that required or not? 

Thanks a lot!

**Comment by mikepenz** [comment]
@edesdan it should be enough if you jsut register the font in your `Application`:
```java
Iconics.registerFont(new GoogleMaterial());
```

It can happend that it won't be autodetected if you have a `applicationId` set in your gradle, or if you have proguard enabled.
