### ISSUE TITLE
Community Material Design font is outdated

### ISSUE THREAD

**Issue by AAverin** [mikepenz/Android-Iconics#176]
Currently used Community Material Design font is 1.5.54, while the latest available is already 1.6.50.
Would it be possible to update it, and keep it up to date?
Thanks

**Comment by mikepenz** [comment]
@AAverin the font is updated whenever someone mentions that it is outdated, and whenever I see that it is outdated. No way to automatically keep the font updated

**Comment by AAverin** [comment]
I see.
Sorry for the alarm - looks like everything is up to date, I just mixed up the font and used Material Design Iconic Font dependency instead of the Community one=)
