### ISSUE TITLE
IconicsTextView not working on some devices

### ISSUE THREAD

**Issue by artkoenig** [mikepenz/Android-Iconics#179]
On some devices the IconicsTextView do not display the icons at all or display dummy unicode characters. IconicsImageView works fine, though. The problem popped up while testing in Google Cloud Test Lab. Here some examples:

**This is a working example, testen on Nexus 4 - Android 5.1 | Deutsch**
![c6bec783](https://cloud.githubusercontent.com/assets/1738628/15469785/d56c64e6-20ec-11e6-93e0-92080700af87.png)

**Galaxy Note3 - Android 4.4 | Englisch**
![86ed9b9e](https://cloud.githubusercontent.com/assets/1738628/15469770/b1712ec8-20ec-11e6-9b2a-ce1e81469616.png)

I tried it with Community Material Typeface and with my own custom font.

**Comment by mikepenz** [comment]
@artkoenig that's a weird issue. Could you also please try if it is the same for icons you create via the `IconicsDrawable` directly?

**Comment by artkoenig** [comment]
The icons created by IconicsDrawable are displayed correctly in all cases (xml and code). This is indeed a weird issue. One of the problematic devices was the HTC One, I had the opportunity to debug the app on this device today and the icons were displayed correctly. Perhaps this issue only appear on Cloud Test devices? What about your Iconics Library app, can you check it on Cloud Test devices?

**Comment by mikepenz** [comment]
I can't test it in the Cloud Test lab, as I do not have credits for the Firebase testing, which will cost about 5$ per hour. The automatic pre testing in the play store might only will show the initial screen (I am not sure about this one) I will give it a try

**Comment by mikepenz** [comment]
Seems correct
<img width="979" alt="bildschirmfoto 2016-05-24 um 20 30 02" src="https://cloud.githubusercontent.com/assets/1476232/15515402/580f9556-21ee-11e6-96c8-f2e771add50e.png">

**Comment by artkoenig** [comment]
Nope, look at IconicTextView showcase...

**Comment by mikepenz** [comment]
Oh you are right :O. The thing is this was only screenshoted for this one device, I think it randomly clicks. so i don't see it for the other devices :/.

**Comment by mikepenz** [comment]
The question is why it only occurs on the `IconicsTextView` I have no idea as it does basically the same as the normal `TextView` just at a different point of time

**Comment by mikepenz** [comment]
@artkoenig I am really without a hint. Where you able to get something similar on any real device? In general I always recommend to use the `IconicsDrawable` directly as it gives more control over correct paddings, margins, placement etc than within the text set via the font, as it will differ on phones or may be different size as different baselines etc are used on phones.

**Comment by mikepenz** [comment]
Haha last open issue from all my open source projects. If I only could reproduce this on any of my phones.

**Comment by thelou1s** [comment]
Yes, same problem.  and http://testin.cn test site could reproduce this and it's free.

**Comment by artkoenig** [comment]
I found [this post](http://stackoverflow.com/a/31439499/321106) on StackOverflow.

**Comment by mikepenz** [comment]
@artkoenig oh if it is this problem. There is nothing I can do about this, as the character range is defined by the font so in this case by Google. 

You can use one of the alternative fonts. Like the Material Design Iconic font which includes basically the same icons with different names and it uses a different character range: http://zavoloklom.github.io/material-design-iconic-font/

Changing the local might be a solution to. Sounds a bit "dirty" so I can't do it inside the library. 

Thanks for pointing this out @artkoenig 

Seems like I can close this, as there is nothing I can do about those things.
