### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by csaq7151** [mikepenz/Android-Iconics#18]
Only the Custom Font of the sample is showing the Icons. Working now on this problem since 2 days but no result.

Can you help me ? 

![screenshot_2015-03-25-12-28-45](https://cloud.githubusercontent.com/assets/10165699/6823679/b4dee286-d2ea-11e4-8f74-4880915b560b.png)

**Comment by mikepenz** [comment]
@csaq7151 is this the sample application without any modifications?

**Comment by csaq7151** [comment]
@mikepenz yes

**Comment by mikepenz** [comment]
what phone do you use? you also use Android Studio?

**Comment by csaq7151** [comment]
I use Nexus 4 and Nexus 5. I use eclipse.

**Comment by mikepenz** [comment]
I assume it's a problem with eclipse.
I give you the advice to switch to the Android Studio.

For eclipse i can't really help you

**Comment by csaq7151** [comment]
But why is it working with the Custom Font then ?

**Comment by mikepenz** [comment]
You mean as class to your project? I am sure there must be an issue with the eclipse setup. Here it's working on all devices and emulators.

**Comment by csaq7151** [comment]
yes exactly. If I add them as class everything its working fine.

thanks anyway :)
