### ISSUE TITLE
ClassCastException: IconicsContextWrapper cannot be cast to android.app.ContextImpl

### ISSUE THREAD

**Issue by meNESS** [mikepenz/Android-Iconics#180]
Hi Mike,

**Android Studio:** version 2.1.1
**Tested On:** Emulator API 23

> FATAL EXCEPTION: main
>                                                                      Process: ir.barandeh.android, PID: 11768
>                                                                      java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdInternalReceiver: java.lang.ClassCastException: com.mikepenz.iconics.context.IconicsContextWrapper cannot be cast to android.app.ContextImpl
>                                                                          at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
>                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java)
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                          at android.os.Looper.loop(Looper.java:148)
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                       Caused by: java.lang.ClassCastException: com.mikepenz.iconics.context.IconicsContextWrapper cannot be cast to android.app.ContextImpl
>                                                                          at android.app.ActivityThread.handleReceiver(ActivityThread.java:2722)
>                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java) 
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                          at android.os.Looper.loop(Looper.java:148) 
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

**Dependencies Are:**
> dependencies {
>     compile fileTree(include: ['*.jar'], dir: 'libs')
>     compile 'com.android.support:support-v4:23.4.0'
>     compile 'com.android.support:appcompat-v7:23.4.0'
>     compile 'com.android.support:design:23.4.0'
>     compile 'com.android.support:cardview-v7:23.4.0'
>     compile 'com.jakewharton:butterknife:8.0.1'
>     apt 'com.jakewharton:butterknife-compiler:8.0.1'
>     compile 'com.mobsandgeeks:android-saripaar:2.0.3'
>     compile('com.mikepenz:fastadapter:1.5.0@aar') {
>         transitive = true
>     }
>     compile 'com.afollestad.material-dialogs:core:0.8.5.9'
>     compile('com.mikepenz:materialdrawer:5.2.6@aar') {
>         transitive = true
>     }
>     compile 'com.squareup.retrofit2:retrofit:2.0.2'
>     compile 'uk.co.chrisjenx:calligraphy:2.2.0'
>     compile 'io.github.meness:easyintro:1.2.9'
>     compile 'com.github.PhilJay:MPAndroidChart:v2.2.4'
>     compile 'com.mikepenz:community-material-typeface:1.5.54.1@aar'
>     compile 'com.github.iwgang:countdownview:1.2'
>     compile 'com.google.android.gms:play-services-analytics:9.0.0'
> }

**Comment by mikepenz** [comment]
@meNESS seems like Firebase does not allow you to run it with a wrapped context. 

What activity do you use?

**Comment by meNESS** [comment]
@mikepenz But I'm not using Firebase! What do you mean what activity I use?

**Comment by mikepenz** [comment]
@meNESS your exception states so: com.google.firebase.iid.FirebaseInstanceIdInternalReceiver

**Comment by meNESS** [comment]
@mikepenz I know what the exception is but I'm not using Firebase. I checked the settings and it didn't implemented! I have just a few fragments and Firebase doesn't needed at all. Maybe this is a bug from Android Studio because I didn't have any problem previously before updating to the latest stable version.

**Comment by mikepenz** [comment]
@meNESS that's weird. Perhaps from the latest play services? 
```gradle
compile 'com.google.android.gms:play-services-analytics:9.0.0'
```

**Comment by meNESS** [comment]
@mikepenz Yes, I recently updated to the latest version of Play Services and perhaps it is the problem but what's the solution? I need Google Analytics. Should I wait for a bug fix from Google?

**Comment by meNESS** [comment]
If I remove following lines from Application everything would works fine:

```
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(IconicsContextWrapper.wrap(CalligraphyContextWrapper.wrap(base)));
    }
```

**Comment by meNESS** [comment]
I changed that dependency and now I'm using Firebase itself instead and everything works. Thanks Mike :+1:

**Comment by mikepenz** [comment]
@meNESS ok great. Seems like the crash was just passed through the `ContextWrapper` and the initial issue was an incompatiblity of the analytics sdk

**Comment by AAverin** [comment]
An addition to this bug.
My custom BroadcastReceiver throws the same exception
```
  Caused by: java.lang.ClassCastException: com.mikepenz.iconics.context.IconicsContextWrapper cannot be cast to android.app.ContextImpl
                                                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:2722)
                                                                               at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
```

**Comment by AAverin** [comment]
Probably related to this: https://github.com/chrisjenx/Calligraphy/issues/211

**Comment by AAverin** [comment]
https://code.google.com/p/android/issues/detail?id=200832

**Comment by AAverin** [comment]
Confirming the fix:
`attachBaseContext(IconicsContextWrapper(base))` should be done in **Activity**, not Application context

**Comment by mikepenz** [comment]
@AAverin thanks for the report. 

So this means that the description is correct with `Activity` here: https://github.com/mikepenz/Android-Iconics#3-alternative-inject-into-context-optional ?

**Comment by AAverin** [comment]
Yes, it's correct. 

Maybe stress Activity a little? A colleague of mine made an unconscious mistake and put initialization into Application context, because attachBaseContext method is present in both Activity and Application

**Comment by mikepenz** [comment]
@AAverin once again thanks for the detailed information
