### ISSUE TITLE
Usage as FAB icon?

### ISSUE THREAD

**Issue by Polyterative** [mikepenz/Android-Iconics#181]
Is it possible? 
I tried using `{}` without sucess.
What I want is use the library here: 
```xml
<android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        android:src="------>>>>>>>>is it possible to use this library here?---------<<<<<<<<"
        />
```

Thanks

**Comment by mikepenz** [comment]
The FAB extends from the `ImageView` so everything which is written in this section:
https://github.com/mikepenz/Android-Iconics#as-imageview-only-available-if-you-follow-step-3-or-inject-the-context
applies to it.

**Comment by Polyterative** [comment]
Still can't get it to work.
I've tried the following:
`<android.support.design.widget.FloatingActionButton
        ...
        app:ico_icon="ion_alert"
        app:ico_size="24dp"`
and 
`<android.support.design.widget.FloatingActionButton
        ...
        app:ico_icon="{ion_alert}"
        app:ico_size="24dp"
        />`

If I try: `android:src="{ion_alert}"` or `android:src="ion_alert"` Gradle doesn't compile.
Am I missing something? I followed the "Step 3" correctly, like this:
`@Override
    protected void onCreate(Bundle savedInstanceState) {
        LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));...}`

**Comment by mikepenz** [comment]
@Polyterative the first variant should work. 

And you get no log output? You have the corresponding font in your project? And it was able to register? 

Is it the first position where you use a font via XML?

**Comment by Polyterative** [comment]
Log is clear.

**Comment by Polyterative** [comment]
Log is clear, the fab is ok, just without the icon.
https://imgur.com/gV1zdpq

I've imported the font in `build.gradle ` like this:
```
    compile 'com.mikepenz:ionicons-typeface:2.0.1.1@aar'
```

**Comment by mikepenz** [comment]
Could you please do the following step. (registering `Ionicons` in your case) just to make sure the font got autodetected (auto detection won't work if proguard is configured wrong, and also if an applicationId is set in the build.gradle)

https://github.com/mikepenz/Android-Iconics#register-fonts

**Comment by mikepenz** [comment]
Oh sorry I missed one thing. You use the `LayoutInflaterCompat` this one does not work on `FAB`s for a weird reason. See here:
https://github.com/mikepenz/Android-Iconics/issues/161#issuecomment-220830768

**Comment by Polyterative** [comment]
It's working now with the 
```Java
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
```
Thank your for your time!
Awesome library

**Comment by mikepenz** [comment]
@Polyterative sorry for wasting your time, should have remembered this point. 

I have added the information to the README. Thanks again

**Comment by Polyterative** [comment]
I found that another way to solve this can be assigning the `Drawable ` in the activities/fragments involved.
```Java
...
mainFab = (FloatingActionButton) findViewById(R.id.fab);
mainFab.setImageDrawable(new IconicsDrawable(this, Ionicons.Icon.ion_alert)
                .color(Color.WHITE).sizeDp(24));
...
Since the preview doesn't show the icon anyway (at least to me), this (maybe?) can be a faster solution for someone.

**Comment by mikepenz** [comment]
@Polyterative yes I know ;). But many people prefer to set it via XML so they have no code for it. Internally it will do exactly what you just did programatically.
