### ISSUE TITLE
IconicsDrawable doesn't work on TextView.setCompoundDrawables

### ISSUE THREAD

**Issue by frodoking** [mikepenz/Android-Iconics#182]
IconicsDrawable doesn't work on TextView.setCompoundDrawables()
```
TextView textView = (TextView) getRootView().findViewById(R.id.text);
Drawable drawable = new IconicsDrawable(getAndroidContext()).icon(Octicons.Icon.oct_alert).sizeDp(30);
textView.setCompoundDrawables(drawable, null, null, null);
```

but it will work if do like:
```
TextView textView = (TextView) getRootView().findViewById(R.id.text);
Drawable drawable = new IconicsDrawable(getAndroidContext()).icon(Octicons.Icon.oct_alert).sizeDp(30);
textView.setBackground(drawable);
textView.setCompoundDrawables(drawable, null, null, null);
```
why?, I only want to get a Drawable.

**Comment by mikepenz** [comment]
@frodoking so it works as `CompoundDrawable` if you have a background set or it still only applies to the background then?

What's about this answer:
https://github.com/mikepenz/Android-Iconics/issues/8#issuecomment-62551409

**Comment by frodoking** [comment]
@mikepenz Perhaps you can see if that helps when you save a IconicsDrawable.toBitmap() to a png file.

**Comment by rmarau** [comment]
@mikepenz 

this problem appeared to me upon commit 7f51cfddb7892f51ad735e85bee04e9e1a4dbabb when addressing the N-Preview issue.

Im creating a `Drawable` and inserting it as a `CompoundDrawable`, as such:

`final Drawable eyeDrawable = new IconicsDrawable(LoginActivity.this)`
                `.icon(MaterialDesignIconic.Icon.gmi_eye)`
                `.color(ContextCompat.getColor(MyActivity.this, R.color.primary))`
                `.sizeDp(24);`
`edittext.setCompoundDrawables(null, null, eyeDrawable, null);`

Testing in **API10**: the icon is visible but its size reduced (maybe half the size), as compared to before.
Testing in **API21 and M**: the visible icon not visible.
Didn't test in **N-preview**.

Could this be related to how the CompoundDrawable fetches the containing Drawable size?

**Comment by mikepenz** [comment]
@rmarau I assume it is related to the fact that I no longer set the bounds explicitely, as this was noted by the Android developer in the Android N ticket. I can try to readd the `setBounds` but this should not be done as noted here: https://code.google.com/p/android/issues/detail?id=210834&thanks=210834&ts=1463954825

**Comment by rmarau** [comment]
@mikepenz  I didn't pay much attention to your reference to https://github.com/mikepenz/Android-Iconics/issues/8#issuecomment-62551409 , because it was much older than this commit. But after revisiting and trying to be explicit with respect to the bounds (from the outside) worked for me.

`eyeDrawable.setBounds( 0, 0, 24, 24 );` did the trick.

I understand the arguments in the google code ticket in which onBoundsChange() is where the Drawable should respond. But in this case the CompoundDrawable handler is not doing so. It seems to be expecting a drawable already set an bounded, such as one got from resources.

Thanks!

**Comment by mikepenz** [comment]
@rmarau yes. I think this is the best option to use it as compound drawable now.

Thanks. (I added the label good to know so hopefully people will search it ;))

**Comment by mikepenz** [comment]
This is back to the old behavior. I have readded the `setBounds` calls as they do not break the Android N fix.
