### ISSUE TITLE
Space between glyphs' outermost strokes and glyphs' bounds is not honored

### ISSUE THREAD

**Issue by jayrave** [mikepenz/Android-Iconics#183]
This is best explained with an example => the following two icons look exactly the same when displayed using the iconics library when they are not supposed to
- a 8x8 square inside a 12x12 box 
- a 4x4 square inside a 12x12 box 

The reason for this being that the space between a glyph's outermost strokes and glyph's bounds is not honored

*Visual example:* Look the following icons - arrow-left, arrow-small-left (similarly for down, up & right) 
- Looks as it should on [Octicons](https://octicons.github.com/) (the small icons are smaller than the normal ones)
- Iconics's [demo app](https://play.google.com/store/apps/details?id=com.mikepenz.iconics.sample) (the small icons are the same size as the normal ones)

**Comment by mikepenz** [comment]
@jayrave the icons do not respect the padding as this information is lost in the process of drawing the icon. 

You can set paddings on the icons via: https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L351 (or the other padding methods)

**Comment by mikepenz** [comment]
@jayrave I have added a new feature which allows to keep those paddings (if enabled custom provided paddings do not work on this single icon)

**Comment by jayrave** [comment]
@mikepenz thanks a lot for the quick reply & update

I still see that there is some alignment issues (could be just my custom icons). I will investigate further & let you know if something turns up

Great library
