### ISSUE TITLE
Not Usabe in non-Appcompat activities

### ISSUE THREAD

**Issue by shayanzoro** [mikepenz/Android-Iconics#184]

**Comment by mikepenz** [comment]
@shayanzoro could you please be a bit more specific. You can use the `IconicsDrawable` in all activties without any issues. 

And this: https://github.com/mikepenz/Android-Iconics#3-alternative-inject-into-context-optional should also work

**Comment by shayanzoro** [comment]
Hi,

I am using calligraphy library & I can't inject the context, because I am do it with calligraphy wrapper.
I also don't use AppCompatActivity. So both  "defining the IconicsLayoutInflater" and "injecting the context" are not possible for me.

P.S. I use Calligraphy to set a default font for all textviews, Does your library have such a feature?

**Comment by mikepenz** [comment]
@shayanzoro if you can't do the auto detection for normal `TextView`s you still always have the option to use the `IconicsTextView` and the other `Iconics`* views. 

In general I suggest that you just go with the `IconicsDrawable` and use it on `ImageView`s as it will make sure that sizes etc stay the same even if users mod their font etc on the device
