### ISSUE TITLE
Can I use my custom font from XML?

### ISSUE THREAD

**Issue by fweigl** [mikepenz/Android-Iconics#186]
I've seen the usage of fonts directly from XML with the provided fonts like 
`com.mikepenz:google-material-typeface:2.1.0.1.original@aar`

Can I also use my custom font directly from XML? I tried to use the font name from the generated class as identifier: 

```
    @Override
    public String getFontName() {
        return "my_font";
    }
```

and then in my XML: 

```
    <ImageView
        android:id="@+id/imageView"
        app:ico_icon="my_font-sunshine"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="16dp"/>
```
Sunshine being the name of the icon. 
The logcat says

`E/Iconics: Wrong icon name: my_font_sunshine`

I did: 

```
    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
```

and 

```
        Iconics.init(getApplicationContext());
        Iconics.registerFont(new my_font());
```

Is it possible in general with custom fonts? Are there any more caveats?

**Comment by mikepenz** [comment]
@fweigl your font must have a correct `mappingPrefix` (with exact 3 characters) here: 
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/typeface/CustomFont.java#L43

and it has to match the prefix of the enum too:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/typeface/CustomFont.java#L111

**Comment by fweigl** [comment]
@mikepenz Thanks for your help, I applied the requirements you mentioned, unfortunately I still can't manage to set icons from XML directly. 
I created a small example, perhaps you could have a look at what I'm doing wrong: 

https://bitbucket.org/asco33/iconicstest

**Comment by mikepenz** [comment]
@fweigl exactly. the prefix is picked up to efficiently detect which font to use.
