### ISSUE TITLE
Provide licenses of the icon-libs for AboutLibs

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/Android-Iconics#188]

**Comment by Rainer-Lang** [comment]
- Google Material Design Icons: Creative Commons Attribution 4.0 International License (CC-BY 4.0) - https://github.com/google/material-design-icons

**Comment by mikepenz** [comment]
@Rainer-Lang you want to do a pull request?

**Comment by Rainer-Lang** [comment]
@mikepenz First things first :-)

1. Collect information
2. PR (author: unknown)

**Comment by Rainer-Lang** [comment]
@mikepenz How could these licences included, that only the license is shown of the font which is used?

**Comment by mikepenz** [comment]
the font informations have to be added to the specific font addon module
and the license needs to be added to the AboutLibraries

**Comment by mikepenz** [comment]
@Rainer-Lang added the licenses you sent to me to the AboutLibraries. and added the first definition files to the first 3 fonts. you can do a pull request for the other fonts please.

**Comment by Rainer-Lang** [comment]
Only Meteocons is missing.

**Comment by mikepenz** [comment]
Great ;)

**Comment by mikepenz** [comment]
@Rainer-Lang meteocons has a custom license:

> Meteocons are free for use in both personal and commercial projects.
> 
> No attribution or backlinks are required, but any form of spreading the word is always appreciated!
> 
> You must not resell any icons or distribute them in any other way.
> 
> The Icons as such are the property of the author.

**Comment by Rainer-Lang** [comment]
PRs for Iconics and AboutLibs are ready to merge :)
After merging - issue could be closed. :+1: :-D

**Comment by mikepenz** [comment]
thanks
