### ISSUE TITLE
Messy chinese code problem

### ISSUE THREAD

**Issue by thelou1s** [mikepenz/Android-Iconics#190]
<com.iconics.view.IconicsTextView
        android:id="@+id/back_iv"
        android:layout_width="@dimen/base_titlebar_size"
        android:layout_height="fill_parent"
        android:layout_alignParentLeft="true"
        android:background="@drawable/home_titlebar_btn_selector"
        android:gravity="center"
        android:text="{ICON_BACK}"
        android:textColor="@color/grey_666666"
        android:textSize="26dp" />

IconicsTextView shows messy code in some devices, please help me.

**Comment by mikepenz** [comment]
@thelou1s could you also please add a screenshot? Can you reproduce this? I think this is related to this issue: https://github.com/mikepenz/Android-Iconics/issues/179 (please answer my questions there)
