### ISSUE TITLE
R.color.<value> incorrectly sets color

### ISSUE THREAD

**Issue by cgudea** [mikepenz/Android-Iconics#20]
I want a 54% opacity on an all black icon (its what android asset studio generates their icon colors as).
If I set it as follows:

    mNavBtn.setImageDrawable(
            new IconicsDrawable(this, FontAwesome.Icon.faw_location_arrow)
                    .color(0x8a000000)
                    .sizeDp(24));

I get the correct color. If I try to use values in my colors.xml, the color is all wrong.

    mNavBtn.setImageDrawable(
            new IconicsDrawable(this, FontAwesome.Icon.faw_location_arrow)
                    .color(R.id.ButtonColor)
                    .sizeDp(24));

I get a wrong color. I found this [stackoverflow](http://stackoverflow.com/questions/6177273/textview-settextcolor-not-working) post that gives me the work around: 

    mNavBtn.setImageDrawable(
            new IconicsDrawable(this, FontAwesome.Icon.faw_location_arrow)
                    .color(getResources().getColor(R.id.ButtonColor))
                    .sizeDp(24));

Not sure if using `getColor()` is the intended behavior. Maybe you'll want to add it to the README or mention it somewhere --- I was definitely confused by it!

**Comment by mikepenz** [comment]
@cgudea just use the method `.colorRes` 

there is a separat method for this because the color itself is an int and the ressource identifier is an int. i won't be able to get the difference of both :P

But in fact your "workaround" basically does the same

**Comment by cgudea** [comment]
haha woops, yeah I'll just use that method instead =D
