### ISSUE TITLE
Wrong behavior on View with textAllCaps

### ISSUE THREAD

**Issue by pedronveloso** [mikepenz/Android-Iconics#201]
I've a style that defines the following for my buttons:

`<item name="android:textAllCaps">true</item>`

The moment I enable Iconics by using `attachBaseContext` all the buttons text becomes lower case, so it is somehow overriding that property. The text that I assign to the button at XML level is indeed lower-case, but otherwise it would become capitalized and now it does not.

**Comment by mikepenz** [comment]
@pedronveloso textAllCaps is not supported as it prevents spanables to be set on a `TextView` this is a limitation by android, nothing I can do here.

**Comment by dreamcatcha** [comment]
Is it possible for Iconics to target only specific view in a layout? So the TextAllCaps can work for everything else that isn't targeted?

**Comment by mikepenz** [comment]
Yes there is. Showcased in the sample application: https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L57

**Comment by dreamcatcha** [comment]
Brilliant Thank you!
