### ISSUE TITLE
Support Tinting for NavigationView.

### ISSUE THREAD

**Issue by mikerussellnz** [mikepenz/Android-Iconics#202]
I am using Iconics drawables for the icons in a NavigationView.  The NavigationView uses tinting so that the icons are grey when the item is unselected and the accent colour when the item is selected.

This works fine for bitmaps but does not work for Iconics drawables leaving them black at all times. 

It appears that Iconics drawables need to implement setTintList and setTintMode and render accordingly.  

Currently I am using a workaround where I call toBitmap() and then create a BitmapDrawable.

**Comment by mikepenz** [comment]
@mikerussellnz I am not sure on how to implement those two methods. Have not found any implementations. Also the `IconicsDrawable` already implement the `Drawable` so I expected those methods to be in place. 

Do you have any references? 

Perhaps it's necessary to follow those steps:

```java
Drawable drawable = ...;

// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
drawable = DrawableCompat.wrap(drawable);

// We can now set a tint
DrawableCompat.setTint(drawable, Color.RED);
// ...or a tint list
DrawableCompat.setTintList(drawable, myColorStateList);
// ...and a different tint mode
DrawableCompat.setTintMode(drawable, PorterDuff.Mode.SRC_OVER);
```
as noted here: https://chris.banes.me/2015/04/22/support-libraries-v22-1-0/

**Comment by mikerussellnz** [comment]
Hi 

I did not have success with using DrawableCompat.  I believe it is for compatibility with pre-v21 devices (which I am not testing on) and that on v21+ devices it just passes the call through to the underlying drawable. 

setTintList and setTintMode are both empty implementations in the base drawable class as it is up to drawable itself to implement it appropriately.  
https://github.com/android/platform_frameworks_base/blob/master/graphics/java/android/graphics/drawable/Drawable.java#L568

As Iconics is dealing with vector data the best reference would be the Android VectorDrawable implementation.

https://android.googlesource.com/platform/frameworks/base/+/eb034fb/graphics/java/android/graphics/drawable/VectorDrawable.java#212

There is a updateTintFilter function provided in the base Drawable that may be useful.

**Comment by mikerussellnz** [comment]
I have updated to the latest version but I am still seeing the same behaviour where the icon does not change colour when it is the icon of a selected item.

Here is a minimal test application that compares with the android vector format:

[IconicsTest.zip](https://github.com/mikepenz/Android-Iconics/files/386439/IconicsTest.zip)

**Comment by mikepenz** [comment]
@mikerussellnz hmmm weird. I tested with setting the `tint` via the specific API on the `Drawable` and it worked without troubles

**Comment by mikepenz** [comment]
@mikerussellnz the download doesn't seem to work :(

**Comment by mikerussellnz** [comment]
Try here
https://www.dropbox.com/s/swtn1e0d04v3xrp/IconicsTest.zip?dl=0

**Comment by mikepenz** [comment]
@mikerussellnz I have found the last missing bit and fixed it. There will be an update soon. 

One more thing which may be interesting for you. If you add `.respectFontBounds(true)` to your icon it will be the same size as the original `VectorDrawable`. By default the icon will use the full width and/or height (24dp will result in a real 24dp height icon). With the above setting it will keep the bounds from the font which may be what you want in your case

**Comment by mikepenz** [comment]
v2.7.1 is rolling out now

**Comment by mikepenz** [comment]
Thanks for the sample project

**Comment by mikerussellnz** [comment]
Hi

It is much better but I see one small issue with the initial color of the icons.   When the application starts they have the wrong color (in the sample project they are a lighter color than they should be) but when you select any item they all jump to the correct color.

See screenshot when the application is first opened showing the lighter coloring:

https://dl.dropboxusercontent.com/u/7742667/Screenshot_20160728-223823.png

**Comment by mikerussellnz** [comment]
Updated sample project with more icons https://dl.dropboxusercontent.com/u/7742667/IconicsTest.zip

**Comment by mikepenz** [comment]
@mikerussellnz that's weird.
