### ISSUE TITLE
 There is no application method to'(com.mikepenz.google_material_typeface_library.GoogleMaterial.Icon)'

### ISSUE THREAD

**Issue by EasyLian** [mikepenz/Android-Iconics#203]
All import, what is the cause of the error?

```java
import android.app.Activity;
import android.content.Context;
import android.graphics.Color;
import android.os.Bundle;
import com.mikepenz.google_material_typeface_library.GoogleMaterial;
import com.mikepenz.iconics.IconicsDrawable;
import com.mikepenz.iconics.context.IconicsContextWrapper;

public class MainActivity extends Activity 
{
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);
        
       
       new IconicsDrawable(this)
            .icon(GoogleMaterial.Icon.gmd_airplay)
            .color(Color.RED)
            .sizeDp(24);
        
           }
    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
}
```

**Comment by mikepenz** [comment]
@EasyLian have you added the `GoogleMaterial` font addon?

```gradle
compile 'com.mikepenz:google-material-typeface:2.2.0.2.original@aar' 
```

**Comment by EasyLian** [comment]
@mikepenz
Yes.
I added.
Use as TextView and  Custom Views is  Okeys.
But  use as drawable for  code is error.
 `new IconicsDrawable(this)
            .icon(GoogleMaterial.Icon.gmd_airplay)
            .color(Color.RED)
            .sizeDp(24);
 `
Error:`GoogleMaterial.Icon.gmd_airplay)`
Error:There is no application method to'(com.mikepenz.google_material_typeface_library.GoogleMaterial.Icon)'

Other font is the same.

Thank you.

**Comment by mikepenz** [comment]
@EasyLian you use AndroidStudio and the latest build tools and everything? 

Also the latest version of the library? 

There are no issues with this in the sample app:
```java
new IconicsDrawable(this, MaterialDesignIconic.Icon.gmi_search).color(Color.WHITE).sizeDp(24).respectFontBounds(true)
```

**Comment by mikepenz** [comment]
@EasyLian otherwise may you can provide a zip containing the source code so I can try it?

**Comment by EasyLian** [comment]
@mikepenz
Thank you very much! 
Is the cause of the IDE.
Using Android Studio is no problem. What I use is the AIDE. I'm very sorry to delay you so much time, at the same time also thank you for your efforts.
😃😃😃
```Thank you.```

**Comment by mikepenz** [comment]
@EasyLian oh great that you solved it ;)
