### ISSUE TITLE
Is it possible to change icon color only when using button with icon and text 

### ISSUE THREAD

**Issue by ahmetcj4** [mikepenz/Android-Iconics#204]

**Comment by mikepenz** [comment]
@ahmetcj4 sorry could you please be a bit more specific about what you need?

**Comment by ahmetcj4** [comment]
@mikepenz I wanted to use a button that has Icon and text. Then I want to change color of the icon, not the text.

After some exploration, I found that this is already shown in code.

With some small changes, I get the desired solution, thanks!

This is the code I used.

        Button b4 = (Button) findViewById(R.id.button);

        new Iconics.IconicsBuilder().ctx(this)
                .style(new RelativeSizeSpan(1.2f))
                .style(new ForegroundColorSpan(color))
                .on(b4)
                .build();

**Comment by mikepenz** [comment]
@ahmetcj4 great ;)
