### ISSUE TITLE
Usage of custom font unclear

### ISSUE THREAD

**Issue by BobOtike** [mikepenz/Android-Iconics#205]
Hi Mike, 

I just used your generator to create a custom font from *.css/*.ttf files. I tried to include the created addon in my project via "New Module -> Import Gradle Project" but when syncing afterwards gradle gives me the following error:

`Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist`

Is this the correct way to go about it or am I supposed to include it in another way?

**Comment by mikepenz** [comment]
@BobOtike I assume it looks something like this:
https://github.com/mikepenz/Android-Iconics/blob/develop/devicon-typeface-library/build.gradle#L20

Either you define those properties in your root build.gradle or you replace it with a specfic version in your case

**Comment by BobOtike** [comment]
@mikepenz Yes, exactly. 

I tried setting the project SDK according to this guide [https://www.jetbrains.com/help/idea/2016.1/configuring-global-project-and-module-sdks.html](url), but the option is not present in the dialog I get when following the steps. 

Can you give me a hint on how to define this in the root build.gradle?

**Comment by BobOtike** [comment]
To move on for now I put in the SDK version for the module by hand and now I get the next problem:

The dependency `compile project(':library-core')` could not be found. 

I'm really not to keen on gradle usage.

**Comment by mikepenz** [comment]
@BobOtike I can't really help you regarding "gradle" as I can only give library specific support (everything else would be too much work) 

Everything is visible in the github project.

Here's the definition for vars in the root build.gradle
https://github.com/mikepenz/Android-Iconics/blob/develop/build.gradle#L13

here you define modules:
https://github.com/mikepenz/Android-Iconics/blob/develop/settings.gradle

and yeah the other gradle files are also in the project

**Comment by BobOtike** [comment]
Yeah, I understand that. 

Anyways, figured out how its done going through your links, thanks a lot, its working now.
