### ISSUE TITLE
String resources for icons

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#208]
Is there a reason why you can't generate string resources for the icons?

Instead of `app:ico_icon="gmd-bug-report"` it would be possible to use `app:ico_icon="@string/gmd-bug-report"`... Would make auto complete better... and typos would not happen that easily anymore...

**Comment by mikepenz** [comment]
@MFlisar no there is no reason for this. but it's a good idea. would take pull requests for this.

**Comment by mikepenz** [comment]
will be in the next update of fontawesome and googlematerial for all others I will add them if they have an update or wait for a PR
