### ISSUE TITLE
IconicsImageView layout attributes doesn't work

### ISSUE THREAD

**Issue by arcao** [mikepenz/Android-Iconics#21]
I have problem to set icon and color from a layout for `IconicsImageView`. The attributes are not applied.

Example of layout
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <IconicsImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:iiv_icon="gmd-label"
        app:iiv_color="@color/secondary_text"/>
</LinearLayout>
```

Also Android Studio 1.2 Beta 3 say: 

> Unexpected namespace prefix "app" found for tag IconicsImageView less... (Ctrl+F1) 
>
>Most Android views have attributes in the Android namespace. When referencing these attributes you must include the namespace prefix, or your attribute will be interpreted by aapt as just a custom attribute.
>
>Similarly, in manifest files, nearly all attributes should be in the android: namespace.

By the way there is no way to change icon color from the code (maybe possible via `IconicsDrawable.colorRes(...)`).

**Comment by kosiara** [comment]
Is there a workaround for this in Android Studio? I can't get Designer to work with IconicsImageView. :)

**Comment by mikepenz** [comment]
@kosiara you can add to ignore the unknown prefixes

**Comment by kosiara** [comment]
@mikepenz Thanks a lot ! I'll try it

**Comment by mikepenz** [comment]
@kosiara what is the error message you get from the layout editor? i never use it :D i create my layouts in my head :P

**Comment by sherpya** [comment]
https://code.google.com/p/android/issues/detail?id=65176

**Comment by mikepenz** [comment]
@sherpya not sure. He's talking about the preview.

**Comment by sherpya** [comment]
Please look at the last comment, the guy says it's still a bug, anyway the support library does not suffer of this problem. Also the designer goes crazy and it's unable to draw nothing, not only the custom widget

**Comment by mikepenz** [comment]
@sherpya inside fragment tags. but as far as i can say @arcao has no <fragment>

**Comment by sherpya** [comment]
looks like using the full class `android.view.IconicsButton` does not trip the designer, at this point it would be better to have a different namespace (yes this will break compatibility)

**Comment by mikepenz** [comment]
Moved views to new package

**Comment by sherpya** [comment]
this fixed also namespace problem using iiv_xxxx
