### ISSUE TITLE
No fontawesome fa-edit

### ISSUE THREAD

**Issue by joielechong** [mikepenz/Android-Iconics#211]
I'm trying to add fontawesome fa-edit with faw-edit. Not work. using fa-edit, not work either.

I'm using the latest Android-Iconics library.

Error:
 E/Iconics: Wrong icon name: faw_edit

**Comment by mikepenz** [comment]
@joielechong there is no icon called faw_edit in the current `FontAwesome`

https://github.com/mikepenz/Android-Iconics/blob/develop/fontawesome-typeface-library/src/main/java/com/mikepenz/fontawesome_typeface_library/FontAwesome.java

**Comment by joielechong** [comment]
I found fa-edit in [FontAwesome cheatsheet](http://fontawesome.io/cheatsheet/):
 fa-edit (alias) [&#xf044;]

**Comment by mikepenz** [comment]
@joielechong which is an alias for: fa-pencil-square-o

**Comment by joielechong** [comment]
Thank you very much.
