### ISSUE TITLE
No erase-variant in Community Material

### ISSUE THREAD

**Issue by marbat87** [mikepenz/Android-Iconics#212]
Hi,

I'm not able to find eraser-variant in Community Material typeface.
But I see it on the site https://materialdesignicons.com/

Thanks in advance.
Marcello

**Comment by marbat87** [comment]
I add also:
- reorder-vertical
- reorder-horizontal

**Comment by mikepenz** [comment]
@marbat87 it's on their website but not included in the export. The easiest way to validate this is to search in their `css`  and try to find the name: http://cdn.materialdesignicons.com/1.6.50/css/materialdesignicons.min.css

**Comment by marbat87** [comment]
Sorry but I'm not sure to understand, because i find eraser-variant in the link you posted.

Regards
