### ISSUE TITLE
Online generation tool can't create font pack

### ISSUE THREAD

**Issue by MisterY** [mikepenz/Android-Iconics#214]
http://android-iconics.mikepenz.com/

"ERROR: ReferenceError: TEMPORARY is not defined"

'e is undefined' when clicking Create button

```
TypeError: e is undefined[Learn More]main.min.js:1:3994
p http://android-iconics.mikepenz.com/scripts/main.min.js:1:3994
d http://android-iconics.mikepenz.com/scripts/main.min.js:1:3618
f http://android-iconics.mikepenz.com/scripts/main.min.js:1:2606 
a/e.onmessage http://android-iconics.mikepenz.com/scripts/main.min.js:1:1341
```

**Comment by mikepenz** [comment]
@MisterY could you please tell me which files you provided? and which information you entered?

**Comment by MisterY** [comment]
Attached is the result from Fontastic. It contains the styles.css and the mmex.ttf, which I've used in this case.

[mmex.zip](https://github.com/mikepenz/Android-Iconics/files/424503/mmex.zip)

**Comment by MisterY** [comment]
And for the data, I've tried what appeared like legit data as well as some dummy text (i.e. aoeua).
I'm guessing it would have to do with the generated CSS rather than the manually entered font info.

**Comment by mikepenz** [comment]
Just tried it with the data (and just inserted some dummy text) and it worked
[mmex.zip](https://github.com/mikepenz/Android-Iconics/files/424507/mmex.zip)
<img width="753" alt="bildschirmfoto 2016-08-18 um 11 21 22" src="https://cloud.githubusercontent.com/assets/1476232/17768778/f639e2ec-6535-11e6-87fb-ffe30f7abdb3.png">

**Comment by MisterY** [comment]
Hm! Thanks for the confirmation! 
It does not work in the latest Firefox Developer (50) but it does in Vivaldi (Chromium).
OK, I got the file. Thanks a lot. Will continue testing the lib. 
You can try to check what is the issue with Firefox if you can reproduce it. Cheers.

**Comment by mikepenz** [comment]
@MisterY ah ok :D I am not a real frontend dev so it may not work with anything other than `Chrome` xD
