### ISSUE TITLE
Resulting Unicode characters not usable

### ISSUE THREAD

**Issue by MisterY** [mikepenz/Android-Iconics#215]
Hi! Everything seems to work great so far.
The only issue I've encountered is the treatment of 2-char codes. The resulting CSS from Fontastic includes the codes like `'\u61'`.
When parsed into an Iconic library, Android Studio complains that these are invalid escape sequences.
I've fixed it manually by turning them into `'\u0061'` codes, by adding 00.

Now, the issue is that I keep adding individual icons over time and update the generated library. This process would mean I'd have to replace these codes every time.
Could this be done automatically in the script that generates the font.java class? A simple check where, if the code is 2-character, append 00. This does not change the semantics but helps with Android Studio lint and compilation.

If you could point me to the location of the parser, I might look into it.

**Comment by mikepenz** [comment]
@MisterY the `iconics-generator` is not open source. I will have a look.

**Comment by MisterY** [comment]
Sure, no worries. This should be a quick and simple improvement. Thanks for looking into it.

**Comment by mikepenz** [comment]
This change is now on the site

**Comment by MisterY** [comment]
Awesome! Thank you!
