### ISSUE TITLE
TextView Marquee is not working after enabled automatic xml icons detection.

### ISSUE THREAD

**Issue by DeveAndyloper** [mikepenz/Android-Iconics#217]
Is it possible to be compatible with Marquee?
Marquee effect is working after I removed this code:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
    super.onCreate(savedInstanceState);
}
```

**Comment by mikepenz** [comment]
@DeveAndyloper just changed the sample application to have marquee activated inside the `AutomaticActivity` and it works without any problems in there. 

You can see the code here:
https://github.com/mikepenz/Android-Iconics/commit/b82dad7e8165c18e088ac68ae8b89e20f48be2d1

**Comment by DeveAndyloper** [comment]
@mikepenz Thanks for the sample.
It's still not working if I set the text programmatically.

`((TextView) findViewById(R.id.test1)).setSelected(true);
		((TextView) findViewById(R.id.test1)).setEllipsize(TextUtils.TruncateAt.MARQUEE);
		((TextView) findViewById(R.id.test1)).setSingleLine();
		((TextView) findViewById(R.id.test1)).setText("a}asdfsadfa{bc{hif-test}defgh{faw-adjust}ijk{fon-test1}lm{gmd-plus-circle}n{gmd-speaker}o{met-wind}pqrs{gmd-tab-unselected}tuv{fon-test2}wxy{zasdfasdf");`

**Comment by mikepenz** [comment]
@DeveAndyloper as it is working when the text was set via the xml, I also assume that it will start working when setting all the properties after the text was set. Also as it is working via xml + the code above it is no Android-Iconics issue, and rather some combination of `TextView`, `Marquee` and `Spannables` and selection not set or so which causes this.
