### ISSUE TITLE
Color within text

### ISSUE THREAD

**Issue by EzraLopez** [mikepenz/Android-Iconics#218]
Is there a way to get the icon in a different color from the other text in a TextView? 

I'm trying to make the heart red, but the following is not working for me:
```
<TextView
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:text="<> with {cmd-heart} by GitHub"
android:textColor="@color/white"
app:ico_color="@color/red" />
```

**Comment by mikepenz** [comment]
@EzraLopez sorry this is not possible with the `Android-Iconics` You may just spilt this text up into 2 TextViews and an `IconicsImageView` in the center.

**Comment by EzraLopez** [comment]
I end up using three TextViews but wanted to double check with you. Thanks for this great library!

**Comment by mikepenz** [comment]
@EzraLopez it is quite a rare requirement so I haven't added this, as you can easily achieve it with different implementations too ;)

Thank you. Great it works for you
