### ISSUE TITLE
How to use on setSmallIcon from Notification ?

### ISSUE THREAD

**Issue by claudiobastos** [mikepenz/Android-Iconics#219]
I couldn't find (if any) a snippet to use Android Iconics with Notifications .

It's is possible?
How ?

**Comment by mikepenz** [comment]
@claudiobastos that's not possible as android's `Notification`s only allow you to provide a real resource. Sorry.

**Comment by claudiobastos** [comment]
Thank for you flash response XD

**Comment by mikepenz** [comment]
No problem :) Sorry that it is not possible
