### ISSUE TITLE
How to support the selector?

### ISSUE THREAD

**Issue by jiangyongandy** [mikepenz/Android-Iconics#220]

**Comment by mikepenz** [comment]
@jiangyongandy please add more details.

**Comment by jiangyongandy** [comment]
@mikepenz I want the icon change color when it is pressed or checked  , just like the StateListDrawable.

**Comment by mikepenz** [comment]
@jiangyongandy you can provide a `TintList` which is a `ColorStateList`, which will then update the color:
https://github.com/mikepenz/Android-Iconics/blob/b8521b6ae449914b064d4b54282b1c9eebdae79e/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L823

**Comment by jiangyongandy** [comment]
@mikepenz Thanks,  How  can  I use it as  a  attributes via XML?

**Comment by mikepenz** [comment]
You can set it via xml on API >= 21 (http://stackoverflow.com/a/28353871/325479) 
otherwise you have to do it programtaically
