### ISSUE TITLE
Using ProGuard without excluding R

### ISSUE THREAD

**Issue by EzraLopez** [mikepenz/Android-Iconics#221]
This might be useful to someone:

I didn't want to exclude R from ProGuard so I just initialized the font in my Main Activity like this:

```
Iconics.init(getApplicationContext());
Iconics.registerFont(new CommunityMaterial());
```

and defined IconicsLayoutInflater in all my other activities that needed it like indicated
[here](https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional
):

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
    //...
    super.onCreate(savedInstanceState);
    //...
}
```
(I'm assuming the [alternative: Inject into Context](https://github.com/mikepenz/Android-Iconics#3-alternative-inject-into-context-optional) would also work, but I haven't tested it.)

and after that I could do things like this:

```
<ImageView
android:layout_width="72dp"
android:layout_height="72dp"
app:ico_color="@color/primary"
app:ico_icon="cmd-map" />
```
I've tested this with different devices. My Main Activity is always at the bottom of the activities stack, but I don't know if that makes any difference. 

Cheers!

**Comment by mikepenz** [comment]
@EzraLopez thanks. That's the correct implementation if you don't want to exclude the `R` fields. 

I have marked this as "good to know" hopefully people will use the search function or the tag function prior to asking ;)

**Comment by EzraLopez** [comment]
Ok, cool. No problem @mikepenz! :) You could also add something related to this to the readme file if you consider it necessary.

**Comment by mikepenz** [comment]
@EzraLopez if you got time you may can setup a FAQ section similar to the one of the `MaterialDrawer`. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md
