### ISSUE TITLE
Using icons inside textviews in xml alongside with the Android data binding library

### ISSUE THREAD

**Issue by guenodz** [mikepenz/Android-Iconics#222]
Hi,

How we can add icons to textviews using XML alongside with the Android data binding library ? which use the same characters: "{" & "}" to bind data. Can we change these characters to new ones ?

Thanks.

**Comment by mikepenz** [comment]
@guenodz hi. 

no changing those is not possible. (if changed it will require every single app to be changed to support this again) 

Would you be able to just use `ImageView`s or `IconicsImageView`s in your application?

**Comment by guenodz** [comment]
Hi @mikepenz 

Yes, I can use them. But, I wanna add more than one icon to a TextView.The best approach is to add them inside the text in XML.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/commit/66b338ccb48c317089a28492f0db660abb093e35

**Comment by guenodz** [comment]
Thank you @mikepenz

**Comment by mjmarathon** [comment]
@mikepenz Is there any chance you could add this info to the readme?

**Comment by mikepenz** [comment]
@mjmarathon this feature is not really recommended and people should stay with the default characters. It's a hidden gem ;)
