### ISSUE TITLE
Should I use -'s or _'s?

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/Android-Iconics#223]
Simple as that. What is the recommended (or required) syntax for icons?<br /><br />For example, should I use gmd_add, or gmd-add, and would is be the same in code vs. in XML?

**Comment by drinfernoo** [comment]
I've figured it out :)

**Comment by Eloar** [comment]
@drinfernoo could you provide 'right' answare as you figured it out?

**Comment by mikepenz** [comment]
@Eloar depends on "where" :D in general it doesn't matter
