### ISSUE TITLE
Custom font prefix requires three characters in IconicsImageView

### ISSUE THREAD

**Issue by ade** [mikepenz/Android-Iconics#224]
When making a custom font, three characters in the prefix are required, or the font will not work in XML IconicsImageView

A log message saying "E/Iconics: Wrong icon name: xx_icon_name_here" is only shown, which does not adequately pinpoint the problem.

Suggestion: Add a descriptive error message for this, or support less characters in prefix.

**Comment by mikepenz** [comment]
@ade the character count for the prefix is documented in javadoc:
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/typeface/ITypeface.java#L40

**Comment by mikepenz** [comment]
http://static.javadoc.io/com.mikepenz/iconics-core/2.8.1/com/mikepenz/iconics/typeface/ITypeface.html#getMappingPrefix--

**Comment by ade** [comment]
Ok, I can see that now. However, I do not believe that prevents potential users from getting confused, as the project readme, the generator itself, or any of the generated code contains this note (I just spent an hour troubleshooting this).

**Comment by mikepenz** [comment]
I know that it does not prevent it, but I can't throw an exception inside the interface. (default methods are not supported) 

So I have added the javadoc, and mentioned it here: https://github.com/mikepenz/Android-Iconics/wiki/CustomFontAddonCreating

**Comment by ade** [comment]
The thing is, the front page contains enough information to make your own custom font with the provided generator page, there's no hint that reading the javadocs or the wiki is necessary. That is why I got this confusing error. So what I'm proposing is a santity check somewhere to avoid this for other users. For example;

- Add a simple length check in the javascript font library generator at http://android-iconics.mikepenz.com/ for the mapping prefix

- In com.mikepenz.iconics.IconicsregisterFont(ITypeface font) add a simple check e.g.
`if(font.getMappingPrefix().length != 3) throw new IllegalArgumentException()`

**Comment by mikepenz** [comment]
@ade you can open a PR for the later ;)

**Comment by ade** [comment]
Fair enough.
