### ISSUE TITLE
Custom font generator does not support backslash character

### ISSUE THREAD

**Issue by ade** [mikepenz/Android-Iconics#225]
When using the custom font generator, the backslash (unicode 0x5C) character value in a font will generate invalid java source code in the icons enum, specifically:

`xxx_icon_name('\u005c'),`

which is equivalent to (in the java compiler):

`xxx_icon_name('\'),`

this escapes the end quote character.

the proper code generated should be:

`xxx_icon_name('\\'),`

Using two unicode codes ('\u005c\u005c') does not seem to work, at least in IntelliJ IDEA, so the double backslash literal is provided as the suggested solution.

**Comment by mikepenz** [comment]
@ade the icon should be in general a single unicode character. (I have not tested) and so I do not support multi character unicode mappings. 

Which font generator do you use, which generates cases like the one mentioned above?

**Comment by ade** [comment]
Sorry, perhaps I did not explain the issue adequately. It's a single character. The problem arises due to the compiler interpreting the single backslash character as an escaping character (so instead, it sees an escaped single quote character, and then the parenthesis, so a java syntax error is created).

I'm using IcoMoon.

**Comment by mikepenz** [comment]
@ade still not really sure. It is correct that it used the backslash as escape character:
https://github.com/mikepenz/Android-Iconics/blob/develop/google-material-typeface-library/src/main/java/com/mikepenz/google_material_typeface_library/GoogleMaterial.java#L117

**Comment by ade** [comment]
Trying using `\u005c` for any character and you'll see what I mean! :)

**Comment by mikepenz** [comment]
You miss the `e` after the `u`

**Comment by ade** [comment]
No - Unicode characters start at \u0000. The "E" you are referring to is just a greater number in the valid range.

**Comment by mikepenz** [comment]
Oh yeah sorry. was not on a ide right now. 

The main issue is exactly the following `\u005c` all chars before and after will work. I think in general it is already not a good idea to use common text characters as icon. Do you have a special use case which requires to stay in such a low unicode range?

**Comment by ade** [comment]
I agree that it should probably be avoided. This is just what our designer decided to use... It has worked in our other apps so there was not a problem until now. There are more characters that could cause trouble, such as `\u0027`, the single quote character.

**Comment by mikepenz** [comment]
@ade yes. That's true there may be some more characters. But I think it should be enough to mark this issue as good to know, so hopefully future devs who also have to use such a low unicode range will find it.

**Comment by lukaspili** [comment]
Encountered this issue as well, with a font mapping generated by a design team that's used across several apps/websites. Change in the mapping is therefore not wanted at this state.

The compilation error can be corrected manually very easily, but requires to be done each time a new version of the font is created. Not a big thing, but it would be nice to if the custom font generator would take care of the few special chars automatically.
