### ISSUE TITLE
Is it possible to add "Badges" to the icons?

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/Android-Iconics#227]
I would like to know if its possible to add badges for the icons which are placed on the activity. I am aware that https://github.com/mikepenz/Android-ActionItemBadge will help me to add badge to menu item, But, I would like to add it in app.

**Comment by mikepenz** [comment]
@rakesh1988 the `Android-ActionItemBadge` is only meant for the `Toolbar` that's right. 

At the moment there is no plan to have a separate lib which will created badge views. You will have to do it on your own. (There may be already other libs doing something like this)

You can always also use the icons from the `Android-Iconics` as drawable and put them somewhere

**Comment by danielfaust** [comment]
Hi Mike,

I'm trying to overlay a text over an IconicsButton. Basically it is an IconicsButton in a frame, and it has a TextView as the next sibling. On a standard ImageButton it works, but as soon as I replace it with a IconicsButton, the text is drawn behind the icon.

Could you please briefly explain why this happens? Should I then add the icon as a drawable for the background of the TextView?
