### ISSUE TITLE
Animate IconicsDrawable into another IconicsDrawable

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/Android-Iconics#228]
Is there support for this? Specifically something like a FAB with a 'plus' icon to a 'check' icon.

**Comment by mikepenz** [comment]
@drinfernoo no this is not supported as we do not have direct access to the font vectors, but rather use the system built in font rendering processor to generate the drawable

**Comment by drinfernoo** [comment]
That's what I was afraid of. Thanks anyway!
