### ISSUE TITLE
only half icon displayed in Android 7.0 

### ISSUE THREAD

**Issue by MickHardins** [mikepenz/Android-Iconics#230]
Hi, with the new version of android, icons of drawer appear cutted.
the code i use is:
```java
[...]
.addDrawerItems(new PrimaryDrawerItem().withName(R.string.drawer_item_Search)
                                .withIcon(FontAwesome.Icon.faw_search)
                                .withIdentifier(FragmentTypes.SEARCH_FRAGMENT)
                                .withSelectable(true),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_WishList)
                                .withIcon(FontAwesome.Icon.faw_bi[...]
```
As you can see the icon is cutted, but after pressing on the element the icon goes back to it's expected positining.
this happens also if i use the icon as an iconic drawable:
```java
.setImageDrawable(new IconicsDrawable(mContext, myTypeface.getIcon(iconPrefix+"BLANK")).sizeDp(35));
```
this issue was not present on android 6.
Any ideas about this ? :smiley:

![screenshot_20161001-183103](https://cloud.githubusercontent.com/assets/5359147/19270026/2d06781e-8fbe-11e6-8511-441f6c1800ae.png)

**Comment by mikepenz** [comment]
@MickHardins please update to the latest version of the android iconics library. This was fixed 1 or 2 months ago

**Comment by MickHardins** [comment]
Sorry to have bothered you, i was pretty sure i had the latest version. Thank you Mike!

**Comment by mikepenz** [comment]
No problem ;) As long as it works now, everything is fine :D
