### ISSUE TITLE
Use SVG file directly to get a drawable

### ISSUE THREAD

**Issue by joaomgcd** [mikepenz/Android-Iconics#231]
Would it be possible to add a SVG to drawable converter? Or is that out of scope for this project?

Thanks in advance

**Comment by mikepenz** [comment]
@joaomgcd for using `svg`s I recommend to use the Android's built in mechanism via the `VectorDrawable` or the `VectorDrawableCompat`.
There are also already other projects just for the use case with svg's so you might have a look at those too. 

This project aims to use the advantage of having an icon font (just a single file) with many possible icons, and using the fast internal text rendering to get the drawables.

**Comment by joaomgcd** [comment]
Thank you very much for the recommendations :) Really appreciate it!

**Comment by joaomgcd** [comment]
@mikepenz since you have a lot of experience with this: do you know of way to load a VectorDrawable from the file system? VectorDrawable.createFromPath() always returns a null drawable.

Or do you know a library that does that? Thanks again!
