### ISSUE TITLE
error Wrong icon name in product flavour

### ISSUE THREAD

**Issue by athasamid** [mikepenz/Android-Iconics#234]
Hi I  create app with product flavour, this icon work in base app, but not in build variant

**Comment by mikepenz** [comment]
@athasamid could you please provide some additional details? What do you mean it does not work?

**Comment by athasamid** [comment]
sorry for my bad english. 
the icon show in defaultConfig app, but not in product flavour

here my grade
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

apply plugin: 'com.neenbedankt.android-apt'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    productFlavors{
        cas{
            applicationId "com.athasoft.crimealarmsystem.baru"
            buildConfigField "Double", "LAT", '-7.1560885'
            buildConfigField "Double", "LNG", '111.8785383'
            buildConfigField "Boolean", "WITHHASHTAG", "true"
            versionCode 24
            versionName "3.4"
            multiDexEnabled true
        }

        trust{
            applicationId "com.synergics.trust.cimahi"
            buildConfigField "Double", "LAT", '-6.8730021'
            buildConfigField "Double", "LNG", '107.540597'
            buildConfigField "Boolean", "WITHHASHTAG", "true"
            versionCode 13
            versionName "2.2"
            multiDexEnabled true
        }

        area{
            applicationId "com.synergics.area.minsel"
            buildConfigField "Double", "LAT", '1.2130099'
            buildConfigField "Double", "LNG", '124.594992'
            buildConfigField "Boolean", "WITHHASHTAG", "true"
            versionCode 4
            versionName "1.3"
            multiDexEnabled true
        }

        siaga{
            applicationId "com.synergics.siaga.lamsel"
            buildConfigField "Double", "LAT", '-5.6146788'
            buildConfigField "Double", "LNG", '105.4913116'
            buildConfigField "Boolean", "WITHHASHTAG", "false"
            versionCode 1
            versionName "1.0"
            multiDexEnabled true
        }

    }

    signingConfigs {
        cas {
            storeFile file('/Users/athasamid/projects/Mobile/Android/base-alarm/personil/cas-personil')
            storePassword "polresbojonegoro_1"
            keyAlias "cas-personil"
            keyPassword "polresbojonegoro_1"
        }

        trust {
            storeFile file('/Users/athasamid/projects/Mobile/Android/base-alarm/personil/trust-cimahi')
            storePassword "polrescimahi_1"
            keyAlias "trust-cimahi"
            keyPassword "polrescimahi_1"
        }

        area {
            storeFile file('/Users/athasamid/projects/Mobile/Android/base-alarm/personil/area-minsel')
            storePassword "polresminsel_1"
            keyAlias "area-minsel"
            keyPassword "polresminsel_1"
        }
    }

    defaultConfig {
        applicationId "com.athasoft.crimealarmsystem.baru"
        minSdkVersion 15
        targetSdkVersion 23
        multiDexEnabled true
    }

    buildTypes {
        def casSigninConfig = signingConfigs.cas
        /*def trustSigninConfig = singningConfigs.trust
        def areaSigninConfig = signingConfigs.area*/
        release {
            signingConfig casSigninConfig
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.mikepenz:iconics-core:2.8.1@aar'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:cardview-v7:24.2.0'
    compile 'com.android.support:percent:24.2.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.android.support:design:24.2.0'
    //compile 'com.google.android.gms:play-services:9.4.0'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
    compile 'com.google.android.gms:play-services-location:9.4.0'
    compile 'com.google.android.gms:play-services-places:9.4.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'id.zelory:compressor:1.0.2'
    compile 'com.mikepenz:ionicons-typeface:2.0.1.2@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.6.0.3@aar'
    compile 'com.schibstedspain.android:leku:2.1.0'
    compile 'com.github.nguyenhoanglam:ImagePicker:1.0.3'
    compile 'com.github.armcha:SpaceNavigationView:1.0.0'
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'
    compile 'io.realm:android-adapters:1.3.0'
    compile 'com.google.firebase:firebase-core:9.4.0'
    compile 'com.google.firebase:firebase-messaging:9.4.0'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.mobsandgeeks:android-saripaar:2.0.3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.wdullaer:materialdatetimepicker:2.5.0'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.kbeanie:multipicker:1.1.1@aar'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.github.quentin7b:android-location-tracker:3.2'
    compile project(':socket.io-client')
    compile('com.crashlytics.sdk.android:crashlytics:2.6.3@aar') {
        transitive = true;
    }
}

apply plugin: 'realm-android'
apply plugin: 'com.google.gms.google-services'`

from grade above, icon just shown in package com.athasoft.crimealarmsystem.baru, but not show in other package.

**Comment by mikepenz** [comment]
do you use the icons via xml or java? Do you have some log output regarding the iconics library?

**Comment by athasamid** [comment]
i use via xml

**Comment by mikepenz** [comment]
@athasamid oh ok then it'S very easy. Either you follow the steps shown here to support proguard:
https://github.com/mikepenz/Android-Iconics#proguard (which will enable font auto detection) 

Or you just register the fonts you use at some place before using. Like done here:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17

**Comment by athasamid** [comment]
i've tried that solution but nothing change, keep show error wrong icon name

**Comment by msneujink** [comment]
I've encountered the same problem when I define a flavor with a different `applicationId`. None of the icons are shown. The console logs: 
```
E/Iconics: Wrong icon name: gmd_home
```
But i've found a fix, add the following code in your Application class. In this case, I am using CommunityMaterial, Fontawesome and GoogleMaterial.

```
Iconics.init(getApplicationContext());
Iconics.registerFont(new CommunityMaterial());
Iconics.registerFont(new GoogleMaterial());
Iconics.registerFont(new FontAwesome());
```

**Comment by athasamid** [comment]
thanks, yeah, ive tried that solution too, but nothing happen

**Comment by mikepenz** [comment]
@athasamid where do you do the `registerFont` in your `CustomApplication`?

@msneujink yes that's the proper way of registering the fonts when proguard or different applicationId prevents the auto detection of the fonts

**Comment by athasamid** [comment]
in Application class

**Comment by mikepenz** [comment]
That's weird. do you see any special logcat? Can you probably debug? Are you sure this icon does not exist? Have you tried it programatically instead XML?

**Comment by mikepenz** [comment]
@athasamid please report back

**Comment by CMircea** [comment]
@mikepenz I am having the exact same issue on version 6.2.3, targeting 28 and running on 23, with flavors using application ID suffix. I am using the attachBaseContext method to wrap the context. Once I added Firebase & Crashlytics, the icons no longer show and I see warnings in logcat about "wrong icon name".

If I manually initialize Iconics and the fonts in the Application's onCreate as @msneujink sugested the icons are displayed again. No other changes are needed. It's quite weird.

**Comment by mikepenz** [comment]
@CMircea usually it has something to do with the reflection based approach not being able to find the icons. (it tried to get the R class and via the R.class the string resource which specifies the font to load)

if you register them you basically tell the library which fonts are available and then it can find the icon which you use

**Comment by CMircea** [comment]
@mikepenz yeah I figured as much. It's excluded from ProGuard/R8, looks like the Firebase plugins break something. I think manually registering the fonts is a good enough compromise.

**Comment by ecino** [comment]
Hello, I'm having the same issue and I wanted to apply proposed solution:
```
Iconics.init(getApplicationContext());
Iconics.registerFont(new FontAwesome());
```
However in cannot do `new FontAwesome()`, I get the error : `error: FontAwesome() has private access in FontAwesome`. How can I do this?

**Comment by vivekav-96** [comment]
> private

I too am facing the same issue. Please resolve.

**Comment by zTrap** [comment]
FontAwesome.INSTANCE

**Comment by mikepenz** [comment]
@vivekav-96 if you are not using kotlin you may want to stay with the old v3 and the non kotlin fonts

**Comment by vivekav-96** [comment]
Thanks @zTrap. That fixed my issue. 

@mikepenz The navigation drawer v6 was causing issues in android 10. So I upgraded it to 7, and in the while, I updated the Iconics library too. Please let me know where things could go wrong if use v4 fonts in my non-kotlin project?

**Comment by mikepenz** [comment]
@vivekav-96 nothing could go wrong doing this. the API is just not as nice as it would be in kotlin :)
