### ISSUE TITLE
Issue with Multiple Icons in text

### ISSUE THREAD

**Issue by amithgc** [mikepenz/Android-Iconics#236]
Using versions 
 compile "com.mikepenz:iconics-core:2.8.1@aar"
 compile 'com.mikepenz:community-material-typeface:1.7.22.1@aar'

I am using Android-Iconics to display star rating, I have a TextView and when i put the following code in XML, everything works fine

 ```
<TextView
                        android:id="@+id/stars"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical"
                        android:gravity="left"
                        android:text="{cmd_star}{cmd_star}{cmd_star}{cmd_star_half}{cmd_star_outline}"
                        android:textColor="@color/star_yellow"
                        android:textSize="15sp" />
```

But when i do the save in Java code, 
`stars.setText("{cmd_star}{cmd_star}{cmd_star}{cmd_star_half}{cmd_star_outline}");`
the second star is not displayed, It is rendered as *{cmd_star}***

is this a bug or am i doing something wrong?

**Comment by mikepenz** [comment]
@amithgc in general I recommend not to use it like this, there is also a android component doing a rating bar with stars?

other than this. it might be a bug, which I have to debug first

**Comment by amithgc** [comment]
Thanks, Please let me know if this is a bug. If yes we will find a workaround for now
