### ISSUE TITLE
Icon not appearing on extends Activity

### ISSUE THREAD

**Issue by arvi** [mikepenz/Android-Iconics#237]
Hello, thanks for this plugin. I was able to make it work if class extends to AppCompatActivity, but for my activities with no action bar which extends to Activity I can't make it work since there is no `getDelegate()`.

`LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));`

Do you have any suggestions to make this work on cases it extends Activity? Thank you :smile:

**Comment by mikepenz** [comment]
@arvi in general you don't have to use the iconics inside text. Youc an use them as normal drawables everywhere. 

In addition if the automatic solution would not work in your case, to just do it manually. 
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L57

**Comment by arvi** [comment]
Thank you I will use this as guide. :smile:
