### ISSUE TITLE
Couldnt align icon to the right

### ISSUE THREAD

**Issue by B-Esmaili** [mikepenz/Android-Iconics#239]
I have downloaded and tested your lib , it's simply awesome! but i am not able to align icon to right with non-latin letters. 

this is the case i am talking about

<img width="289" alt="2016-11-27_153630" src="https://cloud.githubusercontent.com/assets/9152515/20648275/84c9dffa-b4b7-11e6-93d0-b49b2b8de734.png">

any idea how can i make it float to right?

**Comment by mikepenz** [comment]
@B-Esmaili this is not library dependent. seems like some android framework thing. 

In your case I suggest to set it as compound drawable or just in an ImageView programatically.

**Comment by B-Esmaili** [comment]
@mikepenz  thanks for your response, i resolved the issue by creating custom `Drawable` from `faw` and setting `DrawableRight` manually.

**Comment by mikepenz** [comment]
great.
