### ISSUE TITLE
Add ability to update an existing library

### ISSUE THREAD

**Issue by alorma** [mikepenz/Android-Iconics#24]
Hi.

As you can see in https://octicons.github.com/, currently the Octicons library is version 2.2.2, and the app uses 2.2.0.

How can i update the Octicons lib (or anyone else), without recreate full Octicons class? Is there any way to ```.withFontFil("file.ttf);```?

**Comment by mikepenz** [comment]
@alorma the only way to update a font is use the js included and update the mapping entries, and updating the file. as far as i know there's no way to get the (string - utf8 char) mapping from the ttf.

**Comment by alorma** [comment]
Uhmm.

I wasn't talking about add new icons.

Ex: imagine UI designer sent you font_01.ttf, and then, after a week font_02.ttf, with the same icon, but well designed (with material design ex).

I need to compile a new version of my icon library?

**Comment by mikepenz** [comment]
ah i see. if the icons itself don't change. you can just add a new custom "font" to your project. as shown in the sample activity. just use the font class inside your app then.

**Comment by alorma** [comment]
Ok :)

I just suggest something like

```new Octicon().withFile("octicons_2.2.3.ttf")```

**Comment by mikepenz** [comment]
@alorma yeah not sure if it makes sense because the provided addons should be updated with new release. and custom fonts which are created by your designers are a module or a simple class in your project
