### ISSUE TITLE
Icon padding

### ISSUE THREAD

**Issue by sagits** [mikepenz/Android-Iconics#240]
Hey @mikepenz , im having that design issue where the icons have different paddings. 

I know that the builder has a setPaddingDp() function, which sets all four paddings. Im thinking about creating separeted functions for the 4 sides and defining the original paddings somehow (in a way other users can select the icon and use an automatic padding function). Do you think that will work? Thanks in advance.

**Comment by mikepenz** [comment]
@sagits do these icons have the paddings already in the raw data?
If yes you could try `respectFontBounds(true)` 

If not there are the methods to define an offset inside its bounds

**Comment by sagits** [comment]
@mikepenz thanks for answering, i wanna try this approach for the Material Design fonts. I know that they have a default padding, but its the same padding for all 4 sides. I wanna give custom paddings to the 4 sides (following the original icon guides). 

My intention is to make this in a way i could make a pull request later and help other users with this issue.
What do you suggest?

**Comment by mikepenz** [comment]
@sagits with `respectFontBounds` it should have the correct paddings as defined inside the font. so this should be fine for those icons. Are you sure it does not change? 

I am not sure how such a PR would look like as you would basically have to go though all icons and add a util or a helper to define the correct paddings for those.

**Comment by sagits** [comment]
Thanks for answering. I have followed the discussion on this issues:
https://github.com/mikepenz/Android-Iconics/issues/85
https://github.com/mikepenz/Android-Iconics/issues/48

As you said:
"The thing is that google does not use the same paddings for all of their icons, and i see no programmatically solution to automatically define the different paddings."

I guess that respectFontBounds will not solve that, am i right? And my issue is that some icons have diferent top and left paddings, thats why i was thinking of creating a function for each side padding, what do you think? Thanks in advance.

**Comment by mikepenz** [comment]
@sagits yes that was in those old issues. `respectFontBounds` was added at a later point, adding the feature that it will now set the paddings as defined in the font. (I didn't know in the past that this was possible) As far as I've seen, this worked. But maybe I am wrong. 

Not sure. Perhaps adding this informatoin to the "enum" of the font

**Comment by sagits** [comment]
Thanks @mikepenz  Ill give it a try and answer if it solves the problem. By the way, how could i use respectfontBounds along with IconicsImageView in xml? Thanks in advance.

**Comment by mikepenz** [comment]
@sagits currently not possible via xml only.

**Comment by sagits** [comment]
Hi @mikepenz , i have tryied to set default paddings using respectFontBounds() for the GoogleMaterial font but it didnt work. Im in a hurry with a project, but if i came up with something usefull ill let your know. Thanks again.
