### ISSUE TITLE
Which context to use for IconDrawable

### ISSUE THREAD

**Issue by ashwanikumar04** [mikepenz/Android-Iconics#241]
Hello:

This is more of a question than an issue.

We can use ```IconicsDrawable``` with ImageView. My question is what context to use with it. 
Suppose I have an icon which is shown in a recyclerview. Icon's image changes with some logic so I will use IconicsDrawable. 
Here is it better to use ApplicationContext and cache the drawables in the adapter and then use them accordingly? 
Thanks

**Comment by mikepenz** [comment]
@ashwanikumar04 the `IconicsDrawable` will allways make sure to use the `ApplicationContext` 
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L127

The context is mainly used to resolve resources you may pass into the drawable

**Comment by ashwanikumar04** [comment]
Thanks :)
