### ISSUE TITLE
IconicsDrawable error handling

### ISSUE THREAD

**Issue by Tolriq** [mikepenz/Android-Iconics#242]
First thanks for the lib it's pretty cool :)

There's just a small limitation about error handling that I'd like to enhance (Can do PR once you decide how).

Currently when creating IconicsDrawable with an invalid icon name it will log something but there's no status or anything that app can check to see if the Drawable is correctly initialized.

It's problematic to correctly handle problems like a user rollback to a previous version that include less icons for example (and using icon name in db or online or whatever). And I'm sure many valid other use case.

Could be for example a haveValidIcon() getter, or maybe a global util iconExists() ?

Could also add a errorIcon() that would be loaded when icon can't be loaded.

Lot's of possible idea to solve the simple issue: How to handle properly the fact that an icon can't be loaded as not available.

**Comment by mikepenz** [comment]
@Tolriq to say it in a different way, you would like to have a fallback icon if the main icon fails to load? 

My only question is, you as developer implement it, so during implementation you check if the icon is there, so you can take care this is shown during implementation, and nothing will change in the icon set itself after you implemented it?

I understand such a usecase for image loader libraries, but for this case? Icons are static somehow. And what would be if the fallback is not existing?

**Comment by Tolriq** [comment]
Well for my use case yes a fallback could be ok but maybe not enough for other cases if a user want to show a non iconic Drawable.

Maybe I was not clear about the use case.

A user can assign icon to something displayed in a recyclerview. Since this data can be persistent the name of the icon will be stored somewhere and can be used with another version of the application.

Then displayed with for example : 

> holder.imageView.setImageDrawable(new IconicsDrawable(holder.imageView.getContext(), holder.data.icon).sizeDp(24).respectFontBounds(true));

Imagine I rollback the icons library for licensing issue or anything, then the name of the icon stored in database would no longer be available even if it was once.
Or that this database is shared between some users that do not have the same version of my app and as such not the same amounts of icons included.

This case can't be solved currently. For the default icon since it would be from the code and not random DB value it would be available at the time I write code, so each app version would have a valid default. (But as said at start maybe for some use case people would want to display a static drawable in that case)

**Comment by Tolriq** [comment]
@mikepenz any thoughts about the need? Finally your lib fulfill my needs so I'll use it in production and need to know what will be my todo list if / when I'll update your lib with more icons.

**Comment by Rainer-Lang** [comment]
I agree with @mikepenz - icons are static. For all other I would use Glide or Piccasso, there you have "error" and "placeholder" and even "thumbnail".

**Comment by Tolriq** [comment]
I guess my English is really bad ;)

Icons are not static by nature, they are static only for the embedded font at one single time.

Let met explains with how I use the library and why error handling is needed.

In my application users can create custom commands to replace buttons in a remote screen. They can associate icons with the command and everything is saved on the cloud.

So when they use my application version 1 that propose community-material-typeface:1.7.22.1 they have let's say 534 icons available.

So for the moment no problem there's 534 icons, they can choose inside those, and the name of the icon is saved on the cloud.

Now in 3 months I update the application and community-material-typeface is now updated and contains 550 icons.

New users have the new version of the application they can now assign 550 icons. But when another user restore the cloud database and still have version 1 of the application he only have access to 534 icons.

Meaning for 16 icons that some other users may have used, he well see a null drawable undetectable by the application due to how failure are now handled.

And this is valid for anything that store the icon name outside of the application. You can not control what icons are available at the time they are displayed.

**Comment by Rainer-Lang** [comment]
Why store the name of an icon? I think this is the point. 😉

**Comment by Rainer-Lang** [comment]
Read your text once more. Maybe a method like "iconExists" would be good...

**Comment by Tolriq** [comment]
Then please tell me, how do you allow a user to assign an icon to something, store it in the cloud and allow restoration?

And even if not using name, but codepoint or anything else, that does not change the issue, at one point the user can have data that point to an icon that his version of the application does not have.

Anyway no problem if you do not understand this basic need, I'll keep a fork that fill the need, just sad that I won't PR and have to maintain something.

**Comment by Rainer-Lang** [comment]
@Tolriq could yiu provide a link to your methid in your fork?

**Comment by Tolriq** [comment]
For the moment I'm in beta so I've just added a temp solution copied from IconicsDrawable source.

There's not yet a fork as I don't know what Mike would prefer.

```
    public static boolean iconExist(String icon) {
        try {
            ITypeface font = Iconics.findFont(Application.getInstance(), icon.substring(0, 3));
            icon = icon.replace("-", "_");
            font.getIcon(icon);
            return true;
        } catch (Exception ignore) {
        }
        return false;
    }

```

**Comment by mikepenz** [comment]
@Tolriq I am fine with a PR and I think the above method would definitely be helpful :). 

The only issue is that `Application.getInstance()` shouldn't be used, and the context should be passed in via the method

**Comment by Tolriq** [comment]
#245 

This was just a quick internal function ;)

**Comment by mikepenz** [comment]
Sorry for missing this one for so long. merged your PR
