### ISSUE TITLE
Need help in displaying all icons and storing the icon value in DB

### ISSUE THREAD

**Issue by kalyandechiraju** [mikepenz/Android-Iconics#243]
Hi, I want to display list of all available icons under one Font type (say GoogleMaterial) and store the picked icon in DB. Can anyone help me out in implementing this?

**Comment by mikepenz** [comment]
@kalyandechiraju just check out the sample app. that does exactly this.

**Comment by kalyandechiraju** [comment]
Hi @mikepenz Can I know if it's possible to set icon in textview at runtime? All I am trying is to get weather condition ID from openweather map api and trying to resolve icon and set it to textview. Can you please help me out? Thank you

**Comment by mikepenz** [comment]
@kalyandechiraju yes that's possible. check out the sample app's code. it showcases how you can do this ;)
