### ISSUE TITLE
How to set the icon color and size for icons rendered using {icon-identifier} syntax?

### ISSUE THREAD

**Issue by kalyandechiraju** [mikepenz/Android-Iconics#248]
If I want to render the iconics using the { icon-definer } syntax into a textview from code, then can I set the color and icon size for that icon?

**Comment by mikepenz** [comment]
@kalyandechiraju this is supported to a specific amount. You can find out more in the sample app. 

This will allow you to color an icon: 
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L59

**Comment by kalyandechiraju** [comment]
That's a good one in the sample. But my TextView already has some text before and after the icon. Then I think that way won't help me.

**Comment by mikepenz** [comment]
the code will just style the icon. not the text before and after

**Comment by kalyandechiraju** [comment]
Will that sample code append the icon to the passed in TextView ?

**Comment by mikepenz** [comment]
```java
new Iconics.IconicsBuilder().ctx(this)
                .styleFor("faw-adjust", new BackgroundColorSpan(Color.RED), new ForegroundColorSpan(Color.parseColor("#33000000")), new RelativeSizeSpan(2f))
                .on(yourTextView)
                .build();
```

will just apply the colorspan and forgroundspan and RelativeSizeSpan on the "faw-adjust" icon in the given textview for example.

**Comment by kalyandechiraju** [comment]
perfect
