### ISSUE TITLE
ITypeface shouldn't force me to add data

### ISSUE THREAD

**Issue by alorma** [mikepenz/Android-Iconics#25]
Adding the following methods to ```Typeface```

```
    String getAuthor();

    String getUrl();

    String getDescription();

    String getLicense();

    String getLicenseUrl();
```

Is weird, it should be in a ILicense class?

**Comment by mikepenz** [comment]
@alorma yeah it would be possible to split it up. but if you don't require these information just keep them empty.

**Comment by mikepenz** [comment]
@alorma ok i think in fact you can keep those fields with an empty `String`.
