### ISSUE TITLE
google-material-typeface-library like `font_addon.xml` for all font modules

### ISSUE THREAD

**Issue by jayrave** [mikepenz/Android-Iconics#250]
Hey Mike, `google-material-typeface-library`'s `font_addon.xml` has string resource for all the icons in that module & they are really useful while setting up the icons using `IconicsImageView` & siblings via XML. Between versions, if the code for an icon has changed, a compilation error would be thrown instead of later seeing empty space on UI in runtime (unless some other icon has taken on that code)

Can we such files for all font modules?

**Comment by mikepenz** [comment]
@jayrave you can do a PR and provide something like this :D

**Comment by jayrave** [comment]
Sure. Sounds good. I will start working on it

**Comment by mikepenz** [comment]
@jayrave I'll close this issue as it is no more issue :) I would still love to see a PR at some point, if you find time.
