### ISSUE TITLE
Is there a way to "group" the selection of drawer items?

### ISSUE THREAD

**Issue by rpgdev** [mikepenz/Android-Iconics#251]
I'm wondering if there is a way to take into account the grouping of drawer items in order to only keep one item selected in each group. As it is, multiselect lets you choose multiple items regardless of where they are located. I'd like to be able to select one item from one collapsable drawer item and then select another from other collapsable drawer item while leaving the previous one selected (since it would be in another group).

**Comment by mikepenz** [comment]
@rpgdev first this question is in the wrong repository. 
Second no this feature does not exist, and would need to be implemented manually on your side

**Comment by rpgdev** [comment]
Sorry, my bad. I had both tabs opened alongside each other and that's why it happened. Can you please give me some pointers as to where I could begin to implement this behaviour?

**Comment by mikepenz** [comment]
@rpgdev basically you will have to listen to the click events and then decide based on select/deselect if this current item is in group 1 and then check if you have to selecect somethinng in group 1

**Comment by rpgdev** [comment]
@mikepenz I tried this but it seems you can't select more than one item in code even with multiselect set to true. Is there a way to accomplish this? I wanted to set as selected some fields from the get go and allow the user to change them as they went along using the app. I know that isn't exactly the use that should be given to the drawer but in my app it makes sense.

**Comment by rpgdev** [comment]
@mikepenz for the record, I ended up modifying your lib and removing the deselect() inside setSelected(), it made it easier to get the behavior I wanted. Granted now I don't take advantage of the one in the repo but it works and since the modification is so simple I can easily update the drawer if need be. Thanks!
