### ISSUE TITLE
Question: Is it possible to use Iconics to load custom icons?

### ISSUE THREAD

**Issue by NovaViper** [mikepenz/Android-Iconics#252]
Hey, is it any way possible to use this library to load custom icons, like you can with fonts?

**Comment by mikepenz** [comment]
@NovaViper you can use it to load custom fonts, so you just create a extension with the icons. 

For vectors, or normal drawables just use the system default components

**Comment by NovaViper** [comment]
Ah ok, I'm trying to load the icons from Iconics for my fragments in my app intro.. I can't see to find the methods in the xml to load the images in the default ImageViewer nor in the Iconics ImageViewer (for this, I can't get the images to display)

**Comment by mikepenz** [comment]
what's the log output?

**Comment by NovaViper** [comment]
There isn't any log output.. it just doesn't show me anything when I enter it in the xml (in preview mode)

**Comment by mikepenz** [comment]
In preview mode you will never see it :D

**Comment by NovaViper** [comment]
Oh *facepalm* Then is there a way to have the icons switch on certain conditions, say if the lockscreen is unlocked?

**Comment by mikepenz** [comment]
@NovaViper do it programatically as you would do it in general :D

**Comment by NovaViper** [comment]
I know but I'm trying to add in the icon in the, but it says unexpected namespace

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:orientation="vertical" android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="10"
        android:id="@+id/main">

    <TextView
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:layout_gravity="center"
            android:gravity="center"
            android:paddingLeft="32dp"
            android:layout_weight="3"
            android:fontFamily="sans-serif-thin"
            android:paddingRight="32dp"
            android:textSize="28sp"
            android:text="@string/disableSystemLockIntro"/>

    <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="0dp"
            android:orientation="vertical"
            android:gravity="center"
            android:layout_weight="5">

        <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:paddingLeft="16dp"
                android:paddingRight="16dp"
                android:id="@+id/intro_disableSLImage"
                app:ico_color="@color/md_black_1000"
                app:ico_icon="@string/gmd_lock_open" />
    </LinearLayout>
    <TextView
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:layout_weight="3"
            android:layout_gravity="center"
            android:gravity="center"
            android:paddingLeft="64dp"
            android:paddingRight="64dp"
            android:textSize="16sp"
            android:textStyle="bold"
            android:onClick="disableLock"
            android:id="@+id/disableLockTxtBt"
            android:text="@string/disableSystemLockBtnTxt"/>
    <TextView
            android:layout_width="fill_parent"
            android:layout_height="64dp" />
</LinearLayout>
```

**Comment by NovaViper** [comment]
And I do another notice another strange thing.. When I do force the icon to change programmically, nothing displays (Sorry I'm asking alot of questions, I'm just having a hard time figuring out what's wrong <_>)
Fragment Code: https://paste.ofcode.org/9DYLDqfXEJYBV6hp58yQAS
XML: https://paste.ofcode.org/SUYWNkihaQrT3KakB25yqd
Main Activity: https://paste.ofcode.org/PAGPMyH5UiTUkZEmueYmCH

**Comment by mikepenz** [comment]
You should give the icons a size

**Comment by mikepenz** [comment]
And color :D

**Comment by NovaViper** [comment]
Ah ha! I changed from "setImageDrawable" to 'setIcon' and I can get the program to display the icons on switch.. but now I got one important question; how do I get the icon to fit inside the parent LinearLayout?

**Comment by mikepenz** [comment]
@NovaViper that's nothing for the Drawable. That's just layout's and definition of your ImageView :D

**Comment by NovaViper** [comment]
Oh, lol. Thanks for helping!
