### ISSUE TITLE
Add a emoji character inside an IconicsImageView

### ISSUE THREAD

**Issue by csbenz** [mikepenz/Android-Iconics#253]
When i use `setIconText()` with the unicode character for my icon, it only display the unicode value.

**Comment by mikepenz** [comment]
@csbenz that's how this method works. It uses a text and displays this text. there is the method `icon` which will use the icon name:

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L175

**Comment by csbenz** [comment]
Are you suggesting I can use that method to display a system emoji such as 🎩? Because nothing is shown when I do that.

**Comment by mikepenz** [comment]
@csbenz this library is not meant nor can't it show system emojis
