### ISSUE TITLE
WearAction - addAction - How to use it?

### ISSUE THREAD

**Issue by chrisonline** [mikepenz/Android-Iconics#254]
I want to use it via the Android Wear or Notification method addAction.
But this method does only accept an int to the drawable, but not a drawable.

How can I use it with your library?
Or is this not possible?

**Comment by mikepenz** [comment]
@chrisonline notifications do only allow real resources, no programatically generated drawables. So you can not use it there. Sorry. That's no limitation of the lib, that's a general limitation of the system.
