### ISSUE TITLE
Icon not renderred properly on specific devices 

### ISSUE THREAD

**Issue by spoonart1** [mikepenz/Android-Iconics#255]
Hello, i have been using this powerful libs for my app.
i was using my custom font for my icon, but suddenly the icon not renderred properly on some devices..
here.. 

this how it looks on MOTO G (1ST GEN) | MOTO X (2 GEN) - ANDROID 4.4 | HINDI | ARABIC | GERMAN
![screen shot 2017-02-20 at 12 18 15 pm](https://cloud.githubusercontent.com/assets/17171325/23112968/43d052de-f767-11e6-9eea-1c7631cce0fb.png)

this is how it looks on LG G3 - ANDROID 4.4 | GALAXY NOTE3 - ANDROID 4.4 | ENGLISH 
![screen shot 2017-02-20 at 12 17 58 pm](https://cloud.githubusercontent.com/assets/17171325/23113026/b0764eb6-f767-11e6-9ebf-62f16aeec095.png)

any idea??

note : the font has already been initted on customApplicationClass in onCreate method

**Comment by mikepenz** [comment]
@spoonart1 which typeface do you use? And which version of the library? 
It seems some phones have altered the way of font rendering which results in this issue for some unicode range. 

You may want to use the `material-design-iconic-typeface` and try if it solves the problem

**Comment by mikepenz** [comment]
This maybe the same as discussed here:
https://github.com/mikepenz/Android-Iconics/issues/90
And this:
https://github.com/mikepenz/Android-Iconics/issues/179#issuecomment-231070781
