### ISSUE TITLE
Community Material update

### ISSUE THREAD

**Issue by rpgdev** [mikepenz/Android-Iconics#256]
Any chance of having an update to the Iconics community material? They are on 1.8.36 now with quite a few new icons added. Please consider it. 

Thanks!

**Comment by mikepenz** [comment]
@rpgdev it possible will take me a bit longer to update. You could open a PR updating it though :D

**Comment by rpgdev** [comment]
I may just do that haha.

**Comment by mikepenz** [comment]
I currently do the update. Thanks anyways ;)
For the next time you can also use: http://android-iconics.mikepenz.com/

**Comment by rpgdev** [comment]
Thanks @mikepenz!
