### ISSUE TITLE
[SUGGESTION] Show Icon Parts in Editor as a symbol

### ISSUE THREAD

**Issue by toyongbanatero** [mikepenz/Android-Iconics#257]
Hello! I've been using Android Iconics since I saw this repo about 2 years ago and it is great! Easy adding of icons and combining text with icons everywhere is very easy. So now with my question (or suggestion).  

We know that adding icons in XML using `IconicsButton` or `IconicsTextView` requires you to have a format of `{cmd-delete}` as an example. Now when you look at the Layout Editor of Android Studio, you will see the text instead of a rendered icon, and I know this is a limitation with no easy way to fix at the moment. Unfortunately, this causes some problems if you want to see how things will look like in the Layout Editor quickly. For example, I am working with a simple app now and I have added a button that has a width of 48dp, for this will be only containing a delete icon when running on a device.  

![screenshot from 2017-02-25 11-29-17](https://cloud.githubusercontent.com/assets/8281524/23327876/39d45e7e-fb4f-11e6-95bb-d395a4f81865.png)

The problem now is that the `IconicsButton` now occupies more vertical space than what really it should have. I could fix the problem by adding `android:maxLines="1"` in the XML and it will be rendered as 1 line only, truncating the text, but it is not really that intuitive and may cause problems/not applicable on other situations.  

So I am thinking if it is possible that every time it picks up some text with a format of {icon-font-name}, it will be converted in a symbol that can identify that it is an icon during design, for example showing up as ⬛ or ⬜ in the editor (just an example). This will eliminate the problem that it shows up as text on design time.  

There could be a problem, like it could be slightly confusing because you will see the same symbol if you are using multiple icons in many places and also if your text contains a { } block in it.  

If you ever think this kind of workaround will work not work, it's alright. :) If you have some other tips or techniques you use when dealing with this problems, then I'll do that instead. Thanks for your time developing and maintaining this awesome library!

**Comment by mikepenz** [comment]
@toyongbanatero thanks for the really really detailed report. 
I totally understand your problem, but I think that might not be possible as easy it it may sounds. 

In your case I see an additional "Problem" You are using the `IconicsButton` even though you just need a single drawable. Using a `ImageButton` and setting the `IconicsDrawable` programatically would be a better solution I think.
