### ISSUE TITLE
Community Material Design Icons - Icon "Widgets" not shown

### ISSUE THREAD

**Issue by chrisonline** [mikepenz/Android-Iconics#258]
I use the cmd icons and the cmd-widgets is not shown in the app.

https://materialdesignicons.com/icon/widgets

Here the code:
`<ImageView
                        android:layout_width="48dp"
                        android:layout_height="48dp"
                        android:layout_margin="20dp"
                        app:ico_color="@color/category_phone"
                        app:ico_icon="cmd-widgets"
                        app:ico_size="48dp"
                        android:layout_column="1"/>`

Other icons are working like this:
` <ImageView
                        android:layout_width="48dp"
                        android:layout_height="48dp"
                        android:layout_margin="20dp"
                        app:ico_color="@color/category_phone"
                        app:ico_icon="cmd-repeat"
                        app:ico_size="48dp"
                        android:layout_column="1"/>`

**Comment by mikepenz** [comment]
@chrisonline you have the "cmd" icon set which are the material community icons, and not the google material icons. Just use the sample app to check which icons are in which icon set.

**Comment by chrisonline** [comment]
No I rever  to this website; http://materialdesignicons.com/ and this are the community Material Design Icons!

**Comment by mikepenz** [comment]
@chrisonline do you have an too old addon included? If you check the sample app you will see it is there, and works

**Comment by chrisonline** [comment]
@mikepenz Yeah you are right. Have missed that the cmd font library was also updated. Sorry to bother you!
