### ISSUE TITLE
Wrong case on AlertDialog buttons when using IconicsLayoutInflater

### ISSUE THREAD

**Issue by pn** [mikepenz/Android-Iconics#259]
It seems adding
`LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));`
breaks style of AlertDialog buttons which should be upper case but aren't.

To reproduce create simple dialog with lower case text action button in AutomaticActivity.

**Comment by mikepenz** [comment]
@pn in Android spannables do not work if the text of a button is `UPPERCASE` which is the default on the system, so the inflator changes this to make icons possible (setting the text in uppercase in the first place is more performant by the way anyways)  Please use the normal `IconicsDrawable` approach if the above does not work as you expect

**Comment by pn** [comment]
@mikepenz Thanks, that is what I did. If that is intended behavior than maybe it should be documented or at least users should be warned that this method may have some side effects except adding icons.
