### ISSUE TITLE
IconicsTextView and Html.fromHtml colors

### ISSUE THREAD

**Issue by SanderTuit** [mikepenz/Android-Iconics#26]
`IconicsTextView` doesn't follow HTML colors when using `setText(Html.fromHtml('Test: <font color='#FF0000'>Colored text goes here</font>'))`. Is this intentional, a bug or a feature? ;-)

**Comment by mikepenz** [comment]
@SanderTuit i assume the spanables which are create by the Html.fromHtml method are overwritten by Android-Iconics. Not sure if it's that easy to keep both. 

Is it an required function for you?

**Comment by SanderTuit** [comment]
Well, I was actually trying to use it to color the icon, but I guess that would be more difficult altogether. My use case is the following. I'm displaying an icon after a username and want to use different colors for different user types. I guess I can use a different kind of `View` (perhaps `IconicsImageView`) if supporting Html.fromHtml is not on your todo list. :-)

**Comment by mikepenz** [comment]
There is something different which allows you to color icons inside a textView :D 
Look at the playground activity.

Html.fromHtml is not planned :D

**Comment by mikepenz** [comment]
Here's a snippet how you can style elements of an TextView with spanables :D 

```java
//Show how to style the text of an existing TextView
        TextView tv1 = (TextView) findViewById(R.id.test1);
        new Iconics.IconicsBuilder().ctx(this)
                .style(new ForegroundColorSpan(Color.WHITE), new BackgroundColorSpan(Color.BLACK), new RelativeSizeSpan(2f))
                .styleFor("faw-adjust", new BackgroundColorSpan(Color.RED), new ForegroundColorSpan(Color.parseColor("#33000000")), new RelativeSizeSpan(2f))
                .on(tv1)
                .build();
```
