### ISSUE TITLE
IconicsLayoutInflater and Home Screen Widget

### ISSUE THREAD

**Issue by msegmx** [mikepenz/Android-Iconics#260]
Is it possible to use Iconics in a layout xml file of a home screen widget ?

Since AppCompatDelegate only supports an Activity I can't use this line

`LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));`

inside AppWidgetProvider.

Using <com.mikepenz.iconics.view.IconicsCompatButton> just gives an error inside the home screen widget, nothing in logcat.

When using IconicsButton I get this line in logcat :

> 
I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

Is there a way to make it work ?

**Comment by mikepenz** [comment]
@msegmx no you can't use the inflater there. But you can use the manual approach and just replace the iconics icons on the `TextView`s (buttons) where you need. 

Have a look here:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L56
