### ISSUE TITLE
[Suggestion] Update Community Material Icons pls

### ISSUE THREAD

**Issue by natnayr** [mikepenz/Android-Iconics#261]
Hi,

Please update cause i dun see a "decagram" Icon in your nice little library that has made my life easier. I think quite afew others are missing too :)

Thanks

**Comment by mikepenz** [comment]
@natnayr this icon is not mapped in their *.css web font. Nothing I can do about it. (check yourself by downloading their zip and opening the materialdesignicons.css)

The icon font of Android-Iconics is already on the latest though

**Comment by natnayr** [comment]
Thanks :) 

just checked and its quite a new icon in their library, will wait for it to roll out.
