### ISSUE TITLE
Images in textview are displayed incorrectly when using IconicsLayoutInflater 

### ISSUE THREAD

**Issue by thaindq** [mikepenz/Android-Iconics#262]
I'm using textview to display some images from html using Html.fromHtml with an ImageGetter implemented using Glide.

![](http://i.imgur.com/u2e1l1O.png)

Everything is ok until I use IconicsLayoutInflater to enable automatic xml icons detection and images start to display incorrectly

![](http://i.imgur.com/JS0jbRX.png)

I've tried both ways `set factory` and `inject to context` but results are the same. This is my sample code if needed.
>https://drive.google.com/file/d/0B0AVNHNWkZF0TjVPUTduNVMyRk0/view?usp=sharing

**Comment by mikepenz** [comment]
@thaindq seems like the spannables do not like each other. In this case I suggest to simply not use the `IconicsLayoutInflator` and just use the `Iconics` icons on views where you need them

**Comment by thaindq** [comment]
@mikepenz: thank you. I switched to custom views and it's running fine now.
