### ISSUE TITLE
Does the IconicsLayoutInflater work with android.support.v7.widget.AppCompatButton buttons?

### ISSUE THREAD

**Issue by drewlarsen** [mikepenz/Android-Iconics#263]
I've been incorporating your library into my project for the past couple weeks successfully, thank you for your efforts!

I have an xml layout which I've a/b tested with android.support.v7.widget.AppCompatButton and just a plain Button:

```
        <android.support.v7.widget.AppCompatButton xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/buttonSignup"
            style="@style/Sugar.Button.Tall"
            android:layout_width="match_parent"
            android:layout_marginTop="@dimen/control_vertical_margin_large"
            android:text="@string/{faw-envelope} Sign up with Email"
            android:textColor="@color/sugar_secondary"
            app:backgroundTint="@color/button_white_tint" />
```

I am using the IconicsLayoutInflater:

```
LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
```

When using just a plain `Button`, the font awesome icon appears, when I use the `AppCompatButton`, I get only `{faw-envelope}`

Any ideas? Should the icons be detected with an AppCompatButton?

**Comment by mikepenz** [comment]
it should as the `AcppCompatButton` extends the `TextView` 
It might be related to the `TextAllCaps` flag which is set to the view by it I think

**Comment by mikepenz** [comment]
In general I would anyways suggest to directly use the `Iconics` class to apply the icon, or set it as compount drawable. It is not necessary to check all TextViews for a possible icon which needs to be replaced

**Comment by drewlarsen** [comment]
ok, thx for the feedback. Would it make sense to extend AppCompatButton in a similar way to the extension of Button?

```
public class IconicsAppCompatButton extends AppCompatButton {
    public IconicsAppCompatButton(Context context) {
        super(context);
    }

    public IconicsAppCompatButton(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public IconicsAppCompatButton(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    public void setText(CharSequence text, BufferType type) {
        // NOTES:
        // 1. Need to disable the All Caps option to make Spannable work properly!
        // 2. This method will be called from the constructor of the super class
        setAllCaps(false);

        if (!isInEditMode()) {
            super.setText(new Iconics.IconicsBuilder().ctx(getContext()).on(text).build(), type);
        } else {
            super.setText(text, type);
        }
    }
}
```

This seems to work. I like the cleanliness of having the {faw-*} icons in the strings.xml file rather than in code across my app. Or am I missing something? Would you want a pull request with this?

**Comment by mikepenz** [comment]
@drewlarsen you can also do the `SetAllCaps` false via xml. So if you know it, you won't necessarily need a different view ;)
