### ISSUE TITLE
Icons are being cutoff on ImageViews

### ISSUE THREAD

**Issue by rpgdev** [mikepenz/Android-Iconics#265]
I'm having issues showing the community material icons on ImageViews. If you take a look at the screenshot attached you'll see that the icons are being cutoff on the left and top side. I thought this was because of the margins but I've set the ImageViews with no margin and the issue still happens. Adjusting the size of the imageview seems to fix the issue sometimes but aren't these icons supposed to be size independent? Maybe I'm missing something.

![screenshot_2017-03-27-18-57-36](https://cloud.githubusercontent.com/assets/20094474/24381889/d5dec028-1320-11e7-8643-39d4c43b3011.png)

**Comment by mikepenz** [comment]
@rpgdev the icons are size independent. The question is how you apply the icons to that `ImageView` which `scaleType` is set to the `ImageView` and which `size()` the `IconicsDrawable` were crated with. 

They still have to follow the normal rules of scaling within an `ImageView` :D

**Comment by rpgdev** [comment]
@mikepenz What do you mean by "and which size() the IconicsDrawable were crated with"? I'm passing the drawable to the imageview without changing the drawable in any way, trusting that they will scale right and they do, but then this issue happens.

The emoji in the middle is shown in this imageview:
            <ImageView
                android:id="@+id/ivEmoji"
                android:layout_width="18sp"
                android:layout_height="18sp"/>
And the drawable is setup in code. No other setting is being applied to this imageview. The green up arrow is using this one:
            <ImageView
                android:id="@+id/ivUp"
                android:layout_width="16sp"
                android:layout_height="16sp"
                android:layout_marginRight="4sp"
                android:layout_marginEnd="4sp"
                android:layout_gravity="center"
                app:ico_icon="cmd-arrow-up-bold-circle"
                app:ico_color="@color/green_600" />

Is there a recommended scaletype for the imageview? I'm using the default one but I tried several others and the issue was still present.

**Comment by mikepenz** [comment]
@rpgdev you should give them a size. the android system can otherwise not correctly define its bounds resulting in issues like the one you see. 

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L452

**Comment by rpgdev** [comment]
Interesting, I applied the icon size using `app:ico_size` but the issue still occurs. Weirdly, I see now that it only occurs on my 4.2.2 device, I can't reproduce it on other versions of android or 4.2 emulators. Could something in that version of android be causing this issue?

**Comment by mikepenz** [comment]
@rpgdev yeah it could be. Are you seeing the same issue in the sample app?

**Comment by rpgdev** [comment]
@mikepenz they look fine in the sample appv :/

**Comment by mikepenz** [comment]
Perhaps you can try a few more things. like shown in the sample app. It should work for you too

**Comment by mikepenz** [comment]
Do you have an update? Please report back. Close til that
