### ISSUE TITLE
[Question] Isn't the ico_size working on xml's IconicsButton?

### ISSUE THREAD

**Issue by DasserBasyouni** [mikepenz/Android-Iconics#267]
I am trying to set button size and round shape by this layout
```
<!-- "\n" it for making the icon on top-->
<com.mikepenz.iconics.view.IconicsButton
        android:text="{gmd-replay}\nRetry"  
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/round_btn"
        app:ico_size="100dp"
        />
```
the ico_size is not working, and if there is an option i don't know in `Android-Iconics Library` make round shape I appreatiat if you have mentioned it

Thank you, for a great library and a great responding to its users till now

**Comment by mikepenz** [comment]
@DasserBasyouni the `ico_size` is not working in this case as the `IconicsButton` does not use the raw `IconicsDrawable` but instead displays the drawable as part of the text. This means the icon will always be in the same size as the text. 

If you want to change the icon size in that case, either set it as `CompoundDrawable` programatically (which is the better solution) or you do this:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L58

You can then use any spannable to change it's look.
