### ISSUE TITLE
Typeface making impossibile to include custom library if used inside them

### ISSUE THREAD

**Issue by RiccardoM** [mikepenz/Android-Iconics#268]
Hi, first of all thanks for the awesome job you've made with this library.

I'd like to report to you a strange behaviour that I've encoutered while working with it inside a custom library that I'm currently working on. 

## The error
The situation is the following:

**1**. I have a custom library, let's call it `library`, which has the following code inside its `build.gradle` file:
```groovy
dependencies {
    compile 'com.mikepenz:iconics-core:2.8.2'
    compile ('com.mikepenz:fontawesome-typeface:4.7.0.0'){transitive = false}
    // I also tried using compile 'com.mikepenz:fontawesome-typeface:4.7.0.0@aar' instead but it does not change anything
}
```

This library is uploaded to a private maven repo with the following id: `com.mycompany:library:1.0.0`

**2**. I have an application project which uses this library inside its dependencies in the `build.gradle` file:
```groovy
dependencies { 
    compile 'com.mycompany.library:1.0.0'
}
```

**3**. Once i try to compile the application project, the compilation throws the following error:
```java
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find Android-Iconics:library-core:unspecified.
     Required by:
         project :app > com.mycompany:library:1.0.0 > com.mikepenz:fontawesome-typeface:4.7.0.0
```

## Searching for a solution
I've searched the whole web for a solution to this, also reading the other issues that have been opened more than a year ago, and looking trough the code of bot the core library and the typeface, i realized that inside the typeface library's `build.gradle` file there is the following line of code:
```groovy
dependencies {
    compile project(':library-core')
}
```

So, I've made some researches tryouts and found out that when `library` is included inside the application project, all of its dependencies are marked as `transitive = true`, so even `com.mikepenz:fontawesome-typeface:4.7.0.0` is marked as `transitive = true`, which makes it throw the error. This does not happen if the library is included as an aar file (using `compile 'com,mycompany:library:1.0.0@aar`) because whole of its dependencies are set to `transitive = false`.
I even tried to set `com.mikepenz:fontawesome-typeface:4.7.0.0` as `transitive = false` inside `library`, but it gets overwritten during the inclusion inside the application project.

## A possibile solution
I've come to the conclusion that the only way to solve this problem is to remove the following line of code from the `build.gradle` file of the typeface libraries
```groovy
dependencies {
    compile project(':library-core')
}
```
and replace it with the following equivalent line
```groovy
dependencies {
    compile 'com.mikepenz:iconics-core:2.8.2'
}
```
I'm aware that this will make all the typeface libraries a little harder to maintain, due to having to change the core library version each time that it is updated, but I'm 98% sure that this would solve all the problems that many users had experienced in the past. Also, this would make all the typeface libraries totally usable either using the `aar` format or not, without any problem in specific cases.

**P.S.** Please excuse me for my bad english.

**Comment by mikepenz** [comment]
@RiccardoM have you tried to exclude this "wrong" sub dependency? Like shown here: http://stackoverflow.com/a/21765656/325479

**Comment by RiccardoM** [comment]
@mikepenz I've just tried and now everything is working properly 👍 . Even if it works I think that it might be more usable for the final users to not having to do that 😜

**Comment by mikepenz** [comment]
@RiccardoM I understand that it is a bit more complicated. But it will just get too hard to do releases afterwards. I'll mark it as "good to know" and will remember for future questions

**Comment by 10erlosh** [comment]
I'm facing the exact same problem with latest core-library 3.0.4 and latest FA typeface 5.0.13.0 . Here is my setup:

library module (aar)
```
implementation "com.mikepenz:iconics-core:$VERSIONS.ICONICS@aar"
implementation "com.mikepenz:fontawesome-typeface:$VERSIONS.ICONICS_FA@aar"
```
app module
```
implementation("com.mycompany:library:1.0.0") {
        transitive true
}
```
results in
```
Could not find com.mikepenz:library-core:3.0.4.
...
project :app > com.mycompany:library:1.0.0 > com.mikepenz:fontawesome-typeface:5.0.13.0
```
@RiccardoM where did you put the exclusion statement? Library / app module? On which dependency? Core / typeface?

@mikepenz btw it's working fine with FA typeface 5.0.6.0...

**Comment by mikepenz** [comment]
you have jcenter as providing repository in your root gradle? 

It is available here: https://bintray.com/bintray/jcenter/iconics-core/3.0.4

**Comment by 10erlosh** [comment]
yes i have.
the problem was that the published pom of my library didn't had the exclusion rules.
i fixed it by adjusting my publish task, now this works:

in library module:
```
implementation "com.mikepenz:iconics-core:$VERSIONS.ICONICS@aar"
implementation("com.mikepenz:iconics-views:$VERSIONS.ICONICS@aar") {
    exclude group: 'com.mikepenz', module: 'library-core'
}
implementation("com.mikepenz:fontawesome-typeface:$VERSIONS.ICONICS_FA@aar") {
    exclude group: 'com.mikepenz', module: 'library-core'
}
```
