### ISSUE TITLE
Community Material update

### ISSUE THREAD

**Issue by lorisgir** [mikepenz/Android-Iconics#269]
It would be possible to update the library with the latest icon? Right now they are on v1.9.32 and they added a few icon I need!

Thanks!

**Comment by mikepenz** [comment]
@lorisgir thanks a lot for doing the update. merged your PR. and published it to maven central :)

**Comment by lorisgir** [comment]
Your welcome! Thank You for your awensome libs!

Il mar 18 apr 2017, 23:22 Mike Penz <notifications@github.com> ha scritto:

**Comment by mikepenz** [comment]
Thanks
