### ISSUE TITLE
CSS to compatible lib

### ISSUE THREAD

**Issue by Anatidae-Project** [mikepenz/Android-Iconics#27]
It would be cool to get an NPM module going that converts  TTF / CSS data into a custom font library ready for Android-Iconics.

Something like this:
https://github.com/FokkeZB/IconFont

**Comment by mikepenz** [comment]
@Anatidae-Project there is no npm module but a js file which can be used with node to convert ttf & css to the entries for an Android-Iconics addon

**Comment by Anatidae-Project** [comment]
Are you talking about the extractor.js script?

**Comment by mikepenz** [comment]
yes :D this can be executed with node and will output a list with the mapping. it's not yet perfect, but already a good start
