### ISSUE TITLE
icon for actionbar or bottomnavigationview

### ISSUE THREAD

**Issue by goutomroy** [mikepenz/Android-Iconics#270]
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item
        android:id="@+id/action_movies"
        android:enabled="true"
        android:icon="@drawable/ic_local_movies_black_24dp"
        android:title="Movie"
        app:showAsAction="always" />
</menu>

How I will add icons in menu ?

**Comment by mikepenz** [comment]
@goutomroy you can use the `IconicsDrawable` wherever you can set a `Drawable` this is only possible programatically. 

You can't use those via xml. (Just in the provided `IconicsButton` and `IconicsImageView`)

**Comment by bschwind** [comment]
@mikepenz Quick question: When using `IconicsDrawable` as a drawable for the BottomNavigationView, it seems the icons don't resize when changing between tabs. Have you ever used this library with `BottomNavigationView`? It *seems* like it's not working with other `Drawable`s so it's probably nothing wrong in this library, but I'm just curious if anyone has a working example. I'm working with `BottomNavigationView` programmatically, and so far it's been a huge pain.

**Comment by mikepenz** [comment]
@bschwind if it also happens with other drawable's I assume it is a general issue then. 

Have you tried to invalidate, or to set a specific size to it?

**Comment by bschwind** [comment]
@mikepenz I'm experimenting with it now. At first I thought maybe it was a React Native thing but now I have a vanilla android project. I've at least determined it's not an issue with this library, so no worries :)

It seems to not like the menu items I've added dynamically, but the items that were inflated from a resource file animate and resize correctly.

**Comment by mikepenz** [comment]
@bschwind ok that's weird. Seems to be an issue with the bottom navigation view then. Perhaps the icon needs to be set as `Bitmap`? It might do this for icons set via xml

**Comment by bschwind** [comment]
Haha, definitely weird. So if I do something like this:

```
Menu menu = navigation.getMenu();

menu.clear();
menu.add("List").setChecked(false);
menu.add("Map").setChecked(false);
menu.add("Filter").setChecked(true);
menu.add("Other").setChecked(false);
```

Then none of the animations work, though the tabs still display ripples when you touch them.

But if I don't clear the menu, and instead call `addIcon` on the existing menu items, everything works (both programmatically created Drawables and Drawables from this library work):

```
menu.getItem(0).setIcon(badge);
menu.getItem(1).setIcon(drawable2);
menu.getItem(2).setIcon(drawable3);
menu.getItem(3).setIcon(drawable4);
```

I could very well be doing something stupid, and it's not an issue with this library so don't waste your time on it if you're busy :P

If you're curious, I've boiled it down to a pretty minimal reproduction of the issue:

[https://gist.github.com/bschwind/a43cb6ebbd51ccf97436dece7beb126c](https://gist.github.com/bschwind/a43cb6ebbd51ccf97436dece7beb126c)

**Comment by bschwind** [comment]
Okay I found the issue. If you return `false` in the `onNavigationItemSelected` handler, it just won't animate the tab. That took way too long to figure out...

**Comment by mikepenz** [comment]
@bschwind thanks for adding the solution. It is really strange. Great that you found out what was causing it

**Comment by bschwind** [comment]
@mikepenz Heh, so I realized that only solved it for a sample native app I made to reproduce the issue.

I'm actually using BottomNavigationView and this library from React Native and despite having essentially the same code, they're still not animating so there's something fishy with React Native now.

In any case, thanks for the fantastic library!

**Comment by mikepenz** [comment]
Thank you very much :)
