### ISSUE TITLE
IconicsImageView doesn't appear on phone screen

### ISSUE THREAD

**Issue by PeterPhyo** [mikepenz/Android-Iconics#273]
Before, I got; it appear on phone screen. Now, IconicsImageView doesn't appear on phone screen. I don't change nothing.  What happened?

```
<com.mikepenz.iconics.view.IconicsImageView
android:layout_width="13dp"
android:layout_height="13dp"
app:iiv_color="@color/colorBlack"
app:iiv_icon="gmd_check_circle" />

compile "com.mikepenz:iconics-core:2.8.3@aar"
compile 'com.mikepenz:google-material-typeface:3.0.1.0.original@aar'
compile 'com.mikepenz:community-material-typeface:1.9.32.1@aar'
```

**Comment by mikepenz** [comment]
@PeterPhyo what do you mean with it does not appear in xml? The Android Studio preview will not show the icon, and never did. When you launch the application it will as long as the icon exists.

**Comment by PeterPhyo** [comment]
Yeah! I know, AS preview doesn't show icon, when lunch it shows on phone screen. But when I run, it doesn't show on phone screen, Error message show (E/Iconics: Wrong icon name: gmd_check_circle), not wrong name. What happened?

**Comment by PeterPhyo** [comment]
I got it. I changed PackageName, I forgot to change applicationId.  wrong applicationId "xxx.xxx.xxx".
