### ISSUE TITLE
textAllCaps doesn't work

### ISSUE THREAD

**Issue by Philipp91** [mikepenz/Android-Iconics#274]
Android-Iconics sets `.setAllCaps(false);` https://github.com/mikepenz/Android-Iconics/issues/97 https://github.com/mikepenz/Android-Iconics/commit/a90c4f4dd114701ad9f4002a6e9abcc9bd77be40

This is done for all buttons, whether they use a spannable text or any icon at all, or not. Thus, if Android-Iconics is installed, `textAllCaps="true"` does not work on any button. That's a drawback in itself (but can be worked around by setting it programmatically, which is annoying), but most importantly it's very unexpected and it took me quite some debugging time to find out why it doesn't work (didn't suspect that Android-Iconics would influence this).

**Comment by mikepenz** [comment]
@Philipp91 nothing I can do about. that's Android's limitation. 

Android `textAllCaps` breaks `Spannables` being used. you would not be able to for example make the text bold, color parts of it either....

Just set the text in `UPPERCASE` programmatically. It's anyway the prefered way as it is much faster with less overhead.

There is a `IconicsImageButton` for example which disables textAllCaps automatically
