### ISSUE TITLE
Problem with Spannable

### ISSUE THREAD

**Issue by carmas123** [mikepenz/Android-Iconics#277]
I try to use IconicsTextView with this:

```
val spannable = SpannableString("{gmi-pin} my text bla bla bla")
spannable.setSpan(ForegroundColorSpan(Color.MAGENTA), 0, 10, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
mytextView.Text = spannable

```
but the Magenta Color does not appear.
If I change the TextView color for all text without spannable it work.

**Comment by mikepenz** [comment]
@carmas123 please use hte built in functionality to color icons:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L57

**Comment by carmas123** [comment]
I try it but also does not work

**Comment by mikepenz** [comment]
@carmas123 can you please show what you tried? Because in the sample it is working fine

**Comment by carmas123** [comment]
Ok but I use Kotlin and not Java...

Iconics.IconicsBuilder().ctx(activity)
  .style(ForegroundColorSpan(Color.RED), BackgroundColorSpan(Color.RED), RelativeSizeSpan(2f))
  .styleFor("gmi-pin", BackgroundColorSpan(Color.RED), ForegroundColorSpan(Color.parseColor("#33000000")), RelativeSizeSpan(2f))
  .on(b.textView)
  .build()

The textview is always empty

**Comment by mikepenz** [comment]
@carmas123 shouldn't change much. 

The textview is always empty? the code you posted will only adjust the color of the icon if it was set. So if no text is set, it makes sense that it stays empty :D

**Comment by carmas123** [comment]
```
myTextView.text = "{gmi-pin} my Text"
Iconics.IconicsBuilder().ctx(activity)
		.style(ForegroundColorSpan(Color.RED), BackgroundColorSpan(Color.RED), RelativeSizeSpan(2f))
		.styleFor("{gmi-pin}", BackgroundColorSpan(Color.RED), ForegroundColorSpan(Color.parseColor("#33000000")), RelativeSizeSpan(2f))
		.on(myTextView)
		.build()
```
This is the result

![image](https://cloud.githubusercontent.com/assets/6574219/25748617/f81de282-31ab-11e7-976f-29cb2eeab0e8.png)

**Comment by mikepenz** [comment]
Do you have any other spannables or fonts or so set manually? Anything which might break the icon? 

any log output saying that the icon does not exist or so? 

is it working without any color change or so?

**Comment by carmas123** [comment]
Yes it work.without spannable

**Comment by mikepenz** [comment]
you mean without this:
```java
val spannable = SpannableString("{gmi-pin} my text bla bla bla")
```
?

**Comment by carmas123** [comment]
It work:

![image](https://cloud.githubusercontent.com/assets/6574219/25750382/d3b08b38-31b1-11e7-8614-47ca69ab7d1d.png)

**Comment by mikepenz** [comment]
@carmas123 so why do you want this `SpannableString` then?

**Comment by carmas123** [comment]
I need to highlight the Icon into TextView with another color

**Comment by mikepenz** [comment]
@carmas123 for this there is:
```java
Iconics.IconicsBuilder().ctx(activity)
  .style(ForegroundColorSpan(Color.RED), BackgroundColorSpan(Color.RED), RelativeSizeSpan(2f))
  .styleFor("gmi-pin", BackgroundColorSpan(Color.RED), ForegroundColorSpan(Color.parseColor("#33000000")), RelativeSizeSpan(2f))
  .on(b.textView)
  .build()
```

and the best would anyways to set the `Drawable` as compound drawable

**Comment by carmas123** [comment]
Yes but the text into TextView need to have {gmi-pin} or not?

**Comment by mikepenz** [comment]
@carmas123 if you set it as compound drawable not.

**Comment by carmas123** [comment]
The result is same with this text: 
`b.textIndirizzo.text = "{gmi-pin} my text bla bla bla"`
![image](https://cloud.githubusercontent.com/assets/6574219/25752013/499835c6-31b7-11e7-81cd-47cd4c2b538c.png)

without {gmi-pin} is this:
![image](https://cloud.githubusercontent.com/assets/6574219/25752073/72439b6e-31b7-11e7-9c32-e1fa095c170e.png)

**Comment by mikepenz** [comment]
@carmas123 and then you set the icon via the `IconicsDrawable` as compoundDrawable

**Comment by carmas123** [comment]
It's work but with this I cannot use the com.mikepenz.iconics.view.IconicsTextView with all functionality :(

**Comment by mikepenz** [comment]
@carmas123 well using the android iconics as Drawable via the `IconicsDrawable` is anyways the better and prefered solution. The other is just a gimmick, and gives by design (and by the limitations of Spannables) a less flexible and a more complicated solution...

**Comment by tmm1** [comment]
> The other is just a gimmick, and gives by design (and by the limitations of Spannables) a less flexible and a more complicated solution...

I would suggest that this be mentioned in the README, as the gimicky solution is currently featured prominently and gives the impression that it is the recommended way to use the library. An example in the README of how to use setCompoundDrawables would be great too.
