### ISSUE TITLE
IconicsImageView background color issue in MaterialDrawer v5.9.1 

### ISSUE THREAD

**Issue by alessandrotorres** [mikepenz/Android-Iconics#278]
Hi Mike,

For IconicsImageView, in MaterialDrawer 5.9.1 package, you can set background color with .setBackgroundColor(int color) in onCreate() but, if called runtime, e.g. onClickListener(), it seems to ignore it.

Rolling back to 5.9.0 all is ok.

Referring issue for MaterialDrawer:
[https://github.com/mikepenz/MaterialDrawer/issues/1851](https://github.com/mikepenz/MaterialDrawer/issues/1851)

Thanks,
Ale

**Comment by mikepenz** [comment]
@alessandrotorres this might be related to this PR: https://github.com/mikepenz/Android-Iconics/pull/272

**Comment by mikepenz** [comment]
Sadly I am / was very busy in the last time so I haven't yet had a chance to take a closer look. If you have a bit more time it would be great if you could debug into it and check if you possibly see a cause which could lead to that. 

@hanneskuettner referring you here as you might have an idea.

**Comment by MFlisar** [comment]
I have following idea:

The icon is ONLY checking the color for the current state, this means changing colors where the default state is the same color will NOT invalidate the view. Code I'm refering to is here: https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L1045

**Comment by mikepenz** [comment]
@alessandrotorres can you please try to invalidate the icon after changing the color?

**Comment by mikepenz** [comment]
Thanks to @MFlisar this will be fixed in the next version
