### ISSUE TITLE
Edittext compound drawables are offset until focus

### ISSUE THREAD

**Issue by jwburnside** [mikepenz/Android-Iconics#279]
I seem to be having a strange problem when using an Iconics drawable in an EditText. Attached is an image of what I am experiencing. The firstName field is using an Iconics drawable, and the lastName field is using a regular drawable. As you can see, the firstName drawable doesn't respect the padding that I assigned to it. The lastName drawable, however, does. The really weird part is that when I click into _any_ edittext on the page, all of the Iconics compound drawables move to the appropriate position. Happening on my Nexus 6 (7.0), but not on older ones like ZTE 4.4. 

![error](https://cloud.githubusercontent.com/assets/854180/26069412/c5ff771e-396e-11e7-9749-b8f7ffaa5c05.png)

```
        // Set the first name icon
        mEtFirstName = (EditText)v.findViewById(R.id.login_firstname_input);
        Typeface myFont = Typeface.createFromAsset(getActivity().getAssets(), "fonts/myFont.ttf");
        IconicsDrawable nonWorkingDrawable = new IconicsDrawable(getActivity())
                .icon(getString(R.string.icon_icon_person))
                .typeface(myFont)
                .color(getResources().getColor(R.color.default_blue))
                .sizeDp(21);
        mEtFirstName.setCompoundDrawablesWithIntrinsicBounds(nonWorkingDrawable, null, null, null);
```

        // Set the last name icon.
        mEtLastName = (EditText)v.findViewById(R.id.login_lastname_input);
        Drawable workingDrawable;
        final int version = Build.VERSION.SDK_INT;
        if (version >= 21) {
            workingDrawable = ContextCompat.getDrawable(getActivity(), R.drawable.test);
        } else {
            workingDrawable = getResources().getDrawable(R.drawable.test);
        }
        mEtLastName.setCompoundDrawablesWithIntrinsicBounds(workingDrawable, null, null, null);`

```
<EditText
                android:id="@+id/login_firstname_input"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/hint_first_name"
                android:drawablePadding="5dp"
                android:nextFocusDown="@+id/login_lastname_input" />

            <EditText
                android:id="@+id/login_lastname_input"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="textCapWords"
                android:hint="@string/hint_last_name"
                android:drawablePadding="5dp"
                android:nextFocusDown="@+id/signup_email_input"/>
```

Anyone run into this issue or know how to troubleshoot?

**Comment by mikepenz** [comment]
@jwburnside you can try something like the following 

```java
d.setBounds(0, 0, d.getIntrinsicWidth() - UIHelper.convertDpToPixel(4), d.getIntrinsicHeight() - UIHelper.convertDpToPixel(4));
textView.setCompoundDrawables(d, null, null, null);
```

**Comment by jwburnside** [comment]
I attempted your fix, but the issue continued to happen. I have narrowed it down even more since yesterday, though, and now it's even more baffling.

I realized I have another fragment where I am applying Iconics drawables to an EditText exactly as I am in the above example, but they are aligned correctly. 

So as a test, I removed all unnecessary code and duplicated the working fragment (so I have two identical fragments, Fragment A and B). When I add Fragment A, the inputs are aligned correctly. But when I add Fragment B after Fragment A, Fragment B has misaligned icons. Furthermore, if I reverse the order in which I add the fragments, the misaligned icons are always on the second added fragment (or any consecutive fragment I add). 

Really weird, any ideas?

**Comment by mikepenz** [comment]
That's completely weird. Something breaks it. But I have no idea what it could be :/. 

Please try if it also happens with normal drawables. (from resources), if yes it is a framework issue or so and you should open a bug on Android, if not some text rendering might cause troubles

**Comment by mikepenz** [comment]
Closing as there was no answer > 2 weeks
