### ISSUE TITLE
Using alpha/transparency in colors

### ISSUE THREAD

**Issue by somghosh** [mikepenz/Android-Iconics#28]
My code sets the colour of an icon as follows:

        menu.findItem(R.id.action_notification).setIcon(new IconicsDrawable(this, FontAwesome.Icon.faw_android).
                color(R.color.iconactive).sizeDp(24));

Color is defined with a transparency component. However it still appears black on my app when I run it. Is this not supported then?

     <color name="iconactive">#36000000</color>

**Comment by mikepenz** [comment]
@somghosh it works but only on api level 21+. i have not found a solution for pre lollipop devices yet

**Comment by somghosh** [comment]
Thanks
