### ISSUE TITLE
[IconicsTextView] with offset icon

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/Android-Iconics#280]
Hi,
How I can use the IconicsTextView class (or some override) for next task:
I want show icon with text (icon as drawableLeft for example). So I using next code:

        <com.mikepenz.iconics.view.IconicsTextView
            style="@style/TextIndicator"
            android:background="@android:color/holo_blue_light"
            android:id="@+id/watches"
            android:layout_weight="1"
            android:layout_width="wrap_content"
            android:layout_height="15dp"
            android:text="{gmd_visibility} 000"/>
        <com.mikepenz.iconics.view.IconicsTextView
            style="@style/TextIndicator"
            android:background="@android:color/holo_orange_light"
            android:id="@+id/rating"
            android:gravity="center_vertical"
            android:layout_weight="1"
            android:layout_width="wrap_content"
            android:layout_height="30dp"
            android:text="{gmd_visibility_off} 111" />

but icon is draw on top with some offset. And I cannt set icon and text on one line (for example center by vertical)

On this attach image RED line - center of icon. GREEN - center of text.
![1](https://cloud.githubusercontent.com/assets/1124827/26151551/0daf252a-3b0c-11e7-9e05-de8898e577b7.png)

So, How you can help me with this ?

**Comment by mikepenz** [comment]
@gromiloff in that case i'd suggest do use the `IconicsDrawable` as compound drawable of the TextView as it results in better results than using it witihn the text

**Comment by mikepenz** [comment]
(there is not enough control I have about icon's displayed within text, you can possibly somehow adjust it by using some spannable, but for the best possible solution use a `ComoundDrawable`)
