### ISSUE TITLE
IconicsImageView doesn't work in fragment.need some help!

### ISSUE THREAD

**Issue by dandingol03** [mikepenz/Android-Iconics#281]
<b>Hi</b>
here is my case :
1.has registered the font in Application
```js
 Iconics.init(getApplicationContext());
 Iconics.registerFont(new GoogleMaterial());
 Iconics.registerFont(new FontAwesome());
```
2.IconicsImageView works in activity xml layout
3.xmlns:app has been declared in xml
```js
 xmlns:app="http://schemas.android.com/apk/res-auto"
```
4.Maybe,there is some different.i use that component in a RecyclerView which is placed at the fragment layout xml.
  Help me to fix this problem. thanks

**Comment by mikepenz** [comment]
Do you have any additional logs or outputs?

**Comment by dandingol03** [comment]
@mikepenz  no,there is no additional logs or outputs
  By the way,i also setFactory in the activity which the fragment belongs to ,here is the code:
```js
  LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
```

**Comment by mikepenz** [comment]
Have you tried the alternative solution: https://github.com/mikepenz/Android-Iconics#3-alternative-inject-into-context-optional ?

If that does not work I highly suggest that you use the `Iconics` provided views. And / or set the icons programatically

**Comment by dev2961io** [comment]
@mikepenz I would like to address this issue as well. I have made the injection into the parent activity but I cannot use the icons in xml without the Iconics provided view, and this posses an issue for me because I am using a CircularImageView library. Is There any way for you to look into this please?
