### ISSUE TITLE
BottomNavigationView - selector not working

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#283]
Using `BottomNavigationView` does currently not work with `IconicsDrawables`. The weird thing is that the default state color tinting works fine, but the selected state color is not working.

Any ideas why? I checked the code and saw, tinting should be supported. And I check older issues and see that this should work, but it does not...

**Comment by mikepenz** [comment]
@MFlisar so the default color tinting of that view does not work? 

How do you define the drawable? I remember there are some problems in the framework (for normal drawables at least) if you tint using the xml, you can no longer tint using code. There are also problems if you tint with a single color, and afterwards with a colorStateList. 

Have you tried to directly supply a `ColorStateList` for tinting? 

In addition it could also be related to this:
https://github.com/mikepenz/Android-Iconics/issues/278

**Comment by MFlisar** [comment]
The default color tinting is working. The selected color tinting not. I use following simple selector (for text + icon):

    <?xml version="1.0" encoding="utf-8"?>
	<selector xmlns:android="http://schemas.android.com/apk/res/android">
		<item android:state_checked="true" android:color="@color/md_orange_500" />
		<item android:color="@color/md_white_1000"  />
	</selector>
	
I do following:

	* I use `IconicsDrawable` in white, no selector, simple color
	* I tried wrapping it in a CompatDrawable with no effect
	* I tried loading the selector in code and passing it als `ColorStateList`, does not have any effect either
	
The BottomNavigationView defines following selectors:

	app:itemIconTint="@color/bottom_bar_selector"
	app:itemTextColor="@color/bottom_bar_selector"
	
**Effect**

My icons are always white, even the selected ones whereas the lables are white (if not selected) or orange (if selected). As the `BottomNavigationView` does use tinting I would assume I should *not* use a selector as color for the `IconicsDrawable`, sadly this does not work

**Comment by mikepenz** [comment]
It might be really related to the other problem of not switching the color later. 

have you also tryed the `android:state_selected` also?

**Comment by MFlisar** [comment]
No, I haven't because the selector is working with a default drawable... But I'll add it and try it

**Comment by MFlisar** [comment]
Does not help. I've checked the code and found something:

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L890

Isn't an `invalidateSelf` missing here?

**Comment by MFlisar** [comment]
I have following idea:

The icon is ONLY checking the color for the current state, this means changing colors where the default state is the same color will NOT invalidate the view. Code I'm refering to is here: https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L1045

**Comment by mikepenz** [comment]
Can you please try the previous version of Android-Iconics? I am curious if it really was that PR wem erged

**Comment by MFlisar** [comment]
I'll try that. Sadly, the missing invalidation I found in code is not the case when the tinting is changed...

I'll try it later though, need to adjust a few things in code because I'm using the menu inflator wrapper from my pull request

**Comment by mikepenz** [comment]
Oh ok sadly. :/ would have been an easy fix :D

ok :)

**Comment by MFlisar** [comment]
I tried invalidating the drawable manually in `OnNavigationItemSelectedListener` as well and it has no effect...

Here's the code from the `NavigationView`. Maybe it's related to it?

     public void setIcon(Drawable icon) {
        if (icon != null) {
            Drawable.ConstantState state = icon.getConstantState();
            icon = DrawableCompat.wrap(state == null ? icon : state.newDrawable()).mutate();
            DrawableCompat.setTintList(icon, mIconTint);
        }
        mIcon.setImageDrawable(icon);
    }

`getConstantState` is not overwritten in `IconicsDrawable`, not sure if it's necessary though, I actually have never made any deeper experience with drawables yet...

**Comment by mikepenz** [comment]
@MFlisar hmmm you tried the previous Iconics version right?

**Comment by MFlisar** [comment]
Not yet. Which version should I try? I don't know where I see into which version this PR was merged

**Comment by MFlisar** [comment]
I now tried v2.8.1, it does not support `ColorStateList` as color yet. It's working back than, at least something to start with :-)

**Comment by mikepenz** [comment]
yes

**Comment by MFlisar** [comment]
Tried v2.8.3 as well, everything working there as well...

And then I tried adding the changes one by one, following is breaking the behaviour already:

https://github.com/mikepenz/Android-Iconics/commit/cc2d47858f1a25389057615942ef1ae02aece5ac

Changing only `setState` from v2.8.3 to the implementation above, breaks the behaviour for me...

**Comment by mikepenz** [comment]
oh wait
can you please try to call super.setState(stateSet); in addition?

**Comment by MFlisar** [comment]
Just wanted to try this

**Comment by MFlisar** [comment]
Tried the head branch and add the super call and it's working again :-)

    @Override
    public boolean setState(@NonNull int[] stateSet) {
        boolean b = super.setState(stateSet);
        return b || (mIconColor != null && mIconColor.isStateful() || mColorFilter != null || mTintFilter != null);
    }

I'm not sure what I should do with the super return value though...

**Comment by mikepenz** [comment]
well looks good that way. Awasome. With that working again that means I will have to do a update. Possibly it also directly fixes: #278

**Comment by MFlisar** [comment]
Probably. I pushed the change to my branch, so it's part of my pull request now

**Comment by mikepenz** [comment]
Merged your PR

**Comment by anandgaur22** [comment]
bottomNavigation.setItemIconTintList(null); 
remove this line then show icon colour
