### ISSUE TITLE
Font Generator

### ISSUE THREAD

**Issue by ligol** [mikepenz/Android-Iconics#287]
Hi,

I can't find the code for the font generator, is it open source?
I'd like to see if I can make it as gradle plugin to automatically download the file from a service and then generate the associated code.

**Comment by mikepenz** [comment]
@ligol no that one is not open source sorry. But it basically generates a font module and defines all the icons. There were some other "icon" generator already added as source. See here:
https://github.com/mikepenz/Android-Iconics/tree/develop/DEV
(the extractor)

**Comment by ligol** [comment]
Do you think you will open-source it some day?

I will see what I can do with the extractor script. I was looking a bit more for the source generator to be sure to don't forget something.

I think the gradle script could at term provide several ways to get the font (Local, Pre-Generated, External service)

By this ways it could be use automatically during build or release and be even more easy to integrate

**Comment by mikepenz** [comment]
@ligol not about the web tool sorry. All the scripts and javascript things which are almost doing everything (the web tool basically just copies the resources to the right places and does what the javascript script does) 

Sounds very interesting,. Let me know if I can help with something

**Comment by mikepenz** [comment]
I guess the issue itself can be closed :D if you ever decide to do a PR that would be awesome. if not thanks for the idea

**Comment by ligol** [comment]
Hey, I finally found the time to develop the gradle plugin.
Would be awesome if you can tell me what you think of it.
I plan to support more than just fontastic in next release and maybe rework a bit the config part but that's a nice first shoot I think.

https://github.com/ligol/IconicsFontGenerator

**Comment by mikepenz** [comment]
@ligol that looks fantastic. I haven't had a chance to try it out yet, but looking at the readme it really sounds like a super life safer. 

You might want to open a PR here and add somewhere some information in the README :)

**Comment by ligol** [comment]
I will do that.
