### ISSUE TITLE
Fix Alpha

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/Android-Iconics#288]
https://github.com/mikepenz/MaterialDrawer/issues/1892

**Comment by h6ah4i** [comment]
@mikepenz Hi. I am facing a problem due to this `IconicsDrawable.setColor()` behavior change. It also affect to `IconicsImageView` in the following scenario. Do you think is it an intentional change? 

```java
IconicsImageView imageView = ...;

imageView.setColor(Color.argb(128, 255, 0, 0)); // Red (50% opacity)

imageView.setColor(Color.argb(255, 255, 0, 0)); // Red (full opacity)   <-- but alpha is not applied!
((IconicsDrawable) imageView.getDrawable()).alpha(Color.alpha(255)); // <-- so, this workaround is required for now.
```

**Comment by mikepenz** [comment]
@h6ah4i please create a new issue with this, you are right that this might be a problem in some cases
