### ISSUE TITLE
Is it really a good idea to put View classes into android package?

### ISSUE THREAD

**Issue by magicgoose** [mikepenz/Android-Iconics#29]
I mean, these classes https://github.com/mikepenz/Android-Iconics/tree/master/library/src/main/java/android/view. There's a benefit of not having to type the package name in XML layout definitions, but if everyone will do like this, there will be name clashes (because packages are no longer preventing them).

**Comment by mikepenz** [comment]
@magicgoose you are right. I will change this in the next release
