### ISSUE TITLE
IconicsTextView and drawables

### ISSUE THREAD

**Issue by zTrap** [mikepenz/Android-Iconics#291]
Hi, someday `IconicsTextView` will have `xml-attributes` for `drawablesRight` - `...Left` etc, or not?

**Comment by mikepenz** [comment]
@zTrap no plan to do this. You simply can set this programatically by using the `IconicsDrawable`

**Comment by zTrap** [comment]
Not always code way is convenient. I can do this, but I want to be sure you will accept pull request (if all will be right) :)

**Comment by mikepenz** [comment]
Well there are many things you have to take care of, left, right, top, bottom, size, padding, ... 

But sure if the PR is nice I am always more than happy to merge it in ;)
