### ISSUE TITLE
Question: Why didn't you exclude the R file from ProGuard in the library-core module?

### ISSUE THREAD

**Issue by davidgerrad55** [mikepenz/Android-Iconics#294]
Hi @mikepenz ,
Thank you for the great library :) 
I have a question, Why didn't you exclude the R file from ProGuard in the library-core module?
```
-keep class .R
-keep class **.R$* {
    <fields>;
}
```

**Comment by mikepenz** [comment]
@davidgerrad55 adding proguard rules like this is not very clever, because I force basically everyone using my library to accept this. being es precise as possible with proguard is very important, so it can do it's magic and obfuscate and optimize as much as possible
