### ISSUE TITLE
How to set IconicsDrawable to bold?

### ISSUE THREAD

**Issue by jazzgil** [mikepenz/Android-Iconics#295]
Hi Mike,

I'm using `IconicsDrawable` to set an icon for an `ImageView`. Currently I set the icon font to bold by...:

```java
GoogleMaterial.Icon add = GoogleMaterial.Icon.gmd_add;
imgView.setImageDrawable(new IconicsDrawable(img.getContext(), add)
       .typeface(Typeface.create(add.getTypeface().getTypeface(getContext()), Typeface.BOLD))
       .sizeDp(20).color(Color.WHITE).backgroundColor(Color.GRAY).paddingDp(5));
```
Is there a more optimal way?

**Comment by mikepenz** [comment]
@jazzgil what are you trying? Are you creating a `IconicsDrawable` with `text`? You can't set it bold like that, you might be able to do it with a spannable around afterwards, but not sure if it would work

**Comment by jazzgil** [comment]
Actually it works. Just realized I forgot to show how `add` is initialized... I'm setting an ImageView to show a text icon from GoogleMaterial.

**Comment by mikepenz** [comment]
Great that it works :)
