### ISSUE TITLE
Use as menu item

### ISSUE THREAD

**Issue by pesseyjulien** [mikepenz/Android-Iconics#297]
Hi,

How can I use fa icons in a menu item, I have tried a lot of combo, but whitout success. Here is an example :

```
    <item android:id="@+id/action_fav"
        android:icon="@string/faw_heart"
        android:title="search"
        app:showAsAction="always"  />
```

Thanks in advance,
Julien

**Comment by mikepenz** [comment]
@pesseyjulien you can only set it programatically. Android has no way to hook into this.

**Comment by pesseyjulien** [comment]
Got it ! Thanks for the quick reply !

**Comment by connyduck** [comment]
What? I use Iconics in menu xml all the time?
It is possible since this change https://github.com/mikepenz/Android-Iconics/pull/282

**Comment by mikepenz** [comment]
@connyduck thanks for mentioning this. I completely forgot abou tit
