### ISSUE TITLE
Filtering on 2.6.2 is not working.

### ISSUE THREAD

**Issue by jelther** [mikepenz/Android-Iconics#298]
Mike,

I guess the filtering is broken in this new version (2.6.2). Setting my adapter to mAdapter.filter("") doesn't bring my list back. I've managed to revert the filtering if the library version was 2.5.1.

You can see my code here in this gist : https://gist.github.com/jelther/9c0bf03c34a47110c6484cfc2750ed5e

There are some comments because it looks you've changed the way to access the filtering methods.

**Comment by mikepenz** [comment]
@jelther are you sure this is an Android-Iconics issue? Sounds like you opened this on the wrong project?

**Comment by mikepenz** [comment]
Please open this on the FastAdapter

**Comment by mikepenz** [comment]
setting to "" should still reset the filter. it works and is tested (I use it in some of my projects) 

Seems like something else conflicts with this

**Comment by jelther** [comment]
@mikepenz , indeed, wrong project. I'll post there.
I'll check my code again but I've rolledback to a previous version and my code worked.
