### ISSUE TITLE
Formatted text support

### ISSUE THREAD

**Issue by magicgoose** [mikepenz/Android-Iconics#30]
IconicsBuilder's `on` method accepting TextView doesn't care about any formatting (spans) in the text, probably because it puts existing text in `StringBuilder` and it keeps only the text, dropping the spans.

It would be great to add support for formatted text and maybe even I will make a pull request someday, but are there any current workarounds for achieving this result? (I want to insert some icons into some formatted text (for example, created by `Html.fromHtml(…)` or something like that)

**Comment by magicgoose** [comment]
Oops, I found the issue about the same thing https://github.com/mikepenz/Android-Iconics/issues/26

**Comment by magicgoose** [comment]
Here it is: https://gist.github.com/magicgoose/8b4bb1eb7ee428c0fc3b

**Comment by mikepenz** [comment]
isn't this working for you:

```java
//Show how to style the text of an existing TextView
        TextView tv1 = (TextView) findViewById(R.id.test1);
        new Iconics.IconicsBuilder().ctx(this)
                .style(new ForegroundColorSpan(Color.WHITE), new BackgroundColorSpan(Color.BLACK), new RelativeSizeSpan(2f))
                .styleFor("faw-adjust", new BackgroundColorSpan(Color.RED), new ForegroundColorSpan(Color.parseColor("#33000000")), new RelativeSizeSpan(2f))
                .on(tv1)
                .build();
```

?

**Comment by magicgoose** [comment]
If I do it like in your snipped, any existing formatting in tv1's text is lost.

**Comment by mikepenz** [comment]
@magicgoose ah ok i see. So perhaps this method should be modified to support pre formatted stuff.

**Comment by magicgoose** [comment]
Or you can include these methods as well https://gist.github.com/magicgoose/8b4bb1eb7ee428c0fc3b, because sometimes it's handy to just get a Spanned text with some icons. (if the text is displayed in something other than a TextView, for example)

**Comment by jemshit** [comment]
@mikepenz Hi, any snippet for using `Html.fromHtml` with Iconics? I give `Spanned` to `IconicsTextView` but it loses formatting.
