### ISSUE TITLE
Using Deprecated LayoutInfalterCompat.setFactory

### ISSUE THREAD

**Issue by bschnack** [mikepenz/Android-Iconics#302]
Hello,

The LayoutInflaterCompat.setFactory that we are told to use in the instructions has been deprecated in API 26 and instead we are supposed to use setFactory2 and IconicsLayoutInflater will need to extend LayoutInflater.Factory2 instead. With the deprecated function, it still works as expected.

Thanks,
Brian

**Comment by mikepenz** [comment]
@bschnack thank you very much. Currently I did not upgrade to 26 as it is sadly not yet final (at least the support libs, I know that the API is final). Will revisit it as soon as it's out (support libs + Android Studio 3)

**Comment by mikepenz** [comment]
@bschnack if you want to fix it anytime before. Feel free to do so by opening a PR :D

**Comment by bschnack** [comment]
I will give it a try sometime this week.

**Comment by mikepenz** [comment]
thank you

**Comment by mikepenz** [comment]
Merged, and will be in the next release. thank you
