### ISSUE TITLE
Some font awesome icon missing due to same values.

### ISSUE THREAD

**Issue by atulgoswami21** [mikepenz/Android-Iconics#306]
Some font awesome icon missing due to same values.
for example faw-close and faw-times has same value. I have to change to faw-times as faw-close is missing in the latest version.
Hope you will find the fix soon.

**Comment by mikepenz** [comment]
@atulgoswami21 well I can only use the mapping of the font. if the mapping of their font links to these names I am not really able to fix this.

**Comment by mikepenz** [comment]
You might also want to open a PR and add / adjust the ones you miss manually. 
It would be un-maintainable if I would have to do somehting like this manually. It's just possible to use my automatic tooling to save time and be fast :)

**Comment by mr746866** [comment]
In the latest Font Awesome versions, they have variants of the same icon. For example, the user icon has solid, regular and light variants, as seen from the following link.
https://fontawesome.com/icons/user?style=solid

Is it currently possible to get different variants of the same icon?

**Comment by mikepenz** [comment]
@mr746866 check out the sample app it shows all the available icons. (and yes it contains a faw_user and a faw_user2 (filled and non filled))
