### ISSUE TITLE
IconicsTextView's setText() shows the invalid icons on Lenovel TAB2.

### ISSUE THREAD

**Issue by annawang1** [mikepenz/Android-Iconics#308]
![from](https://user-images.githubusercontent.com/14036928/28655789-a0072fc0-72d0-11e7-9c05-a20c657cd86d.png)
![to](https://user-images.githubusercontent.com/14036928/28655790-a007d3ee-72d0-11e7-84f3-dc60c432c00f.png)

Precondition:
1: use google material design,
2: Lenovel tablet OS Android 5.0.1.
Reproduce steps:
1: set the data source which contains a list of strings using the template of "{gmd-icon-name}" to the dapter, and the adapter contains the item IconicsTextView,
2: show the ListView.
Results:
the icons switch quickly to invalid.
Note:
1: please read the from.png and to.png.
2: here is the source code: https://github.com/annawang1/Lenovel

**Comment by mikepenz** [comment]
@annawang1 do you get the same with other fonts provided by `Android-Iconics`?

**Comment by annawang1** [comment]
@mikepenz Thanks for your reply.
I have also tried the 'community-material-typeface' and 'octicons-typeface', and both of them have the same invalid icons.
When to debug, the setText(CharSequence text, BufferType type) in IconicsTextView has the invalid 'text' of CharSequence, and I don't know why.

**Comment by mikepenz** [comment]
Can you try and install the sample app on this phone please?

**Comment by annawang1** [comment]
@mikepenz Sorry for the delay.
I performed the clean install, and unfortunately, it turned out to be the same.
It's the demo sample, but not available in the market, and could you please access the APK file from
[here](https://github.com/annawang1/Lenovel/blob/master/lenovel.apk) if needed.

**Comment by annawang1** [comment]
@mikepenz Sorry for the delay.
I tried and install the sample app, and it works well. And I will check my code.

**Comment by mikepenz** [comment]
@annawang1 did you find something?

**Comment by annawang1** [comment]
@mikepenz little, I will keep this updated if had any progress. 
So, you could close it since I'm not sure how long it would take to be resolved. :)

**Comment by mikepenz** [comment]
Ok. Just let me know if oyu find something

**Comment by annawang1** [comment]
@mikepenz yes, of course.
