### ISSUE TITLE
Wrong icon color in 2.9.1

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/Android-Iconics#309]
I set the color of my icon in xml via iiv_color - but it seems the icon color is always black.

**Comment by Gounlaf** [comment]
Hi,

I've got the same probleme; not only color, size too.

**Comment by mikepenz** [comment]
@Rainer-Lang @Gounlaf thanks for the report. With v2.9.x the way how those values are processed changed quite a bit. Sorry for the issues. 

Using the programatical way should work for now

**Comment by Gounlaf** [comment]
Hi @mikepenz,

Sorry for the imprecision: setting it programmatically doesn't work for me.

**Comment by Rainer-Lang** [comment]
For me neither.

**Comment by Rainer-Lang** [comment]
@mikepenz Any news on this?

**Comment by fssilva** [comment]
I was looking the code for the first time and I noticed that all xml attributes are set within `IconicsViewsAttrsReader`,  after this condition `if (!TextUtils.isEmpty(icon.getPlainIcon())) {`

However it seems that this condition is always false. I bypassed the if-else just for testing and it seems to be working again (colors, size, background, etc). 

Can somebody tell me why this if-statement is so important ? I might can help fixing it.

**Comment by mikepenz** [comment]
@fssilva well the check was added to optimize and not set anything in case if there is no icon. but Yeah now as I think about it, I think we can remove it safely. 

This still does not describe though why there are also reports of it not working via the programatic approach (which seems weird)

**Comment by mikepenz** [comment]
The issue should be fixed in v2.9.2 of the views extension

Sorry for the issue

**Comment by Rainer-Lang** [comment]
@fssilva @mikepenz Thanks.

**Comment by Gounlaf** [comment]
Thanks !
