### ISSUE TITLE
Stacked icons 

### ISSUE THREAD

**Issue by mutindaz** [mikepenz/Android-Iconics#31]
How do you create the below using Android-Iconics? Looked at the demo but I seem not to get an example for this.

``` css 
<span class="fa-stack fa-lg fa-5x">
	<i class="fa fa-square-o fa-stack-2x"></i>
	<i class="fa fa-cloud  fa-stack-1x"></i>
</span>
```
Basically a cloud icon with a square around it.

The output is here http://jsfiddle.net/mutinda/w5zbxm20/

**Comment by mikepenz** [comment]
@mutindaz if you need to overlap to icons i would recommend you to create a `RelativeLayout` with two `ImageViews` inside it where one ImageView overlaps the other.

**Comment by mutindaz** [comment]
@mikepenz nice one!

**Comment by mikepenz** [comment]
@mutindaz a different solution could be this: http://stackoverflow.com/a/2740198/325479
