### ISSUE TITLE
Text + Background Icon

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#311]
Is this possible? I don't think so.

Something like `new IconicsDrawable(context).icon(FontAwesome.Icon.faw_circle).iconText(counter);` would be nice I think. Only an own color for the text would be needed I think...

**Comment by mikepenz** [comment]
@MFlisar it's not possible. And I don't think this makes sense. If you need text + icon. Use an `IconicsTextView`

**Comment by MFlisar** [comment]
Actually in my case it's depending on the item's property that's why this would be nice. I can simply load another drawable, just thought this would be nice
