### ISSUE TITLE
Icon color does not work from 2.9.1

### ISSUE THREAD

**Issue by carmas123** [mikepenz/Android-Iconics#318]
I've updated you library to lastest version 2.9.1 and now the icon color specified into XML does not will be applied.

```
                app:iiv_color="@color/white"
                app:iiv_icon="gmi-delete"
```
The icon is always black

this is my gradle

    implementation "com.mikepenz:iconics-core:2.9.1@aar"
    implementation "com.mikepenz:iconics-views:2.9.1@aar"
    implementation "com.mikepenz:material-design-iconic-typeface:2.2.0.3@aar"
    implementation "com.mikepenz:community-material-typeface:1.9.32.2@aar"

**Comment by Gounlaf** [comment]
Hi,

It has been fixed in com.mikepenz:iconics-views:2.9.2 https://github.com/mikepenz/Android-Iconics/issues/309

**Comment by carmas123** [comment]
Thank you, I try it

**Comment by carmas123** [comment]
But this version is not released.

**Comment by mikepenz** [comment]
@carmas123 it is :O

**Comment by mikepenz** [comment]
https://bintray.com/mikepenz/maven/iconics-views/2.9.2

**Comment by mikepenz** [comment]
It's available on `jCenter()`

**Comment by carmas123** [comment]
Sorry but I always got 
Error:Failed to resolve: com.mikepenz:iconics-views:2.9.2

I've jcentral() into repo.

**Comment by mikepenz** [comment]
released it now also to maven central (sorry I am currently traveling so not as responsive as normally)

it will take a while but in 15-45 mins it will be available

**Comment by carmas123** [comment]
Thank you

**Comment by Gounlaf** [comment]
Thanks @mikepenz. I was stuck too, trying to install it on "local maven"... but didn't succeed :x

**Comment by mikepenz** [comment]
Hmmm I wonder why it is not downloaded via jCenter because it is available up there :D

**Comment by Gounlaf** [comment]
It was not available on jcenter when @carmas123 posted (I looked at both jcenter and maven central)

**Comment by mikepenz** [comment]
@Gounlaf isn't this the correct place to check for jcenter availibility: https://bintray.com/mikepenz/maven/iconics-views/2.9.2 ?

**Comment by mikepenz** [comment]
Oh ok I see now: https://bintray.com/bintray/jcenter/com.mikepenz%3Aiconics-views 

weird :O
