### ISSUE TITLE
cannot set iconfont attr

### ISSUE THREAD

**Issue by chanderwoo** [mikepenz/Android-Iconics#319]
why there is a condition of  if (!TextUtils.isEmpty(icon.getPlainIcon())) before set iconfon attr in IconicsViewsAttrsReader. Is it a bug?  it should be if (!TextUtils.isEmpty(icon.getIcon())) right?

**Comment by chanderwoo** [comment]
Sorry, I didn't find the 2.9.2 has fixed the issue. well done. but  doesn't release yet

**Comment by mikepenz** [comment]
@chanderwoo v2.9.2 is released https://repo.maven.apache.org/maven2/com/mikepenz/iconics-views/
