### ISSUE TITLE
Problem using Lollipop

### ISSUE THREAD

**Issue by carmelo-ruota** [mikepenz/Android-Iconics#32]
On Lollipop, using IconicsButton, only the normal text "Button" is displayed.

 <IconicsButton
        android:text="{faw-adjust} Button"
        android:layout_width="120dp"
        android:layout_height="60dp"/>
   
Same code, on Kitkat shows both icon and text.

**Comment by mikepenz** [comment]
@carmelo-ruota just tried on my Nexus 5. The sample activity shows the icon for the IconicsButton. Not if you try to style it via code.

**Comment by carmelo-ruota** [comment]
The same code:
    <IconicsButton
                    android:id="@+id/buttonAdd"
                    android:layout_height="36dp"
                    android:layout_width="36dp"
                    android:text="{faw-plus}"/>
Works fine with a fragment and shows nothing in Activity.

**Comment by mikepenz** [comment]
@carmelo-ruota first please update to the latest version. and then make sure you don't do different things with this button between fragment and activity

**Comment by carmelo-ruota** [comment]
Just update to latest version and still not works. The only difference between fragment and activity is that in fragment IconicsButton is contained in TableRow, while in Activity IconicsButton is inside a LinearLayout (Horizontal):

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content" android:gravity="center_vertical" android:orientation="horizontal">
            <it.myapp.view.MaterialSpinner
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/spinnerProprietario"
                app:ms_floatingLabelText="Proprietario"
                android:layout_weight="1"/>


            <com.mikepenz.iconics.view.IconicsButton
                android:id="@+id/buttonAddProprietario"
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:text="{faw-plus}"/>
            <com.mikepenz.iconics.view.IconicsButton
                android:id="@+id/buttonEditProprietario"
                android:layout_width="36dp"
                android:layout_height="36dp"
                android:text="{gmd-create}"/>

        </LinearLayout>

**Comment by mikepenz** [comment]
Do you use any font modifying library?

**Comment by carmelo-ruota** [comment]
Yes I do! This:
https://github.com/chrisjenx/Calligraphy

**Comment by mikepenz** [comment]
@carmelo-ruota i assume this one overwrites the typeface for the view. try to disable it, to check my assumption.

**Comment by carmelo-ruota** [comment]
Now, without Calligraphy, seem it works fine! :-)
