### ISSUE TITLE
IconicsImageView color inconsistancy

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#324]
I tried following to set my icons color:

*Layout*

	<com.mikepenz.iconics.view.IconicsImageView
		android:id="@+id/ivIcon"
		style="@style/SettImage" />

1) style the color in my theme:

		<style name="SettImage">
			
			<item name="ico_color">?android:attr/textColorPrimary</item>
			<item name="ico_size">24dp</item>
			<item name="iiv_color">?android:attr/textColorPrimary</item>
			<item name="iiv_size">24dp</item>
		</style>
	
In this case I get black for both themes: `Theme.AppCompat.Light.DarkActionBar` and `Theme.AppCompat` (instead of black for the light theme and white for the dark theme)

2) style in code:

		IconicsImageView iv = (IconicsImageView)getIconView();
		iv.setIcon(icon);
		iv.setPaddingDp(data.getIconPaddingDp());
		iv.setColor(Util.getTextColor());
		// IconicsDrawable d = ((IconicsDrawable) getIconView().getDrawable());
		// d.icon(icon).color(Util.getTextColor()).paddingDp(data.getIconPaddingDp());
		
		public static int getTextColor() {
			return ContextCompat.getColor(SettingsManager.get().getContext(),
					SettingsManager.get().getState().isDarkTheme() ? android.R.color.primary_text_dark : android.R.color.primary_text_light);
		}
	
In this case, everything works as expected with following themes: `Theme.AppCompat.Light.DarkActionBar` and `Theme.AppCompat`. No matter if I use the code above or the commented alternate solution.

3) I use solution 2 in a library of mine and use this in an app in which I use `MaterialDrawerTheme.Light.DarkToolbar` and `MaterialDrawerTheme` theme. In this case, I get gray icons if I use the commented solution for the dark theme and the correct colors if I use the not commented solution.

Any ideas why 1 is not working? Can you explain the weird behaviour I describe in 3?

**Comment by mikepenz** [comment]
@MFlisar I don'T think you can style these values like this, as we do not have them as styled attributes. It's not like in the MaterialDrawer where I made them resolve via the theme and styles. 

We just use a default color, or the one you define in xml, but nothing from a style or anywhere else. so it is correct behaviour

**Comment by MFlisar** [comment]
What's this call then? 

https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsImageView.java#L69

And this:

https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-view-library/src/main/res/values/attrs.xml#L22

I think you are using the attributes and am resolving them... I'm talking about the `IconicsImageView ` not about using a custom inflater (I will make my library open source, so I avoid using the custom inflater in it)

**Comment by mikepenz** [comment]
the fields you can define inside the view in xml.

**Comment by MFlisar** [comment]
That's what I do here:

    <com.mikepenz.iconics.view.IconicsImageView
		android:id="@+id/ivIcon"
		style="@style/SettImage" />

This will expand to

    <com.mikepenz.iconics.view.IconicsImageView
		android:id="@+id/ivIcon"
        app:ico_color="?android:attr/textColorPrimary"
        app:ico_size="24dp"
        app:iiv_color="?android:attr/textColorPrimary"
        app:iiv_size="24dp" />

I think this should work...
