### ISSUE TITLE
Icons getting cut off, or displaced. 

### ISSUE THREAD

**Issue by jd-alexander** [mikepenz/Android-Iconics#325]
So I am having this issue with all the icons I am using. I am basically using both ImageViews and IconicsImageViews as well and this is what's happening. 
![cut_off](https://user-images.githubusercontent.com/1509205/29940447-df5bfa26-8e54-11e7-8748-3d479cefa2db.png)

Only time the issue is partially resolved is if the user pull downs the notification bar.

![cut_off_2](https://user-images.githubusercontent.com/1509205/29940504-172868ea-8e55-11e7-8ca0-6c9856d71436.png)

 so I am wondering if it's some issue with layout rendering. I have set the image size appropriately as well in xml and code. Any thoughts?

**Comment by mikepenz** [comment]
@jd-alexander do you define a size for them? do you see the same behaviour in the sample app?

**Comment by jd-alexander** [comment]
I was using an older version of the library; version 1.5. Once I updated the issue disappeared.
