### ISSUE TITLE
Update Textview normal text ( Textview with text set to icon code+normal text)

### ISSUE THREAD

**Issue by utsavmadaan1995** [mikepenz/Android-Iconics#326]
Sir, I have a Textview in xml of which text attribute is set to say "{faw-search} All sites". Now programatically i want to update normal text("All sites") of a textview..so that textview would show same icon+updated text. I havent found or able to figure out how to do this if you can help.

**Comment by mikepenz** [comment]
@utsavmadaan1995 either you use a `IconicsTextView` or you manually apply the icon replacement

```java
new Iconics.IconicsBuilder().ctx(getContext()).on(textView).build()
```

**Comment by utsavmadaan1995** [comment]
Not working for me i have tried that. My code:
textView.setText(String.valueOf(textView.getText()).replaceFirst("\\n[^~]*","\n"+String.valueOf(text)));
                                new Iconics.IconicsBuilder().ctx(view.getContext()).styleFor(FontAwesome.Icon.faw_search).on(textView).build();

Maybe the problem is that i am replacing the text of textview before giving it to IconicsBuilder to build upon it which it is not recognizing have any icon.In log it print "fl/nAll Sites" before passing it to IconicsBuilder.

**Comment by mikepenz** [comment]
@utsavmadaan1995 the second thing you wrote is fine. 

One recommendation. If you have the icon in a position in the beginning etc of a TextView. Consider the compound drawable functionality.
