### ISSUE TITLE
How to set icon from R.drawable

### ISSUE THREAD

**Issue by ryandailey100** [mikepenz/Android-Iconics#328]
I am trying to set an icon from my drawable resource folder but it doesnt seem to work. How can this be done?

        val icon1 = IconicsDrawable(this)
        icon1.icon(R.drawable.white_icon_1x)
        icon1.sizeDp(24)
        actionItemSearch.setImageDrawable(icon1)

.icon() doesnt seem to want to take R.drawable.white_icon_1x

**Comment by mikepenz** [comment]
@ryandailey100 you can't this library is not meant to do something with normal drawables. Please read it's description
