### ISSUE TITLE
why does 'com.mikepenz:community-material-typeface:1.9.32.2@aar' there are no string ref resources

### ISSUE THREAD

**Issue by chanderwoo** [mikepenz/Android-Iconics#329]
the other typefaces can use in xml by "string/gmd-xxx-xx" but only this lib.

**Comment by mikepenz** [comment]
Can you please be a bit more specific. what's the issue?

**Comment by zTrap** [comment]
@mikepenz I'll add `string` fields for all icon in all libs. Don't worry about that. This issue can be closed
