### ISSUE TITLE
Icons not showing after upgrade to latest

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/Android-Iconics#330]
It seems that something is broken with updates to libs.

My current setup doesn't show icons properly
```
compile('com.mikepenz:materialdrawer:5.9.5@aar') {
        transitive = true
    }
    compile('com.mikepenz:aboutlibraries:5.5.5@aar') {
        transitive = true
    }
    compile 'com.mikepenz:crossfader:1.5.0@aar'
    compile 'com.mikepenz:google-material-typeface:3.0.1.1.original@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.5.0.1@aar'
    compile 'com.mikepenz:octicons-typeface:3.2.0.1@aar'
    compile 'com.mikepenz:community-material-typeface:1.3.41.1@aar'
```

![screenshot_20170913-195739](https://user-images.githubusercontent.com/1249919/30387592-03569b5c-98be-11e7-8636-231b8de8b124.png)

But when i downgrade google-material to compile 'com.mikepenz:google-material-typeface:2.1.0.1.original@aar' it works well.

**Comment by mikepenz** [comment]
any log outputs?

**Comment by androideveloper** [comment]
Can't find any related to this problem :/ The problem is after upgrade to 3.x.x.x versions. Even 2.2.0.3 works pretty well.

**Comment by androideveloper** [comment]
`09-14 10:32:55.224 32010-32010/? I/art: Late-enabling -Xcheck:jni
09-14 10:32:55.285 32010-32010/com.armsoft.mtrade.dev W/System: ClassLoader referenced unknown path: /data/app/com.armsoft.mtrade.dev-1/lib/arm
09-14 10:32:55.341 32010-32010/com.armsoft.mtrade.dev D/DebugDB: Open http://192.168.0.20:8080 in your browser
09-14 10:32:55.542 32010-32057/com.armsoft.mtrade.dev I/stetho: Listening on @stetho_com.armsoft.mtrade.dev_devtools_remote
09-14 10:32:55.558 32010-32010/com.armsoft.mtrade.dev W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-14 10:32:55.925 32010-32010/com.armsoft.mtrade.dev I/zzbx: Making Creator dynamically
09-14 10:32:56.028 32010-32010/com.armsoft.mtrade.dev W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000f/n/armeabi
09-14 10:32:56.074 32010-32010/com.armsoft.mtrade.dev I/Google Maps Android API: Google Play services client version: 11020000
09-14 10:32:56.080 32010-32010/com.armsoft.mtrade.dev I/Google Maps Android API: Google Play services package version: 11509436
09-14 10:32:56.438 32010-32042/com.armsoft.mtrade.dev E/Beta: Error reading Beta build properties
                                                              java.io.FileNotFoundException: crashlytics-build.properties
                                                                  at android.content.res.AssetManager.openAsset(Native Method)
                                                                  at android.content.res.AssetManager.open(AssetManager.java:313)
                                                                  at android.content.res.AssetManager.open(AssetManager.java:287)
                                                                  at com.crashlytics.android.beta.Beta.loadBuildProperties(Beta.java:172)
                                                                  at com.crashlytics.android.beta.Beta.doInBackground(Beta.java:75)
                                                                  at com.crashlytics.android.beta.Beta.doInBackground(Beta.java:30)
                                                                  at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
                                                                  at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
                                                                  at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
09-14 10:32:56.626 32010-32137/com.armsoft.mtrade.dev D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-14 10:32:56.641 32010-32010/com.armsoft.mtrade.dev I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
09-14 10:32:56.664 32010-32137/com.armsoft.mtrade.dev I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-14 10:32:56.667 32010-32137/com.armsoft.mtrade.dev I/OpenGLRenderer: Initialized EGL, version 1.4
09-14 10:32:56.908 32010-32010/com.armsoft.mtrade.dev W/View: requestLayout() improperly called by android.widget.LinearLayout{816dd57 V.E...... ......I. 0,0-0,0 #7f100134 app:id/second} during layout: running second layout pass
09-14 10:32:57.133 32010-32010/com.armsoft.mtrade.dev W/ResourceType: No known package when getting name for resource number 0x9e626c54
09-14 10:32:57.133 32010-32010/com.armsoft.mtrade.dev W/View: requestLayout() improperly called by android.widget.LinearLayout{39dd337 V.....CL. ......I. 0,0-128,144 #9e626c54} during second layout pass: posting in next frame
09-14 10:32:58.624 32010-32133/com.armsoft.mtrade.dev W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
09-14 10:32:58.652 32010-32133/com.armsoft.mtrade.dev I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
09-14 10:32:58.652 32010-32133/com.armsoft.mtrade.dev I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 4
09-14 10:32:58.712 32010-32133/com.armsoft.mtrade.dev W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000d/n/armeabi-v7a
09-14 10:32:58.712 32010-32133/com.armsoft.mtrade.dev W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000d/n/armeabi
`

**Comment by mikepenz** [comment]
the log does not show anything :/ could you possibly debug into it and see where it stops?

**Comment by mikepenz** [comment]
do you see the same behaviour in the sample app?

**Comment by androideveloper** [comment]
Hey, I have debuged it and when calling this method
`    public IconicsDrawable icon(IIcon icon) {
        mIcon = icon;
        mPlainIcon = null;
        ITypeface typeface = icon.getTypeface();
        mIconPaint.setTypeface(typeface.getTypeface(mContext));
        invalidateSelf();
        return this;
    }`

typeface is com.mikepenz.google_material_typeface_library.GoogleMaterial
but nex line typeface.getTypeface(mContext) return null!

**Comment by androideveloper** [comment]
Are you considering to rewrite the lib using native fonts support?

**Comment by androideveloper** [comment]
I get exception here typeface = Typeface.createFromAsset(context.getAssets(), "fonts/" + TTF_FILE); cannot find font. I will try to clean/build now and let you know

**Comment by mikepenz** [comment]
@androideveloper the icon fonts are not really used as real font. I'll look into it, but I guess it does not bring any real advantage. 

do you have proguard or anything which might remove it?

**Comment by androideveloper** [comment]
After clean build everything is ok! Current setup AS 3.0, Gradle plugin 3.0. Can't recall if I updated any other libs during this month. No, proguard is disabled.

**Comment by androideveloper** [comment]
You are loading fonts from assets and have custom TypeFaceProvider, which I guess can be removed if you switch to /fonts resources

**Comment by mikepenz** [comment]
very interesting. seems AS was just acting weird. 

Yes I'll look into it ;) thanks

**Comment by arose13** [comment]
Sorry what is `AS` ?

**Comment by zTrap** [comment]
@arose13 AS means Android Studio

**Comment by SaeedRe** [comment]
I had the same problem.
In my case a folder named "fonts" in my assets folder caused the problem.
I renamed my fonts folder to something unique and now the icons is loading fine.
