### ISSUE TITLE
Dynamically change icon in a TextView

### ISSUE THREAD

**Issue by mr746866** [mikepenz/Android-Iconics#331]
I want to change the icon of a `TextView` dynamically using code. I tried the following code in my `Fragment` but it causes an `IndexOutOfBoundsException`.

```
if (someCondition)
{
    myTextView.setText("{faw-check}  Done");
}
```
Sorry if this is already answered somewhere.

**Comment by mikepenz** [comment]
@mr746866 can you please post the whole exception?

for such a case I recommend using Compound drawables by the way

**Comment by mikepenz** [comment]
Please report back with additional details

**Comment by mojtabamalaekeh** [comment]
Hi,
I've simillar problem.
There is no error. But dynamically added TextViews show raw codes like {faw-times}.
TextViews in xml file are OK.
I'm using com.mikepenz:iconics-core:3.0.4@aar
Is there any method I should call after adding views?

My code:
TextView textView = new TextView(this);
textView.setText("{faw-times}");
tableRow.addView(textView);

**Comment by Hatzen** [comment]
Something like: `Iconics.Builder().on(textview).build()` may help
