### ISSUE TITLE
A-Z letters

### ISSUE THREAD

**Issue by fmeneuhe** [mikepenz/Android-Iconics#335]
Hi Mike,
Do you have A-Z letters included in any of your icons?
Thanks

**Comment by zTrap** [comment]
@fmeneuhe, hello! You can use [this](https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L224) method for drawing some text

**Comment by Rainer-Lang** [comment]
@fmeneuhe Look at the possible icons-font-libs: in readme `Already available fonts`

**Comment by fmeneuhe** [comment]
Is possible to create my own custom font with all the A-Z letters? I cannot find an example about how to do that.
