### ISSUE TITLE
Building icon on a Textview within ItemView of a List

### ISSUE THREAD

**Issue by utsavmadaan1995** [mikepenz/Android-Iconics#336]
Sir,

I am having a recyclerview in which every item has some text and a image(build on textview through Iconics). In adapters onBindViewHolder i am doing this:
...
textview.setText(someIconCode);
new Iconics.IconicsBuilder().ctx(context).on(textview).build()
...

Everything is working as usual but my question is it the appropriate way of adding icon to textview within some listitem view through iconics???

I mean for everyitem i am doing this in onBindViewHolder(building with iconicsBuilder+it must have performed some lookup for which icon is this, etc) ...apperently i am not seeing any performance degrade or anything but still would want to know this.

**Comment by zTrap** [comment]
@utsavmadaan1995, hello.

You can try to use `IconicsTextView` instead standard `TextView`, and delete using `Iconics.IconicsBuilder`. For using it add `com.mikepenz:iconics-views:2.9.3@aar"` in dependencies.

**Comment by mikepenz** [comment]
In addition please remember that using a compound drawable is better in case the icon needs to be top,bottom,right,left ...
