### ISSUE TITLE
attr/iiv_color and attr/iiv_size not found in styles

### ISSUE THREAD

**Issue by mtrakal** [mikepenz/Android-Iconics#337]
I try to upgrade from `2.8.9` to `2.9.3` and got error below:
```
Error:(241, 5) style attribute 'attr/iiv_color (aka com.droid4you.application.wallet:attr/iiv_color)' not found
Error:(241, 5) style attribute 'attr/iiv_size (aka com.droid4you.application.wallet:attr/iiv_size)' not found
```

We use in our style file: 
```
<style name="Forms.IIV">
        <item name="android:layout_gravity">top</item>
        <!--<item name="android:layout_margin">@dimen/form_padding</item>-->
        <item name="iiv_color">@color/forms_text_light</item>
        <item name="iiv_size">20dp</item>
        <item name="android:layout_width">20dp</item>
        <item name="android:layout_height">20dp</item>
    </style>
```

Until upgrade to latest version everything was ok. Not with latest release. Was this variables renamed?

My previous issue was: https://github.com/mikepenz/Android-Iconics/issues/322 it's a reason why we stay until today on `2.8.9`.

Thanks for help

**Comment by mikepenz** [comment]
@mtrakal yeah with the latest version we split the core and the views apart. 

The possible attrs are found here: https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-view-library/src/main/res/values/attrs.xml

**Comment by mtrakal** [comment]
Ouch, my fault. I forgot on views module. Thanks a lot
