### ISSUE TITLE
Usage on Fab and Calligraphy

### ISSUE THREAD

**Issue by arashzz** [mikepenz/Android-Iconics#338]
First of all thanks for your great library. I'm using this to add icons to my fabs but also need to include Calligraphy in my app.

When i attach your lib to my based context fab icons are shown but the font is not changed and it's vice versa when I attach Calligraphy's context. 

Since you said context-injection is the only way to go for fab icons, is there any way to use it along side with Calligraphy?

**Comment by mikepenz** [comment]
@arashzz just set the icon programatically
