### ISSUE TITLE
Icon is created then disappears

### ISSUE THREAD

**Issue by fmorel90** [mikepenz/Android-Iconics#34]
I included "compile 'com.mikepenz:iconics:1.0.1@aar'" in my gradle config and then tried to used both IconicsTextView and IconicsImageView in a layout. The icon (I tried different ones) appears briefly and then disappears. In case of a conflict, I tried both with and without your Material Drawer library.

Example layout:

```xml
<RelativeLayout
		android:id="@+id/card_border"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:background="@color/accent"
		android:gravity="fill_vertical"
		android:paddingBottom="8dp"
		android:paddingLeft="16dp"
		android:paddingRight="16dp"
		android:paddingTop="8dp">
		<android.support.v7.widget.AppCompatTextView
				android:id="@+id/txtGame"
				android:layout_width="wrap_content"
				android:layout_height="wrap_content"
				android:layout_alignParentLeft="true"
				android:layout_alignParentStart="true"
				android:text="CE"
				android:textColor="@android:color/white"
				android:textIsSelectable="false"
				android:textSize="12sp"
				android:typeface="sans"/>
		<com.mikepenz.iconics.view.IconicsTextView
				android:id="@+id/iconAlert"
				android:layout_width="16dp"
				android:layout_height="16dp"
				android:layout_centerInParent="true"
				android:text="{gmd-error}"
				android:textAlignment="center"
				android:textColor="@android:color/white"
				android:textSize="16sp"/>
		<android.support.v7.widget.AppCompatTextView
				android:id="@+id/txtLevel"
				android:layout_width="wrap_content"
				android:layout_height="wrap_content"
				android:layout_alignParentEnd="true"
				android:layout_alignParentRight="true"
				android:singleLine="false"
				android:text="***"
				android:textColor="@android:color/white"
				android:textIsSelectable="false"
				android:textSize="12sp"
				android:typeface="sans"/>
</RelativeLayout>
```

**Comment by fmorel90** [comment]
I had no problem with the same icon on a AppCompatTextView using ```new Iconics.IconicsBuilder().ctx(activity).on(alert).build();```.

**Comment by mikepenz** [comment]
@fmorel90 just as info. you don't have to add the Android-Iconics to your project. The MaterialDrawer already comes with it. It's also the same version. 

It disappears?
Can it be that it get's overlapped by a different view?

**Comment by fmorel90** [comment]
Thanks. That's what I thought, but preferred to make the dependency explicit.

No, I tried it in several places & sizes because I thought maybe wrap_content or being in a RelativeLayout was the issue, but it always disappeared.

**Comment by mikepenz** [comment]
@fmorel90 yeah :D

it'S really strange. can you share the code. perhaps i can reproduce it.

**Comment by fmorel90** [comment]
The layout file, or the whole project?

**Comment by mikepenz** [comment]
@fmorel90 the project would be gerat. you can remove all your project specific stuff. just to be able to reproduce this issue.

**Comment by mikepenz** [comment]
if it is still the case please just write here again
