### ISSUE TITLE
can include map-icons?

### ISSUE THREAD

**Issue by maxid** [mikepenz/Android-Iconics#340]
https://github.com/scottdejonge/map-icons

**Comment by mikepenz** [comment]
They don't look like being a font

**Comment by Rainer-Lang** [comment]
https://github.com/scottdejonge/map-icons/issues/60

**Comment by powerhcm8** [comment]
https://github.com/scottdejonge/map-icons/tree/master/dist/fonts

**Comment by mikepenz** [comment]
@powerhcm8 @maxid  you might want to open a PR and add this font? 

https://github.com/mikepenz/Android-Iconics/wiki/CustomFontAddonCreating

**Comment by mikepenz** [comment]
If you want to use it please open a PR. I am more than happy to include it ;)
