### ISSUE TITLE
Use Icon as hint

### ISSUE THREAD

**Issue by dev2961io** [mikepenz/Android-Iconics#343]
What I am trying to do is use one of the icons as a hint within a EditText, but ImageSpan even tho' is meant to work with drawables does not recognise the icon as a drawable. Any idea how can I solve this?
My code:
```
EditText searchBar = (EditText) view.findViewById(R.id.searchBar);
        Drawable searchIcon =
                new IconicsDrawable(getContext())
                .icon(FontAwesome.Icon.faw_search)
                .color(Color.RED)
                .sizeDp(24);
        
        ImageSpan imageHint = new ImageSpan(getContext(), searchIcon);
        SpannableString spannableString = new SpannableString("Search");
        spannableString.setSpan(imageHint, 0, 1, Spanned.SPAN_INCLUSIVE_EXCLUSIVE);
        searchBar.setHint(spannableString);
```

Thank you for your time!

**Comment by mikepenz** [comment]
@dev2961io did you figure something out? 
did you try to set the instrinct bounds? perhaps the `ImageSpan` needs this?

**Comment by mikepenz** [comment]
Close for now. Please report back

**Comment by dev2961io** [comment]
I have tried but with no luck, I was away from that project for a while now and I just got back on it. I was still not able to come up with a solution.
