### ISSUE TITLE
Icons with shadow

### ISSUE THREAD

**Issue by jayrave** [mikepenz/Android-Iconics#345]
I am overlaying some icons over other UI elements which could be of any color. To make the icons look good no matter what the color behind them is, I am planning to make the icons white and add some shadow to (like the Nexus camera). The good news is, `Paint#setShadowLayer` can do this for us! Unfortunately, there isn't an API in `IconicsDrawable` that would allow me to pass this info to the paint!

Would you be fine with adding such a method? I'll be happy to open a PR too instead

**Comment by mikepenz** [comment]
@jayrave that sounds amazing. sure please go ahead and open a PR for that.

**Comment by mikepenz** [comment]
I think this issue can be closed. Please open a PR as soon as you have something ;). 

Thanks a lot!

**Comment by zTrap** [comment]
@jayrave I can do this, or you want to do it yourself?

**Comment by jayrave** [comment]
@zTrap I was gonna do it some time this week, but if you wanna work on it please go ahead

**Comment by zTrap** [comment]
@jayrave sorry, after I writed this ↑ I tryed and I had some problems with bounds and shadow. Also while I tryed I found mistakes in my current PR and I'm gonna to resolve the problems. So if you still can - do it yourself ^^

**Comment by mikepenz** [comment]
@jayrave thank you very much. it would be awesome if you could work on this and open a PR. it would give a great feature ;). 

I am currently really filled with some other libraries. just took the time yesterday to update everything ;)

**Comment by jayrave** [comment]
Yup. I'll get this done this week

**Comment by mikepenz** [comment]
@jayrave amazing! :) 
thank you very much

**Comment by jayrave** [comment]
I have gotten the shadow to come up, but the problem is it gets cut off. I still haven't taken a deeper dive to figure out the reason. 

Will do it this weekend. I just wanted to post an update & let know that I haven't abandoned :)

**Comment by mikepenz** [comment]
Please just open a WIP PR we can look into it to. I might have some ideas.

Awesome work!

**Comment by jayrave** [comment]
#355
