### ISSUE TITLE
incompatible types: IIcon cannot be converted to IconicsDrawable

### ISSUE THREAD

**Issue by mtrakal** [mikepenz/Android-Iconics#351]
iconics-views-2.9.5-sources.jar!/com/mikepenz/iconics/view/IconicsImageView.java:63

`iconicsImageView.setIcon(object.getIIcon());`

In previous versions there was possible to insert IIcon not just IconicsDrawable.
In all places of our code we use IIcon, after uprade from 2.9.3 to 2.9.5 project is not possible to compile due to error in title.

Is there some migration guide?
No info in release notes about required changes in code.

**Comment by zTrap** [comment]
This way was deprecated in 2.9.3 and removed in 2.9.4. You still can set IIcon uses `iconicsView.getIcon().icon(IIcon)`. If `IconicsDrawable` wasn’t setted via xml or code `getIcon()` will return `null`.

**Comment by mtrakal** [comment]
Sorry, I revert back to 2.9.3 and search, that method is deprecated with note how to replace it.
