### ISSUE TITLE
IconicsMenuInflaterUtil not working with Submenus

### ISSUE THREAD

**Issue by marbat87** [mikepenz/Android-Iconics#352]
Hi,

I found that the IconicsMenuInflaterUtil doens't work when the menu has subitems like this:
```
<menu>
    <item>
        <menu>
            <item/>
            <item/>
        </menu>
    </item>
    <item />
    <item />
</menu>
```

It render just icons from begining until the first subitem.
Others are ignored.

**Comment by zTrap** [comment]
@marbat87 How do you inflate that menu

**Comment by marbat87** [comment]
Like this:
`@Override
    public boolean onCreateOptionsMenu(Menu menu) {
IconicsMenuInflaterUtil.inflate(getMenuInflater(), CreaListaActivity.this, R.menu.mymenu, menu);
super.onCreateOptionsMenu(menu);
return true;
}`

**Comment by zTrap** [comment]
@marbat87 for enable checking submenus you must use 
```
IconicsMenuInflaterUtil.inflate(getMenuInflater(), this, R.menu.mymenu, menu, true);
instead of 
IconicsMenuInflaterUtil.inflate(getMenuInflater(), this, R.menu.mymenu, menu);
```
In the next time you can simply look in an class (ctrl+left click) and see overload(s) of an method(s).
