### ISSUE TITLE
Icon is not displayed in preference

### ISSUE THREAD

**Issue by zwieback** [mikepenz/Android-Iconics#353]
Hi,
I use [PreferenceFragmentCompatDividers](https://github.com/Gericop/Android-Support-Preference-V7-Fix) and after `setPreferencesFromResource` (load preferences from xml resource) I call `setPreferenceScreenIcon`:

```java
private void setPreferenceScreenIcon(Context context, String key, IIcon icon) {
    Preference preference = findPreference(key);
    if (preference != null) {
        preference.setIcon(new IconicsDrawable(context).icon(icon));
        // or this:
        // preference.setIcon(new IconicsDrawable(preference.getContext()).icon(icon));
    }
}
```

But in this case the icon is not displayed. Although if the icon is loaded from resources, it is displayed correctly:

```java
private void setPreferenceScreenIcon(Context context, String key, IIcon icon) {
    Preference preference = findPreference(key);
    if (preference != null) {
        preference.setIcon(R.drawable.any_drawable);
    }
}
```

Maybe there is another way to load the icon into the preference?

**Comment by zwieback** [comment]
Indeed, I forgot to add the size.

Is it possible to add a warning if the size is not specified?
Thanks for the help.

**Comment by mikepenz** [comment]
@zwieback there are rare cases where it's fine to have no size. that's why it is not an requirement. 

Glad that it works now :)
