### ISSUE TITLE
Problem with xml icons

### ISSUE THREAD

**Issue by juanm4** [mikepenz/Android-Iconics#357]
Hi, I have added this in gradle:

`implementation 'com.mikepenz:iconics-core:3.0.0@aar'`
`implementation 'com.mikepenz:iconics-views:3.0.0@aar'`
`implementation 'com.mikepenz:fontawesome-typeface:4.7.0.0@aar'`

In the file .xml I have next code:

`<com.mikepenz.iconics.view.IconicsButton
                        android:layout_width="@dimen/size_button_mini"
                        android:layout_height="@dimen/size_button_mini"
                        android:text="{faw-adjust}"
                        android:textSize="@dimen/text_size_button_mini"
                        android:background="@drawable/button_main_small"
                        android:textColor="@color/white"
                        android:layout_marginBottom="@dimen/margin_button_mini"/>`

Well, when I execute the proyect I can't see the icon, I see the raw text "{faw-adjust}".

What is the problem? In previous versions it worked, but now doesn't work.

Thanks in advance!

**Comment by mikepenz** [comment]
@juanm4 any log output? 
any crash? 

which support lib version?
which build tools?

**Comment by juanm4** [comment]
@mikepenz this is my full gradle file:

`apply plugin: 'com.android.application'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        google()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

repositories {
    mavenCentral()
    jcenter()
    google()
    maven { url "https://jitpack.io" }
}

android {
    compileSdkVersion 27
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.isotader.aguasprl"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1"
        // Enabling multidex support.
        //multiDexEnabled true
    }
    //dexOptions {
    //    incremental true
    //    javaMaxHeapSize "4g"
    //}
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:27.0.1'
    compile 'com.android.support:support-v4:27.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:percent:27.0.1'
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.6'
    implementation 'com.mikepenz:iconics-core:3.0.0@aar'
    implementation 'com.mikepenz:iconics-views:3.0.0@aar'
    implementation 'com.mikepenz:fontawesome-typeface:4.7.0.1@aar'
    compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.barteksc:android-pdf-viewer:2.5.1'
    compile 'com.tuyenmonkey:mkloader:1.2.0'
    testCompile 'junit:junit:4.12'
}
`

I'm starting to think that the problem is because I have some error in my gradle file. 
Before I have told you that in previus versions (2.8.3) it woks. But now none of all versions work.

It's clear, the probles isn't in the library, is that I'm missing some configuration.

Thanks and sorry for the inconveniences!

**Comment by mikepenz** [comment]
What's the error you see?

**Comment by juanm4** [comment]
I have no errors in log. But just now I have detect the problem.

I was using:
`implementation 'com.mikepenz:fontawesome-typeface:4.7.0.0@aar'`

And the correct is:
`implementation 'com.mikepenz:fontawesome-typeface:4.7.0.1@aar'`

Also, after change that and clear all cache icons come back to appear.

Again, sorry for the inconveniences and thanks.

PD: I think this library is awesome!!!!!!

**Comment by mikepenz** [comment]
Thank you very much
