### ISSUE TITLE
Expose size settings in IconicsImageDrawable

### ISSUE THREAD

**Issue by str4d** [mikepenz/Android-Iconics#36]
It is quite common to have an `ImageView` with a size of e.g. 40dp but containing a centered 24dp icon, to increase the touch-responsive area. Currently, using an `IconicsImageView` causes the icon to expand to fill the whole space. Exposing `IconicsDrawable.setSizeDp()` etc. as parameters of `IconicsImaveView` would resolve this.

**Comment by str4d** [comment]
Another reason for supporting this is that I have found that the relative sizes of the Material Design icons do not match the drawables, because they don't include any of the margins that the drawables do. So I find that even where I *do* want a 24dp `ImageView`, I often need to set the `IconicsImageDrawable` size to less than that to have a consistent sizing between icons.

**Comment by mikepenz** [comment]
There are methods to set the size of the drawable:
https://github.com/mikepenz/Android-Iconics/blob/master/library/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L343

And also to define a padding for it:
https://github.com/mikepenz/Android-Iconics/blob/master/library/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L284

**Comment by str4d** [comment]
Sorry, I just realized I had typos in my first comment. Fixed.

I already use `IconicsDrawable.setSizeDp()` to handle this (although good to know about the padding method), but as `IconicsImageView` is meant to reduce the verbosity of using `IIcon`s, it would be nice to be able to set size (and maybe padding) there.

**Comment by mikepenz** [comment]
@str4d oh yes i totally missed the fact that you were talking about the view :D
