### ISSUE TITLE
Usage in navigation drawer

### ISSUE THREAD

**Issue by starapple2** [mikepenz/Android-Iconics#360]
This is not an issue but a question: How can this be used for icons in a navigation drawer?

**Comment by mikepenz** [comment]
@starapple2 it can only be used programatically. If you can set a `Drawable` programatically for the `NavigationDrawer` this is possible. 

There is sadly no way in Android, to hook into the xml parsing for the menu and interpret these icons

**Comment by starapple2** [comment]
Really sad Mike. I was drawn to your contributions while searching for info on navigation drawer and vector graphics. Since I wasn't going to try to reinvent the wheel, I added the default activity from Android Studio but became concerned about replacing the grouped vectors with PNG images.

The great part though is that Iconics has sooo simplified styling some media buttons into which I had inserted PNG backgrounds and a couple other instances where the vector is much more suited than other formats.

Thanks for making this available and I hope you'll at some stage get Iconics to cooperate with items in the group.

Best.
