### ISSUE TITLE
Resource strings missing (google material typeface)

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/Android-Iconics#363]
Updating `com.mikepenz:google-material-typeface` from `3.0.1.1` to `3.0.1.2`  results in that all resources like `gmd_(.*)` are gone. Is this intended?

**Comment by DJafari** [comment]
yes, using `gmd-refresh` instead of `@strings/gmd_refresh`

**Comment by MFlisar** [comment]
Why is this intended? It was added explicitly to avoid types in hand written strings after I asked for this...

**Comment by zTrap** [comment]
Resources was deleted from each libs. Now it’s contained in folder “FONT_IDS” https://github.com/mikepenz/Android-Iconics/tree/develop/FONT_IDS

**Comment by MFlisar** [comment]
I see thanks. Can you show me how I do add those files to my project? They are not added with aar automatically

**Comment by mikepenz** [comment]
@MFlisar it was removed because it would add many many fields to your project (even though you might not need them) pushing apps over the dex limit requireing MultiDex which is definitely bad. 

Simply use the xml and add it to your projects ressources :)

**Comment by mikepenz** [comment]
(on a side node. I think that is the question with the most and fastest answers, excluding me, since working on open source. Awesome job @zTrap & @DJafari :D)

**Comment by MFlisar** [comment]
Does this mean I need to copy those files now manually?

**Comment by mikepenz** [comment]
yes. as there is no way to bundle it with the library without it being generated into the R.class file. (just filling up your fields)

**Comment by MFlisar** [comment]
Ok, than I know everything I need to know. Still, the files could be placed in a seperate project than could be added via a gradle import than

**Comment by MFlisar** [comment]
I was using 3 fonts in my app (gmd, community and faw) and now finally updated my dependencies. Just for documentation (this may be interesting for others as well), this removed **3794 fields** from my apk... Although I'm proguardig my app which should remove unused fields from `R.` files so I was surprised here...

I did not use more than ~100 strings in my xml files...
