### ISSUE TITLE
3.0.1 bugs

### ISSUE THREAD

**Issue by Tolriq** [mikepenz/Android-Iconics#367]
## About this issue

Lot's of random icon size / centering issues when updating from 3.0.0 to 3.0.1

## Details
3.0.1

Using ``` holder.imageView.setImageDrawable(IconicsDrawable(holder.imageView.context, icon).sizeDp(24).respectFontBounds(true))``` in a recyclerview

With 3.0.0 and before all works perfectly.

With 3.0.1 random issues with icons having wrong size or being left aligned. (Really fully random, sometimes auto fix when scrolling, sometimes not, showing a popup menu also sometimes fix or trigger the issue).

I guess https://github.com/mikepenz/Android-Iconics/commit/2ef858439aed094396c5e49591081d19efff8db8 have side effects and may not be the correct fix.

**Comment by mikepenz** [comment]
@Tolriq thanks. reverted it and just wrapped it with a `Try` it hopefully resolves the AS issues, and still keep the old behaviour. 

It is released in a quick bugfix release v3.0.2
