### ISSUE TITLE
Iconics Addon Generator not working

### ISSUE THREAD

**Issue by ptrbrynt** [mikepenz/Android-Iconics#368]
## About this issue

I'm trying to generate a custom font addon using FA5 Pro. I upload the files, fill in the details, click 'Create' and nothing happens (no error message or anything). I've tried on Safari and Firefox (latest versions of both).

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@ptrbrynt just tried it again with a other icon set. 

added the `*.ttf` and the `*.css` added the description. and it correctly worked. 

With Chrome. (there is a high chance it won't work with other browsers :D I am no web dev)

**Comment by ptrbrynt** [comment]
Yep, worked with Chrome. Thanks!
