### ISSUE TITLE
App crashes on clicking search button

### ISSUE THREAD

**Issue by aesher9o1** [mikepenz/Android-Iconics#369]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
updated the apk with the fix in the release page
