### ISSUE TITLE
Missing icon "gmd-favorite-outline".

### ISSUE THREAD

**Issue by amatkivskiy** [mikepenz/Android-Iconics#37]
After last update (**1.0.2**) PlaygroundActivity crashes with :
```
Caused by: java.lang.IllegalArgumentException: gmd_favorite_outline is not a constant in com.mikepenz.google_material_typeface_library.GoogleMaterial$Icon
```
due to missing icon **gmd_favorite_outline**.

**Comment by mikepenz** [comment]
@amatkivskiy thanks. Missed this with the update of the Google Material Design Icons. They changed some names.

**Comment by mikepenz** [comment]
@amatkivskiy the icon was renamed: https://www.google.com/design/icons/#ic_favorite_border
