### ISSUE TITLE
while only "Google Material Design Icons" there are string resource?

### ISSUE THREAD

**Issue by chanderwoo** [mikepenz/Android-Iconics#371]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@chanderwoo sorry I do not really understand what you mean?

**Comment by mikepenz** [comment]
Close. There are no different resources than in the other addons
If you refer to a old version. All resources were moved to: https://github.com/mikepenz/Android-Iconics/tree/develop/FONT_IDS
