### ISSUE TITLE
how can i change background in widget 

### ISSUE THREAD

**Issue by nbjo460** [mikepenz/Android-Iconics#372]
how can i change background in widget with icon?

**Comment by mikepenz** [comment]
@nbjo460 in which widget?

**Comment by nbjo460** [comment]
@mikepenz app widget i trh to do this: `remoteViews.setInt(R.id.minus, "setBackgroundResource", R.drawable.***);` but i vave no id... and if i try this: `                remoteViews.setImageViewBitmap(R.id.minus, bitmap);
` the background Still remains and added a picture. 
I want to make the button or node if there is only a picture without a background such as the command: setBackground

**Comment by mikepenz** [comment]
@nbjo460 this project is a `Drawable` the icons are not bitmaps nor ressources. 

Just read the README. or look into the sample app: https://github.com/mikepenz/Android-Iconics#use-as-drawable
