### ISSUE TITLE
Is there any option to make an iconicsimageview circular?

### ISSUE THREAD

**Issue by dev2961io** [mikepenz/Android-Iconics#373]
Right now I am stuck with an issue. Even though I have injected into the activity context the IconcsContextWrapper I still cannot use iconics in my xml. So since I cannot use iconics with a cricularimageview I was wondering if there is an option to make an iconicsimageview circular?

**Comment by mikepenz** [comment]
@dev2961io no. And that's not really a usecase for it :D 

You can always use the `IconicsDrawable` as source and set it into a circular view or so.

**Comment by dev2961io** [comment]
@mikepenz ok, I get it, my bad it doesn't make sense for it to be circular. But can you please help me understand how to fix the issue where I simply cannot use the iconics in a layout of a fragment if even though I have injected into the activity context the IconcsContextWrapper?

**Comment by mikepenz** [comment]
You don't specify what is not working with the context wrapper. 

What are you trying to do. what's the crash. ..

**Comment by dev2961io** [comment]
Ok I've worked on that, the issue is a bit more complex.
In my activity I do the following:
```
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
```

This allows me to use the iconics in imageviews like so:
```
<de.hdodenhof.circleimageview.CircleImageView
                    android:id="@+id/uploadPicture"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:ico_color="@color/white"
                    app:ico_padding="10dp"
                    app:ico_icon="gmd-camera-alt"
                    app:ico_background_color="@android:color/transparent"
                    app:ico_size="32dp"
               />
```

But in this situation **I cannot use iconics** with **android:text="{gmd-check}"**
Not even in 
```
<com.mikepenz.iconics.view.IconicsButton
                    android:id="@+id/saveButton"
                    android:layout_width="45dp"
                    android:layout_height="45dp"
                    android:background="@android:color/transparent"
                    android:text="{gmd-check}"
                    android:textSize="18sp" />
```

But if I use ONLY
**LayoutInflaterCompat.setFactory2(getLayoutInflater(), new IconicsLayoutInflater2(getDelegate()));**

I can use iconics in android:text but the ones used with app:ico_icon are no longer displayed.

I mention that whilst having attachBaseContext and LayoutInflater the same thing happens as when you only have attachBaseContext.

**Comment by mikepenz** [comment]
So you should definitely just use one. either the factory or the context. NEVER both. 

For the other strange combination I have to check but as far as I know it is not conflicting in the sample app :/

**Comment by swafsarl** [comment]
you could wrap the iconicsImageView with a RelativeLayout and put another ImageView on top of it with a transparent PNG with a circular transparent hole inside. It may look dirty but is very efficient.
In the end you will have one relativeLayout with 2 imagesViews inside. the one on the top is the png with circular transparent "hole".
Hope this help

**Comment by mikepenz** [comment]
I highly recommend to simply set the icon programatically. Which will work on any view, custom views or anything. 

Closing this as it works in the sample for the provided cases
