### ISSUE TITLE
resource string for community-material-typeface is empty 

### ISSUE THREAD

**Issue by dderakhshani** [mikepenz/Android-Iconics#376]
resource string for community-material-typeface is empty  and iiv_icon can not find any cmd-{...} resource.
but I can use any gmd-{...} resources

**Comment by mikepenz** [comment]
what do you mean with resource string? 

"@string/..."? 

These were removed as they count against the DEX limit in Android. 

If you want to use it, you can get it from here: https://github.com/mikepenz/Android-Iconics/tree/develop/FONT_IDS and add it to your project

**Comment by dderakhshani** [comment]
yes I mean "@string/..."? 
Is there any other way to define icon type of the IconicsImageView?

**Comment by mikepenz** [comment]
you just type the "name" of an icon, like "cmd_alarm_light"

**Comment by dderakhshani** [comment]
Nice. Thanks a lot.
