### ISSUE TITLE
Fontawesome 5.0.8 is available

### ISSUE THREAD

**Issue by msneujink** [mikepenz/Android-Iconics#377]
Could you please update the library? Thanks!

**Comment by swafsarl** [comment]
i have lot of vertical alignment issues and icon size (very huge) since my last upgrade fontawesome-typeface to 5.0.7.0
the 4.7.0.1 version was perfect, but lacking many icons

**Comment by mikepenz** [comment]
Do you need any of the new icons? 
I am currently super flooded, and it will most likely take a while until the new icons will be available

**Comment by msneujink** [comment]
it can wait, no problem

**Comment by hooman-pro** [comment]
what about now? Version 5.0.10 released

**Comment by hooman-pro** [comment]
Thank you @zTrap .
@mikepenz Do you have any plane for new version of fontaswome(5.0.10)?

**Comment by Mehran-tr** [comment]
The newest version is 5.0.13 !!
Is this library outdated?
When we can get new update?

**Comment by mikepenz** [comment]
I am super busy right now. instructions on how to create a icon pack are font addon are available :) Anybody who needs it can create them :)

**Comment by hooman-pro** [comment]
could you add newest fontawesome version? 5.5
