### ISSUE TITLE
Icon size and vertical alignment with fontawesome upgrade to 5.0.7.0 with { icon-definer } syntax

### ISSUE THREAD

**Issue by swafsarl** [mikepenz/Android-Iconics#378]
## About this issue

i have lot of vertical alignment issues and icon size (very huge) since my last upgrade fontawesome-typeface to 5.0.7.0
the 4.7.0.1 version was perfect, but lacking many icons

PS: this concern only { icon-definer } syntax.

## Details

using
 LayoutInflaterCompat.setFactory2(getLayoutInflater(), new IconicsLayoutInflater2(getDelegate()));

    // FontAwesome gradle
    compile "com.mikepenz:iconics-views:3.0.2@aar"
    compile "com.mikepenz:iconics-core:3.0.2@aar"
    //compile 'com.mikepenz:fontawesome-typeface:4.7.0.1@aar'
    implementation 'com.mikepenz:fontawesome-typeface:5.0.6.0@aar'

**Comment by mikepenz** [comment]
@swafsarl sadly font awesome changed the way the icon font is packed and created resulting in a different behaviour. 

I highly recommend to use the `IconicsDrawable` programatically and enable: https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L398

**Comment by swafsarl** [comment]
Thank you mike, do u advice me to use another font familly from the ones Iconics support? a font that won't have those problems (alignment and size) and have rich font library?
guess font awesome just lost a client :(

Btw, thank you for quick answer, in fact i have completed your library with some code that enable support of multilingual content from xml layout file with a simple use of the "android:tag" attribute and the "android:text" attribute. The script iterates through all views recursively and replaces the text attributes with the translated value according to the selected language. 
That being said, the final text content that populates the TextView (or button or whatever) comes from a server, and some times it contains {faw-user} or any other icon. 
Your library were perfect for my multilingual script and enabled my CMS to have icons support within text. Wich was great. My clients were very happy abt it.

We could talk if you wanna add some multilingual _content mangement features_ to your library
Take care

**Comment by mikepenz** [comment]
@swafsarl well fontawesome was not meant to be used in such a use case :D it is just a coincidence that font rendering can be used to support icons in android :) 
If you don't need any of the new icons you can easily stay with the old release of it ;)

Otherwise I always suggest to use the material icons :) 

Sounds interesting. 
You can by the way always use the `Iconics` class to restyle a specific `Spannable` with icons

**Comment by mikepenz** [comment]
Closing as the main concern was addressed. 

Thank you very much! :)
