### ISSUE TITLE
sizeDp() function does't work.

### ISSUE THREAD

**Issue by ice45571** [mikepenz/Android-Iconics#379]
```
var drawable = IconicsDrawable(this,Pixeden7Stroke.Icon.pe7_7s_add_user).sizeDp(5)
img.background = drawable
```
```
<ImageView
    android:id="@+id/img"
    android:layout_width="100dp"
    android:layout_height="100dp" />
```

it does't work for me. the img is so big that full the imageview

**Comment by mikepenz** [comment]
did you try different scale types on the `ImageView`? the `ImageView` usually tries to fill the available space

**Comment by ice45571** [comment]
I hava try it, but it can't effect the `ImageView` by  this way, so I decide
 use `TextView#setCompoundDrawables` instead of `ImageView` .

**Comment by mikepenz** [comment]
Ok :)

**Comment by curiousily** [comment]
For those who are struggling with this issue - set icon with `setImageDrawable` for ImageView, try using `respectFontBounds(true)` on `IconicsDrawable`.
