### ISSUE TITLE
Clarify icon's font creation process.

### ISSUE THREAD

**Issue by amatkivskiy** [mikepenz/Android-Iconics#38]
Hi, guys.
Recently I used Android-Iconics with my custom font with icons. I faced with the problem that there is lack of information how to generate custom icon font. Maybe it worth mentioning a few lines about this process in ```README.MD```.

**Comment by mikepenz** [comment]
@amatkivskiy you mean creating an addon for this library. The process is very easy. Just look at the source code. There are different add-on modules. In fact it is enough if you copy one of them, change the details and information to the new font, then you can use the js or the phyton script to generate the mapping :D. 

Ok it could be easier xD

**Comment by mikepenz** [comment]
There is already a section about this in the readme: https://github.com/mikepenz/Android-Iconics#contribute

**Comment by mikepenz** [comment]
I have added a new improved section here: 
https://github.com/mikepenz/Android-Iconics#create-custom-fonts-using-fontello-or-icomoon
