### ISSUE TITLE
Migration removed IconicsImageView.setIcon(String s)

### ISSUE THREAD

**Issue by csbenz** [mikepenz/Android-Iconics#383]
## About this issue

Before you could pass the icon id as String to the setIcon() method. 
Now it conly accepts IconicsDrawable.

**Comment by mikepenz** [comment]
and a `IconicsDrawable` can be created with a string :P

**Comment by csbenz** [comment]
It seems we are complicating the development of this library by adding not-so-useful changes at every update, without documenting them.
We now need a context to create an IconicsDrables. Also, the setColor() method doesn't exist anymore on IconicsImageView.

**Comment by mikepenz** [comment]
You can always stay with a old version if you prefered it's API. 

The IconicsDrawable has all the APIs which were available on the view. And if you have the view you have the context (view.getContext()) 

You can also just extend the view and add the shadow methods again if you really need them. 

The change was made to minimize method count.

**Comment by csbenz** [comment]
The issue is that all your libraries have to be updated to work together, MaterialDrawer, AboutLibraries, ... and create new problems. I try to follow the migration guides, but not everything is mentioned.
Trying to get the setColor() method to work.

**Comment by mikepenz** [comment]
I am sorry. Keeping things updated is a lot of work. I do that for free, in
my freetime, beside a full time job working 50+ hours.

If somebody will write the migration guides, or more detailed update notes,
I am more than happy to take any PR.

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L411



Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com

**Comment by csbenz** [comment]
Thanks for your hard work and awesome libraries. I know you like keeping the code very clean and sometimes that impedes on ease of use when everything changes.
I managed to migrate after modifying code in my app. 
Thanks!
