### ISSUE TITLE
Usage with app shortcuts

### ISSUE THREAD

**Issue by csaq7151** [mikepenz/Android-Iconics#388]
Hi mike, first of all I wanted to say thanks for all your great libraries.

Now the issue. Is there a way to use this library to set the Icons of the App Shortcuts introduced in API 25 ?? 

**ShortcutInfo.Builder setIcon (Icon icon)**

```
ShortcutInfo webShortcut = new ShortcutInfo.Builder(this, "shortcut_web")
                    .setShortLabel("website.com")
                    .setLongLabel("Open website.com web site")
                    .setIcon(ICON not WORKING)
                    .setIntent(new Intent(Intent.ACTION_VIEW, Uri.parse(url)))
                    .setRank(0)
                    .build();
```

This is what the documentation of the functions says. In my opinion its not possible. However it would be awesome so I thought I should ask before giving up on it.

```
Only icons created with createWithBitmap(Bitmap), createWithAdaptiveBitmap(Bitmap) and createWithResource(Context, int) are supported. Other types, such as URI-based icons, are not supported.
**Parameters**
icon Icon 
```

## Details
- [ 3.0.3] Used library version
- [27.1.1 ] Used support library version
- [ 3.1.2] Used gradle build tools version
- [ ] Used tooling / Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
App shortcuts only take resources / bitmaps if I am not wrong. 

This is not supported by the framework. 

IconicsDrawable are and will always be Drawables :) 

You have to convert it into a bitmap if you really want a bitmap
