### ISSUE TITLE
not in center

### ISSUE THREAD

**Issue by hooman-pro** [mikepenz/Android-Iconics#389]
in new version when use fontasome like this code:

<com.mikepenz.iconics.view.IconicsTextView
                                    android:id="@+id/record_icon"
                                    android:gravity="center"
                                    android:layout_marginLeft="10dp"
                                    android:text=" {faw-microphone} "
                                    android:textColor="#8a8a8a"
                                    android:textSize="16dp"
                                    android:layout_width="35dp"
                                    android:layout_height="35dp" />

when set a background color you can see the icon is not in center

**Comment by mikepenz** [comment]
if you want to have icons perfectly in the center and not follow the rules of a "font" then simply use the `IconicsDrawable` in a `ImageView` which looks like it would make much much more sense in your case.
