### ISSUE TITLE
EditextIcon Left Drawable in xml

### ISSUE THREAD

**Issue by hafiz013** [mikepenz/Android-Iconics#390]
Hi there, i am looking for custom library that can edit text icon ionicons without programmatically. thank you

**Comment by mikepenz** [comment]
Why not programmatically?

**Comment by hafiz013** [comment]
because i can easily view the icon in preview xml instead of programmatic.

**Comment by mikepenz** [comment]
Android-Iconcis does not render the icon in the preview either. The preview won't handle fonts. 

You will need to search for a different library as this project does not fit your requirement
