### ISSUE TITLE
IconicsMenuInflatUtil is not compatible with app bundles

### ISSUE THREAD

**Issue by rubengees** [mikepenz/Android-Iconics#391]
- Used library version: `3.0.3`
- Used support library version `27.1.1`
- Used gradle build tools version: `28-rc-2`
- Used tooling / Android Studio version: `3.2.0-alpha15`
- Other used libraries, potential conflicting libraries: Irrelevant

I just tried to build an [app bundle](https://developer.android.com/guide/app-bundle/) from my app and stumbled upon the attached crash. This seems to happen, because the tool repackages the resource to not be in the expected `@<idNumber>` format but to still contain the actual reference (in my case `@+id/filter`).

@MFlisar maybe you can take a look since you initially implemented this?
Thanks in advance!

Problematic item in my menu:

```xml
<item
    android:id="@+id/filter"
    android:title="@string/action_filter"
    app:ico_color="@android:color/white"
    app:ico_icon="cmd_filter_variant"
    app:ico_padding="2dp"
    app:ico_size="24dp"
    app:showAsAction="ifRoom">
```

Stacktrace:

```ruby
java.lang.NumberFormatException: For input string: "+id/filter"
        at java.lang.Integer.parseInt(Integer.java:608)
        at java.lang.Integer.parseInt(Integer.java:643)
        at com.mikepenz.iconics.IconicsMenuInflaterUtil.parseMenu(SourceFile:115)
        at com.mikepenz.iconics.IconicsMenuInflaterUtil.inflate(SourceFile:70)
        ...
```

**Comment by MFlisar** [comment]
you can try adjusting this line:

https://github.com/mikepenz/Android-Iconics/blob/bd96d8379fc696bc0bc37c8e14517a13d435735d/library-core/src/main/java/com/mikepenz/iconics/utils/IconicsMenuInflaterUtil.java#L115

Maybe to something like following:

    int id = Integer.parseInt(attrsMap.get("id").replace("@", "").replace("+", ""));

Just debug it and try yourself please, I actually can just guess and have never used the bundle feature yet...

Additionally following may help as well if the attribute map contains a string that is no integer:

    String name = attrsMap.get("id").replace("+id/", "");
    int id = context.getResources().getIdentifier(name, "id", context.getPackageName());
