### ISSUE TITLE
Allow spanned icons to be styled separately

### ISSUE THREAD

**Issue by tmm1** [mikepenz/Android-Iconics#396]
The ability to add icons via text (i.e. `{faw-android}`) is awesome, but since the spanned font inherits the style of the rest of the text it is quite hard to use in practice.

It would be nice to allow the user to use a separate theme or style for the icon so that it can be sized/colored separately from the normal text, making it much more practical to use this feature.

This SO comments lists three practical ways in which this can be implemented: https://stackoverflow.com/a/20861064/332798. `TextAppearanceSpan` is likely the best way for Iconics.

**Comment by mikepenz** [comment]
Using spannables to style the icons in some places is showcased in the sample app :)
