### ISSUE TITLE
Support for _outline  icons

### ISSUE THREAD

**Issue by FrankCharlz** [mikepenz/Android-Iconics#397]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Please follow the issue template

**Comment by mikepenz** [comment]
There is currently no plan to do so :) but you can always add your own icon fonts :) just check out the sample and the readme

**Comment by AllanWang** [comment]
Can we maybe open and look into this? New GM styles have all moved to outlined icons, so it would be nice if we can build a new font that has the same interface as the existing one, but with the outlines

**Comment by mikepenz** [comment]
@AllanWang google does not provide an icon font for the outlined version. so sadly not supported. 

But you could use the contour support of iconics to make outlined versions of the solid icons

**Comment by AllanWang** [comment]
There does seem to be a sizeable repo [here](https://material.io/resources/icons/?style=outline). It's missing a lot of common icons, but I will check to see if there are public versions available

**Comment by mikepenz** [comment]
Yeah but the github does not contain a icon font for the outline ones. perhaps you can do it all via creating a complete custom one based on the svg's but I am not sure
