### ISSUE TITLE
[Request] Make iicon parcelable

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/Android-Iconics#398]
This is just a suggestion, but if it isn't too hard, would it be okay to make IIcon parcelable? It's quite useful to have it in parcelable data models along with other strings and res values. I'm not sure how it would work to deserialize icons back given that they are all separate dependencies, but you may have more ideas than I do.

**Comment by mikepenz** [comment]
Happy to accept a PR for that :D

**Comment by AllanWang** [comment]
I can take a look after my internship (around September).

Do you have any ideas for this though? Going from Parcelable to the actual icon seems to be only possible through reflection, since the icon collections are separate dependencies

**Comment by mikepenz** [comment]
Hmmm I have not had a lot of time to think about it. never faced a case where I would have needed it. 

Theoretically you can use the identifier for the icon set, and the string name of the icon and you can retrieve it later again from the enum using that name. 

Closing this issue though :) Letting it up to you if you'd like to open a PR at some point. 

Thanks a lot for your input!
