### ISSUE TITLE
(Request) IconicsRadioButton

### ISSUE THREAD

**Issue by mree58** [mikepenz/Android-Iconics#399]
## About this issue
Thanks for this great library. I used it in my project but I'm having an issue that I could not solve yet.

The project I am working on have multi language support. I have to use custom ContextWrapper to be able to support multi language since Android 7.0. So I could not enable the library with "Inject into Context" method. 

I have radio buttons inside a radio group, some of the buttons can be disabled depends on the settings. With IconicsContextWrapper I can use e.g., "{faw-asterisk} All", "{faw-ban} All" strings as a radio button's text. But I have to use my own ContextWrapper. Can you support also Iconics for RadioButton or how can I solve this ? 

Thanks.

## Details
- [3.0.4] Used library version
- [27.1.1] Used support library version
- [3.1.3] Used gradle build tools version
- [3.1.3] Used tooling / Android Studio version

## Checklist

- [+] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [+] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [+] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [+] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [+] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [+] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@mree58 I would recommend you simply extend the RadioButton in your project and do something like we do in the button included: 

https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-view-library/src/main/java/com/mikepenz/iconics/view/IconicsButton.java#L142

**Comment by mree58** [comment]
Thanks. The library has limitations that I could not extend or implement needed constructors/functions. But It worked with this : 

`radioButton.setText(new Iconics.IconicsBuilder().ctx(getContext()).on(getString(R.string.all_disabled)).build());
`

**Comment by mikepenz** [comment]
Great :)
