### ISSUE TITLE
use iconics with data binding

### ISSUE THREAD

**Issue by anggap** [mikepenz/Android-Iconics#401]
use iconics with data binding 

`<ImageView
                    android:layout_width="18dp"
                    android:layout_height="18dp"
                    app:ico_icon="@{ viewModel.isAlarm ? @string/gmd_alarm_on : @string/gmd_alarm_off }"
                    app:ico_color="@{ viewModel.isAlarm ? @color/icon_light : @color/icon_dark }"/>`

Error
****/ data binding error ****msg:Cannot find the setter for attribute 'app:ico_icon' with parameter type java.lang.String on android.widget.ImageView.

****/ data binding error ****msg:Cannot find the setter for attribute 'app:ico_color' with parameter type java.lang.integer on android.widget.ImageView.

**Comment by mikepenz** [comment]
An ImageView does not have these attributes, they should only be available on an `IconicsImageView`
