### ISSUE TITLE
Cannot get implementation to work

### ISSUE THREAD

**Issue by matt-matt1** [mikepenz/Android-Iconics#403]
In the build.gradle (app), I added imp...-core:3.0.0 (the latest [3.1.0-rc01] complained about appcompat... tried many version numbers...)
Synced fine.  When I add imp...views:3.0.0 and try sync, it says "Failed to resolve: com.mikepenz:library-core:2.9.3"
(Added imp...fontawesome...  That line caused no problems.)

## Details
new project (clean I believe) Android Studio 3.1.4
compileSdkVersion 28
targetSdkVersion 28
using kotlin

**Comment by mikepenz** [comment]
@matt-matt1 please see the changelog. v3.1.0-rc01 upgrades to androidX and does no longer depend on the appcompat libs.

**Comment by matt-matt1** [comment]
Where can I see the changelog?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/releases

**Comment by matt-matt1** [comment]
Thanks for the link.  But that doesn't explain how I can use the icons.
Should I use an old version?  Is kotlin a problem?  Is kotlin androidX?

**Comment by mikepenz** [comment]
You should be able to use v3.0.4 normally. 

Do you have maven central as repository in your project?

https://repo1.maven.org/maven2/com/mikepenz/iconics-core/3.0.4/

**Comment by mikepenz** [comment]
e.g.:

```
repositories {
        google()
        jcenter()
        mavenCentral()
    }
```
