### ISSUE TITLE
CommunityMaterial Update

### ISSUE THREAD

**Issue by chrisonline** [mikepenz/Android-Iconics#404]
Can you please update the "com.mikepenz:community-material-typeface:2.0.46.1@aar" to the latest icons?
Some icons are missing.

Thanks!

**Comment by mikepenz** [comment]
the readme contains docs on how to do a create a font extension, there are prs from the past. This can be used to update a font too. 

I am happy to see a PR providing an update :). in most cases the new icons are just minor so updates are not done frequently as it costs some time. 

It might take a few weeks until I will have time to update again :) 

Thanks for the understanding.

**Comment by mikepenz** [comment]
update released
