### ISSUE TITLE
fontawesome new versions

### ISSUE THREAD

**Issue by hooman-pro** [mikepenz/Android-Iconics#405]
fontawesome new versions 5.1 and 5.2.0! have you plane for these new versions?

**Comment by mikepenz** [comment]
the readme contains docs on how to do a create a font extension, there are prs from the past. This can be used to update a font too. 

I am happy to see a PR providing an update :). in most cases the new icons are just minor so updates are not done frequently as it costs some time. 

It might take a few weeks until I will have time to update again :) 

Thanks for the understanding.

**Comment by mikepenz** [comment]
update released
