### ISSUE TITLE
Creating an `android.graphics.drawable.Icon` from Iconics seems to be clunky

### ISSUE THREAD

**Issue by oliverlockwood** [mikepenz/Android-Iconics#406]
There doesn't seem to be any way to set a notification icon (large or small) directly from a `Drawable`.

As far as I can tell, it's possible to create an `android.graphics.drawable.Icon` from Iconics in the following way:
>```Icon.createWithBitmap(IconicsDrawable(context).icon(GoogleMaterial.Icon.gmd_directions_bike).sizeDp(24).toBitmap())```

Compared to `Icon.createWithResource(context, R.drawable.directions_bike)`, this is pretty clunky.  I'd like to think it would be possible to (at worst)! do something like:
>```IconicsDrawable(context).icon(GoogleMaterial.Icon.gmd_directions_bike).toDrawableIcon()```

without having to specify the size.

Would you agree?  If so, would you consider a PR to add the suggested implementation, or would you want to do it in a different way?

**Comment by mikepenz** [comment]
I am not so sure where there's a problem. 

```java
IconicsDrawable(context)
   .icon(GoogleMaterial.Icon.gmd_directions_bike)
   .sizeDp(24)
   .toBitmap()
```

Is a super simple notation and will directly give you a bitmap of a size in 24dp. 

Adding an extra method `toDrawableIcon()` just to combine `.sizeDp(24).toBitmap()` does not seem to make any big difference.

**Comment by zTrap** [comment]
Actually method-converter to `android.graphics.drawable.Icon` from IconicsDrawable (skip steps `toBitmap()`, `Icon.createWithBitmap()`) seems pretty good and useful. Like this: 
```
IconicsDrawable(context)
   .icon(GoogleMaterial.Icon.gmd_directions_bike)
   .sizeDp(24)
   .toAndroidIcon()
```

**Comment by zTrap** [comment]
I can provide PR, if it is needed

**Comment by zTrap** [comment]
@mikepenz or if, you wont to add this in main `core`-lib, I can include it in extensions library only for kotlin

**Comment by zTrap** [comment]
@oliverlockwood FYI I've been add this to [extensions-lib](https://github.com/zTrap/Android-Iconics-Kt). If your project based on kotlin, you can use it

**Comment by oliverlockwood** [comment]
@zTrap My project is partially Kotlin-based (we're gradually migrating it).  The relevant source file is in Kotlin, and I'm trying to call your new `.toAndroidIcon()` on an `IconicsDrawable` with the dependency  `api 'ru.ztrap.iconics:core-kt:1.0.2'` configured in Gradle.

Unfortunately the compile spits out:
>Unresolved reference: toAndroidIcon

Am I missing something obvious?

**Comment by zTrap** [comment]
@oliverlockwood actual signature of this method is `toAndroidIconCompat` for guarantee more compatibility

**Comment by mikepenz** [comment]
Thank you both so much!
