### ISSUE TITLE
How to use 'Android-Iconics' for FloatingActionButton

### ISSUE THREAD

**Issue by lixianyu** [mikepenz/Android-Iconics#408]
### How to use 'Android-Iconics' for FloatingActionButton ?

Thank you very much!

**Comment by mikepenz** [comment]
if a `FloatingActionButton` extends `TextView` the usual approach via the inflator works: https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional

Ohterwise the programatical approach by setting it as drawable via `IconicsDrawable` is the easiest :)
