### ISSUE TITLE
Could not get unknown property 'androidXVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by holoto** [mikepenz/Android-Iconics#410]
`  implementation "com.mikepenz:iconics-core:3.1.0-rc01"
    implementation "androidx.appcompat:appcompat:${androidXVersion}"

    implementation 'com.mikepenz:google-material-typeface:3.0.1.3.original@aar  '
    implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.5@aar'
    implementation 'com.mikepenz:fontawesome-typeface:5.3.1.1@aar'
    implementation 'com.mikepenz:octicons-typeface:3.2.0.5@aar'
    implementation 'com.mikepenz:meteocons-typeface:1.1.0.5@aar'
    implementation 'com.mikepenz:community-material-typeface:2.7.94.1@aar'
    implementation 'com.mikepenz:weather-icons-typeface:2.0.10.5@aar'
    implementation 'com.mikepenz:typeicons-typeface:2.0.7.5@aar'
    implementation 'com.mikepenz:entypo-typeface:1.0.0.5@aar'
    implementation 'com.mikepenz:devicon-typeface:2.0.0.5@aar'
    implementation 'com.mikepenz:foundation-icons-typeface:3.0.0.5@aar'
    implementation 'com.mikepenz:ionicons-typeface:2.0.1.5@aar'
    implementation 'com.mikepenz:pixeden-7-stroke-typeface:1.2.0.3@aar'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.6.1'
    releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.6.1'
`

**Comment by mikepenz** [comment]
Replace the placeholder with the actual `androidXVersion` you want to use :) 

Like 1.0.0 or 1.0.0-rc02, ... 

https://github.com/mikepenz/Android-Iconics/blob/develop/build.gradle#L1

**Comment by holoto** [comment]
ths

**Comment by mikepenz** [comment]
give me a bit to wrap up the final release :)
will be the stable release now with the androidX deps being stable too

**Comment by mikepenz** [comment]
(oops sorry. mixed the issue up with a different one :D) 

glad it helped
