### ISSUE TITLE
setColor() in IconicsImageView not found

### ISSUE THREAD

**Issue by fmeneuhe** [mikepenz/Android-Iconics#413]
Hi,
I have update the Iconics library to 2.9.5, and support library to 27.1.1.
Now with this code:

`IconicsImageView selected_icon = (IconicsImageView) getView().findViewById(R.id.selected_icon);
 selected_icon.setColor(mColor);`

I get this error:
"error: cannot find symbol method setColor(int)"

Anything has changed or I am doing something wrong?
Thanks

**Comment by mikepenz** [comment]
This was changed. 

Please simply retrieve the drawable via `getIcon()` and then apply the color on it. 

The delegate methods were removed to minimize the count of methods in the library

**Comment by fmeneuhe** [comment]
Do you mean this right?:
`selected_icon.getIcon().color(mColor);`

Thanks!
