### ISSUE TITLE
Wrong font id

### ISSUE THREAD

**Issue by ShshyDevooo** [mikepenz/Android-Iconics#416]
When i am using this library ,it doesn't work for me.
The logcat showed " Wrong fontId: gmd_message" ,but the fontid is correct! I can find it in the demo.
How can i solve this problem?
Library version:
                       "com.mikepenz:iconics-core:3.0.4@aar",
                        "com.mikepenz:google-material-typeface:3.0.1.2.original@aar",
SupportLibraryVersion:
26.0.0-alpha1

![qq 20181109140049](https://user-images.githubusercontent.com/9620338/48246023-ad2c8180-e428-11e8-8949-8fe347e5853c.png)

**Comment by zTrap** [comment]
Did you initialize `Iconics` in your `Application.onCreate()`?

**Comment by ShshyDevooo** [comment]
> Did you initialize `Iconics` in your `Application.onCreate()`?
No,the api doc doesn't menthion that.I follow the api doc steps.
Should i initialize the library in the Application.onCreate()? And how to initialize?

**Comment by ShshyDevooo** [comment]
> Did you initialize `Iconics` in your `Application.onCreate()`?

No,the api doc doesn't menthion that.I follow the api doc steps.
Should i initialize the library in the Application.onCreate()? And how to initialize?

**Comment by mikepenz** [comment]
If you use proguard: https://github.com/mikepenz/Android-Iconics#proguard 

If auto detection does not work try it like this:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17

**Comment by mikepenz** [comment]
Please report back. close for the time being.
