### ISSUE TITLE
Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by AxelCC** [mikepenz/Android-Iconics#419]
I've tried to use Iconics on my app by Context injection but when I run the app I get this error: 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference

I tried to fix it by replacing newBase with getApplicationContext() but did not work

**Comment by zTrap** [comment]
Your provided `context` is `null`, it’s not a Iconics bug. Try to check and resolve this

**Comment by AxelCC** [comment]
I try but I dont know where is the error

@Override
	protected void attachBaseContext(Context newBase)
	{
		// TODO: Implement this method
		super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
	}

The method is the same as readme.md

**Comment by mikepenz** [comment]
@AxelCC please post the full stacktrace. But I am 99% sure that the `Iconics` line is just in the middle somewhere, due to it being in the call chain. Which is normal for the attachBaseContext method.

**Comment by mikepenz** [comment]
Please report back

**Comment by AxelCC** [comment]
The problem is fixed, I had to rebuild my project and download gradle again
I dont know why I get this error but I think because I have other libraries that could interfere with Iconics

**Comment by mikepenz** [comment]
As mentioned above I don't think anything interferes with Iconics. It's just part of the stacktrace as the "exception" is thrown "up" as such iconics is in the stacktrace due to the context wrapping. but the actual exception is something else
