### ISSUE TITLE
IconicsButton with AppcompatButton Style ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/Android-Iconics#42]
hey mike, I wonder why the buttons appear with the old theme rather than to the material style.

I have all my application buttons with material theme, and this buttons appear ugly with old theme.

**Comment by mikepenz** [comment]
@seba123neo i assume this happenes because the appcompat lib will style all default buttons but not buttons with a different package name. i think you will have to extend the AppCompatButton to have the same behavior
