### ISSUE TITLE
Could you import eva icons?

### ISSUE THREAD

**Issue by mcauto** [mikepenz/Android-Iconics#420]
https://akveo.github.io/eva-icons/#/?type=outline

**Comment by mikepenz** [comment]
You can read up here: https://github.com/mikepenz/Android-Iconics#create-custom-fonts
And create your own module with icons

**Comment by mikepenz** [comment]
We are also happy to take PRs if you like to :)

**Comment by mikepenz** [comment]
Close as there are no plans to add this icon font directly. A PR would still be highly appreciated though
