### ISSUE TITLE
Can I set disabled IconicsButton color? 

### ISSUE THREAD

**Issue by ocsike** [mikepenz/Android-Iconics#421]

**Comment by zTrap** [comment]
At this time You can set stateful color only for icon, but from next version You will can set it to all icon's components (contour, background and background contour). For make stateful colors list (`StateListColor`) You must do something like this:
 - via xml:
  https://developer.android.com/guide/topics/resources/color-list-resource
 - via code:
  https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/utils/Utils.java#L29

**Comment by zTrap** [comment]
When @Mikepenz will have free time for review this #417 and make new release 😄

**Comment by mikepenz** [comment]
I released a rc release with the changes by the awesome @zTrap here: https://github.com/mikepenz/Android-Iconics/releases/tag/v3.2.0-rc1
