### ISSUE TITLE
new version of fontawesome

### ISSUE THREAD

**Issue by hooman-pro** [mikepenz/Android-Iconics#422]
Hi I realty need new version fo font asome in my android project
so I want to ask you when could you release new font asome version 5.6?

**Comment by mikepenz** [comment]
The instructions on how to create a icon font are in the README. I am happy to take a PR to update to new versions :)

**Comment by hooman-pro** [comment]
I tried but it was not successful.

**Comment by mikepenz** [comment]
@sdabhi23 the namings of the icons are the same we got from the font. there is not much which can be done about that.

**Comment by hooman-pro** [comment]
@mikepenz 
thank u for update
