### ISSUE TITLE
IconicsCheckBox state color not working

### ISSUE THREAD

**Issue by farfromrefug** [mikepenz/Android-Iconics#426]
I tried to use the new state color feature from 3.2.0-rc1 with ```IconicsCheckBox``` but i only get black icon.

Is it not supposed to work with ```IconicsCheckBox```? 
Is there another way to set disabled color?

Thanks

**Comment by zTrap** [comment]
Yes, I noticed of this problem. Its actual not only for checkboxes, its a bug and work to fix it in-progress

**Comment by zTrap** [comment]
Fixed in #428
