### ISSUE TITLE
BottomNavigationView icon tinting broken in 3.2.0

### ISSUE THREAD

**Issue by m-rm** [mikepenz/Android-Iconics#429]
## About this issue

- When updating com.mikepenz:iconics-core from 3.1.0 to 3.2.0 the icon color is not updated anymore for the selected item in a BottomNavigationView.

Before:
![device-2019-02-05-170102](https://user-images.githubusercontent.com/7124804/52286426-7b17b680-2968-11e9-8bcc-f7fad8584dca.png)

After:
![device-2019-02-05-170240](https://user-images.githubusercontent.com/7124804/52286439-836ff180-2968-11e9-9cb2-324eb4557446.png)

res/layout/activity_main.xml (only relevant code)
```xml
<com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/navigation"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_marginStart="0dp"
    android:layout_marginEnd="0dp"
    android:background="?android:attr/windowBackground"
    app:itemIconTint="@color/main_menu_items"
    app:itemTextColor="@color/main_menu_items"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintLeft_toLeftOf="parent"
    app:layout_constraintRight_toRightOf="parent"
    app:menu="@menu/navigation" />
```

res/color/main_menu_items.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true" android:color="@color/green" />
    <item android:color="@color/grey"  />
</selector>
```

MainActivity.kt (only relevant code)
```kotlin
// Create icons for navigation
val planningIcon = IconicsDrawable(this).icon(CommunityMaterial.Icon2.cmd_history)
val homeIcon = IconicsDrawable(this).icon(CommunityMaterial.Icon2.cmd_home)
val calendarIcon = IconicsDrawable(this).icon(CommunityMaterial.Icon.cmd_calendar)

// Set icons
val menu = navigation.menu
menu.findItem(R.id.menu_nav_planning).icon = planningIcon
menu.findItem(R.id.menu_nav_home).icon = homeIcon
menu.findItem(R.id.menu_nav_calendar).icon = calendarIcon
```

## Details
- Used library version: iconics-core 3.2.0, iconics-views 3.2.0
- Used support library version: Appcompat 1.0.2
- Used gradle build tools version: 3.3.0
- Used tooling / Android Studio version: 3.3

**Comment by mikepenz** [comment]
Theoretically the tint should be set correctly:
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/BottomNavigationItemView.java#L292

I suppose it has something to do with this PR:
https://github.com/mikepenz/Android-Iconics/pull/417

Even though the tintList does not change: https://github.com/mikepenz/Android-Iconics/pull/417/files#diff-6dd39d3e1d57d5981614d1655a09362aR1228

**Comment by mikepenz** [comment]
Do you set a tintList to the bottom navigation view, or just a single color?

**Comment by m-rm** [comment]
I created a demo app that shows the issue. If you edit app/build.gradle and change the version to 3.1.0 it works fine.

[MyApplication.zip](https://github.com/mikepenz/Android-Iconics/files/2833057/MyApplication.zip)

**Comment by zTrap** [comment]
Fixed in #430

**Comment by zTrap** [comment]
Also You can set all icons automatically via

```
Menu menu2 = ((BottomNavigationView) findViewById(R.id.navigation_auto)).getMenu();
IconicsMenuInflaterUtil.parseXmlAndSetIconicsDrawables(this, R.menu.menu_playground, menu2);
```

**Comment by m-rm** [comment]
Thanks for the fix! I will try your suggestion when there is a new release.
