### ISSUE TITLE
IconicsButton not display the icon in Lollipop

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/Android-Iconics#43]
I'm using the Navigation Drawer with the icons of the font (google material), and works perfect in all devices (API 10, Lollipop and others).

I'm also using the IconicsImageView and also works well in all devices.

But the IconicsButton don't show the icon in Lollipop (in the others devices works perfect), a cross appears like a "Chinese icon"...

**Comment by amatkivskiy** [comment]
@seba123neo Maybe there is problem with loading Typeface for font?

**Comment by seba123neo** [comment]
the icon is the "{gmd-delete}" but none works on buttons...but the SAME icon work well in the 
ImageView. 

only in lollipop in the others versions works well...

![20150630_155437](https://cloud.githubusercontent.com/assets/9873666/8439200/cacf9bd8-1f40-11e5-8446-6bb566fdfae0.jpg)

**Comment by mikepenz** [comment]
@seba123neo i try to reproduce it. but i think there are other problems which cause this. a simple fix would be that you just create an ImageButton here, and set the icon as Drawable

**Comment by mikepenz** [comment]
@seba123neo do you use the IconicsButton here? this one should work :/. it's working on my device. at least. Perhaps it gets replaced by the AppCompatButton? can you try to extend this one and add it into your project?

**Comment by seba123neo** [comment]
@mikepenz yes, i use the IconicsButton, here is a capture of the layout file (is a simple row in the listview), in my samsung galaxy s3 with android 4.3, works perfect.

![screenshot_2015-06-30-17-10-20](https://cloud.githubusercontent.com/assets/9873666/8440851/527c60e8-1f4b-11e5-879f-5d95b894c44a.png)

and the layout file:

![sin titulo](https://cloud.githubusercontent.com/assets/9873666/8440882/85f11c84-1f4b-11e5-98ff-1f57d25c0ecb.png)

**Comment by mikepenz** [comment]
You have to add
```xml
android:textAllCaps="false"
```

to your button
