### ISSUE TITLE
Unclear readme

### ISSUE THREAD

**Issue by edvaldeysteinsson** [mikepenz/Android-Iconics#432]
Hi

I'm not sure if this is working as intended but if it is this might be something that might need to be clarified in the readme.

`IconicsDrawable(ctx, "faw-adjust")` doesn't work unless you register the font by calling this `Iconics.registerFont(FontAwesome())` but `IconicsDrawable(ctx, FontAwesome.Icon.faw_adjust)` works fine without it.

**Comment by mikepenz** [comment]
`IconicsDrawable(ctx, "faw-adjust")` would also work if the auto font detection worked for a specific font addon. 

the proper approach to create an icon via code would be in general to go via the `Icon` though. 

But you are right that this would be good to be mentioned. 
Right now the registerFont is only mentioned for custom fonts in the advanced usage section, or showcased in the sample code.

That might be something for the upcoming version which is a huge refactor to kotlin and some other changes.

**Comment by mikepenz** [comment]
Happy to take a PR to improve docs ;)
