### ISSUE TITLE
Hello, the typeicons-typeface lib is not available. I cannot use the icon string resource in typeicons-typeface lib. But other lib is ok.

### ISSUE THREAD

**Issue by 2193531059** [mikepenz/Android-Iconics#437]
compile 'com.mikepenz:iconics-core:2.8.2@aar'
    compile 'com.mikepenz:materialdrawer:5.8.2'
    compile 'com.mikepenz:fontawesome-typeface:4.7.0.0@aar'
    compile 'com.mikepenz:google-material-typeface:3.0.1.0.original@aar'
    compile 'com.mikepenz:community-material-typeface:2.0.46.1@aar'

    compile 'com.mikepenz:typeicons-typeface:2.0.7.5@aar'

**Comment by mikepenz** [comment]
Hmmm as far as I can see the font is available on jcenter:
https://bintray.com/mikepenz/maven/com.mikepenz%3Atypeicons-typeface/2.0.7.5

Do you have `jCenter` in the list of repos?

**Comment by 2193531059** [comment]
Yes, I have jCenter in my repos, I'm going to study your demo and learn how it works.

**Comment by mikepenz** [comment]
I wonder. So resolving the artifact works? But only using icons of it then does not work? 

Can you try to `register` that font (replace with that font class): 
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17

**Comment by 2193531059** [comment]
I've already tried to register the font, and it's no use.

**Comment by mikepenz** [comment]
Have you figured anything out? There is no real reason why this particular font might fail :/

**Comment by mikepenz** [comment]
released v4 now. I hope this issue is resolved for you
