### ISSUE TITLE
Inflation error when using IconicsImageView

### ISSUE THREAD

**Issue by excaliburthesword** [mikepenz/Android-Iconics#441]
Hi mike.
Thank you for your hard work on this library
I recently updated from 3.1.0 to 3.2.2 and i get the following error when using IconicsImageView in XML.
I also tried the kotlin version. but the result was the same

The sample code that rises the error:
```
<com.mikepenz.iconics.view.IconicsImageView
android:layout_width="32dp"
android:layout_height="32dp"
app:iiv_icon="ion_ios_plus_empty" />
```

The related error:
```
Caused by: java.lang.IncompatibleClassChangeError: com.mikepenz.iconics.internal.IconicsViewsAttrsApplier
        at com.mikepenz.iconics.view.IconicsImageView.applyAttr(IconicsImageView.java:59)
        at com.mikepenz.iconics.view.IconicsImageView.initialize(IconicsImageView.java:53)
        at com.mikepenz.iconics.view.IconicsImageView.<init>(IconicsImageView.java:43)
        at com.mikepenz.iconics.view.IconicsImageView.<init>(IconicsImageView.java:37)
```

because of the error **"More than one file was found with OS independent path 'META-INF/library-core_release.kotlin_module'"** i added the following code to the build.gradle
```
packagingOptions {
       exclude 'META-INF/library-core_release.kotlin_module'
}
```

**Comment by mikepenz** [comment]
https://stackoverflow.com/a/1980474/325479 

Hmmm do you by any chance have multiple different versions of the library in your project?

can you check that you only use one version? 


Yeah that kotlin meta file conflict is android tooling, as far as I know they are working to handle that in the tooling in one of the next updates.

**Comment by excaliburthesword** [comment]
Thank you for reply.
As i am using this library inside one of my core libraries as 'api', Yes. i am using only the latest version. no other old versions exists in project.
as i am not with my laptop now, i will check if removing app:iiv_icon="ion_ios_plus_empty" have any effect or not, in some hours.

**Comment by excaliburthesword** [comment]
After checking the codes i found that i am also using the Material Drawer that uses library-core 3.1.0 as api.
so the following arrangement works in my library:
```
api 'com.mikepenz:iconics-core:3.1.0'
api 'com.mikepenz:iconics-views:3.1.0'
api 'com.mikepenz:materialdrawer:6.1.2'
```
but this fails:
```
api 'com.mikepenz:iconics-core:3.2.2'
api 'com.mikepenz:iconics-views:3.2.2'
api 'com.mikepenz:materialdrawer:6.1.2'
```

**Comment by mikepenz** [comment]
yeah. never use multiple versions of any library. that just causes problems 

Consider to enforce a specific version (as long as the API itself stays compatible) the MaterialDrawer will also still work.

E.g. specify the version for a specific dependency: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L89
