### ISSUE TITLE
Black icons with alpha remain black

### ISSUE THREAD

**Issue by rubengees** [mikepenz/Android-Iconics#442]
## About this issue

After upgrading from `3.1.0` to `3.2.2`, black icons with alpha remain completly black.
I reproduced this in the sample (On Android 9.0), when changing this line:

https://github.com/mikepenz/Android-Iconics/blob/29e13749350d6a44050ceedcebfdb8199fa67ca2/app/src/main/java/com/mikepenz/iconics/sample/item/IconItem.java#L52

to:

```java
holder.image.getIcon().color(Color.parseColor("#77000000"));
```

| `3.1.0` | `3.2.2` |
| ------- | ------- |
| ![3 1 0](https://user-images.githubusercontent.com/8021265/54859505-42605080-4d0e-11e9-9e70-541ec73f8ff1.png) | ![3 2 2](https://user-images.githubusercontent.com/8021265/54859507-468c6e00-4d0e-11e9-9d0d-013aba706cb3.png)

I also quickly checked the latest alpha and were able to produce similar results.

## Details

- Used library version: `3.2.2`
- Used support library version: `appcompat 1.0.2`
- Used gradle build tools version: `3.3.2`
- Used tooling / Android Studio version: `3.5 Canary 7`

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by zTrap** [comment]
Fixed in #443

**Comment by marbat87** [comment]
Could you fix this in 4.0.0-b1 version also?

Thanks in advance

**Comment by mikepenz** [comment]
Fixed in v3.2.3 

@marbat87 we will fix this in an upcoming update to the v4.x version too.

**Comment by rubengees** [comment]
@zTrap @mikepenz I tried the latest version, but am still able to reproduce that in some places in my app.

One place in the sample (current `develop` branch) is the drawer:

In previous versions (like `3.1.0`) the icons were gray by default. Now they are black. Setting `withIconColor(Color.parseColor("#77000000"))` for example here:

https://github.com/mikepenz/Android-Iconics/blob/959a567a2b838146f5038253722b83ed979aadc4/app/src/main/java/com/mikepenz/iconics/sample/MainActivity.java#L89

has no effect.

Another place is when setting a compound drawable on any `TextView`:

```java
final Drawable compoundDrawable = new IconicsDrawable(this)
        .icon(FontAwesome.Icon.faw_android)
        .sizeDp(24)
        .color(Color.parseColor("#77000000"));

textView.setCompoundDrawablesWithIntrinsicBounds(compoundDrawable, null, null, null);
```

I tried that in the sample in the `PlaygroundActivity` and also got entirely black icons.

**Comment by mikepenz** [comment]
@rubengees sorry for the delay. Fixed this bug too

**Comment by rubengees** [comment]
No problem, works great, thanks! 🙂
