### ISSUE TITLE
Make variable `TAG` private

### ISSUE THREAD

**Issue by mueller-ma** [mikepenz/Android-Iconics#448]
## About this issue

It's a quite common practice to use `static final String TAG` as tag for Android log calls. Whenever I use `TAG` in a class where I haven't defined it before, Android Studio wants to import `com.mikepenz.iconics#TAG` (https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L47). Can you make it private, so AS doesn't want to use always your TAG?

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by zTrap** [comment]
In version 4 this field is marked as `internal` and wouldn’t be visible outside of module. Stay tuned for release
