### ISSUE TITLE
Execution failed for task ':app:mergeExtDexDebug'.

### ISSUE THREAD

**Issue by ibrahimbroachwala** [mikepenz/Android-Iconics#452]
Getting this error while building.

Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'iconics-core.aar (com.mikepenz:iconics-core:3.2.5)' to match attributes {artifactType=android-dex, dexing-is-debuggable=true, dexing-min-sdk=21}
      > Execution failed for DexingTransform: /Users/apple/.gradle/caches/transforms-2/files-2.1/d5a9e46b08fc3a87a4eb4c070e854658/jars/classes.jar.
         > Error while dexing.

**Comment by ibrahimbroachwala** [comment]
Some more error info:

AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): void com.mikepenz.iconics.animation.IconicsAnimationListener.onAnimationCancel(com.mikepenz.iconics.animation.IconicsAnimationProcessor)","sources":[{}],"tool":"D8"}

**Comment by mikepenz** [comment]
@ibrahimbroachwala this version requires Java8 support:

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/build.gradle#L26

**Comment by ibrahimbroachwala** [comment]
Thanks a lot. It worked :D

**Comment by gauravsngarg** [comment]
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

**Comment by chrisoemma** [comment]
Hi I solved the same issue  by setting  **multiDexEnabled true** in /android/app/build.gradle

like:

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "xxxxx"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true //add this line
    }

}

**Comment by itzpradip** [comment]
@chrisoemma Thanks bro, you're a true life savior.

**Comment by Shalabyer** [comment]
@chrisoemma Thanks man, it did work .

**Comment by Ramanpreet6532** [comment]
@chrisoemma i tried above solution but it doesn't work... is there any alternative for this

**Comment by Bruno-hub19** [comment]
@chrisoemma Thanks bro, success.

**Comment by magic990619** [comment]
Success.

**Comment by samanrana** [comment]
great

**Comment by pgThiago** [comment]
> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }

why it fixed the problem? anyone knows?

**Comment by harrykalsi9899** [comment]
> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }



> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }

tysm bro

**Comment by azharcool** [comment]
thank u...

**Comment by vimalswaroopj** [comment]
If you are installing via USB be sure to click on install button when the device asks for permission, It was the solution in my case.

**Comment by fredybangs** [comment]
> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }

Thank you very much... Worked

**Comment by arslan-prism** [comment]
> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }

Perfect. Worked for me as well. Thanks man.

**Comment by douglas-bernardo** [comment]
> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }

Thank you very much... Worked

**Comment by dorianmariefr** [comment]
in my case, this fixed the error: https://github.com/facebook/react-native/issues/28954#issuecomment-632967679

> Solved this issue by deleting the .gradle folder from <NameOfProject>/android and again run npm run android, and it solved this error.

**Comment by Piyush132000** [comment]
> Hi I solved the same issue by setting **multiDexEnabled true** in /android/app/build.gradle
> 
> like:
> 
> android {
> compileSdkVersion rootProject.ext.compileSdkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> 
> defaultConfig {
>     applicationId "xxxxx"
>     minSdkVersion rootProject.ext.minSdkVersion
>     targetSdkVersion rootProject.ext.targetSdkVersion
>     versionCode 1
>     versionName "1.0"
>     multiDexEnabled true //add this line
> }
> ```
> 
> }

Why we are adding this line please ca you give small answer ?

**Comment by mikepenz** [comment]
https://developer.android.com/studio/build/multidex

**Comment by student1060632fpt** [comment]
> @ibrahimbroachwala this version requires Java8 support:
> 
> https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/build.gradle#L26

I don't want to thumb down your comment but your link now is cannot access anymore

**Comment by mikepenz** [comment]
@student1060632fpt https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-core/build.gradle#L48-L55

**Comment by ummartoor** [comment]
i have tried everything still the same error **Task :app:mergeLibDexDebug FAILED** this is error i am getting when trying to run 
npx react-native run-android

**Comment by AlessioCamm** [comment]
Thank you so much @chrisoemma
