### ISSUE TITLE
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6

### ISSUE THREAD

**Issue by colinrtwhite** [mikepenz/Android-Iconics#454]
## About this issue

`4.0.0-rc02` is being shipped with Kotlin code that requires Java 1.8. This causes the following compiler error:

```
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6
```

I believe upgrading to Kotlin 1.3.31 should fix the issue.

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
You can overwrite the dependency version you use by defining a resolution strategy for your dependencies. So you might try to use kotlin 1.3.31.

Also you have enabled java 1.8 for your project?

**Comment by colinrtwhite** [comment]
Yep, I have:

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

However, I also have:

```
kotlinOptions {
    jvmTarget = "1.6"
}
```

as the Kotlin compiler can generate Java code which can't be desugared by D8.

`4.0.0-rc02` currently has its Kotlin `jvmTarget="1.8"`. I think setting `jvmTarget="1.6"` in the library's Gradle file would fix the issue.

**Comment by zTrap** [comment]
@colinrtwhite strange what you use kotlin 1.6 if you use java target and sources 1.8

read this [post](https://twitter.com/jakewharton/status/1107684548140322816?s=12) for explanations

**Comment by colinrtwhite** [comment]
@zTrap Setting `kotlinOptions.jvmTarget` to 1.8 causes the Kotlin compiler to generate code that uses Java 8 APIs that cannot be desugared. See [here](https://stackoverflow.com/questions/55708793/switch-to-kotlin-1-3-30-breaks-hashcode-only-on-android-api-21).

**Comment by rubengees** [comment]
@colinrtwhite You can use the latest R8, which is able to desugar all relevant Java 8 APIs that Kotlin Code produces.

To do so, you add the R8 dependency to your buildscript block:

```grovvy
buildscript {
    maven {
        url "https://storage.googleapis.com/r8-releases/raw"
    }

    dependencies {
        classpath "com.android.tools:r8:1.5.39"
    }
}
```

You can look up the latest R8 version here (tags on the left): https://r8.googlesource.com/r8/

Very recent Android Studio versions may also ship with a working R8, but not sure if a stable version has it yet (the latest Canary has).

I'm doing this in one of my Apps and it's working perfectly, having set
`jvmTarget = JavaVersion.VERSION_1_8`.

**Comment by mikepenz** [comment]
releasing v4 now with 1.3.31 of kotlin. hopefully it resolves your issue.
