### ISSUE TITLE
Kotlin DSL

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/Android-Iconics#457]
Concerns v4.0.0

Like material drawer, iconics will benefit greatly from a kotlin dsl.

For instance, you can do something like

```kt
iconicsDrawable {
    size = sizeDp(5f)
    color = colorInt(Color.White)
}
```

etc

You can have functions such as `dp` or `colorInt` be applicable only within `iconicsDrawable`, which also avoids creating extensions that get suggested everywhere (currently, typing `to` after `Int` will suggest all iconics extensions, even though it won't apply to most situations).

As for the lambdas, I'm not sure if it was meant for performance or readability, but if it's for readability, you won't need it here since you can freely compute anything you want within the DSL

```kt
iconicsDrawable {
    val a = // bunch of code
    size = sizeDp(a)
}
```

**Comment by mikepenz** [comment]
@AllanWang absolutely. 

related the second issue of seeing the methods suggested everywhere. I started deprecating them and only allowing extensionFunctions directly on the `IconicsDrawable` scoping it so it is not causing these sorts of problems anymore
