### ISSUE TITLE
IconicsContentProvider causes black screen of death on app start

### ISSUE THREAD

**Issue by guntherhoppe** [mikepenz/Android-Iconics#468]
The ```IconicsContentProvider``` calls ```Iconics.init``` in ```onCreate```. The ```Iconics.init``` uses the ```GenericsUtil.getDefinedFonts``` to received configured fonts from the app's ```R``` class using the following method:
```
    /** Helper to resolve the correct R Class for the package */
    @JvmStatic private fun resolveRClass(packageName: String): Class<*>? {
        var tempPackageName = packageName
        do {
            try {
                return Class.forName("$tempPackageName.R\$string")
            } catch (e: ClassNotFoundException) {
                tempPackageName = tempPackageName.substringBeforeLast('.', "")
            }
        } while (packageName.isNotBlank())

        return null
    }
```
 And here is where the problem occurs. Our ```R```class in fact is ```ch.srf.android.newsapp.R```. The application ID of our app which is provided as ```packageName```to the method is ```ch.srf.mobile``` for historical reason. This means in fact there is no class ```ch.srf.mobile.R```, which results in an endless while loop.

Possible workaround: Remove Iconic ContentProvider from manifest (We don't use it actually. It comes as a dependency of another lib we use)
```
<!-- FIX black screen of death -->
<provider
   android:name="com.mikepenz.iconics.IconicsContentProvider"
   tools:node="remove" />
```

**Library version: 4.0.0**

**Comment by mikepenz** [comment]
@guntherhoppe thank you so much for the report. 

You could update to the latest version v4.0.1-b02 which has the contentProvider disabled by default now:

https://github.com/mikepenz/Android-Iconics/blob/33f77c95c25aaf65b6a1a8855d0c93675ff93815/library-core/src/main/res/values/booleans.xml#L3

(you can btw. define this setting in your configuration as described in the README:
https://github.com/mikepenz/Android-Iconics#advanced-usage

**Comment by guntherhoppe** [comment]
Yes I'll try - thx. 
But this won't solve the real issue of endless loop which happens any time when the application ID does not match the package of the ```R``` class.
Maybe you can use application meta to make the ```R```class configurable from within manifest, something like:
```
        <meta-data
            android:name="com.mikepenz.iconics.R"
            android:value="my.package.name.to.R"/>
```

**Comment by AllanWang** [comment]
While loop seems fixed already since it was checking `packageName` instead of `tempPackageName`. For config, `init` can take in an R class or whatever it needs directly, and have the original context function point to it, so users can configure the class themselves.

**Comment by mikepenz** [comment]
Ah yes I forgot. I had that fixed already too. 

Instead of the reflection based approach you can always just register the fonts you need:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.kt#L29
and after that mark the init as done:
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.kt#L100

**Comment by mikepenz** [comment]
the R class is only needed for it to try to identify available fonts automatically
