### ISSUE TITLE
Application crashes on ActionItemBadge with Materialdrawer v7 and iconics-core v 4

### ISSUE THREAD

**Issue by SSinteZ** [mikepenz/Android-Iconics#469]
Hi. Code crashed App :

 **if (badgeCount > 0) {
                ActionItemBadge.update(this, cartMenuItem, FontAwesome.Icon.faw_shopping_cart, ActionItemBadge.BadgeStyles.DARK_GREY, badgeCount);
            } else {
                ActionItemBadge.hide(cartMenuItem);
            }**

Error:

  java.lang.NoSuchMethodError: No virtual method color(I)Lcom/mikepenz/iconics/IconicsDrawable; in class Lcom/mikepenz/iconics/IconicsDrawable; or its super classes (declaration of 'com.mikepenz.iconics.IconicsDrawable'

**Comment by mikepenz** [comment]
@SSinteZ there is a chance v4 of Iconics is no longer compatible. You may want to stay with v3 of iconics for the ActionItemBadge. 

Open an issue on that repo (ActionItemBadge), as it may need to be updated to work with the latest iconics. 

It is not an Iconics issue :D 

also make sure you have iconics defined as dependency
