### ISSUE TITLE
Icon + Text not centered?

### ISSUE THREAD

**Issue by xsorifc28** [mikepenz/Android-Iconics#47]
I have the following: 

	<com.mikepenz.iconics.view.IconicsButton
		android:id="@+id/facebookLogin"
		android:theme="@style/Button_Facebook"
		android:text="{faw-facebook} Log in with Facebook"
		android:textAllCaps="false"
		android:layout_below="@+id/textView2"
		android:layout_centerHorizontal="true"
		android:layout_marginTop="16dp"
		android:layout_width="wrap_content"
		android:layout_height="56dp"
		android:textColor="@android:color/white"
		android:textSize="20sp"
		android:paddingLeft="16dp"
		android:paddingRight="16dp">
	</com.mikepenz.iconics.view.IconicsButton>

The icon doesn't seem to be centered with the text. Is this something wrong with my implementation or a bug? The padding also doesn't seem to apply. Any help is appreciated!

**Comment by mikepenz** [comment]
@xsorifc28 vertical centering within the text is not possible, as the icon interacts as a normal text within this sample. If you want it in front of the text you should go with a CompoundDrawable and set it via code.

**Comment by tmm1** [comment]
> If you want it in front of the text you should go with a CompoundDrawable and set it via code.

When using drawableLeft with an IconicDrawable, the icon appears left-aligned. Is there any way to make it centered horizontally along with the text so it looks similar to how the spannable version does?
