### ISSUE TITLE
I did a brand new build with the bottom tabs template, touched nothing and got this error. bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

### ISSUE THREAD

**Issue by Isonomic** [mikepenz/Android-Iconics#471]
![Screenshot (93)](https://user-images.githubusercontent.com/37713396/65263036-de55f380-dac8-11e9-8ee4-3414d9c43142.png)

**Comment by Isonomic** [comment]
![Screenshot (94)](https://user-images.githubusercontent.com/37713396/65263101-0c3b3800-dac9-11e9-97db-801f783f9746.png)

**Comment by mikepenz** [comment]
This lib uses java8 with lambdas. (as every project should these days :P) It is a shame that this is not done by default by google. Theoretically there exists Java 13 by now...

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/build.gradle#L45-L48

**Comment by zTrap** [comment]
Probably we also need to specify 
```
compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by zTrap** [comment]
Because it is not the same with 
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by mikepenz** [comment]
the source and target thing should be enough :)
