### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Amin2020R** [mikepenz/Android-Iconics#472]
Hello when i used this library:
4.0.1-b02- [ ] Used library version
my app crashed
and when i delete this from build.gradle:
com.mikepenz:iconics-views:4.0.1-b02- [ ] Used support library version
my app starts successfully.

see this:
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 15
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.mikepenz:iconics-core:4.0.1-b02"
    implementation "com.mikepenz:iconics-views:4.0.1-b02"

    implementation 'com.mikepenz:google-material-typeface:3.0.1.4.original-kotlin@aar'
    implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.6-kotlin@aar'
    implementation 'com.mikepenz:fontawesome-typeface:5.9.0.0-kotlin@aar'
    implementation 'com.mikepenz:octicons-typeface:3.2.0.6-kotlin@aar'
    implementation 'com.mikepenz:meteocons-typeface:1.1.0.5-kotlin@aar'
    implementation 'com.mikepenz:community-material-typeface:3.5.95.1-kotlin@aar'
    implementation 'com.mikepenz:weather-icons-typeface:2.0.10.5-kotlin@aar'
    implementation 'com.mikepenz:typeicons-typeface:2.0.7.5-kotlin@aar'
    implementation 'com.mikepenz:entypo-typeface:1.0.0.5-kotlin@aar'
    implementation 'com.mikepenz:devicon-typeface:2.0.0.5-kotlin@aar'
    implementation 'com.mikepenz:foundation-icons-typeface:3.0.0.5-kotlin@aar'
    implementation 'com.mikepenz:ionicons-typeface:2.0.1.5-kotlin@aar'
    implementation 'com.mikepenz:pixeden-7-stroke-typeface:1.2.0.3-kotlin@aar'
    implementation 'com.mikepenz:material-design-icons-dx-typeface:5.0.1.0-kotlin@aar'

    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

my android studio is the latest version for now and the app shows this error:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 15301
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #18 in com.example.myapplication:layout/activity_main: Binary XML file line #18 in com.example.myapplication:layout/activity_main: Error inflating class Button
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #18 in com.example.myapplication:layout/activity_main: Binary XML file line #18 in com.example.myapplication:layout/activity_main: Error inflating class Button
     Caused by: android.view.InflateException: Binary XML file line #18 in com.example.myapplication:layout/activity_main: Error inflating class Button
     Caused by: java.lang.RuntimeException: A 'Iconics.init(context)' has to happen first. Call from your application. Usually this happens via an 'IconicsDrawable' usage.
        at com.mikepenz.iconics.Iconics.init(Iconics.kt:64)
        at com.mikepenz.iconics.Iconics.init$default(Iconics.kt:55)
        at com.mikepenz.iconics.Iconics.init(Iconics.kt:90)
        at com.mikepenz.iconics.Iconics.style(Iconics.kt:212)
        at com.mikepenz.iconics.Iconics$BuilderView.build(Iconics.kt:281)
        at com.mikepenz.iconics.utils.IconicsExtensionsKt.buildIconics(IconicsExtensions.kt:89)
        at com.mikepenz.iconics.utils.IconicsExtensionsKt.buildIconics$default(IconicsExtensions.kt:88)
        at com.mikepenz.iconics.context.IconicsFactory.onViewCreatedInternal(IconicsFactory.kt:63)
        at com.mikepenz.iconics.context.IconicsFactory.onViewCreated(IconicsFactory.kt:39)
        at com.mikepenz.iconics.context.InternalLayoutInflater$WrapperFactory2.onCreateView(InternalLayoutInflater.kt:210)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.kt:79)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:545)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

please help me mike  Thanks.

**Comment by AllanWang** [comment]
```
Caused by: java.lang.RuntimeException: A 'Iconics.init(context)' has to happen first. 
Call from your application. Usually this happens via an 'IconicsDrawable' usage.
```

Did you follow this?

**Comment by Amin2020R** [comment]
this is my java code
could you please help me what should i do

import android.Manifest;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.net.NetworkInfo;
import android.net.Uri;
import android.os.AsyncTask;
import android.os.Build;
import android.os.Handler;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.view.LayoutInflaterCompat;

import com.mikepenz.iconics.IconicsDrawable;
import com.mikepenz.iconics.context.IconicsContextWrapper;
import com.mikepenz.iconics.context.IconicsLayoutInflater2;
import com.mikepenz.iconics.typeface.library.community.material.CommunityMaterial;
import com.mikepenz.iconics.typeface.library.googlematerial.GoogleMaterial;

import java.io.BufferedWriter;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.URL;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(IconicsContextWrapper.wrap(newBase));
    }
    Button connectPhones,sent;
    String serverIpAddress = "192.168.4.1",msg = "",str="";
    PrintWriter os;
    Handler handler = new Handler();
    Socket socket;
    NetworkInfo mWifi;
    char wi=0;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        LayoutInflaterCompat.setFactory2(getLayoutInflater(), new IconicsLayoutInflater2(getDelegate()));
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ActivityCompat.requestPermissions(MainActivity.this, new String[]{
                Manifest.permission.ACCESS_FINE_LOCATION}, 1);

        //******************************************************************************************
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            final Button connectBtn = findViewById(R.id.connectBtn);
            final Button ch1 = findViewById(R.id.ch1);
            final Button ch2 = findViewById(R.id.ch2);
            final Button ch3 = findViewById(R.id.ch3);
            final Button ch4 = findViewById(R.id.ch4);
            //******************************************************************************************
            final int[] i = {0, 1, 1, 1, 1};
            connectBtn.setBackground(new IconicsDrawable(MainActivity.this)
                    .icon(GoogleMaterial.Icon.gmd_signal_wifi_off));
                    //.color(Color.BLACK)
                    //.paddingDp(8)
                    //.sizeDp(15));
            ch1.setBackground(new IconicsDrawable(MainActivity.this)
                    .icon(CommunityMaterial.Icon.cmd_account_heart));
                    //.color(Color.BLACK)
                    //.paddingDp(8)
                    //.sizeDp(15));
            ch2.setBackground(new IconicsDrawable(MainActivity.this)
                    .icon(CommunityMaterial.Icon.cmd_account_heart));
                    //.color(Color.BLACK)
                    //.paddingDp(8)
                    //.sizeDp(15));
            ch3.setBackground(new IconicsDrawable(MainActivity.this)
                    .icon(CommunityMaterial.Icon.cmd_account_heart));
                    //.color(Color.BLACK)
                    //.paddingDp(8)
                    //.sizeDp(15));
            ch4.setBackground(new IconicsDrawable(MainActivity.this)
                    .icon(CommunityMaterial.Icon.cmd_account_heart));
                    //.color(Color.BLACK)
                    //.paddingDp(8)
                    //.sizeDp(15));
            //******************************************************************************************
            connectBtn.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    Thread clientThread = new Thread(new ClientThread());
                    if((socket == null)) {
                        clientThread.start();
                        connectBtn.setBackgroundDrawable(new IconicsDrawable(MainActivity.this)
                                .icon(GoogleMaterial.Icon.gmd_wifi));
                                //.color(Color.GREEN)
                                //.paddingDp(8)
                                //.sizeDp(15));
                    }
                    if(socket != null) {
                        Toast.makeText(getApplicationContext(),"is Connected!",Toast.LENGTH_SHORT).show();
                    }
                }
            });
           /*
            connectBtn.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {

                    //Toast.makeText(getApplicationContext(),socket.toString(),Toast.LENGTH_SHORT).show();
                    /*if (i[0] == 1 && mWifi.isConnected() && socket == null) {
                        connectBtn.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(GoogleMaterial.Icon.gmd_signal_wifi_off)
                                .color(Color.BLACK)
                                .paddingDp(8)
                                .sizeDp(15));
                        i[0] = 0;
                    }
                    else if(!mWifi.isConnected() || socket == null)
                    {
                        connectBtn.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(GoogleMaterial.Icon.gmd_signal_wifi_off)
                                .color(Color.BLACK)
                                .paddingDp(8)
                                .sizeDp(15));
                        Toast.makeText(getApplicationContext(),(R.string.toast),Toast.LENGTH_SHORT).show();
                        i[0] = 0;
                    }

                }
            });
*/
            //******************************************************************************************
            ch1.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    if (i[1] == 1) {
                        str="one1";
                        new sentMessage().execute(null,null,null);
                        ch1.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.YELLOW)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[1] = 0;
                    }
                    else {
                        str="one0";
                        new sentMessage().execute(null,null,null);
                        ch1.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.BLACK)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[1] = 1;
                    }
                }
            });
            //******************************************************************************************
            ch2.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    if (i[2] == 1) {
                        str="two1";
                        new sentMessage().execute(null,null,null);
                        ch2.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.YELLOW)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[2] = 0;
                    }
                    else {
                        str="two0";
                        new sentMessage().execute(null,null,null);
                        ch2.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.BLACK)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[2] = 1;
                    }
                }
            });
            //******************************************************************************************
            ch3.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    if (i[3] == 1) {
                        str="three1";
                        new sentMessage().execute(null,null,null);
                        ch3.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.YELLOW)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[3] = 0;
                    }
                    else {
                        str="three0";
                        new sentMessage().execute(null,null,null);
                        ch3.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.BLACK)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[3] = 1;
                    }
                }
            });
            //******************************************************************************************
            ch4.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    if (i[4] == 1) {
                        str="four1";
                        new sentMessage().execute(null,null,null);
                        ch4.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.YELLOW)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[4] = 0;
                    }
                    else{
                        str="four0";
                        new sentMessage().execute(null,null,null);
                        ch4.setBackground(new IconicsDrawable(MainActivity.this)
                                .icon(CommunityMaterial.Icon.cmd_account_heart));
                                //.color(Color.BLACK)
                                //.paddingDp(8)
                                //.sizeDp(15));
                        i[4] = 1;
                    }
                }
            });
        }
    }
    public void wifi(View view) {
        Uri uri = Uri.parse("https://www.tooschip.com"); // missing 'http://' will cause crashed
        Intent intent = new Intent(Intent.ACTION_VIEW, uri);
        startActivity(intent);
    }
    //**********************************************************************************************
    class sentMessage extends AsyncTask<URL, Integer, Long>
    {
        protected Long doInBackground(URL... urls)
        {
            try
            {
                os = new PrintWriter(
                        new BufferedWriter(new OutputStreamWriter(socket.getOutputStream())), true);
                //os.print(str);
                //os.printf(str);
                //os.write(str);
                os.println(str);
                os.flush();
                //os.close();
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
            return null;
        }
        protected void onProgressUpdate(Integer... progress)
        {

        }
        protected void onPostExecute(Long result)
        {

        }
    }
    //**********************************************************************************************
    /*class ClientThread implements Runnable
    {
        public void run()
        {
            try
            {
                while(true)
                {
                    try
                    {
                        socket = new Socket("192.168.4.1", 10000);
                        //char[] buffer = new char[2048];
                        int charsRead = 0;
                        BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                        while ((charsRead = in.read(buffer)) != -1)
                        {
                            String message = new String(buffer).substring(0, charsRead);
                            msg = msg + "Server : " + message + "\n";
                            handler.post(new Runnable()
                            {
                                @Override
                                public void run()
                                {
                                    //chat.setText(msg);
                                }
                            });
                        }

                    }
                    catch (Exception e)
                    {
                    }
                }
            }
            catch (Exception e)
            {
            }
        }
    }
    */
    public class ClientThread implements Runnable
    {
        public void run()
        {
            try
            {
                try
                {
                    socket = new Socket("192.168.4.1", 10000);
                }
                catch (Exception e)
                {

                }
            }
            catch (Exception e)
            {
            }
        }
    }

}

**Comment by Amin2020R** [comment]
wow ! thank you so much , i called Iconics.init(context) and app starts successfully.
