### ISSUE TITLE
imageview click problem

### ISSUE THREAD

**Issue by Blaster-777** [mikepenz/Android-Iconics#475]
My problem is that when I set the icon to the imageview, the icon appears and everything is OK, but the click only works where the icon is colored and if it clicks on the areas of the imageview the icon has zero opacity, it doesn't work.

```
public static final Drawable DRAWABLE_FIRST = new IconicsDrawable(App.context, FontAwesome.Icon.faw_twitter).color(Color.GRAY).sizeDp(20);

ImageView firstIcon = view.findViewById(R.id.toolbar_one);
firstIcon.setImageDrawable(DRAWABLE_FIRST );
```

## Details
- [ ] Used library version 3.0.4
- [ ] Used support library version 28.0.0

**Comment by mikepenz** [comment]
that is not something this library does. please check the behavior of the `ImageView`
