### ISSUE TITLE
"ico_automirror" attribute not working

### ISSUE THREAD

**Issue by hichamboushaba** [mikepenz/Android-Iconics#477]
## About this issue

When using the attribute `ico_automirror` with regular views, it's not used.

It's my fault on the PR: #476 , I forgot to pass the value in the core `IconicsAttrsApplier`.

**Comment by mikepenz** [comment]
Btw. which regular views do you mean? 

Auto layout inflation replacement for normal `View`s is deprecated, and we will mainly support the `IconicsImageView`, ... moving forward

**Comment by hichamboushaba** [comment]
Yes, I meant auto layout inflation. But the attribute will be used also for menu inflation, using `IconicsMenuInflaterUtil` which is not deprecated.

**Comment by mikepenz** [comment]
true :D
