### ISSUE TITLE
ImageViews not correclty rendered with version 4.0.2

### ISSUE THREAD

**Issue by marbat87** [mikepenz/Android-Iconics#479]
## About this issue

Updating to version 4.0.2, standard imageviews filled with normal drawable (or vector assets) don't render, their just invisible.
Everything works fine just reverting to 4.0.1

You can reproduce it with a simple ImageView, like the one in the layout below:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:risuscito="http://schemas.android.com/apk/res-auto">

    <ImageView
        android:id="@+id/imageView1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:contentDescription="any content"
        android:layout_margin="5dip"
        risuscito:srcCompat="@drawable/ic_main_cover"  //ANY DRAWABLE
        android:layout_gravity="center" />

</FrameLayout>
```

Regards

## Details
- [4.0.2 ] Used library version
- [androidx.appcompat:appcompat:1.1.0 ] Used support library version
- [5.6.3 ] Used gradle build tools version
- [ 3.5.1] Used tooling / Android Studio version
- [com.google.android.material:material:1.2.0-alpha01 ] Other used libraries, potential conflicting libraries

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
To be honest. I do not see how these changes: https://github.com/mikepenz/Android-Iconics/commit/84b470a23d3039be3b10c8b901caecb410692ae3 could result in normal views not working anymore?

Do you see any log? anything interesting?

have you done a clean install or similar? 

Do you use the iconicsInflator? or the wrapped context (which were discontinued and deprecated with v4.0.1)?

**Comment by marbat87** [comment]
I removed iconicsInflator usage and moved to IconicsImageView where needed.
Now everything works fine.

Thank you very much
