### ISSUE TITLE
Icons size is not correct 

### ISSUE THREAD

**Issue by leelei** [mikepenz/Android-Iconics#48]
```
compile 'com.mikepenz:iconics:1.2.1@aar'
````
```
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    toolbar.inflateMenu(R.menu.menu_main);
    toolbar.setNavigationIcon(
        new IconicsDrawable(this, GoogleMaterial.Icon.gmd_arrow_back).actionBar());
    toolbar.getMenu()
        .findItem(R.id.action_share)
        .setIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_arrow_back).actionBar());
    toolbar.getMenu()
        .findItem(R.id.action_comment)
        .setIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_comment).actionBar());
```
icons size not the standard Material Design
![](http://ww3.sinaimg.cn/bmiddle/5f5f92d8jw1eu19lomcpmj20p018gta1.jpg)

if i use
```
compile 'com.mikepenz.iconics:library:0.7.5@aar'
```
```
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    toolbar.inflateMenu(R.menu.menu_main);
    toolbar.setNavigationIcon(
        new IconicsDrawableOld(this, GoogleMaterial.Icon.gmd_arrow_back).actionBarSize());
    toolbar.getMenu()
        .findItem(R.id.action_share)
        .setIcon(new IconicsDrawableOld(this, GoogleMaterial.Icon.gmd_arrow_back).actionBarSize());
    toolbar.getMenu()
        .findItem(R.id.action_comment)
        .setIcon(new IconicsDrawableOld(this, GoogleMaterial.Icon.gmd_comment).actionBarSize());
```
this is the correct size
![](http://ww1.sinaimg.cn/bmiddle/5f5f92d8jw1eu19sldxbij20p018g75l.jpg)

**Comment by mikepenz** [comment]
The size with the newest lib is 24dp for the icon and 6dp padding. 

```java
    public static final int ANDROID_ACTIONBAR_ICON_SIZE_DP = 24;
    public static final int ANDROID_ACTIONBAR_ICON_SIZE_PADDING_DP = 6;
```

```java
public IconicsDrawable actionBar() {
        sizeDp(ANDROID_ACTIONBAR_ICON_SIZE_DP + (2 * ANDROID_ACTIONBAR_ICON_SIZE_PADDING_DP));
        paddingDp(ANDROID_ACTIONBAR_ICON_SIZE_PADDING_DP);
        return this;
    }
```

**Comment by mikepenz** [comment]
As of this screenshot in the Material Design Guidelines the Icon should be the size of `24dp`
* 56dp actionBarSize
* 16dp padding
![layout_structure_appbar_metrics1](https://cloud.githubusercontent.com/assets/1476232/8647550/32f2a1b6-2959-11e5-9d4e-2a070afe6fe3.png)

So it should be fine. if a specific icon needs more padding you can define the size manually

**Comment by mikepenz** [comment]
@leelei have you tested on Android M?

**Comment by rf3Studios** [comment]
On Android 4.4.4, the 6dp padding makes the icons slightly large. If I try to set .paddingDp(int) manually it seems to add that arg to the padding already defined. So, if I set .paddingDp(8) it makes the icon extremely small. However, setting to .paddingDp(2) seems to simply add it to the existing 6dp padding that you have thus making it the correct size.

I think it might be more intuitive to override the padding with the argument instead of adding to it.

**Comment by mikepenz** [comment]
@rf3Studios i have modified this behavior on the latest version. the icon is now 24dp with 1dp padding

**Comment by novalu** [comment]
I wanted to replace icons in Toolbar from resources to IconicsDrawable. I had icons defined as:

```
android:icon="@drawable/ic_refresh_white_24dp"
```

with "ic_refresh_white_24dp.png" from official repository and it looks like this:

![iconics_size1](https://cloud.githubusercontent.com/assets/6546116/9980268/1d916a2c-5f92-11e5-90ad-174ddb1351e1.png)

Then I replaced refresh icon with IconicsDrawable

```java
IconicsDrawable layersIcon = new IconicsDrawable(context, GoogleMaterial.Icon.gmd_refresh);
menu.findItem(menuItemId).setIcon(layersIcon.actionBar());
```

And icon was bigger:

![iconics_size2](https://cloud.githubusercontent.com/assets/6546116/9980269/1f58e524-5f92-11e5-8f0e-07dcde5d5c36.png)

I had to set different size and padding for expected size according to Material guidelines:

```
IconicsDrawable layersIcon = new IconicsDrawable(context, GoogleMaterial.Icon.gmd_refresh);
layersIcon = layersIcon.sizeDp(24);
layersIcon = layersIcon.paddingDp(4);
menu.findItem(menuItemId).setIcon(layersIcon);
```

![iconics_size3](https://cloud.githubusercontent.com/assets/6546116/9980283/aa81ed76-5f92-11e5-8218-ec2f0ee37eb9.png)

I've tried on 5.0.0 and 5.1.1 with 1080x1920, 480dpi

**Is this behavior of actionBar method correct?**

**Comment by mikepenz** [comment]
@novalu the `actionBar` method is correct as far as possible for the lib. The thing is that google does not use the same paddings for all of their icons, and i see no programmatically solution to automatically define the different paddings. 

The `actionBar` method sets the size to 24dp with 1dp padding by default. In some cases this will be different as you found out already
