### ISSUE TITLE
new version of CommunityMaterial

### ISSUE THREAD

**Issue by mohammadms2008** [mikepenz/Android-Iconics#482]
hi. when you update the CommunityMaterial library. some new icons (like domain-plus, menu-up, menu-down,...) doesn't exist in version 3.5.95.1-kotlin.

**Comment by mohammadms2008** [comment]
Thanks a lot for releasing new version...

**Comment by mikepenz** [comment]
available as:
```
implementation 'com.mikepenz:community-material-typeface:3.7.95.2-kotlin@aar'
```


Note due to the huge size of the icon set now, I had to split it into 4 parts...

**Comment by mohammadms2008** [comment]
yes, I downloaded...
but there is a problem. Most of icons doesn't appear now....
what is the reason?

**Comment by mikepenz** [comment]
Could be that the name mapping is slightly different because we now have to
manually map the icons via the svg icon names. The original font can no
longer be used as is, as it's mapping of some icons requires 2 byte which
is not supported. And you have included the version with .2 at the end?

**Comment by mohammadms2008** [comment]
Unfortunately I don't understand what you mean.
what can I do now?
for example I use the code below and the icon doesn't appear:

<com.mikepenz.iconics.view.IconicsImageView
                android:layout_width="@dimen/navigation_item_icon_size"
                android:layout_height="@dimen/navigation_item_icon_size"
                android:layout_gravity="center|start"
                android:layout_marginStart="@dimen/navigation_item_icon_margin_from_start"
                app:iiv_color="@color/textColorSecondary"
                app:iiv_icon="cmd-domain-plus"
                app:iiv_size="@dimen/navigation_item_icon_size" />

**Comment by mikepenz** [comment]
Just looked. That icon is still there. 

Which version of the dependency did you use?

**Comment by mohammadms2008** [comment]
the version you just released:
implementation 'com.mikepenz:community-material-typeface:3.7.95.2-kotlin@aar'

**Comment by mikepenz** [comment]
Any messages in the log? And you for sure don't have the old version somehow present? I can see this icon exists and also works using the sample app which displays all available icons. 
Have you also tried cleaning everything?

**Comment by mohammadms2008** [comment]
yes everything is OK.
in previous version, all icons appeared. but when I updated the library to new version, most of icons didn't appear at all.
It's weird

**Comment by mikepenz** [comment]
Which android phone and android version do you use?

Also trying to use it similar like you do in your code snippet in the sample works:

![image](https://user-images.githubusercontent.com/1476232/71626017-426d7500-2beb-11ea-9fbb-523ec3680c29.png)

**Comment by mohammadms2008** [comment]
I test in Emulator Google Pixel API 26

**Comment by mohammadms2008** [comment]
this problem also exists in another project I work on

**Comment by mikepenz** [comment]
Ok thanks for helping me debug this. I have found the problem now. seems it was due to the splitting into 4 sets. have resolved the problem and released as:
```
implementation 'com.mikepenz:community-material-typeface:3.7.95.3-kotlin@aar'
```

Have a great new year :)

**Comment by mohammadms2008** [comment]
Have a great new year too, my friend. very very thank you...

**Comment by mohammadms2008** [comment]
:)))))
