### ISSUE TITLE
Custom Font Icon not recognized in xml

### ISSUE THREAD

**Issue by Nailik** [mikepenz/Android-Iconics#487]
When i want to use an Icon of my Customfont in the xml like:

```
<com.mikepenz.iconics.view.IconicsImageView
        android:id="@+id/ivCodeCount"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_vertical"
        app:iiv_icon="fbd_barcode"
        app:iiv_padding="2dp"
        app:iiv_size="20dp" />
```

it's not shown. However when i use `ivCodeCount.icon!!.icon(FBDFontModule.Icon.fbd_barcode)` it's working.

I initialize it in the App file like (it's a java file): 
```
Iconics.init(getApplicationContext());
Iconics.registerFont(FBLFontModule.INSTANCE);
```

I also tried fbd_barcode `fbd-barcode` and `{fbd-barcode}` and `{fbd_barcode}`.
In the error logs i can find: 
`E/Iconics: Wrong icon name: fbd-barcode` or E/Iconics: `Wrong icon name: fbd-barcode` but when i use `{fbd-barcode}`  i see nothing in the error logs (but also no icon).

I use:
- library version 4.0.2
- support library version 1.0.0
- Used gradle build tools version 3.5.3
- Used tooling / Android Studio version 3.5.3

**Comment by mikepenz** [comment]
could you please provide the custom font implementation? 

It sounds like perhaps the mapping prefix does not match "fbd"
https://github.com/mikepenz/Android-Iconics/blob/develop/fontawesome-typeface-library/src/main/java/com/mikepenz/iconics/typeface/library/fontawesome/FontAwesome.kt#L33

**Comment by Nailik** [comment]
Thank you for the quick reply.
I think i found the problem i had 
  `  override fun getIcon(key: String): IIcon = OtherFontModule.Icon.valueOf(key)` because i just copied the line and Kotlin inserted the other class.
The other problem was that another FontModule had the same mappingPrefix (same thing, coping lines).

Maybe there should be some error when multiple fonts use the same mappingPrefix?
