### ISSUE TITLE
Community icons order change

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/Android-Iconics#488]
The order of icons seems to have flipped
used to be Icon1 started with A's, now  Icon4 starts with A

This breaks almost all icons

**Comment by mikepenz** [comment]
Yes we will look into that again to further approve. sadly the community material icon dataset is soo huge by now that it requires being split apart

**Comment by mikepenz** [comment]
Closing as I will cover it as part of this discussion: https://github.com/mikepenz/Android-Iconics/issues/483
