### ISSUE TITLE
iconicsDrawableStart setVisible false not working

### ISSUE THREAD

**Issue by Nailik** [mikepenz/Android-Iconics#489]
I have a `IconicsTextView` in XML:
   ```
<com.mikepenz.iconics.view.IconicsTextView
            android:id="@+id/txtInformation"
            style="@style/TextViewCaption"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:alpha="0.5"
            android:paddingTop="8dp"
            android:textColor="?attr/color_on_surface_background_themed"
            app:iiv_start_color="?attr/color_on_surface_background_themed"
            app:iiv_start_icon="@string/icon_barcode"
            app:iiv_start_size="20dp" />
```

when i set: `itemView.txtInformation.iconicsDrawableStart!!.setVisible(false, false)`
the Icon is still visible. It returns `true` (hasChanged) and false for `isVisible`.

I use:
- library version 4.0.2
- support library version 1.0.0
- Used gradle build tools version 3.5.3
- Used tooling / Android Studio version 3.5.3

I would be happy if anyone can check this or if i'm the only one with this bug.

**Comment by mikepenz** [comment]
@Nailik the `start` is basically just a synonym for the `compoundDrawableLeft` if you want to remove a compound drawable programmatically. just use the relevant `TextView` method

https://developer.android.com/reference/android/widget/TextView#setCompoundDrawables(android.graphics.drawable.Drawable,%20android.graphics.drawable.Drawable,%20android.graphics.drawable.Drawable,%20android.graphics.drawable.Drawable)

(pass null for all)

**Comment by Nailik** [comment]
But why is it not possible to set it to invisible (Why is there the function when it doesn't work). 
I now use `itemView.txtInformation.iconicsDrawableStart!!.alpha(0)`

**Comment by mikepenz** [comment]
This function is from the `Drawable` class and not from `IconicsDrawable`

**Comment by Nailik** [comment]
I see (.. didn't check) ...
So i think it's somewhere in `TextView` `invalidateDrawable` and just doesn't work with the `IconcisDrawable` but i can't check at the moment. 
Couldn't this be fixed in Iconics or do you just want to wait if this one day get's fixed in the Android lib?

**Comment by mikepenz** [comment]
![image](https://user-images.githubusercontent.com/1476232/72208978-cce68c00-34a9-11ea-98d3-7faa12c3bb93.png)

As of the `Drawable` documentation. We might will support this at some date. But no promise. Will investigate regarding if it makes sense to offer.
