### ISSUE TITLE
Broken icon on 4.0.2 -> v5.0.0-a0* update

### ISSUE THREAD

**Issue by DummyCo** [mikepenz/Android-Iconics#492]
## About this issue

Hello! Facing an issue on `4.0.2 -> v5.0.0-a0*` update.
Using an icon in a simple `ImageView/AppCompatImageView` works just fine, but an attempt to use this same icon in `com.google.android.material.bottomnavigation.BottomNavigationView` via programmatic menu:

```
    mainBottomNavigationView.menu.apply {
      add(
        Menu.NONE,
        R.id.feed_nav_graph,
        Menu.NONE,
        R.string.title_feed
      ).icon = IconicsDrawable(
        requireContext(),
        MaterialDesignDx.Icon.gmf_border_all
      ) //gmf_border_all is not working
    }
```
Results in some sort of invalid icon:

**4.0.2:**

![IFjhKesbTI](https://user-images.githubusercontent.com/3989453/74094520-50b48800-4aeb-11ea-8853-1395128021aa.png)

**5.0.0-a03:**

![xW35EmKHV5](https://user-images.githubusercontent.com/3989453/74094522-514d1e80-4aeb-11ea-853f-239e65aa8e83.png)

Other used icons (`gmf_inbox`,` gmf_people_alt`) are working fine too on **5.0.0-a03**:

![LHku8tFcd8](https://user-images.githubusercontent.com/3989453/74094546-b30d8880-4aeb-11ea-8102-cac1f5fb53f3.png)

## Details

- `com.google.android.material:material:1.2.0-alpha04`
- `androidx.appcompat:appcompat:1.2.0-alpha02`
- `com.mikepenz:iconics-core:5.0.0-a01/02/03`
- `com.mikepenz:material-design-icons-dx-typeface:5.0.1.0-kotlin@aar`
- buildToolsVersion `29.0.3`
- targetSdkVersion `29`
- gradle `gradle-6.2-rc-1`
- gradle wrapper `3.6.0-rc02`
- Pixel XL, Android 10
- Pixel 3 XL API 29 emulator, Android 10

**Comment by mikepenz** [comment]
@DummyCo could you please try a thing for me?

Add
```kotlin
Iconics.init(this)
```
to your `CustomApplication`.

(https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.kt#L55)

**Comment by DummyCo** [comment]
@mikepenz that did the trick! Is that a thing I'm missing or there's an issue with implicit under-the-hood `material-design-icons-dx-typeface` registering?

![ONuFigQF6M](https://user-images.githubusercontent.com/3989453/74102295-ea5f5200-4b4a-11ea-8fba-25cf00f0673a.png)

**Comment by mikepenz** [comment]
I think it is a problem we may be able to solve.

It's due to the under the hood changes to not depend on the context so much

**Comment by mikepenz** [comment]
Fixed the problem if you provide the context, and added log messages if the init did not occur before.
