### ISSUE TITLE
Iconics.init() not yet executed, icon will be missing

### ISSUE THREAD

**Issue by axdeveloper** [mikepenz/Android-Iconics#497]
## About this issue
Hi, I have updated library from 4.0.2 -> 5.0.0-b01 and i keep getting this error

```E/IconicsDrawable: Iconics.init() not yet executed, icon will be missing```

each time i use an icon in my app but the icon looks fine. so I looked at the source and found these lines in ```IconicsDrawableExtensions.kt```
```kotlin
    if (Iconics.isInitDone()) {
        Log.e("IconicsDrawable", "Iconics.init() not yet executed, icon will be missing")
    }
```
that should print the error if ```Iconics.init()``` hasn't executed yet but its opposite.

thank you.

## Details
- [ 5.0.0-b01 ] Used library version

**Comment by mikepenz** [comment]
oh you are right. it's supposed to be the inverse.
