### ISSUE TITLE
Padding is not working properly on Android M

### ISSUE THREAD

**Issue by h6ah4i** [mikepenz/Android-Iconics#50]
Hi. I noticed that `android:padding` setting for `IconicsImageView` is not working properly on Android M. 

![paddings are not applied propery](https://cloud.githubusercontent.com/assets/2552365/8694105/6c62b804-2b17-11e5-8d2f-7fdd6fc8032f.png)

### code  (activity_playground.xml)
```xml
<com.mikepenz.iconics.view.IconicsImageView
    android:layout_width="72dp"
    android:layout_height="72dp"
    android:padding="24dp"
    app:iiv_icon="faw-android" />
```

**Comment by h6ah4i** [comment]
I have just found a solution. Modify [`line 73 of IconicsImageView.java`](https://github.com/mikepenz/Android-Iconics/blob/develop/library/src/main/java/com/mikepenz/iconics/view/IconicsImageView.java#L73).
(maybe Android M has changed the behavior of MATRIX mode for scaling type)

From:
```java
setScaleType(ScaleType.MATRIX);
```

To:
```java
setScaleType(ScaleType.CENTER_INSIDE);
```

**Comment by h6ah4i** [comment]
See the PR #51.

**Comment by mikepenz** [comment]
@h6ah4i thanks. i'll check this later today
