### ISSUE TITLE
Migrating from string resources to SPI

### ISSUE THREAD

**Issue by zTrap** [mikepenz/Android-Iconics#503]
What do you think about migrating to [Java Service Provider Interface](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html)?

**Comment by mikepenz** [comment]
If we can make it work for android without any major overhead I would say absolutely. 
One thing which is very relevant all the time though... obfuscation :D

**Comment by zTrap** [comment]
We can make this, but we need to switch to jar packaging for typeface libraries. And obfuscation work perfectly with SPI :)

**Comment by mikepenz** [comment]
Why would we need the jar packaging? the aar packaging is like a jar with additional features.
Maybe I miss something important here?

**Comment by zTrap** [comment]
Aar removes META-INF folder from package, but SPI requires it

**Comment by mikepenz** [comment]
hmmmm then there may be a different issue, as this may get lost in the end again via proguard. many people have a packaging rule to exclude meta inf files. due to conflicts of other libs.. :/

**Comment by zTrap** [comment]
Hmm, ok, I’ll investigate this

**Comment by zTrap** [comment]
My bad, it works perfectly with aar and [auto-service](https://github.com/google/auto/tree/master/service) (which adds all required information in META-INF automatically)

**Comment by mikepenz** [comment]
Hmm I would propose that we have a look on how this meta data has to look like and we add it manually then to not rely on external dependencies. 
but that sounds like it could work

**Comment by zTrap** [comment]
I'we tried to add `META-INF` manually in `res` folder, but it wont works. Maybe I did something wrong... But I don't think this dependency is redundant. It's can be used in `kapt` configuration for processor and `compileOnly` for annotation, so nothing redundant is added to libraries

**Comment by mikepenz** [comment]
but it will have to be mentioned in the licenses. and as it is a compile time dependency only, there is no reference left in the dependency tree, so AboutLibraries won't see it :D

**Comment by zTrap** [comment]
Sounds good :)

**Comment by mikepenz** [comment]
Theoretically we could just use the ContentProvider of android to auto register the font dependencies...
https://medium.com/@andretietz/auto-initialize-your-android-library-2349daf06920

I am not really sure about the real world performance impact of having many contentProviders in an app :/ 

so let's say there are 5 fonts in an app. what would be the impact?

**Comment by zTrap** [comment]
Idk, we need to test it

**Comment by mikepenz** [comment]
Well google just made this one a lot easier :D https://developer.android.com/topic/libraries/app-startup

**Comment by zTrap** [comment]
Look's so pretty and easy. We'll wait for stable version?

**Comment by mikepenz** [comment]
I'd say we prepare a beta release of Android-Iconics v6 :D and wait for it's release until the app startup library is at least in beta :) 

I'm gonna spend a bit of time on this, this week to prepare things :)
