### ISSUE TITLE
Question about Drawable XML (API 24+)

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/Android-Iconics#506]
Is it expected that android studio complains Element com.mikepenz.iconics.IconicsDrawable must be declared?

It works in app just kinda of annoying to have constant "error" files

**Comment by mikepenz** [comment]
I think it's mainly because AS does not  really understand the existence of a custom defined drawable attribute. I guess this is a super rarely used feature.

**Comment by binarynoise** [comment]
@mikepenz 
Android Studio also fails to render the preview of the Drawables. Did you open a ticket at Google to make them fix this?

**Comment by binarynoise** [comment]
And I just found out, even lint complains that the IconicsDrawable must be declared.
