### ISSUE TITLE
Wrong icon name

### ISSUE THREAD

**Issue by ftoyon** [mikepenz/Android-Iconics#508]
I just add a 'IconicsImageView' in xml we get a "Wrong icon name" for `IconicsImageView` since 5 versions if you don't call `Iconics.init(context)` in application `onCreate` for older version it's work fine.

It's simple to reproduced 
*  Get the sample application
*  Set the playground as main activity
*  Keep only the "IconicsImageView AutoMirror on RTL" part
*  Cleanup all of activity code but keep binding
*  Run it => no icons and you get "Wrong icon name" in logcat
*  Add `Iconics.init(this)` in `CustomApplication.onCreate` 
*  Run it => icons are show

The usage of `Iconics.init(context)` is comment as is :
> //only required if you add a custom or generic font on your own

**Comment by mikepenz** [comment]
@ftoyon thanks for the report I will have a look. 

To also get the init to happen automatically you could enable the content provider again?

By setting this to `true`: https://github.com/mikepenz/Android-Iconics/blob/30287ed7aa625af4f8e06e4586fcb8ace303b898/app/src/main/res/values/booleans.xml#L3

**Comment by mikepenz** [comment]
Will be in a future release. additionally please note that you can still always enable the content provider for the context :)
