### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/iconics/IconicsColor

### ISSUE THREAD

**Issue by ravilukka** [mikepenz/Android-Iconics#509]
App crash and getting following error:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/iconics/IconicsColor

sample code:
ActionItemBadge.update(this, mainMenu.findItem(R.id.notification_action), CommunityMaterial.Icon.cmd_bell_outline,
                    ActionItemBadge.BadgeStyles.RED, notification);

**Comment by mikepenz** [comment]
`ActionItemBadge` was not updated for Iconics 5.x 

This is an issue of the `ActionItemBadge` library: https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/build.gradle#L22
