### ISSUE TITLE
`IconicsTextView` Espresso Support

### ISSUE THREAD

**Issue by ibrahimyilmaz** [mikepenz/Android-Iconics#510]
## About this issue

As a developer, we would like to assert the text in `IconicsTextView`. 

- Missing Android Espresso Test Support for `IconicsTextView`
- We can't easily use `withText` function of Espresso Tests and we get this error:

```sh
Expected: with string from resource id: <2131755121>[network_error_message] value: {faw-wifi} Unable to connect to the internet. Please check your network connection.
Got: "IconicsTextView{id=2131296376, res-name=errorTextView, visibility=VISIBLE, width=1080, height=92, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@876feff, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=820.0, text= Unable to connect to the internet. Please check your network connection., input-type=0, ime-target=false, has-links=false}"
```

```kt
onView(withId(R.id.iconicsTextView))check(
            matches(
                withText(message)
            )
        )
```
Workaround:
```kt
//IconicsEspresso Helper
import android.view.View
import androidx.annotation.StringRes
import androidx.test.espresso.matcher.ViewMatchers
import androidx.test.platform.app.InstrumentationRegistry
import com.mikepenz.iconics.utils.buildIconics
import org.hamcrest.Matcher

fun withIconsText(@StringRes message: Int): Matcher<View> = ViewMatchers.withText(
    InstrumentationRegistry.getInstrumentation().targetContext.getString(message)
        .buildIconics().toString()
)
```

if you want, I would like to contribute testing of(there is no atm) `Android-Iconics`. 

## Details
- ~~[ ] Used library version `Latest Version`~~
- ~~[ ] Used support library version~~
- ~~[ ] Used gradle build tools version~~
- ~~[ ] Used tooling / Android Studio version~~
- ~~[ ] Other used libraries, potential conflicting libraries~~

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I'll absolutely appreciate help with testing 😄 anything to make the library better if ls always appreciated

**Comment by mikepenz** [comment]
I am gonna close this ticket due to inactivity. If you still want to open a PR to improve this it would be highly appreciated.
