### ISSUE TITLE
Iconics v5.0.3 java interoperability

### ISSUE THREAD

**Issue by tfreeman82** [mikepenz/Android-Iconics#511]
Is v5 fully compatible with Java? I'm attempting to update in a hybrid Java/Kotlin product using custom font class and get compiler errors.

error: cannot access ITypeface
                instance.genericFont.registerIcon(icon.name, icon.iconCharacter);
                                    ^
  class file for com.mikepenz.iconics.typeface.ITypeface not found

error: cannot access IIcon
            IconicsDrawable iconDrawable = new IconicsDrawable(EdgeApplication.getInstance(), PREFIX + __ + name);
                                           ^
  class file for com.mikepenz.iconics.typeface.IIcon not found

**Comment by mikepenz** [comment]
@tfreeman82 v5 is no longer targeted at a java audience and it's really suggested to use it in kotlin projects. 

You most likely will get it running but there's no main support from our side. 
If some JVM annotation is needed in some places we are happy to take PRs to improve interop, but it's not a goal of this project anymore. 


Kotlin is the future :D

**Comment by tfreeman82** [comment]
Ok, I had a feeling that was going to be the answer. I guess I'll just have to push to do a full Kotlin conversion of our product.
Thank you for the quick reply!

**Comment by mikepenz** [comment]
If you don't need anything from V5 the old versions will still work perfectly fine ☺️.
