### ISSUE TITLE
Can't access IIcon

### ISSUE THREAD

**Issue by SaeedRe** [mikepenz/Android-Iconics#515]
## About this issue

I updated iconics to 5.0.3 in my project but now I can't use type safe icons from icon libraries and I have to pass the icon name to IconicsDrawable constructor.

`IconicsDrawable(context, GoogleMaterial.Icon.gmd_account_circle)`

Error : None of the following functions can be called with the arguments supplied.
```
<init>(Context, IIcon) defined in com.mikepenz.iconics.IconicsDrawable
<init>(Context, Char) defined in com.mikepenz.iconics.IconicsDrawable
<init>(Context, String) defined in com.mikepenz.iconics.IconicsDrawable
<init>(Resources, Resources.Theme? = ...) defined in com.mikepenz.iconics.IconicsDrawable
```
GoogleMaterial.Icon.gmd_account_circle returns Icon class not IIcon.
Isn't this because you separated IIcon class to a different module?

## Details
- [5.0.3] Used library version
- [latest androidx] Used support library version
- [4.0.1] Used gradle build tools version
- [4.0.1] Used tooling / Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The method exists: https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt#L377

Are you doing it from kotlin?

**Comment by SaeedRe** [comment]
Yes, the constructor exits and I'm calling it from kotlin.
The problem is that `GoogleMaterial.Icon.gmd_account_circle` does not return an instance of `IIcon` class.

**Comment by SaeedRe** [comment]
The problem was related to the way I added the library before version 5.0.3.
Removing @aar from the dependency fixed the problem.
`com.mikepenz:iconics-core:5.0.3@aar`
to
`com.mikepenz:iconics-core:5.0.3`

**Comment by mikepenz** [comment]
Thanks for reporting the solution. I think the problem is that the `@aar` will prevent transitive dependencies to not get resolved

**Comment by mikepenz** [comment]
The readme doesn't state it (just for the font plugins) 

Hope all works great now
