### ISSUE TITLE
"Wrong icon name: gmi_facebook_box"

### ISSUE THREAD

**Issue by sidthakkar12** [mikepenz/Android-Iconics#516]
Hello, this in the context of the issue I'm facing while generating signed APK, the error says "Wrong icon name: gmi_facebook_box", and thus no icons are loading, but same is working excellent with debug APK. Can you please put a look into this! 

I'm using below dependencies (without updating):
implementation 'com.mikepenz:iconics-core:3.0.3@aar'
implementation 'com.mikepenz:iconics-views:3.0.3@aar'
implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.4@aar'
implementation 'com.mikepenz:fontawesome-typeface:5.0.6.0@aar'
implementation 'com.mikepenz:community-material-typeface:2.0.46.1@aar'

And after updating:
implementation 'com.mikepenz:iconics-core:5.0.3'
implementation 'com.mikepenz:iconics-views:5.0.3'
implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.4@aar'
implementation 'com.mikepenz:fontawesome-typeface:5.9.0.0-kotlin@aar'
implementation 'com.mikepenz:community-material-typeface:5.3.45.1-kotlin@aar'

Looking forward to your response, as sooner I need to upload the app. Thank you.

**Comment by mikepenz** [comment]
the `material-design-iconic-typeface` dependency you include is not the `-kotlin` version. and as such incompatible with the v5 release. 

```
implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.6-kotlin@aar'
```

would be the right dependency

**Comment by sidthakkar12** [comment]
Yes, I updated as per your guidance, the error message is not coming but no icons are loading like "cmd_facebook", etc. in signed APK, whereas it loads in debug APK!!

**Comment by mikepenz** [comment]
@sidthakkar12 do you obfuscate the icon classes? 

You may can consider (if the names should be kept for the icons) to keep those:

```
-keep class com.mikepenz.iconics.typeface.** { *; }
```

**Comment by sidthakkar12** [comment]
Yes Mike, I've enabled shrinking and thus kept 2 rules:

-keep class com.mikepenz.iconics.** { *; }
-keep class com.mikepenz.iconics.typeface.** { *; }

But still the same.

**Comment by mikepenz** [comment]
could you send me the apk per e-mail so I can look into the bytecode if obfuscation may be the culprint? 
the behavior at least sounds like obfuscation is causing something to fail. 

You also did register the different fonts in your application (or before you use them)?

https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.kt#L29
