### ISSUE TITLE
Font mapping legend

### ISSUE THREAD

**Issue by khalid-hussain** [mikepenz/Android-Iconics#52]
Hi there,

I've recently used your library in my app but have an issue which I hope you can clarify. A disclaimer: I'm a beginner at Android programming. I've attached a screenshot to show you exactly what happens.

I have two icons next to each other in an XML as so:
````xml
<com.mikepenz.iconics.view.IconicsButton
                    android:id="@+id/button_share"
                    android:layout_width="48dp"
                    android:layout_height="48dp"
                    android:layout_centerVertical="true"
                    android:layout_toLeftOf="@+id/button_star"
                    android:background="?attr/selectableItemBackgroundBorderless"
                    android:text="{gmd-favorite-outline}"
                    android:textColor="@color/primary_dark_material_light"
                    android:textSize="24sp" />

<com.mikepenz.iconics.view.IconicsButton
                    android:id="@+id/button_star"
                    android:layout_width="48dp"
                    android:layout_height="48dp"
                    android:layout_alignParentRight="true"
                    android:layout_centerVertical="true"
                    android:background="?attr/selectableItemBackgroundBorderless"
                    android:text="{faw-star-o}"
                    android:textColor="@color/primary_dark_material_light"
                    android:textSize="24sp" />
````

The button using Font Awesome renders perfectly but the button using GMD just shows me the text. What am I doing wrong?

Here is the screenshot:
![gmd](https://cloud.githubusercontent.com/assets/3102714/8865165/b3b51f18-31dd-11e5-835d-9bd4306406a4.png)

Can the legend for the different fonts be added to the README as well?

**Comment by mikepenz** [comment]
@khalid-hussain you are searching for this one: https://github.com/mikepenz/Android-Iconics/blob/develop/library/src/main/java/com/mikepenz/google_material_typeface_library/GoogleMaterial.java#L371

the legend can be probably added to the wiki, but is not required as the names are also shown on the sites of those fonts https://www.google.com/design/icons/#ic_favorite_border

**Comment by khalid-hussain** [comment]
I have also seen this: https://github.com/mikepenz/Android-Iconics/blob/develop/library/src/main/java/com/mikepenz/iconics/typeface/FontAwesome.java

But we know that when using these icons, we replace '_' with '-'. This is the legend I was referring to. Anyway, after some testing, I realize the problem is with the Android version. I've attached the XML part along with screenshots from an emulator and my real device (Samsung Galaxy Note 2 N7100 with CyanogenMod L 5.1.1).

````xml
<com.mikepenz.iconics.view.IconicsButton
                    android:id="@+id/button_share"
                    android:layout_width="48dp"
                    android:layout_height="48dp"
                    android:layout_centerVertical="true"
                    android:layout_toLeftOf="@+id/button_star"
                    android:background="?attr/selectableItemBackgroundBorderless"
                    android:text="{gmd-share}"
                    android:textAllCaps="false"
                    android:textColor="@color/primary_dark_material_light"
                    android:textSize="24sp" />

<com.mikepenz.iconics.view.IconicsButton
                    android:id="@+id/button_star"
                    android:layout_width="48dp"
                    android:layout_height="48dp"
                    android:layout_alignParentRight="true"
                    android:layout_centerVertical="true"
                    android:background="?attr/selectableItemBackgroundBorderless"
                    android:text="{faw-star-o}"
                    android:textColor="@color/primary_dark_material_light"
                    android:textSize="24sp" />
````

Here is the screenshot from my emulator running KitKat 4.4.4 (please forgive the orientation, I use a laptop with 1366x768 resolution and a portrait orientation is difficult to manage):
![emu](https://cloud.githubusercontent.com/assets/3102714/8870901/1a5a3c58-3224-11e5-809c-5fa6bf3f6d97.png)

And here is the screenshot from my actual device:
![device](https://cloud.githubusercontent.com/assets/3102714/8870912/3074c2ec-3224-11e5-80a0-c60371993c9d.png)

I hope the problem is clear now?

**Comment by mikepenz** [comment]
@khalid-hussain not sure. first you showed a screenshot from a broken icon. now there are two different icons. i assume you have different layouts for different screen resolutions or different orientations and you just missed to modify it in one of those

**Comment by khalid-hussain** [comment]
Yes this is correct. The following icon gives me an error in both the emulator and real device.
    android:text="{gmd-favorite-outline}"

Changing it to
    android:text="{gmd-share}"

gives me the second error. I actually need the "gmd-share" icon. I used "gmd-favorite-outline" to test whether it was a problem from my implementation or from the library since I saw its usage in the README.

**Comment by mikepenz** [comment]
@khalid-hussain because it does not exist. i showed you that it is named "gmd-favorite-border" in the first answer. 

i will fix it in the readme

**Comment by khalid-hussain** [comment]
Okay, what about the error with "gmd-share"? Any idea why it shows in one Android version and not the other?

Thank you very much for the help so far.

**Comment by mikepenz** [comment]
as mentioned in this comment https://github.com/mikepenz/Android-Iconics/issues/52#issuecomment-124446641 i only see that you use two different icons? i don't see an icon not working

**Comment by khalid-hussain** [comment]
The 'gmd-share' icon is showing as a "+1" in lollipop whereas it works fine in the emulator. I hope this is clear.

**Comment by mikepenz** [comment]
@khalid-hussain read my comment again pls: https://github.com/mikepenz/Android-Iconics/issues/52#issuecomment-124447494

the +1 symbol is a different icon. i think you mix up different layouts

**Comment by khalid-hussain** [comment]
[These](https://github.com/khalid-hussain/HisnulMuslim/tree/Favorite/app/src/main/res/layout) are all the layouts I have.

The one in question, is this [one](https://github.com/khalid-hussain/HisnulMuslim/blob/Favorite/app/src/main/res/layout/dua_detail_item_card.xml).

Are you 100% sure it is to do with my layout?

**Comment by mikepenz** [comment]
it has to be something project specific because it displays the share icon. and in the special case of the tablet it shows a different icon. The iconics library does not change to a different icon if you use a different android version or screen resolution. never had any such problem in all of my projects which run on many thousands of devices.

**Comment by khalid-hussain** [comment]
I don't have any layouts for tablets specified yet. Okay, I'll try some more debugging and get back to you if there are any results.

Thanks for all the help.

**Comment by mikepenz** [comment]
@khalid-hussain ok great :). i really can't reproduce this anywhere. so perhaps you should search for occurencies of the +1 drawable
