### ISSUE TITLE
Add a way to show preview in Android Studio layout view

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/Android-Iconics#526]
Don't know if possible but is there anyway when using a IconicsImageView or IconicsButton to show in the previews and process in the android studio preview.

For example

```
<com.mikepenz.iconics.view.IconicsImageView
    android:id="@+id/theme_switch_btn"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="16dp"
    android:tooltipText="@string/switch_theme"
    app:iiv_color="?attr/colorOnPrimary"
    app:iiv_icon="cmd-theme-light-dark"
    app:iiv_size="24dp"
    app:layout_constraintBottom_toBottomOf="@id/header"
    app:layout_constraintStart_toStartOf="parent"/>
````
for example this just shows as an empty view basically in the studio preview of the layout

**Comment by mikepenz** [comment]
As far as we've found it's not possible sadly. What we've done though is that it renders empty. In the past it would not have been able to render at all.

**Comment by CarlosEsco** [comment]
ok makes sense.  What i usually do is just add a tools background color and tools layout size so at least there is something to "simulate" where it is.  Thanks though
