### ISSUE TITLE
Plans to upgrade community material icons?

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/Android-Iconics#527]
http://materialdesignicons.com/cdn/5.7.55/

There ~200 new icons added since  the currently used version

https://dev.materialdesignicons.com/upgrade

**Comment by sawargicms** [comment]
Jika Untuk pembuatan Website bagaimana pemasangan modul nya??

**Comment by eclectice** [comment]
Hi, I would like to ask about the CommunityMaterial updates for the older Java AndroidX version since I encounter issue #524 when using the CommunityMaterial Kotlin library v5.1.0 with my Java codes.

**Comment by mikepenz** [comment]
@eclectice there are no plans to update legacy releases of the library. 

You may be able to build your own custom font class inside your project based on the newer source though. have a look at how the java class is looking, and bring over the details from the new kotlin one. 

You may want to consider though to upgrade to the new version and get started with kotlin :) 

also the community material icon set is huge, you may not need that amount if icons in your project
