### ISSUE TITLE
How to have a round background for Icon?

### ISSUE THREAD

**Issue by rajkshah14** [mikepenz/Android-Iconics#55]
Hello Mike

Thank you for your library, it work like charm.

I want to add a round background behind icon? Like black round background and white icon.
I am trying to do by converting to bitmap. What would be optimal way to do so?

TIA :)

**Comment by mikepenz** [comment]
you can have such a background by setting a rounded corner for the background `roundedCornersRxDp`

**Comment by rothschild86** [comment]
Or use material design FAB:

mMyFab.setImageDrawable(new IconicsDrawable(getApplicationContext(), GoogleMaterial.Icon.gmd_attach_file).color(Color.WHITE).sizeDp(16));

Ref: https://github.com/Clans/FloatingActionButton/issues/55
