### ISSUE TITLE
Consider to replace Google Material Design icon by https://materialdesignicons.com/

### ISSUE THREAD

**Issue by anticafe** [mikepenz/Android-Iconics#56]
New Material Design icon is in https://github.com/templarian/MaterialDesign/, or https://materialdesignicons.com/.

Why I think we should replace official Google Material Design icon by new Material Design icon?
- New Material Design icon includes Google Material Design icon.
- There are many more icons in New icon pack (>1000) than the Google icon pack, such as icon google-play...

**Comment by mikepenz** [comment]
@anticafe those are not the original material icons by google. Those are in as default. But you can have the Material Design Community icons via the addon which is available https://github.com/mikepenz/Android-Iconics#available-fonts (an update to those was merged a few moments ago. will publish it soon)
