### ISSUE TITLE
Icons not showing in androidx.appcompat.widget.Toolbar on Android 9

### ISSUE THREAD

**Issue by sschueller** [mikepenz/Android-Iconics#566]
## About this issue

I am using the following code to populate icons in item elements in the ```androidx.appcompat.widget.Toolbar``` and it works on android 10 but not on android 9. On Android 9 the icons are not drawn and there is no errors in the log.
```
menu.findItem(R.id.action_account).setIcon(
    new IconicsDrawable(this, FontAwesome.Icon.faw_user_circle));
```
I recently updated from an old version of Iconics to 5 and made the changes mentioned in the migration guide.

Did I miss something?

In the README.md there is still a statement about using ```IconicsDrawable(this, "faw-adjust").actionBar()``` but ```actionBar()``` results in an syntax error since 5 so I am confused why that in there.

Full code is here: https://github.com/sschueller/peertube-android/blob/develop/app/src/main/java/net/schueller/peertube/activity/VideoListActivity.java#L131
https://github.com/sschueller/peertube-android/blob/develop/app/src/main/res/menu/menu_top_videolist.xml
https://github.com/sschueller/peertube-android/blob/develop/app/src/main/res/layout/activity_video_list.xml#L16

Thanks

## Details
- Lib: 5.2.4
- Android Build Tools: 29
- Gradle: 6.1.1
- Tools: Fastlane / Android Studio 4.1.2
- https://github.com/sschueller/peertube-android/blob/develop/app/build.gradle

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by zTrap** [comment]
`actionBar()` is [still available](https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-core/src/main/java/com/mikepenz/iconics/utils/IconicsDrawableExtensions.kt#L130) in 5 version but as kotlin extension. Iconics now is kotlin-first and doesn't provide new features for Java users. Last actual version for java you can find in README

**Comment by mikepenz** [comment]
@sschueller please consider to use the latest version only in a kotlin environment. (on that note you should really start using it, you will never want to go back after falling in love with Kotlin) 

That being said. the `actionBar()` function itself only consists of specifying size and padding:
https://github.com/mikepenz/Android-Iconics/blob/4329582f57adda90cb2105c2800926929244311c/iconics-core/src/main/java/com/mikepenz/iconics/utils/IconicsDrawableExtensions.kt#L104-L105

Hope this resolves your question :)

**Comment by sschueller** [comment]
Thanks, I was going to convert to Kotlin eventually just haven't had the time :)

**Comment by sschueller** [comment]
Just FYI, this issue was resolved by using Kotlin and making the call like this:

```
menu.findItem(id.action_account).icon = IconicsDrawable(this, faw_user_circle).actionBar()
```
