### ISSUE TITLE
rectangle instead of a drawable

### ISSUE THREAD

**Issue by rothschild86** [mikepenz/Android-Iconics#57]
Keep getting this:

![2015-07-26_142152](https://cloud.githubusercontent.com/assets/4555882/8895280/c877f2f2-33a1-11e5-8dd6-6f39ce6964e7.png)

I'm on eclipse. Any idea what it could be? Was trying FontAwesome.Icon.faw_edit, but it's the same for all...

Cool lib. Thank you :)

**Comment by mikepenz** [comment]
@rothschild86 i can't give support for eclipse as it is officially not supported anymore. i assume it just parses or handles the font file wrong

**Comment by rothschild86** [comment]
That's cool if you don't want to look into it, but what would be your intuition on why this happens? I know the lib can find the ttf (it throws resource not found if ttf is not there).

**Comment by mikepenz** [comment]
How do you create the iconicsDrawable in the upper sample? Have you tried creating the drawable via code? will it work then? what's your android version?

**Comment by rothschild86** [comment]
new IconicsDrawable(context, FontAwesome.Icon.faw_edit).color(Color.WHITE).sizeDp(16)

Tested android 2,4,5 - same box

**Comment by mikepenz** [comment]
@rothschild86 seems like eclipse messes something up. never had such an issue when creating the icon via code. 

why can't you switch to the official supported android dev environment?

**Comment by rothschild86** [comment]
spoke too soon. the lib was swallowing the exception. had to move the ttf from the library into the project itself.

We can switch. It's just the matter of finding time to do it. 

Thank you for the lib!

**Comment by mikepenz** [comment]
ok great you found a solution ;)
