### ISSUE TITLE
Error  IconicsDrawable color

### ISSUE THREAD

**Issue by fmeneuhe** [mikepenz/Android-Iconics#577]
## About this issue

I have update the libraries to:
`implementation "com.mikepenz:iconics-core:${latestAndroidIconicsRelease}"
implementation "com.mikepenz:iconics-views:${latestAndroidIconicsRelease}" 
implementation 'com.mikepenz:google-material-typeface:4.0.0.1-kotlin@aar'    
implementation 'com.mikepenz:fontawesome-typeface:5.9.0.2-kotlin@aar'
implementation 'com.mikepenz:community-material-typeface:5.8.55.0-kotlin@aar'
implementation 'com.mikepenz:ionicons-typeface:2.0.1.3@aar'`

In my Java code I use to have:
`new IconicsDrawable(this, GoogleMaterial.Icon.gmd_search).color(Color.WHITE)`

Now the "color" method is missing. I took a loot at the migration guide but I could not find the solution.
How can I set the color to the IconicsDrawable now?
Thanks

**Comment by mikepenz** [comment]
The latest release is mainly meant for Kotlin. Most helper functions are actually extension functions and won't be available from java. 

The intended usage is:https://github.com/mikepenz/Android-Iconics#use-as-drawable
