### ISSUE TITLE
Menu icons missing

### ISSUE THREAD

**Issue by HilaryN** [mikepenz/Android-Iconics#580]
## About this issue

On upgrading from 5.0.3 to 5.2.8 the menu icons specified in xml layout have disappeared from the Toolbar.  In fact the issue seems to occur when upgrading from 5.0.3 to 5.1.0.
The menu items are there – tapping in the position where I would expect them to appear produces the expected action, but the icon doesn't show.

Here is the project:
https://github.com/cyclestreets/android/

To try and simplify things I have created an empty project, copied over the relevant bits of code and verified that the same issue occurs when upgrading from 5.0.3:

https://github.com/HilaryN/Test-menu-option-icons

I've looked through the documentation but can't find anything to explain this.

I can get the icons to appear using IconicsDrawable function, but they don't appear just with the xml layout.

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@HilaryN have you given those items a size?

**Comment by HilaryN** [comment]
Hi Mike.

Yes, the size is in the xml.

**Comment by mikepenz** [comment]
Can you reproduce this issue with the sample app?

**Comment by HilaryN** [comment]
Hi Mike.

I reproduced it here, in a very basic app:
https://github.com/HilaryN/Test-menu-option-icons

Do you mean, can I reproduce it in your sample app,
https://github.com/mikepenz/Android-Iconics/tree/develop/app
?

I haven't as yet.  How would I download the code?  (I'm not sure I have access as I can't see a Code / download button:
![image](https://user-images.githubusercontent.com/59799824/119991815-c2a33000-bfc1-11eb-814a-89366b4edfbd.png)


I note that in the MainActivity for your sample app it's calling the IconicsDrawable function - adding this in the app I am working on does make the icons appear, but not calling it and just defining the icons in the xml means that the icons don't appear after 5.1.0, whereas in 5.0.3 they did appear without using the IconicsDrawable function.

**Comment by mikepenz** [comment]
@HilaryN the issue is that you disable the font registration logic by preventing the app-startup library to work

```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            tools:node="remove" />
```

allowing the initialisation to occur as expected things will work again. 

In case you really really don't want the startup library to function (which may also break all sorts of other libraries) you will have to manually register fonts you use via xml

```kotlin
(before init)
Iconics.registerFont(GoogleMaterial)
```
