### ISSUE TITLE
Need help with migration

### ISSUE THREAD

**Issue by msegmx** [mikepenz/Android-Iconics#581]
## About this issue

I have code from around 2017 (pre-Kotlin) that I want to migrate using the latest version of Android-Iconics.

This instantiated an IconicsDrawable object:

```
                new IconicsDrawable(
                        context,
                        GoogleMaterial.Icon.gmd_keyboard_arrow_right
                )
                .sizeDp(size)
                .paddingDp(padding)
                .color(colorWidgetTitle)
                .toBitmap()
```

This is what I have so far:

```

        IconicsSize dp = IconicsSizeDp.dp(size); // size = int
        IconicsColor color = IconicsColor.colorInt(color); // color = int

        new IconicsDrawable(
                        context,
                        GoogleMaterial.Icon.gmd_keyboard_arrow_right.getCharacter()
        ).toBitmap();

```

How can I add _padding_, _IconicsSize_, and _IconicsColor_ to IconicsDrawable?

The migration guide says "_IconcisDrawable now depends on the resources and theme, and tries to eliminate dependency on the Context_". Since I'm still using context in the constructor, what would be the proper way of instantiating an IconicsDrawable?

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
  (Looked at source code, but at this point, Kotlin is like Chinese to me)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@msegmx the new version is mainly targeted for kotlin users, it looks like you are trying to use it from a java project still though.

All those functions to set the above values are extension functions and won't be available from java.

**Comment by msegmx** [comment]
Ah ok, it seems they have to be called via static methods in Java. Will give it try or simply go back to a previous version. Thanks!

**Comment by chrisonline** [comment]
@mehmetgunacti Did you find a solution to call this from Java? I am now in the same situation.

**Comment by mehmetgunacti** [comment]
@chrisonline I didn't look for an alternative, the old (Java) version is still good enough for my app.

**Comment by chrisonline** [comment]
> @msegmx the new version is mainly targeted for kotlin users, it looks like you are trying to use it from a java project still though.
> 
> All those functions to set the above values are extension functions and won't be available from java.

@mikepenz Does this mean I can't use the newest version with Java anymore?

**Comment by mikepenz** [comment]
The newest version is only created for (and tested with) Kotlin.

**Comment by chrisonline** [comment]
Very sad, but thanks for the info.

**Comment by mikepenz** [comment]
Depending on your usecase, you probably could achieve a thing Kotlin based wrapper class which does the respective API adjustments to allow Java classes to use it.

**Comment by chrisonline** [comment]
I need only to set the icon size, padding and color. So the extension functions.
You mean I write a Kotlin wrapper class, so I can call this Kotlin wrapper from Java?

**Comment by mikepenz** [comment]
Indeed. A Kotlin class which is able to access the respective functions of the library, but created so it's compatible with Java. 

One note on this. the `IconicsDrawable` has functions which should be available from Java: 

https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt#L200 -> `setSizeXPx`
https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt#L249 -> `setPaddingPx`
https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt#L66 -> `setColorList`

(the extension functions in Kotlin also call these in the end)

**Comment by chrisonline** [comment]
Thank you very much for your input and help.  
So I will try to use the "set methods". I have thought that this set methods are not available anymore because of the Kotlin functions.  
Great, this would fit my needs.
