### ISSUE TITLE
Question regarding FloatingActionButtons coloring.

### ISSUE THREAD

**Issue by jatsqi** [mikepenz/Android-Iconics#584]
## About this issue
Hey,
i have been using this awesome library for a while now and everything works pretty smoothly overall, but I ran into an issue when it comes to FloatingActionButtons.

The button looks like this:
```kotlin
    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/button_edit_toggle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="16dp"
        android:layout_marginBottom="16dp"
        android:clickable="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />
```

The icon is set via Kotlin at runtime:

```kotlin
val icon = IconicsDrawable(requireContext(), OutlinedGoogleMaterial.Icon.gmo_android).apply {
            colorInt = Color.WHITE
            sizeDp = 50
        }
editToggleButton.setImageDrawable(icon)
```

The icon of the button still appears black, even though I set the color to white. Is this some limitation of the library when it comes to these drawables or did I something wrong here?
This scenario works perfectly fine with the IconicsImageView btw.

## Details
- [5.2.8] Used library version
- Android Studio Emulator, API Level 30 

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@jatsqi sounds like you may have some tinting applied to the FAB. 

Make sure that the tint color from the FAB matches your expectation, as tinting will overrule bare color of drawables.

**Comment by jatsqi** [comment]
@mikepenz Thank your for that advise, I didn't know that such an modifier for drawables even existed.

I solved this as follows, if someone else has a similar problem.
```kotlin
button.imageTintList = null
```
