### ISSUE TITLE
java.lang.NullPointerException for IconicsImageView in 1.5.1/1.5.2

### ISSUE THREAD

**Issue by wKovacs64** [mikepenz/Android-Iconics#59]
Tried migrating from 1.3.0 to 1.5.2 but ran into a NPE when trying to use `IconicsImageView`. Created a blank test project, added the dependency in build.gradle (full, not core), and created a simple `IconicsImageView` (copied from the sample app):
```
<com.mikepenz.iconics.view.IconicsImageView
    android:layout_width="72dp"
    android:layout_height="72dp"
    app:iiv_color="@android:color/holo_red_dark"
    app:iiv_icon="gmd-favorite" />
```
But it causes the following:
```
08-03 00:50:39.859    3415-3415/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 3415
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #146: Error inflating class com.mikepenz.iconics.view.IconicsImageView
```
<*snip*>
```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.mikepenz.iconics.typeface.IIcon com.mikepenz.iconics.typeface.ITypeface.getIcon(java.lang.String)' on a null object reference
    at com.mikepenz.iconics.IconicsDrawable.<init>(IconicsDrawable.java:109)
    at com.mikepenz.iconics.view.IconicsImageView.<init>(IconicsImageView.java:56)
    at com.mikepenz.iconics.view.IconicsImageView.<init>(IconicsImageView.java:39)
```
Seems like `Iconics.findFont()` is returning null - can't find the font? The sample app works fine, but I didn't split it out from the locally compiled library.

Am I missing something here...?

**Comment by mikepenz** [comment]
I think it is because you do not register the Google material nor the fontawesome font. This is required now if you try to use a specific font addon via string or xml

**Comment by mikepenz** [comment]
Totally missed to add it as upgrade notes. Just mentioned it down in the how to use section

**Comment by wKovacs64** [comment]
Oh I see it now, yep. Thanks.

**Comment by mikepenz** [comment]
@wKovacs64 will add it as upgrade notes ;). I have not yet found a solution that existing fonts register them on their own. do you have an idea how i could solve this?

**Comment by mikepenz** [comment]
@wKovacs64 the main difference in the new version is that i had split up the fonts and the core. so the core is only the classes without any font included (this was previously done because so the 2 fonts were automatically in), this now allows you to save on app size by creating your own icon font with just the icons you need. (i have done this for the MaterialDrawer v4.0.0 now ;). A MaterialDrawerFont with just 3 icons -> size 5kb ;) )

**Comment by mikepenz** [comment]
README updated with upgrade notes ;)

**Comment by wKovacs64** [comment]
@mikepenz Great, thanks. Hopefully that helps anyone else who might run into this.

If `iconics` (not core) includes the fonts, why can't you register them automatically or however you did prior to 1.5.x? I haven't looked at the code changes yet, maybe that isn't possible. I might take a look if I can find some time.

**Comment by mikepenz** [comment]
@wKovacs64 the registering happens in the `Iconics` class which is now part of the core. Prior v1.5.x the `Iconics` included the `GoogleMaterial`, `FontAwesome` fonts in it's constructor. So they were added automatically, and you only had to register additional fonts. 

The registering is only required if you try to use the fonts via xml or programmatically via string (when you want to create the icon via the string name). I somehow have to find out the font class by the 3 char identifier --> "gmd" --> via the Iconics font map --> GoogleMaterial.class

I have not found yet that a class is automatically instantiated and it will register itself. (as far as i've found this is not possible), then i tried to have it via pre processor annotations, but this was not possible as this works only when i have only one module. 

I do not want compile time annotations as those will lower the performance. 

Perhaps i can go a similar approach as with the AboutLibraries, to define the fonts via xml in the resources, and i will then just try to instantiate the class via reflection and add it to the map of registered fonts. should be possible, but i would have hopped for a better solution for this problem :/

**Comment by wKovacs64** [comment]
@mikepenz Hmm, I see your point. Although I would personally take a compile time hit from annotation processing before a runtime hit from reflection (not that it would be that much). I don't care how long it takes to build as much as I care how it performs once it's on the device.

Maybe if I get some free time I will take a closer look.

**Comment by mikepenz** [comment]
@wKovacs64 great ;)
