### ISSUE TITLE
Error in inflating IconicsButton when migrating 1.3.0 to 1.5.2

### ISSUE THREAD

**Issue by aacanakin** [mikepenz/Android-Iconics#60]
Hi,
After changing `build.gradle` version, the app keeps crashing and says something like the following;
`Error inflating com.mikepenz.view.IconicsButton`. 
I tried cleaning and rebuilding the app and I tried uninstalling & reinstalling the app but it doesn't seem to be working.
Finally, if I downgrade from 1.5.2 to 1.3.0, it works.
If there are any breaking changes, please write them in release notes.

**Comment by aacanakin** [comment]
The problem is fixed when I add registering font in `Application.onCreate()` like this;
```java
public class App extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Iconics.registerFont(new FontAwesome());
    }
}
```

**Comment by mikepenz** [comment]
@aacanakin great that you solved it in the meantime. This is stated in the Upgrade notes in the README :). This is now required as i split up the project into the core and the main package. I will probably try to find a solution to don't require this but at the moment you have to do this
