### ISSUE TITLE
Using custom fonts, icons can be displayed in Java code, but not in XML

### ISSUE THREAD

**Issue by zhuzhuxiang** [mikepenz/Android-Iconics#607]
Drawable drawable_custom = new IconicsDrawable(this)
                .icon(Cniao5Font.Icon.zhu__denglong)
                .color(Color.GREEN)
                .sizeDp(150);

        ((ImageView) this.findViewById(R.id.image_custom)).setImageDrawable(drawable_custom);   √

      <TextView
           android:layout_width="50dp"
           android:layout_height="50dp"
           android:text="自定义字体{zhu_denglong}" />   ×

**Comment by mikepenz** [comment]
The `Icon` class enum should only have a single `_` for the names. 

See one off the icons provided from the library here: 
https://github.com/mikepenz/Android-Iconics/blob/develop/meteocons-typeface-library/src/main/java/com/mikepenz/iconics/typeface/library/meteoconcs/Meteoconcs.kt

I also see you use Java. Only the latest version of the library is fully supported which is targeted for Kotlin.

**Comment by saeed74** [comment]
thanks for this topic! registering my custom font in Application class was the thing that I forgot:

`Iconics.init(getApplicationContext());`
`Iconics.registerFont( MaterialDesignIcon.INSTANCE );`
