### ISSUE TITLE
Disabling AppStartup silently breaks the library

### ISSUE THREAD

**Issue by Nek-12** [mikepenz/Android-Iconics#609]
## About this issue

1. Follow [Official Google guide](https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration) on workmanager
2. The guide says "If you do not use AppStartup in your project, you can disable it"
Note: I also use Koin for DI and it has its own custom init mechanism for workmanager, which is why I disabled AppStartup.
3. Disable AppStartup in the manifest 
4. Iconics no longer resolves icons for any of the default font typefaces when trying to use their string representation e.g. "gmr_near_me", but works when using <Typeface>.getIcon()
Side effects:
* Resolving fails silently, no warnings are given because icon(String) extension function uses <typeface>?.let { } which ignores unresolved typefaces and only reports icon resolution errors
* No warnings or error are given that appStartup is disabled.

## Checklist
- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)
- [x] Spent more than 8 hours debugging this issue

### Proposed solution:  
1. Mention AppStartup in the README
2. Log typeface resolution errors in logcat 
3. Crash the app if init script has not been run properly. (Fail Early)

**Comment by mikepenz** [comment]
Thank you very much for the report @Nek-12 
I'll add a note in the README to highlight the usage of `jetpack startup` library

**Comment by Nek-12** [comment]
@mikepenz Why have you decided to ignore font resolution errors in the code?
In [this file](https://github.com/mikepenz/Android-Iconics/blob/ff5730a6bbe3044c0fafaf00a7da60babd67c40b/iconics-core/src/main/java/com/mikepenz/iconics/utils/IconicsDrawableExtensions.kt) on line 42 you do not give a warning. Is that intended and if yes, what's the reason behind?

**Comment by mikepenz** [comment]
@Nek-12 that was mainly a historic matter, adding a log for the next release.
