### ISSUE TITLE
Custom Font library import error: Expecting member declaration

### ISSUE THREAD

**Issue by mohammadnouripoor** [mikepenz/Android-Iconics#618]
Hi, I'm trying to import my custom font icon with android-iconics.mikepenz.com but when add the generated lib as module in android studio. Kotlin Class showing me an error on enum: Expecting member declaration.
Can you please help me with that?
![Screenshot (5)](https://user-images.githubusercontent.com/17921848/160279141-a855ea98-8a6d-4191-bee1-92c105d0e4c1.png)

**Comment by saeed74** [comment]
removing `:` will fix this.
so `pho_activity:('\uf230')` must be `pho_activity('\uf230')` for example.

**Comment by mikepenz** [comment]
@mohammadnouripoor sadly some of the more recent icon fonts have a different css format which can cause the above problem. 

Please follow and remove the `:` as outlined by @saeed74 (thanks).
