### ISSUE TITLE
Min version question

### ISSUE THREAD

**Issue by logcat** [mikepenz/Android-Iconics#62]
It looks like library works perfectly on version 9, is there any particular reason that lib minSdk is 10?

**Comment by mikepenz** [comment]
@logcat it is probably possible to use it on API 9, but this version is only used by a tiny number of people: https://developer.android.com/about/dashboards/index.html

As an additional note, i do not like to release it for an API version i can't test on a real device, nor i will on an emulator. 

If you need it for 9 you can include the source in your app.

**Comment by logcat** [comment]
ok, seems legit, and when somebody want in on 2.3 in 2015 it can be done via adding tag to manifest
```
<uses-sdk tools:overrideLibrary="com.mikepenz.iconics, com.mikepenz.iconics.core"/>
```

**Comment by mikepenz** [comment]
@logcat that's true. thanks for this info ;)
