### ISSUE TITLE
Upgrade from 3.x to 5.x

### ISSUE THREAD

**Issue by chrisonline** [mikepenz/Android-Iconics#629]
I am currently using the **3.x core** and want to upgrade to **5.x**!  
If I add the latest core
```
def latestAndroidIconicsRelease = "5.4.0"
implementation "com.mikepenz:iconics-core:${latestAndroidIconicsRelease}"
implementation 'com.mikepenz:community-material-typeface:7.0.96.0-kotlin@aar'
```

I get after gradle.sync following error:
```
Failed to resolve: com.mikepenz:iconics-core:5.4.0
Show in Project Structure dialog
Show Details
Affected Modules: app

Failed to resolve: com.mikepenz:community-material-typeface:7.0.96.0-kotlin
Show in Project Structure dialog
Show Details
Affected Modules: app
```

What do I wrong?

**Comment by mikepenz** [comment]
The artifacts are hosted on `maven central` please make sure your project allows iconics artifacts to be resolved from that source. 

https://mvnrepository.com/artifact/com.mikepenz/iconics-core

**Comment by chrisonline** [comment]
Yes of course I have maven central.
Have now tried it again and now it is working. Seems there was an outage or something else.

I'm sorry I bothered you, but I have tried to sync multiple times before.
