### ISSUE TITLE
Wrong icon name: faw-android

### ISSUE THREAD

**Issue by goku143u** [mikepenz/Android-Iconics#632]
## About this issue

Looks like, library needs to be update

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- implementation 'com.mikepenz:iconics-core:5.4.0'
- implementation 'com.mikepenz:fontawesome-typeface:5.13.3.0-kotlin@aar'
- All Android Versions

**Comment by mikepenz** [comment]
The icon name is from the font mapping. as these are auto generated they can't be changed without breaking the generation. 

As I currently don't have further updates planned to the font awesome icon set. closing as not planned
