### ISSUE TITLE
Can I get source code for the iconpack creator tool?

### ISSUE THREAD

**Issue by Nek-12** [mikepenz/Android-Iconics#634]
I'm improving my icon pack generator script and I would like to let the user skip the process of uploading the file. For that I need the code that translates icon fonts to kt files. Is it available anywhere?

**Comment by mikepenz** [comment]
I suppose you refer to: https://android-iconics.mikepenz.com/ ?

It's sources are not available. In recent years I mostly modified the compiled javascript for smaller tweaks. you probably can download all needed files via the chrome dev tools and adjust it similarly

**Comment by Nek-12** [comment]
Yes, I did refer to that.
Okay, I'll try chrome dev tools. The output there is not very easy to read / navigate, but that should suffice.

**Comment by mikepenz** [comment]
Yeah it's unfortunate. when I originally created the web page, I used a some javascript build tools and project setup, but all of that seems to no longer maintained, as such won't work with recent node versions. So I ended up never open sourcing it...

**Comment by Nek-12** [comment]
Okay, I pondered for some time what to do about the issue itself and decided it's not useful for you to keep it open. Your suggestion, albeit not perfect, works for me.
