### ISSUE TITLE
Interface IIcon is unstable.

### ISSUE THREAD

**Issue by Nek-12** [mikepenz/Android-Iconics#635]
## About this issue
The IIcon parameter of the Image composable is unstable, which leads to unnecessary recompositions.
The IIcon interface is immutable, as all icons that inherit from it are immutable. However, Compose cannot derive the stability of the interface itself, leading to the composable being non-restartable / non-skippable. 

IIcon is widely used in our project because of the api of the `Image` itself, and in our efforts to optimize performance, we discovered that the composables are recursively unstable because of us passing the IIcon everywhere.
How can we solve this problem? 
I'm thinking about something like a wrapper value class that is going to be marked as `@Immutable`. 

```kotlin
@JvmInline
@Immutable
value class StableIcon(val icon: IIcon)  /* : IIcon by icon */

val IIcon.stable get() = StableIcon(this)
``` 

## Details
-  Used library version 5.1.0
-  Compose 1.6.0-alpha01

**Comment by mikepenz** [comment]
Thank you for the suggestion. This seems like a great proposal. I did not actually test such a usage of marking a type `Immutable` for compose. Did you check this improving optimisation in your project?

Actually have a similar ticket open for `AboutLibraries`: https://github.com/mikepenz/AboutLibraries/issues/868

I wished the annotations were available in isolation, to annotate in the core lib without adding any additional overhead.

**Comment by Nek-12** [comment]
According to compose metrics, value classes work well and make the composable stable indeed. We're using the wrapper strategy for a lot of stuff right now and are migrating our code to StableIcon. The only thing that is questionable is delegating the interface, which is why I commented it out as an optional feature. 
About the Image itself, since the composable is very thin, it doesn't need to be restartable/skippable it seems. For example, even the Painter interface from compose is unstable. The Image functions are annotated with `@NonRestartableComposable` which is made for thin wrappers around overload. We could use that annotation too. Another solution is making the Image function inline like Row/Column/Box, making Compose ignore it altogether.

**Comment by Nek-12** [comment]
The bigger problem is how we didn't notice such a small detail and ended up using the interface in a lot of places. That's what the original issue is about I guess. Preventing people from passing the interface up the hierarchy, where it would recursively make parent composables (which in our case can be very heavy on performance, like list items) nonskippable.

**Comment by mikepenz** [comment]
I maybe have something to try for you later today, which will not require the wrapping. Let's see

**Comment by Nek-12** [comment]
I don't think we should include compose in the core module...

**Comment by mikepenz** [comment]
That being said given how stable the core and typeface modules have been. This may work for you, and won't require wrapping. 

Especially as long term it looks compose got significantly better support for icons derived from SVGs

**Comment by Nek-12** [comment]
I'm sorry, I don't understand your last comment. Are you suggesting we move on from using the library?

**Comment by mikepenz** [comment]
Not really, I was mostly thinking that a lot of use-cases which used to be the reason for people using this library got replaced by direct svg usage. 
However your usecase still sounds quite valid, accessing wider part of the fonts. 

With that, I really hope the 5.5.0-compose01 version helps to fix the stability problem you had noted (based on the checks I run it reported the class now as stable) 

-----

Purely for reference on the svg to compose converter I meant for example: https://www.composables.com/svgtocompose

**Comment by Nek-12** [comment]
Yeah this gives me an idea to a next version of this library, a script or a plugin that would convert the SVG/font to an enum, but would use built-in compose functionality (shape, path) for icons instead of falling back to an Iconics implementation. I don't know if you have resources for that though, so for now all we need is for the library to stay updated.

**Comment by mikepenz** [comment]
enum was a problem for iconics given some fonts just have to many elements, which would cause compile issues. 

Anyways, I believe with `5.5.0-compose01` this ticket can be closed?

**Comment by Nek-12** [comment]
Yeah I hope so
