### ISSUE TITLE
Failed to resolve: com.mikepenz:iconics:1.6.2

### ISSUE THREAD

**Issue by mychaelgo** [mikepenz/Android-Iconics#64]
Failed to resolve: com.mikepenz:iconics:1.6.2

my gradle:

    compile 'com.mikepenz:iconics:1.6.2@aar'

**Comment by mikepenz** [comment]
@mychaelgo make sure your gradle is not in offline mode. It is available on MavenCentral: http://search.maven.org/#artifactdetails%7Ccom.mikepenz%7Ciconics%7C1.6.2%7Caar
