### ISSUE TITLE
registerFont does not work without init

### ISSUE THREAD

**Issue by ThomasGoehringer** [mikepenz/Android-Iconics#642]
## About this issue

I wasn't able to register my custom font by following the README here: https://github.com/mikepenz/Android-Iconics?tab=readme-ov-file#register-fonts
To make this work, I also had to call init before:
```
Iconics.init(applicationContext)
```

Shouldn't this be added to the README? I can of course create a pull request for it, but I just wanted to double check with you.

**Comment by mikepenz** [comment]
Good day @ThomasGoehringer thanks for the ticket. 

There shouldn't be a requirement to call it. as it would be called from other places, what was the issue you observed? Or it simply did not work?

**Comment by ThomasGoehringer** [comment]
Yes, it didn't work without calling the init function

**Comment by mikepenz** [comment]
How are you using Iconics afterwards?

**Comment by mikepenz** [comment]
Could you please provide a small sample, or snippet on how you use the font afterwards? 

`init()` is called automatically by a few different operations like creating an `IconicsDrawable` with a `Context`.
