### ISSUE TITLE
Searchview icon margin problem

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/Android-Iconics#65]
the problem I have is that when the searchview is displayed, icons in the right are tight against the edge.

Here is my toolbar with the icons (the search icon is a searchview)

![screenshot_2015-08-06-09-48-05](https://cloud.githubusercontent.com/assets/9873666/9111821/eff3d88c-3c20-11e5-9745-b13f34afd18e.png)

Here is my toolbar with the searchview displayed (the right icon is in the edge)

![screenshot_2015-08-06-09-48-10](https://cloud.githubusercontent.com/assets/9873666/9111826/f44e70b8-3c20-11e5-9278-13f55b9114ae.png)

is this a problem with Iconics library or is a android problem ?

thanks.

**Comment by mikepenz** [comment]
@seba123neo you can provide a padding to the drawables if you like. or have a custom width. This could help here. seems strange that it adds it riectly to the right edge

**Comment by mikepenz** [comment]
Please answer again if it is still a problem

**Comment by seba123neo** [comment]
yes, still the problem, I do not know how to solve, can you try to replicate it?

**Comment by mikepenz** [comment]
will it also happen with a normal drawable?

**Comment by seba123neo** [comment]
good question, I'll try and let you know...

**Comment by seba123neo** [comment]
yes, with a normal drawable also it happens...

**Comment by mikepenz** [comment]
So it's no **Android-Iconics** problem. sorry

**Comment by seba123neo** [comment]
yes, apparently is a problem of the appcompat toolbar, I've solved with this lines in the toolbar

android:contentInsetLeft="0dp"
android:contentInsetStart="0dp"

in these links are treated this problem:

http://stackoverflow.com/questions/26455027/android-api-21-toolbar-padding

http://stackoverflow.com/questions/29447043/unexplained-gap-padding-to-the-left-between-toolbar-and-linearlayout

Thanks

**Comment by mikepenz** [comment]
thanks for adding the answer ;)
