### ISSUE TITLE
Failed to load iconic imageview

### ISSUE THREAD

**Issue by nambv** [mikepenz/Android-Iconics#67]
Hi @mikepenz , I can't load iconics by using XML Layout, It not crash app but appear not thing when run app :( Can you help me plz :(

```
Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged
```

My XML is:

```
<com.mikepenz.iconics.view.IconicsImageView
                        android:id="@+id/favorite_channel_icon"
                        android:layout_width="50dp"
                        android:layout_height="50dp"
                        android:padding="5dp"
                        app:iiv_icon="gmd-repeat"/>
```
Thank you very much

**Comment by nambv** [comment]
My gradle dependencies is:
```
...
compile('com.mikepenz:materialdrawer:3.1.2@aar') {
        transitive = true
    }
compile 'com.mikepenz:community-material-typeface:1.1.72@aar'
compile 'com.mikepenz:google-material-typeface:1.2.0@aar'
```

**Comment by mikepenz** [comment]
Hi. 

The problem is that you have a version conflict with the Android-Iconics included in the Materialdrawer and the latest available version of Android-Iconics. 

With v4.0.0 of the MaterialDrawer i will include the latest version of Android-Iconics. Until you update you have to go with the older version of Android-Iconics. or you exclude the Android-Iconics dependency from the MaterialDrawer.

A version which is compatible is this one: https://github.com/mikepenz/Android-Iconics/tree/88e9d0279f4248cbe20016b72763198c35ab4bae

**Comment by nambv** [comment]
@mikepenz Thank you very much for your supported! It helped me a lot :+1:

**Comment by gpulido** [comment]
Hello,
I'm having a similar problem using iconics-core 1.7.1, google-material-typeface 1.2.0.
When I try to use the IconicsImageView with the app:iiv_icon="gmd-person" I receive a
"E/Iconics﹕ Wrong icon name: gmd_person"
If I load the images by code it works
I have made a little debugging and seems that the FONTS hashmap is not being populated before searching for the icon.
I'm also using material drawer 4.0.0rc7

**Comment by mikepenz** [comment]
@gpulido please update to the latest RC11 of the MaterialDrawer then you can just add the dependencies for the fonts you want. those are not included by default anymore to save apk size for people who don't use them.

Here are all default fonts you can include:
https://github.com/mikepenz/Android-Iconics#2-choose-your-desired-fonts

**Comment by gpulido** [comment]
@mikepenz I've just updated to the rc11 and my gradle file have now the following:

```java
 compile('com.mikepenz:materialdrawer:4.0.0.rc11-SNAPSHOT@aar') {
        transitive = true
    }
    compile 'com.mikepenz:google-material-typeface:1.2.0@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.4.0@aar'
```
Also I have added the following to the proguard-rules.pro:
```java
-keep class com.mikepenz.iconics.** { *; }
-keep class com.mikepenz.fontawesome_typeface_library.FontAwesome
-keep class com.mikepenz.google_material_typeface_library.GoogleMaterial
```
And it is still not showing the icons and  the logcat give me:
```java
Iconics﹕ Wrong icon name: gmd_place
```

**Comment by mikepenz** [comment]
@gpulido ah ok you mean it is working, but it just shows the warnging

**Comment by gpulido** [comment]
@mikepenz Unfortunatelly it isn't  working, it is not showing the icon :(

**Comment by mikepenz** [comment]
@gpulido with proguard deactivated it's also not working?

**Comment by gpulido** [comment]
@mikepenz I have just tested removing the line:

proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
from my build.gradle (I don't know if there are another way of disabling proguard)  and it still doesn't show the icons :(

**Comment by gpulido** [comment]
@mikepenz Hello again, and welcome back :)
I have upgraded to materialdrawer 4.0.0, and I still having the same problem:

I can access the icons programmatically using "new IconicsDrawable(context, GoogleMaterial.Icon.gmd_person, ....) but when I put it on the xml I receive:
```java
E/Iconics﹕ Wrong icon name: gmd_person
```
I have also updated to gradle 1.3, and sdk to 23

I'm using the following compile versions on the app.gradle
```Java
compile 'com.mikepenz:google-material-typeface:1.2.0.1@aar'
compile 'com.mikepenz:fontawesome-typeface:4.4.0.1@aar'
```

**Comment by mikepenz** [comment]
@gpulido thanks for the info. strange. registering should not be required. (i also don't do this in the sample app) 

What's the first spot you try to use the icon?

**Comment by gpulido** [comment]
@mikepenz The first time I access any Iconics element is in the "OnCreate" of the main Activity, when I create the material drawer using your library using the DrawerBuilder.

**Comment by VAdaihiep** [comment]
I have same issue: Wrong icon name gmd_xxx after i try to integrate google admob.
And thanks to @gpulido because 
```
Iconics.init(getApplicationContext());
Iconics.registerFont(new GoogleMaterial());
```
works fine (but i dont know why 😂 )
