### ISSUE TITLE
I would expect getFormattedName to have '_' replaced to '-' so can be used in code

### ISSUE THREAD

**Issue by clement9527** [mikepenz/Android-Iconics#70]
I am trying to change the icon pragmatically as the following: 

```java
mArrowIcon.setText(
  active ? 
    GoogleMaterial.Icon.gmd_keyboard_arrow_down.getFormattedName():
    GoogleMaterial.Icon.gmd_keyboard_arrow_right.getFormattedName()
);
```
It won't work as getFormattedName is using '_' instead of '-' so cannot be formatted properly. 

The fix should be pretty simple, just change getFormattedName() to the following:
```java
public String getFormattedName() {
    return "{" + this.name().replace('_', '-') + "}";
}
```

**Comment by mikepenz** [comment]
@clement9527 why don't you use an `IconicsImageView` instead?

**Comment by clement9527** [comment]
Hmm, I thought getFormattedName is for rendering purpose as you wrap it within bracket, I cannot think of another use case. I switched mine to use string resource than the enum, thanks for helping :)
