### ISSUE TITLE
IconicsButton is not working well.

### ISSUE THREAD

**Issue by h6ah4i** [mikepenz/Android-Iconics#71]
Hi. I noticed that the `IconicsButton` widget is not styled properly on my app, and I've tried to fix it.

| On Android 5.1.1  | On Android 4.4.2  |
|---|---|
| <img src="https://cloud.githubusercontent.com/assets/2552365/9459892/ab0609aa-4b3b-11e5-8679-aff892601d74.png" width="150" /> | <img src="https://cloud.githubusercontent.com/assets/2552365/9459893/ab0a1ebe-4b3b-11e5-8a7b-36d086f6936c.png" width="150" /> |

- Left side buttons:
  - original `IconicsButton` widget
- Right side buttons:
  - [`FixedIconicsButton`] (https://github.com/h6ah4i/AndroidIconicsBugCheck/blob/master/app/src/main/java/com/h6ah4i/android/example/androidiconicsbugcheck/FixedIconicsButton.java) widget

---

```java
public class FixedIconicsButton extends Button {
    public FixedIconicsButton(Context context) {
        super(context);
        // Do not set typeface here
    }

    public FixedIconicsButton(Context context, AttributeSet attrs) {
        super(context, attrs);
        // Do not set typeface here
    }

    public FixedIconicsButton(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        // Do not set typeface here
    }

    public void setText(CharSequence text, BufferType type) {
        // NOTES:
        // 1. Need to disable the All Caps option to make Spannable work properly!
        // 2. This method will be called from the constructor of the super class
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.ICE_CREAM_SANDWICH) {
            setAllCaps(false);
        }

        if(!this.isInEditMode()) {
            super.setText((new Iconics.IconicsBuilder()).ctx(this.getContext()).on(text).build(), type);
        } else {
            super.setText(text, type);
        }
    }
}
```

---

Full of the sample code is uploaded at the following repository.
https://github.com/h6ah4i/AndroidIconicsBugCheck

**Comment by mikepenz** [comment]
@h6ah4i really interesting. I already added this here:

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/Iconics.java#L339

But it seems it is not working in all cases. Thanks i'll add this to the main `IconicsButton`
