### ISSUE TITLE
default font is not rendered for some reason

### ISSUE THREAD

**Issue by clement9527** [mikepenz/Android-Iconics#72]
I have both **gmd** icon and **faw** icon used, however, **gmd** fonts are rendered properly but **faw** are not. Both are working fine if I explicitly register them in my application subclass, but from the documentation, I only need to register the font if it is custom. I wonder if I miss anything here. Please help.

**Comment by mikepenz** [comment]
@clement9527 someone else already had a similar issue, the only solution was to manually register the font. i have not yet found the solution why this happens. do you have any special packagename declaration in your build.gradle?

**Comment by clement9527** [comment]
I have it working now. I invalided the cache, cleaned the code and rebuilt. The fonts start showing up, so I think maybe it is a caching issue. I will close it. Thanks for your times response.
