### ISSUE TITLE
IconicsImageView is not displaying icons when added in XML

### ISSUE THREAD

**Issue by rafalenden** [mikepenz/Android-Iconics#74]
Hi,
thanks for this very useful library!

I'm having an issue with IconicsImageView. When I use it in XML, icon and color is not displayed in the app.

My XML:
```xml
<com.mikepenz.iconics.view.IconicsImageView
    android:id="@+id/icon"
    android:layout_width="20dp"
    android:layout_height="20dp"
    app:iiv_color="@android:color/white"
    app:iiv_icon="faw-plus"
    android:layout_marginRight="10dp"/>
```

However when I add icon to this view by code it works:

```java
@Bind(R.id.icon) IconicsImageView mIcon;
mIcon.setIcon("faw-plus");
```

Other views IconicsTextView and IconicsButton work without any problems.

My gradle file:
```json
compileSdkVersion 22
buildToolsVersion "22.0.1"
minSdkVersion 15
targetSdkVersion 22

compile 'com.mikepenz:iconics-core:1.7.4@aar'
```

**Comment by mikepenz** [comment]
@rafalenden what'S the font dependency you add?

**Comment by rafalenden** [comment]
Font dependency is:

```json
compile 'com.mikepenz:fontawesome-typeface:4.4.0.1@aar'
```

**Comment by NorbertSzydlowski** [comment]
the same issue

**Comment by mikepenz** [comment]
@rafalenden just tried the same in the sample app. empty activity with only the view you posted above. And it showed up. 

Can you create a simple demo app which would show that bug?

**Comment by waninkoko** [comment]
This is happening to me too, but only if ProGuard is enabled. Sounds like an obfuscation issue.

**Comment by mikepenz** [comment]
@waninkoko also with the latest version?

**Comment by waninkoko** [comment]
@mikepenz Yes, I also tried 1.7.2 and 1.7.3 with no luck.

Previously I was using the version that came with MaterialDrawer 3.1.2 (1.2.0) and that one worked perfectly.

**Comment by mikepenz** [comment]
@waninkoko if you manually register the fonts? 

Which version of the font addons are you using?

**Comment by waninkoko** [comment]
@mikepenz  I'm using the latest version right now for everything.

I've checked the library and looks like the typeface is found but the icon is not. If this is true, a manual registration should produce no difference.

**Comment by mikepenz** [comment]
@waninkoko interesting the font contains the proguard rules: https://github.com/mikepenz/Android-Iconics/blob/develop/fontawesome-typeface-library/build.gradle#L10

**Comment by waninkoko** [comment]
@mikepenz Yeah, this is a weird issue. I even tried to put the rules in my "proguard-rules" file with no luck.

**Comment by mikepenz** [comment]
@waninkoko can you please try manual registration of the font?

**Comment by waninkoko** [comment]
@mikepenz That worked!

**Comment by waninkoko** [comment]
@mikepenz More info about the issue:

GenericsUtil.getFields is returning an array of length 0. It is failing to resolve the ```R$string``` class.

**Comment by mikepenz** [comment]
do you have a special package name setup for your application? The `R` has normally the packagename of the application but if you modify this in your gradle it can be somewhere else. so it won't be able to find the `R`

**Comment by waninkoko** [comment]
Nope, nothing special. R class is generated in the package name of the application.

**Comment by mikepenz** [comment]
@waninkoko so `Class.forName(YOURPACKAGENAME + ".R$string")` should return the class instead of `null`

**Comment by waninkoko** [comment]
@mikepenz Yes, it does. Gonna check what ```context.getPackageName()``` is returning.

**Comment by waninkoko** [comment]
It is returning the correct package name... Ok, now I don't understand why the library is not working.

**Comment by mikepenz** [comment]
@waninkoko can you create a small sample app which would allow me to debug this bug? (or a copy of your app with everything removed but the Iconics bug :D)

**Comment by waninkoko** [comment]
@mikepenz Sure, but first I would like to look further into this issue (I feel like I'm getting close to the solution).

I have checked that ```resolveRClass``` is actually looking for the ```R$string``` class in the correct package but... it fails! And when I do ```Class.forName(YOURPACKAGENAME + ".R$string")``` it works.

**Comment by mikepenz** [comment]
@waninkoko strange. :/ in the correct package including no double dot or anyhting? case senstive?

**Comment by waninkoko** [comment]
@mikepenz Yep, the package name is 100% correct.

This is extremely weird... I've modified the library to print the full class name to the logcat. It also prints when a ```ClassNotFoundException``` is thrown. In my "Application" class, I'm calling ```GenericsUtil.getFields(context)``` and checking the returned array length, and after that I'm calling ```Class.forName(YOURPACKAGENAME + ".R$string")``` and checking if the returned class is not null.

And the result is:

- ```getFields()``` is returning an empty array. In the logcat I see that it looks in the proper package and ```ClassNotFoundException```. It also tries to find ```R$string``` in the parent package with no luck.
- ```Class.forName()```is returning the class.

Now I'm thinking about a possible culprit: MultiDex?

**Comment by waninkoko** [comment]
Wow... Now I modified ```resolveRClass()``` and replaced ```packageName + ".R$string"``` with the ```R$string``` class full name. It worked.

This makes no sense at all.

**Comment by mikepenz** [comment]
@waninkoko yeah i'm confused too. And i don't think `MultiDex` is the issue because it is working with a different app of mine containing `MultiDex`

**Comment by waninkoko** [comment]
@mikepenz After my latest test I realized MultiDex is not the culprit.

It's official now: the weirdest problem I ever had.

**Comment by mikepenz** [comment]
@waninkoko yeah really strange. can you send me a sample app perhaps i can reproduce and (fix?) the issue :D

**Comment by waninkoko** [comment]
@mikepenz Now I got to go but tonight I will prepare a sample app. Also, maybe I'll show up in Gitter to chat about this.

**Comment by mikepenz** [comment]
@waninkoko ok great. not sure if i will be still online. it's already 07:48pm here :D

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/blob/develop/README.md#proguard

**Comment by mikepenz** [comment]
Thanks @waninkoko for coming up with the solution and for helping to debug this issue

**Comment by SeunMatt** [comment]
Hello,  the IconicsButton and ImageView aint showing the icons in the design mode of android studio 1.x have added the proguard rule and yet nothing is showing. Though on running the app the icons are visible. I know you have closed this issue but please I need your help thanks.

**Comment by mikepenz** [comment]
@SeunMatt it is known that they don't show the icon in design mode, and it is not intended to be fixed as it is working in the app. 

If you have a solution for this feel free to open a Pull request with the required code changes

**Comment by SeunMatt** [comment]
Alright sir.  Thanks
