### ISSUE TITLE
Problem when I set the icon in TextView or in Radio Button.

### ISSUE THREAD

**Issue by simonesessa** [mikepenz/Android-Iconics#75]
In my project I use the mikepenz material drawer and in my xml, when I use an icon in text TextView o RadioButton, it doesn't work correctly.

This is a part of my test xml:
```
<com.mikepenz.iconics.view.IconicsTextView
            android:text="Test {faw-android}"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content" />
<TextView
            android:text="Test {faw-android}"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content" />
<RadioButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Test {faw-android}"
            android:onClick="onRadioButtonClicked"/>

```
I've added only the material drawer dependence ` compile('com.mikepenz:materialdrawer:3.1.2@aar') {transitive = true}` (I know that there is a new version) and the `com.mikepenz.iconics.view.IconicsTextView` works.
But in classic TextView and RadioButton, the result is "Test {faw-android}".

I've tried to add this dependencies (only one, all three or only last two, I did many test):
`compile 'com.mikepenz:iconics-core:1.7.4@aar'`
`compile 'com.mikepenz:google-material-typeface:1.2.0.1@aar'`
`compile 'com.mikepenz:fontawesome-typeface:4.4.0.1@aar'`
But I have always a problem with build, with the error `Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2`, also after I restarted Android Studio.
//
How can I resolve this?

**Comment by mikepenz** [comment]
@simonesessa yeah the library cna't modify the functionality of the original TextView. You would have to overwrite the behavior of the RadioButton to get the same as the IconicsTextview does. Or you use Iconics programmatically and let it create the spannable for you

the other exception you show is because you canÄT have to different verions of Iconics on the classpath.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/issues/73

```gradle
compile('com.mikepenz:materialdrawer:3.1.2@aar') {
    transitive = true
    exclude group: 'com.mikepenz', module: 'iconics'
}
```

**Comment by simonesessa** [comment]
Thanks!
