### ISSUE TITLE
Destructive Proguard rule.

### ISSUE THREAD

**Issue by Saime1942** [mikepenz/Android-Iconics#77]
Greetings Mr. Penz and I pretty appreciate for all your great works specially the Drawer.
After the loss of gray icon versions in the [official repository] (https://github.com/google/material-design-icons), I decided to put your library into practice, but something kept me away from that.
The R.java class witch includes all the id references is not quite safe to let it ship with the APK because some may use it to access all the string references including the ones with public keys.

Can I just forget the Proguard rule and register the font manually in the Application class?

**Comment by mikepenz** [comment]
@Saime1942 
It depends on how you plan to use the library. If you only use the Android-Iconics as `Drawable` there is no need to register any fonts or anything as this happens automatically. 

The registering (which is done via the `R` variable) only is required if you generate icons from the string name, or if you use them directly via `xml`. 
But no problem as you can just ignore the autodetection. obfuscate your R.java as you would to and register those fonts programmatically as shown with the `CustomFont` in the sample application https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L17 
You can do this with the addon fonts too in the same style.

**Comment by Saime1942** [comment]
That's what I was talking about!
Thanks again, for everything (Drawer, Iconics, Materialize, ...).

**Comment by mikepenz** [comment]
@Saime1942 i do not know if you can overwrite proguard rules. if not, i assume this could break your requirement for obfuscating the `R.class` 

https://github.com/mikepenz/Android-Iconics/commit/3cca9830237c6d3d5364a573566323e7c9db7291 ?

**Comment by Saime1942** [comment]
Nevermind. I am planning to use DexGuard. :)

**Comment by mikepenz** [comment]
ok thanks. :)
