### ISSUE TITLE
Unreliable icons.

### ISSUE THREAD

**Issue by Saime1942** [mikepenz/Android-Iconics#79]
As supposed, the actionbar() method is going to make the icons exactly the same size as MenuItem icons, but practically it is not.

![screenshot_2015-09-10-08-29-24](https://cloud.githubusercontent.com/assets/14172737/9779918/eb70aa9c-5796-11e5-83d8-750ce704b01a.png)

Any idea on how to resolve that?

**Comment by mikepenz** [comment]
@Saime1942 the `.actionBar` method will make the icon 24dp and 1dp padding as you found already. The thing is that google does not use 1dp padding for all of their icons and some have different paddings around the icon itself. in special cases it is required to define a custom padding to exactly match google icons. it is not possible to find the correct padding automatically as it is really different.
