### ISSUE TITLE
FuXX!!!Why not README instructions mappingPrefix length restrictions？

### ISSUE THREAD

**Issue by kongnanlive** [mikepenz/Android-Iconics#82]
I wasted four hours of time, simply because mappingPrefix length is not equal to 3！！！！fucXXXXXX！！！！！！

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/typeface/ITypeface.java#L33

**Comment by kongnanlive** [comment]
I am hoping to explain the README mappingPrefix have length restrictions, to avoid making the same mistakes newcomers @mikepenz Thanks

**Comment by mikepenz** [comment]
@kongnanlive improved the readme. ;). but you should always check the interfaces you are going to implement too :D
