### ISSUE TITLE
Size of some GoogleMaterial icons too big in Toolbar

### ISSUE THREAD

**Issue by timrae** [mikepenz/Android-Iconics#85]
For example, here is the refresh icon side-by-side with the [png version](https://www.google.com/design/icons/#ic_refresh)

![untitled](https://cloud.githubusercontent.com/assets/2818274/10345532/552e430c-6d65-11e5-884e-38f668ed0c43.png)

```java
mToolbar.getMenu().findItem(R.id.action_rebuild).setIcon(new IconicsDrawable(getContext())
                .icon(GoogleMaterial.Icon.gmd_refresh)
                .color(Color.WHITE)
                .actionBar());
mToolbar.getMenu().findItem(R.id.action_rebuild2).setIcon(R.drawable.ic_refresh_white_24dp);
```

Other icons like `GoogleMaterial.Icon.gmd_sync` seem to work more or less as expected
![sync](https://cloud.githubusercontent.com/assets/2818274/10345644/179eafee-6d66-11e5-8446-09381308fbde.png)

**Comment by mikepenz** [comment]
@timrae was already discussed here:
https://github.com/mikepenz/Android-Iconics/issues/48

The problem is that the google icons have different paddings and the icon-font icons do not contain those paddings. By default i add 1dp padding but that's to less for some, so you would have to modify the padding value for those a bit. 

It is no possible to automatically provide the same padding values for all icons via `.actionBar()`

**Comment by timrae** [comment]
Ah that's a shame... I'd rather use the pngs than fiddle around with the padding of every icon. :(
This is kind of a deal breaker issue, you might want to consider complaining to Google about it, and/or writing about it in the main README

**Comment by mikepenz** [comment]
@timrae this is no issue of google nor of the library. 

the thing is that the png's are all well prepared by the designers and define different padding to fit perfect into the system. those can be different by icon and also by icon size (but this is not common)

icon-fonts do not contain any padding around the icon as the font and the vector of the icon fills up the area. so it can be used everywhere. it does not have to contain this information. 

but this is a known thing for all icon fonts. the only solution would be that someone builds up an wiki containing all the paddings for the different icons. (or even an util class would help here)

**Comment by timrae** [comment]
I see, I guess I'll wait and see if a VectorCompat support library is ever released for API10

**Comment by mikepenz** [comment]
yeah. but i'm not sure if they include the padding in the vector icons? if yes you could create an icon font of those vectors and use it. ( i think)

**Comment by timrae** [comment]
there are pre-defined 24px svg set for all the icons e.g.:
https://github.com/google/material-design-icons/tree/master/action/svg/design

**Comment by mikepenz** [comment]
hmmm should be tried if those contain the padding

**Comment by timrae** [comment]
It would be fantastic if you could get that working

I don't think they explicitly contain the "padding" because the vector files are defined on a 24dp grid, so the padding would presumably just be the distance from the edge of the grid to the edge of the line path...? 

On SDK 21+ you can use an xml VectorDrawable directly as an icon instead of a png. For example [here's the refresh icon](https://github.com/google/material-design-icons/blob/master/navigation/drawable-anydpi-v21/ic_refresh_black_24dp.xml) from the example above 

See here for slightly more info:
https://google.github.io/material-design-icons/#icons-for-android

**Comment by mikepenz** [comment]
@timrae sorry for the late answer. 

I looked on how the font is defined and created. It seems to be a limitation of the icon fonts to be not able to include this. 

I'm really sorry. 

Perhaps for use cases like this it is really easier or better to use the new provided tools by google which allows you to use VectorDrawables api 21+ and let the tools create the png's for you.

Thanks for your feedback
