### ISSUE TITLE
Name of icons faw instead of fa

### ISSUE THREAD

**Issue by CROSP** [mikepenz/Android-Iconics#86]
Thank you for great work.  
I have one question, why you use "faw" prefix for icons instead of default "fa".   
I have an app where I this image codes( fa-android for example) are parsed from the server and than used in the app, but with "faw" I have to parse and convert icon identifier.    
Maybe you can add some method to convert from default name to the name convention used in you library.

Thank you.

**Comment by mikepenz** [comment]
@CROSP because i have defined a 3-char prefix for the fonts so more combinations are possible.

I'm sorry but the 3-char prefix is a requirement with this library for the font identifiers. 
So you will have to replace **fa-** with **faw-**

Best,
Mike
