### ISSUE TITLE
The generated POM file of google-material-typeface is missing version for dependency of iconics-core

### ISSUE THREAD

**Issue by clement9527** [mikepenz/Android-Iconics#88]
Hi Mike,

I start having some issue build my project once I have my personal maven repo setup. The issue is in the generated POM file in google-material-typeface,  as the following:

    <dependencies>
      <dependency>
        <groupId>Android-Iconics</groupId>
        <artifactId>iconics-core</artifactId>
        <version>unspecified</version>
        <scope>compile</scope>
      </dependency>
    </dependencies>

which is causing the error whenever I build: 

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find Android-Iconics:iconics-core:unspecified.
     Searched in the following locations:
         https://jcenter.bintray.com/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.pom
         https://jcenter.bintray.com/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.jar
     Required by:
         XXX:app:unspecified > com.mikepenz:google-material-typeface:1.2.0.1

This is happening only when my current project depend on another artifact that also requires google-material-typeface.

**Comment by mikepenz** [comment]
@clement9527 which dependency also requires the **google-material-typeface**? Can you exclude it from this dependency?

**Comment by clement9527** [comment]
I have two modules (serves as a widget) both using iconics, and my main project depends on these two modules. When gradle tries to resolve the dependencies to see if there is any conflicts, it fails because the version of the dependency is unspecified.  

Answering your question, yea, for this case I can merge the two modules together to be one but that would be a hack to me and it means all artifacts using icon fonts will have to be one artifact, which is not an option for me. 

I checked, it is not only the google material fonts but also other fonts would have the same issue.

**Comment by clement9527** [comment]
One way for fixing this is to manually solve the version in gradle by the following: 

        eachDependency { details ->
            //multiple actions can be specified
            if (details.requested.group == 'Android-Iconics' && details.requested.name == 'iconics-core') {
                //changing the name:
                details.useTarget group: 'com.mikepenz', name: 'iconics-core', version: '1.7.8'
            }
        }

        dependencySubstitution {
            substitute module('Android-Iconics:iconics-core:unspecified') with module('com.mikepenz:iconics-core:1.7.8')
        }

**Comment by mikepenz** [comment]
@clement9527 thank you for your solution. i hope it will help others who also have a similar setup to fix this problem.
