### ISSUE TITLE
IconicsImageView not displayed

### ISSUE THREAD

**Issue by fliespl** [mikepenz/Android-Iconics#92]
I am having the problem with using IconicsImageView. It just won't render :) I have went through other issues and tried adding to proguard, registering fonts in Application onCreate, but none has worked. I am trying to use it in dialog fragment using this code:

```xml
<com.mikepenz.iconics.view.IconicsImageView
            android:layout_width="72dp"
            android:layout_height="72dp"
            app:iiv_color="@android:color/holo_red_dark"
            app:iiv_icon="gmd-favorite" />
```

```gradle
compile('com.mikepenz:materialdrawer:4.3.9@aar') {
    transitive = true
}    
compile 'com.mikepenz:google-material-typeface:1.2.0.1@aar'
compile 'com.mikepenz:fontawesome-typeface:4.4.0.1@aar'
```

Let me know how can I help debugging.

Thanks in advance for your help.

**Comment by mikepenz** [comment]
@fliespl do you use proguard?

if yes it sometimes happen that it can't automatically register the font. So this should be done in a `CustomApplication`
```java
Iconics.registerFont(new GoogleMaterial());
```
Shown here: https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/CustomApplication.java#L13


Other than that. Will it work if you use the icon programmatically and set it on the `ImageView`?

**Comment by fliespl** [comment]
@mikepenz Thanks for prompt reply.

I have actually initialized those using Application:

    @Override
    public void onCreate() {
        super.onCreate();
        FacebookSdk.sdkInitialize(getApplicationContext());
        Iconics.init(getApplicationContext());
        Iconics.registerFont(new GoogleMaterial());
        Iconics.registerFont(new FontAwesome());

IconicsButton works correctly as well as setting icon programatically on normal ImageView.

**Comment by mikepenz** [comment]
@fliespl ok great.

You can also try to add this to your proguard configuration:
https://github.com/mikepenz/Android-Iconics#proguard
(it will deactivate obfuscation for all fields which is probably bad for your application)

**Comment by fliespl** [comment]
@mikepenz I think you misunderstood me :) IconicsButton works, but not IconicsImageView.

**Comment by mikepenz** [comment]
@fliespl ok that sounds interesting. Not sure what could cause this as it works in the sample. 
Can you temporary try if it will work without proguard?

**Comment by fliespl** [comment]
It's from debug variant which I believe doesn't have proguard enabled.

**Comment by fliespl** [comment]
That's really strange cause it works on normal layout, but not DialogFragment. Hmmm. I will troubleshoot it a little more.

**Comment by mikepenz** [comment]
@fliespl ok thanks

**Comment by fliespl** [comment]
It's such a shame... I had bad namespace declaration in my layout...

**xmlns:app="http://schemas.android.com/tools"**
instead of:
**xmlns:app="http://schemas.android.com/apk/res-auto"**

Probably it might be added as one of the common problems ;)

Thank you for great contributions to Android Community!

**Comment by mikepenz** [comment]
@fliespl ah great that you found the cause.
