### ISSUE TITLE
Switch between Text and Icon

### ISSUE THREAD

**Issue by candeiasdan** [mikepenz/Android-Iconics#94]
How can i switch between a letter and a registered unicode, and keep the font size?

I do register the fonts on App level:
```java
GenericFont genericFont = new GenericFont("abc", "fonts/"+FONT_FILENAME);
genericFont.registerIcon("option_01", '\ue904');
Iconics.registerFont(genericFont);
```

Then i have on layout (XML):
```xml
<com.mikepenz.iconics.view.IconicsTextView
            android:id="@+id/letter"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:textSize="24sp"
            android:background="#0000FF"
            android:textColor="#FF0000"
            />
```

Now i need to switch between letter "A" and "{abc-option01}". To be more precise i need to keep the font size and switch colors (background and textColor):

State1:
Text: "A"
Font Size: 24sp (does not change)
Background: #0000FF
Text Color: #FF0000

State 2:
Text: "{abc-option01}"
Font Size: 24sp (does not change)
Background: #FF0000
Text Color: #0000FF

How can i accomplish this? The font size seems to change when it switched to unicode.

**Comment by mikepenz** [comment]
@candeiasdan the font size does not change, but the depending on the icon font the icons boundings may differ. 

so switching isn't the issue for you right? As of your sample you register "option_01" but afterwards you use "option01"

**Comment by candeiasdan** [comment]
misspelling mistake. I do use option_01. And yes, I can see my Icon.

How can work around bounds problem? The letter "A" is centered and with proper size, the Icon is not centered (its being shifted in direction of bottom right corner), and quite small for 24sp.

**Comment by mikepenz** [comment]
@candeiasdan depends on the process how you've created the font. That really depends how the vector is placed and defined. Not sure how you can modify the baseline or re-align it. Which service did you use?

If you really want to have full control i highly recommend you that you use the icon via the `IconicsDrawable` and set it on an `ImageView` this will give you better control, like padding, alignment within the bounds, height, width, ...

**Comment by candeiasdan** [comment]
@mikepenz thanks for your feedback. I have just realised that the font it self is shifted, so I won't manage to center it properly, I need to generate it once again.

It seems everything is fine with library, the problem is on my side! 

Thanks for the quick answer anyway!
