### ISSUE TITLE
Missing Google Material icon 'color lens'

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/Android-Iconics#95]
I can't find the equivalent 'color lens' icon, in the new library...

Thanks.

**Comment by seba123neo** [comment]
is 'palette'..

close the issue.

**Comment by mikepenz** [comment]
The new source also contains all icons. Here's the cheat sheet:
http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html

sorry that the names are different. but the updated source has many advantages. It fixes the broken icon mapping on some custom roms, and it also aligns the icons centered within text. 

;)

**Comment by seba123neo** [comment]
it's excellent thanks, perfect library mike...

**Comment by mikepenz** [comment]
thank you :)
