### ISSUE TITLE
How to add pressed state for IconicsDrawable set as Compound Drawable

### ISSUE THREAD

**Issue by fliespl** [mikepenz/Android-Iconics#96]
Hi Mike,
is it possible to change iconics drawable color while it's in pressed state? I was unsuccessful while trying to use StateListDrawable - it has never shown. Any idea how I should proceed? 

In my example I am setting facebook icon as "left drawable" of "Button" element. Not sure how to change iconics drawable color while it's in pressed state (button text gets changed from white to blue by states defined in @color/state_button.xml file).

Thanks for you help.

```
        IconicsDrawable fbDrawable = new IconicsDrawable(getActivity())
                .icon(FontAwesome.Icon.faw_facebook_f)
                .color(getResources().getColor(R.color.primary_color))
                .sizeDp(24);
        fbDrawable.setBounds(0, 0, 60, 60);
        mShareFacebookBtn.setCompoundDrawables(fbDrawable, null, null, null);
```

**Comment by mikepenz** [comment]
The sample contains a `StateListDrawable`

```java
StateListDrawable iconStateListDrawable = new StateListDrawable();
iconStateListDrawable.addState(new int[]{android.R.attr.state_pressed}, new IconicsDrawable(this, FontAwesome.Icon.faw_thumbs_o_up).sizeDp(48).color(Color.parseColor("#aaFF0000")).contourWidthDp(1));
iconStateListDrawable.addState(new int[]{}, new IconicsDrawable(this, FontAwesome.Icon.faw_thumbs_o_up).sizeDp(48).color(Color.parseColor("#aa00FF00")).contourWidthDp(2));
b6.setImageDrawable(iconStateListDrawable);
```

https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/java/com/mikepenz/iconics/sample/PlaygroundActivity.java#L92

**Comment by fliespl** [comment]
Hi Mike,
thank you - I have assumed there is other way since there is comment saying "(NOT WORKING AT THE MOMENT)"

**Comment by mikepenz** [comment]
@fliespl oops. should remove this. this comment was for a different thing i removed from the sample

**Comment by mikepenz** [comment]
will remove the comment ;)

**Comment by AngleV** [comment]
Hi @mikepenz 
an example of a StateListDrawable that animates when user release the Drawable would be nice.

**Comment by mikepenz** [comment]
@AngleV I am currently not sure, but I remember that this is just a setting on the `StateListDrawable`

**Comment by AngleV** [comment]
its possible with StateListAnimator but its only available for android > 21
