### ISSUE TITLE
IconicsCompatButton don't show the icon

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/Android-Iconics#97]
I was testing the IconicsCompatButton and I realized that not show icons, show a rectangle icon.

the same code with IconicsButton works perfect...

**Comment by mikepenz** [comment]
@seba123neo interesting. AllCaps is set to false?

**Comment by seba123neo** [comment]
testing more: in the android 5.1 works perfect the IconicsCompatButton, the icon is showing.

in 2.3 the IconicsCompatButton shows a rectangle, but the same code in API 10 with IconicsButton works well.

**Comment by mikepenz** [comment]
Seems they have some more custom handling in :/

**Comment by seba123neo** [comment]
yes with with AllCaps = false, same result...

in my code, I deleted all the textAllCaps in the IconicsButton, works perfect all the buttons from > API 10

**Comment by mikepenz** [comment]
@seba123neo if you use the new `ContextWrapper` feature and use a normal `Button` ?
