### ISSUE TITLE
Icon add request for WeatherIcon

### ISSUE THREAD

**Issue by ksy5662** [mikepenz/Android-Iconics#98]
Please add WeatherIcon

https://github.com/erikflowers/weather-icons.git

Thanks for your great work!!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-Iconics/tree/develop/weather-icons-typeface-library

Added the weather icons

**Comment by ksy5662** [comment]
Great work!!
Really appreciate your help
