### ISSUE TITLE
Many icons missing when updating from 1.7.9

### ISSUE THREAD

**Issue by paulirotta** [mikepenz/Android-Iconics#99]
I tried to bump up to the latest, but found gmd_group and a number of other icons we were using are no longer supported? They still appear in the Android app list but the constant is not in GoogleMaterial.class

**Comment by mikepenz** [comment]
@paulirotta all icons are still there, with a different name:
https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md#google-material-font-1201----2121

The source changed to the Google Material Iconic project which fixes the icons to be correctly positioned when used in text, and it also fixes a really really rare issue that the icons are not displayed on some custom roms.

You can find the mapping of the material design iconic font here:
http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html

Those are exact the same icons as before. I'm really sorry that the names do not match.
